/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_DIALOG_PARAMS_H
#define GUI_DIALOG_PARAMS_H

/*[[[cog
import DialogParams
DialogParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the file and colour dialogs

 * The parameters are under group "User parameter:BaseApp/Preferences/Dialog"
 *
 * This class is auto generated by Gui/DialogParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/DialogParams.h Gui/DialogParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/DialogParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/DialogParams.cpp with
 * the following signature.
 * @code
 *     void DialogParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport DialogParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DontUseNativeDialog
    ///
    /// Open and save files with Qt's own file dialog instead of the
    /// operating system's. Holding Shift while the dialog is called for
    /// gives the other one. Read each time a file dialog opens.
    static const bool & getDontUseNativeDialog();
    static const bool & defaultDontUseNativeDialog();
    static void removeDontUseNativeDialog();
    static void setDontUseNativeDialog(const bool &v);
    static const char *docDontUseNativeDialog();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DontUseNativeColorDialog
    ///
    /// Pick colours with Qt's own colour dialog instead of the operating
    /// system's. Holding Shift gives the other one. Read each time a
    /// colour dialog opens.
    static const bool & getDontUseNativeColorDialog();
    static const bool & defaultDontUseNativeColorDialog();
    static void removeDontUseNativeColorDialog();
    static void setDontUseNativeColorDialog(const bool &v);
    static const char *docDontUseNativeColorDialog();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class DialogParams
} // namespace Gui
//[[[end]]]

#endif // GUI_DIALOG_PARAMS_H
