/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_EDITOR_PARAMS_H
#define GUI_EDITOR_PARAMS_H

/*[[[cog
import EditorParams
EditorParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the text editors

 * The parameters are under group "User parameter:BaseApp/Preferences/Editor"
 *
 * This class is auto generated by Gui/EditorParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/EditorParams.h Gui/EditorParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/EditorParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/EditorParams.cpp with
 * the following signature.
 * @code
 *     void EditorParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport EditorParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Font
    ///
    /// Font family of the macro and Python editors, the Python console
    /// and the report view. Empty, the value while it is not set, means
    /// the system's fixed-pitch font. Applied at once.
    static const std::string & getFont();
    static const std::string & defaultFont();
    static void removeFont();
    static void setFont(const std::string &v);
    static const char *docFont();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontSize
    ///
    /// Font size in points of the macro and Python editors, the Python
    /// console and the report view. Applied at once.
    static const long & getFontSize();
    static const long & defaultFontSize();
    static void removeFontSize();
    static void setFontSize(const long &v);
    static const char *docFontSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TabSize
    ///
    /// Width of a tab stop in the macro and Python editors, in
    /// characters of the editor font. Applied at once.
    static const long & getTabSize();
    static const long & defaultTabSize();
    static void removeTabSize();
    static void setTabSize(const long &v);
    static const char *docTabSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IndentSize
    ///
    /// Number of spaces one step of indentation is in the macro and
    /// Python editors, when indentation is done with spaces.
    static const long & getIndentSize();
    static const long & defaultIndentSize();
    static void removeIndentSize();
    static void setIndentSize(const long &v);
    static const char *docIndentSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Spaces
    ///
    /// Indent with spaces in the macro and Python editors: the Tab key
    /// and the automatic indentation after Enter insert IndentSize
    /// spaces. When off they insert a tab character.
    static const bool & getSpaces();
    static const bool & defaultSpaces();
    static void removeSpaces();
    static void setSpaces(const bool &v);
    static const char *docSpaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EnableLineNumber
    ///
    /// Show line numbers in the left margin of the macro and Python
    /// editors. Applied at once.
    static const bool & getEnableLineNumber();
    static const bool & defaultEnableLineNumber();
    static void removeEnableLineNumber();
    static void setEnableLineNumber(const bool &v);
    static const char *docEnableLineNumber();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EnableBlockCursor
    ///
    /// Draw the text cursor of the macro and Python editors as a block
    /// one character wide instead of a line. Applied at once.
    static const bool & getEnableBlockCursor();
    static const bool & defaultEnableBlockCursor();
    static void removeEnableBlockCursor();
    static void setEnableBlockCursor(const bool &v);
    static const char *docEnableBlockCursor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CheckSystemExit
    ///
    /// When code run in the Python console raises SystemExit, ask before
    /// the program is closed. When off it closes at once.
    static const bool & getCheckSystemExit();
    static const bool & defaultCheckSystemExit();
    static void removeCheckSystemExit();
    static void setCheckSystemExit(const bool &v);
    static const char *docCheckSystemExit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Text
    ///
    /// Colour of plain text in the editors and the Python console. Not
    /// set means the window's text colour, which follows the theme.
    static const unsigned long & getText();
    static const unsigned long & defaultText();
    static void removeText();
    static void setText(const unsigned long &v);
    static const char *docText();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Keyword
    ///
    /// Colour of Python keywords in the editors and the Python console.
    static const unsigned long & getKeyword();
    static const unsigned long & defaultKeyword();
    static void removeKeyword();
    static void setKeyword(const unsigned long &v);
    static const char *docKeyword();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Comment
    ///
    /// Colour of comments in the editors and the Python console.
    static const unsigned long & getComment();
    static const unsigned long & defaultComment();
    static void removeComment();
    static void setComment(const unsigned long &v);
    static const char *docComment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BlockComment
    ///
    /// Colour of triple-quoted text in the editors and the Python
    /// console.
    static const unsigned long & getBlockComment();
    static const unsigned long & defaultBlockComment();
    static void removeBlockComment();
    static void setBlockComment(const unsigned long &v);
    static const char *docBlockComment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Number
    ///
    /// Colour of numbers in the editors and the Python console.
    static const unsigned long & getNumber();
    static const unsigned long & defaultNumber();
    static void removeNumber();
    static void setNumber(const unsigned long &v);
    static const char *docNumber();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter String
    ///
    /// Colour of quoted text in the editors and the Python console.
    static const unsigned long & getString();
    static const unsigned long & defaultString();
    static void removeString();
    static void setString(const unsigned long &v);
    static const char *docString();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ClassName
    ///
    /// Colour of the name after 'class' in the editors and the Python
    /// console.
    static const unsigned long & getClassName();
    static const unsigned long & defaultClassName();
    static void removeClassName();
    static void setClassName(const unsigned long &v);
    static const char *docClassName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefineName
    ///
    /// Colour of the name after 'def' in the editors and the Python
    /// console.
    static const unsigned long & getDefineName();
    static const unsigned long & defaultDefineName();
    static void removeDefineName();
    static void setDefineName(const unsigned long &v);
    static const char *docDefineName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Operator
    ///
    /// Colour of operators and brackets in the editors and the Python
    /// console.
    static const unsigned long & getOperator();
    static const unsigned long & defaultOperator();
    static void removeOperator();
    static void setOperator(const unsigned long &v);
    static const char *docOperator();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PythonOutput
    ///
    /// Colour of what Python prints in the Python console.
    static const unsigned long & getPythonOutput();
    static const unsigned long & defaultPythonOutput();
    static void removePythonOutput();
    static void setPythonOutput(const unsigned long &v);
    static const char *docPythonOutput();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PythonError
    ///
    /// Colour of Python's error messages in the Python console.
    static const unsigned long & getPythonError();
    static const unsigned long & defaultPythonError();
    static void removePythonError();
    static void setPythonError(const unsigned long &v);
    static const char *docPythonError();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CurrentLineHighlight
    ///
    /// Background colour of the line the cursor is on in the macro and
    /// Python editors.
    static const unsigned long & getCurrentLineHighlight();
    static const unsigned long & defaultCurrentLineHighlight();
    static void removeCurrentLineHighlight();
    static void setCurrentLineHighlight(const unsigned long &v);
    static const char *docCurrentLineHighlight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Background
    ///
    /// Background colour of the Python console. 0, or not set, leaves
    /// the background to the theme.
    static const unsigned long & getBackground();
    static const unsigned long & defaultBackground();
    static void removeBackground();
    static void setBackground(const unsigned long &v);
    static const char *docBackground();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class EditorParams
} // namespace Gui
//[[[end]]]

#include <utility>
#include <vector>

#include <QColor>
#include <QFont>
#include <QString>

namespace Gui {

/** The colour settings of the editors by key, each with its default.
 *
 * Text has no default of its own: it is the window's text colour, which
 * follows the theme. Background is black, which the Python console reads as
 * "leave it to the theme".
 */
GuiExport std::vector<std::pair<QString, QColor>> editorColorDefaults();

/** The editors' font for a family and a size as they are stored.
 *
 * An empty family, which is what the setting is while nobody chose one, is
 * the system's fixed-pitch font, as upstream has it.
 */
GuiExport QFont editorFont(const std::string& family, int pointSize);

} // namespace Gui

#endif // GUI_EDITOR_PARAMS_H
