/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_GENERAL_PARAMS_H
#define GUI_GENERAL_PARAMS_H

/*[[[cog
import GeneralParams
GeneralParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the general application settings

 * The parameters are under group "User parameter:BaseApp/Preferences/General"
 *
 * This class is auto generated by Gui/GeneralParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/GeneralParams.h Gui/GeneralParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/GeneralParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/GeneralParams.cpp with
 * the following signature.
 * @code
 *     void GeneralParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport GeneralParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Language
    ///
    /// User interface language, as its English name (English, German,
    /// ...). Empty or not set uses the system's language. A change
    /// retranslates the interface at once.
    static const std::string & getLanguage();
    static const std::string & defaultLanguage();
    static void removeLanguage();
    static void setLanguage(const std::string &v);
    static const char *docLanguage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseLocaleFormatting
    ///
    /// Decimal and group separators of numbers: 0 the operating system's,
    /// 1 those of the interface language, 2 C/POSIX. Takes effect shortly
    /// after a change.
    static const long & getUseLocaleFormatting();
    static const long & defaultUseLocaleFormatting();
    static void removeUseLocaleFormatting();
    static void setUseLocaleFormatting(const long &v);
    static const char *docUseLocaleFormatting();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SubstituteDecimalSeparator
    ///
    /// Type the locale's decimal separator with the decimal key of the
    /// numeric keypad, whatever the keyboard layout sends for it.
    static const bool & getSubstituteDecimalSeparator();
    static const bool & defaultSubstituteDecimalSeparator();
    static void removeSubstituteDecimalSeparator();
    static void setSubstituteDecimalSeparator(const bool &v);
    static const char *docSubstituteDecimalSeparator();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EnableCursorBlinking
    ///
    /// Blink the text cursor in text and number input fields. When off it
    /// stays steady. Takes effect at once.
    static const bool & getEnableCursorBlinking();
    static const bool & defaultEnableCursorBlinking();
    static void removeEnableCursorBlinking();
    static void setEnableCursorBlinking(const bool &v);
    static const char *docEnableCursorBlinking();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSplasher
    ///
    /// Show the splash screen while the program starts. Takes effect at
    /// the next start.
    static const bool & getShowSplasher();
    static const bool & defaultShowSplasher();
    static void removeShowSplasher();
    static void setShowSplasher(const bool &v);
    static const char *docShowSplasher();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSplasherMessages
    ///
    /// Show the loading messages on the splash screen. When off it shows
    /// its image only. Takes effect at the next start.
    static const bool & getShowSplasherMessages();
    static const bool & defaultShowSplasherMessages();
    static void removeShowSplasherMessages();
    static void setShowSplasherMessages(const bool &v);
    static const char *docShowSplasherMessages();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowVersionInTitle
    ///
    /// Show the version number after the application name in the main
    /// window's title. Takes effect at the next start.
    static const bool & getShowVersionInTitle();
    static const bool & defaultShowVersionInTitle();
    static void removeShowVersionInTitle();
    static void setShowVersionInTitle(const bool &v);
    static const char *docShowVersionInTitle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoApplyPreference
    ///
    /// Apply each change made in the Preferences dialog as it is made,
    /// without Apply or OK. When off a change is stored when Apply or OK
    /// is pressed.
    static const bool & getAutoApplyPreference();
    static const bool & defaultAutoApplyPreference();
    static void removeAutoApplyPreference();
    static void setAutoApplyPreference(const bool &v);
    static const char *docAutoApplyPreference();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SaveUserParameter
    ///
    /// Write the settings file when the Preferences dialog is accepted and
    /// when the list of recent files or of recent macros changes. When
    /// off those do not write it.
    static const bool & getSaveUserParameter();
    static const bool & defaultSaveUserParameter();
    static void removeSaveUserParameter();
    static void setSaveUserParameter(const bool &v);
    static const char *docSaveUserParameter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ToolbarIconSize
    ///
    /// Size of tool bar icons in pixels, at least 5. The icons of the menu
    /// bar, the status bar and the workbench selector follow it unless
    /// given a size of their own. Takes effect shortly after a change.
    static const long & getToolbarIconSize();
    static const long & defaultToolbarIconSize();
    static void removeToolbarIconSize();
    static void setToolbarIconSize(const long &v);
    static const char *docToolbarIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WorkbenchTabIconSize
    ///
    /// Icon size in pixels of the workbench tab bar. 0 uses the tool bar
    /// icon size.
    static const long & getWorkbenchTabIconSize();
    static const long & defaultWorkbenchTabIconSize();
    static void removeWorkbenchTabIconSize();
    static void setWorkbenchTabIconSize(const long &v);
    static const char *docWorkbenchTabIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WorkbenchComboIconSize
    ///
    /// Icon size in pixels of the workbench selector's combo box. 0 uses
    /// 0.8 times the tool bar icon size.
    static const long & getWorkbenchComboIconSize();
    static const long & defaultWorkbenchComboIconSize();
    static void removeWorkbenchComboIconSize();
    static void setWorkbenchComboIconSize(const long &v);
    static const char *docWorkbenchComboIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StatusBarIconSize
    ///
    /// Icon size in pixels of tool bars placed in the status bar. 0 uses
    /// 0.6 times the tool bar icon size.
    static const long & getStatusBarIconSize();
    static const long & defaultStatusBarIconSize();
    static void removeStatusBarIconSize();
    static void setStatusBarIconSize(const long &v);
    static const char *docStatusBarIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MenuBarIconSize
    ///
    /// Icon size in pixels of tool bars placed beside the menu bar. 0 uses
    /// 0.8 times the tool bar icon size, or all of it with the custom
    /// title bar.
    static const long & getMenuBarIconSize();
    static const long & defaultMenuBarIconSize();
    static void removeMenuBarIconSize();
    static void setMenuBarIconSize(const long &v);
    static const char *docMenuBarIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LockTitleToolBars
    ///
    /// Keep the tool bars docked in the menu bar and in the status bar
    /// from being dragged out. Set from the tool bar lock menu.
    static const bool & getLockTitleToolBars();
    static const bool & defaultLockTitleToolBars();
    static void removeLockTitleToolBars();
    static void setLockTitleToolBars(const bool &v);
    static const char *docLockTitleToolBars();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ComboBoxWheelEventFilter
    ///
    /// Ignore the mouse wheel over combo boxes and over spin boxes that
    /// do not have the keyboard focus, so that scrolling a panel does not
    /// change values. Takes effect at the next start.
    static const bool & getComboBoxWheelEventFilter();
    static const bool & defaultComboBoxWheelEventFilter();
    static void removeComboBoxWheelEventFilter();
    static void setComboBoxWheelEventFilter(const bool &v);
    static const char *docComboBoxWheelEventFilter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoloadModule
    ///
    /// Workbench activated when the program starts, by its name, or
    /// $LastModule for the one that was active last. Empty or not set
    /// uses the configured start workbench. Takes effect at the next
    /// start.
    static const std::string & getAutoloadModule();
    static const std::string & defaultAutoloadModule();
    static void removeAutoloadModule();
    static void setAutoloadModule(const std::string &v);
    static const char *docAutoloadModule();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BackgroundAutoloadModules
    ///
    /// Comma separated names of the workbenches loaded in the background
    /// at start, without being shown. Takes effect at the next start.
    static const std::string & getBackgroundAutoloadModules();
    static const std::string & defaultBackgroundAutoloadModules();
    static void removeBackgroundAutoloadModules();
    static void setBackgroundAutoloadModules(const std::string &v);
    static const char *docBackgroundAutoloadModules();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExportDefaultFilenameSingle
    ///
    /// Pattern of the file name Export offers when one object is
    /// selected. %F is the document, %Lx the object labels joined by x,
    /// %Px the parent and object labels joined by x, %U the UTC time, %D
    /// the local time.
    static const std::string & getExportDefaultFilenameSingle();
    static const std::string & defaultExportDefaultFilenameSingle();
    static void removeExportDefaultFilenameSingle();
    static void setExportDefaultFilenameSingle(const std::string &v);
    static const char *docExportDefaultFilenameSingle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExportDefaultFilenameMultiple
    ///
    /// Pattern of the file name Export offers when the selection is not
    /// exactly one object. The codes are those of the pattern for one
    /// object: %F, %Lx, %Px, %U, %D.
    static const std::string & getExportDefaultFilenameMultiple();
    static const std::string & defaultExportDefaultFilenameMultiple();
    static void removeExportDefaultFilenameMultiple();
    static void setExportDefaultFilenameMultiple(const std::string &v);
    static const char *docExportDefaultFilenameMultiple();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecentIncludesImported
    ///
    /// Add files opened with Import to the list of recent files.
    static const bool & getRecentIncludesImported();
    static const bool & defaultRecentIncludesImported();
    static void removeRecentIncludesImported();
    static void setRecentIncludesImported(const bool &v);
    static const char *docRecentIncludesImported();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecentIncludesExported
    ///
    /// Add exported files to the list of recent files, where some module
    /// can open that type of file.
    static const bool & getRecentIncludesExported();
    static const bool & defaultRecentIncludesExported();
    static void removeRecentIncludesExported();
    static void setRecentIncludesExported(const bool &v);
    static const char *docRecentIncludesExported();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DownloadPath
    ///
    /// Directory downloaded files are saved in. Empty uses a folder named
    /// after the program inside the user's Documents folder.
    static const std::string & getDownloadPath();
    static const std::string & defaultDownloadPath();
    static void removeDownloadPath();
    static void setDownloadPath(const std::string &v);
    static const char *docDownloadPath();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoloadTab
    ///
    /// Index of the tab the combined report view shows first. Read when
    /// the view is made.
    static const long & getAutoloadTab();
    static const long & defaultAutoloadTab();
    static void removeAutoloadTab();
    static void setAutoloadTab(const long &v);
    static const char *docAutoloadTab();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProgressDetailLevels
    ///
    /// How many nested levels of progress per thread the progress
    /// detail popup shows. Less than 1 counts as 1.
    static const long & getProgressDetailLevels();
    static const long & defaultProgressDetailLevels();
    static void removeProgressDetailLevels();
    static void setProgressDetailLevels(const long &v);
    static const char *docProgressDetailLevels();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreferXcbOnWsl
    ///
    /// Under WSL with both Wayland and X11 at hand, and QT_QPA_PLATFORM
    /// not set, start on X11 (xcb) instead of Wayland. Takes effect at
    /// the next start.
    static const bool & getPreferXcbOnWsl();
    static const bool & defaultPreferXcbOnWsl();
    static void removePreferXcbOnWsl();
    static void setPreferXcbOnWsl(const bool &v);
    static const char *docPreferXcbOnWsl();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AdditionalLanguageDomainEntries
    ///
    /// Interface languages added to the built-in table, as pairs
    /// "Language Name"="code"; one after the other. Takes effect at
    /// the next start.
    static const std::string & getAdditionalLanguageDomainEntries();
    static const std::string & defaultAdditionalLanguageDomainEntries();
    static void removeAdditionalLanguageDomainEntries();
    static void setAdditionalLanguageDomainEntries(const std::string &v);
    static const char *docAdditionalLanguageDomainEntries();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AdditionalTranslationsDirectory
    ///
    /// Directory searched for translation files ahead of the user's and
    /// the installation's own. Takes effect at the next start.
    static const std::string & getAdditionalTranslationsDirectory();
    static const std::string & defaultAdditionalTranslationsDirectory();
    static void removeAdditionalTranslationsDirectory();
    static void setAdditionalTranslationsDirectory(const std::string &v);
    static const char *docAdditionalTranslationsDirectory();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TempPath
    ///
    /// Directory used for temporary files instead of the system's, when
    /// it exists. Takes effect at the next start.
    static const std::string & getTempPath();
    static const std::string & defaultTempPath();
    static void removeTempPath();
    static void setTempPath(const std::string &v);
    static const char *docTempPath();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class GeneralParams
} // namespace Gui
//[[[end]]]

#endif // GUI_GENERAL_PARAMS_H
