/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_MACRO_PARAMS_H
#define GUI_MACRO_PARAMS_H

/*[[[cog
import MacroParams
MacroParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of macro recording and running

 * The parameters are under group "User parameter:BaseApp/Preferences/Macro"
 *
 * This class is auto generated by Gui/MacroParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/MacroParams.h Gui/MacroParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/MacroParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/MacroParams.cpp with
 * the following signature.
 * @code
 *     void MacroParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport MacroParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MacroPath
    ///
    /// Directory where the user's macros are stored and looked for.
    /// Empty or not set means the Macro directory of the user's
    /// application data. Read each time macros are listed, recorded or
    /// run.
    static const std::string & getMacroPath();
    static const std::string & defaultMacroPath();
    static void removeMacroPath();
    static void setMacroPath(const std::string &v);
    static const char *docMacroPath();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LocalEnvironment
    ///
    /// Run a macro in an environment of its own, so that the variables
    /// it defines do not stay in the Python interpreter afterwards.
    /// Applies to the next macro run.
    static const bool & getLocalEnvironment();
    static const bool & defaultLocalEnvironment();
    static void removeLocalEnvironment();
    static void setLocalEnvironment(const bool &v);
    static const char *docLocalEnvironment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecordGui
    ///
    /// Write commands that only affect the user interface -- selection,
    /// view changes -- to a macro being recorded as well.
    static const bool & getRecordGui();
    static const bool & defaultRecordGui();
    static void removeRecordGui();
    static void setRecordGui(const bool &v);
    static const char *docRecordGui();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GuiAsComment
    ///
    /// Write the recorded user interface commands as comment lines, so
    /// that the macro shows them and does not run them.
    static const bool & getGuiAsComment();
    static const bool & defaultGuiAsComment();
    static void removeGuiAsComment();
    static void setGuiAsComment(const bool &v);
    static const char *docGuiAsComment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ScriptToPyConsole
    ///
    /// Show every command the program issues for a menu or tool bar
    /// action in the Python console, as it is carried out.
    static const bool & getScriptToPyConsole();
    static const bool & defaultScriptToPyConsole();
    static void removeScriptToPyConsole();
    static void setScriptToPyConsole(const bool &v);
    static const char *docScriptToPyConsole();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ReplaceSpaces
    ///
    /// Replace spaces by underscores in a macro file name entered in the
    /// Macro dialog: on create, rename and duplicate.
    static const bool & getReplaceSpaces();
    static const bool & defaultReplaceSpaces();
    static void removeReplaceSpaces();
    static void setReplaceSpaces(const bool &v);
    static const char *docReplaceSpaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateFrom001
    ///
    /// When a macro whose name ends in @ and three digits is duplicated,
    /// look for a free name starting at @001 instead of continuing from
    /// that macro's own number.
    static const bool & getDuplicateFrom001();
    static const bool & defaultDuplicateFrom001();
    static void removeDuplicateFrom001();
    static void setDuplicateFrom001(const bool &v);
    static const char *docDuplicateFrom001();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateIgnoreExtraNote
    ///
    /// When a macro is duplicated, leave out of the suggested name
    /// whatever stands between the number and the file extension.
    static const bool & getDuplicateIgnoreExtraNote();
    static const bool & defaultDuplicateIgnoreExtraNote();
    static void removeDuplicateIgnoreExtraNote();
    static void setDuplicateIgnoreExtraNote(const bool &v);
    static const char *docDuplicateIgnoreExtraNote();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class MacroParams
} // namespace Gui
//[[[end]]]

#endif // GUI_MACRO_PARAMS_H
