/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_MAINWINDOW_PARAMS_H
#define GUI_MAINWINDOW_PARAMS_H

/*[[[cog
import MainWindowParams
MainWindowParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the main window and theme settings

 * The parameters are under group "User parameter:BaseApp/Preferences/MainWindow"
 *
 * This class is auto generated by Gui/MainWindowParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/MainWindowParams.h Gui/MainWindowParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/MainWindowParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/MainWindowParams.cpp with
 * the following signature.
 * @code
 *     void MainWindowParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport MainWindowParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ColorScheme
    ///
    /// Palette the interface is drawn with: Light, Dark, or empty to
    /// follow the desktop. Not set at all means Light. Ignored while the
    /// theme follows the desktop. Takes effect at once.
    static const std::string & getColorScheme();
    static const std::string & defaultColorScheme();
    static void removeColorScheme();
    static void setColorScheme(const std::string &v);
    static const char *docColorScheme();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StyleSheet
    ///
    /// Style sheet of the interface: a file of the 'qss' search path, or
    /// a full path. Empty means none. Applied shortly after a change.
    static const std::string & getStyleSheet();
    static const std::string & defaultStyleSheet();
    static void removeStyleSheet();
    static void setStyleSheet(const std::string &v);
    static const char *docStyleSheet();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OverlayActiveStyleSheet
    ///
    /// Style sheet of the overlay dock panels: a file of the 'overlay'
    /// search path, or a path. Empty picks the light or the dark outline
    /// sheet to match the interface. Takes effect at once.
    static const std::string & getOverlayActiveStyleSheet();
    static const std::string & defaultOverlayActiveStyleSheet();
    static void removeOverlayActiveStyleSheet();
    static void setOverlayActiveStyleSheet(const std::string &v);
    static const char *docOverlayActiveStyleSheet();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MenuStyleSheet
    ///
    /// Style sheet of the menus that pop up over the 3D view: a file of
    /// the 'qssm' search path, or a path. Empty gives ordinary menus.
    /// Read each time such a menu is set up.
    static const std::string & getMenuStyleSheet();
    static const std::string & defaultMenuStyleSheet();
    static void removeMenuStyleSheet();
    static void setMenuStyleSheet(const std::string &v);
    static const char *docMenuStyleSheet();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IconSet
    ///
    /// Icon set that replaces built-in icons: a file of the 'iconset'
    /// search path or a path, or several separated by ';'. Empty means
    /// none. Applied with the style sheet shortly after a change.
    static const std::string & getIconSet();
    static const std::string & defaultIconSet();
    static void removeIconSet();
    static void setIconSet(const std::string &v);
    static const char *docIconSet();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeIconSetPolicy
    ///
    /// What applying a theme does to the icon set: Reset takes the
    /// theme's (none if it names none), Merge puts the theme's over the
    /// user's, Keep leaves it alone.
    static const std::string & getThemeIconSetPolicy();
    static const std::string & defaultThemeIconSetPolicy();
    static void removeThemeIconSetPolicy();
    static void setThemeIconSetPolicy(const std::string &v);
    static const char *docThemeIconSetPolicy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TiledBackground
    ///
    /// Fill the empty area of the main window with a tiled image instead
    /// of plain grey. Drawn only while no style sheet is chosen.
    static const bool & getTiledBackground();
    static const bool & defaultTiledBackground();
    static void removeTiledBackground();
    static void setTiledBackground(const bool &v);
    static const char *docTiledBackground();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter QtStyle
    ///
    /// Qt widget style the interface is drawn with: FreeCAD for the
    /// built-in one, System for the platform's, or any style name Qt
    /// knows. Empty leaves the style as it is. Themes set it.
    static const std::string & getQtStyle();
    static const std::string & defaultQtStyle();
    static void removeQtStyle();
    static void setQtStyle(const std::string &v);
    static const char *docQtStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeAuto
    ///
    /// Follow the desktop's light or dark mode: the Light or the Dark
    /// theme is applied at start and when the desktop changes. Set by
    /// Match Desktop on the Start page; cleared when a theme is applied.
    static const bool & getThemeAuto();
    static const bool & defaultThemeAuto();
    static void removeThemeAuto();
    static void setThemeAuto(const bool &v);
    static const char *docThemeAuto();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeStyleParametersFile
    ///
    /// Path of a YAML file of style parameters used instead of the
    /// current theme's own. Empty uses the theme's. Read at start and
    /// each time the style sheet is applied.
    static const std::string & getThemeStyleParametersFile();
    static const std::string & defaultThemeStyleParametersFile();
    static void removeThemeStyleParametersFile();
    static void setThemeStyleParametersFile(const std::string &v);
    static const char *docThemeStyleParametersFile();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CustomTitleBar
    ///
    /// Draw the title bar inside the application instead of the
    /// platform's, so that the menu and tool bars can share its row.
    /// Themes set it. Takes effect at once.
    static const bool & getCustomTitleBar();
    static const bool & defaultCustomTitleBar();
    static void removeCustomTitleBar();
    static void setCustomTitleBar(const bool &v);
    static const char *docCustomTitleBar();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TitleBarToolBars
    ///
    /// With the custom title bar, put the workbench tool bar into the
    /// title bar instead of under the menu bar. No effect with the
    /// platform's title bar. Takes effect at once.
    static const bool & getTitleBarToolBars();
    static const bool & defaultTitleBarToolBars();
    static void removeTitleBarToolBars();
    static void setTitleBarToolBars(const bool &v);
    static const char *docTitleBarToolBars();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FoldTitleBarMenu
    ///
    /// With the custom title bar, hide the menu bar behind the logo
    /// button and open it on hover, leaving the row to tool bars. No
    /// effect with the platform's title bar or on macOS.
    static const bool & getFoldTitleBarMenu();
    static const bool & defaultFoldTitleBarMenu();
    static void removeFoldTitleBarMenu();
    static void setFoldTitleBarMenu(const bool &v);
    static const char *docFoldTitleBarMenu();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TitleBarMenuClickGuard
    ///
    /// How long, in milliseconds, a click on the title bar's logo is
    /// ignored after hovering has opened the folded menu, so that a
    /// habitual click does not close it again. 0 turns the guard off.
    static const long & getTitleBarMenuClickGuard();
    static const long & defaultTitleBarMenuClickGuard();
    static void removeTitleBarMenuClickGuard();
    static void setTitleBarMenuClickGuard(const long &v);
    static const char *docTitleBarMenuClickGuard();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultToolBarArea
    ///
    /// Side of the main window where workbench tool bars are docked by
    /// default: Top, Left, Right or Bottom. Anything else means Top. The
    /// tool bars are moved shortly after a change.
    static const std::string & getDefaultToolBarArea();
    static const std::string & defaultDefaultToolBarArea();
    static void removeDefaultToolBarArea();
    static void setDefaultToolBarArea(const std::string &v);
    static const char *docDefaultToolBarArea();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GlobalToolBarArea
    ///
    /// Side of the main window where the global tool bars (File,
    /// Structure, Macro, View and those made global) are docked by
    /// default: Top, Left, Right or Bottom. Anything else means Top.
    static const std::string & getGlobalToolBarArea();
    static const std::string & defaultGlobalToolBarArea();
    static void removeGlobalToolBarArea();
    static void setGlobalToolBarArea(const std::string &v);
    static const char *docGlobalToolBarArea();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WSPosition
    ///
    /// Where the workbench selector goes. WSToolbar puts it into a tool
    /// bar of its own. Read each time a workbench sets its tool bars up.
    static const std::string & getWSPosition();
    static const std::string & defaultWSPosition();
    static void removeWSPosition();
    static void setWSPosition(const std::string &v);
    static const char *docWSPosition();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DockableWindowShortcut
    ///
    /// Key sequence the entries of the dockable window menu get as a
    /// shortcut, each followed by its number. Empty turns these shortcuts
    /// off. Read each time the menu opens.
    static const std::string & getDockableWindowShortcut();
    static const std::string & defaultDockableWindowShortcut();
    static void removeDockableWindowShortcut();
    static void setDockableWindowShortcut(const std::string &v);
    static const char *docDockableWindowShortcut();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class MainWindowParams
} // namespace Gui
//[[[end]]]

#endif // GUI_MAINWINDOW_PARAMS_H
