/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_MISC_PARAMS_H
#define GUI_MISC_PARAMS_H

/*[[[cog
import MiscParams
MiscParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of several small parameter groups

 * The parameters are under group "User parameter:BaseApp/Preferences"
 *
 * This class is auto generated by Gui/MiscParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/MiscParams.h Gui/MiscParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/MiscParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/MiscParams.cpp with
 * the following signature.
 * @code
 *     void MiscParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport MiscParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecentMacros
    ///
    /// Number of macros the recent macros menu lists.
    static const long & getRecentMacros();
    static const long & defaultRecentMacros();
    static void removeRecentMacros();
    static void setRecentMacros(const long &v);
    static const char *docRecentMacros();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShortcutCount
    ///
    /// Number of entries of the recent macros menu that get a keyboard
    /// shortcut, the modifiers below and a digit. At most 9.
    static const long & getShortcutCount();
    static const long & defaultShortcutCount();
    static void removeShortcutCount();
    static void setShortcutCount(const long &v);
    static const char *docShortcutCount();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShortcutModifiers
    ///
    /// Modifier keys of the shortcuts of the recent macros menu, written
    /// as in a shortcut and ending in +, such as Ctrl+Shift+.
    static const std::string & getShortcutModifiers();
    static const std::string & defaultShortcutModifiers();
    static void removeShortcutModifiers();
    static void setShortcutModifiers(const std::string &v);
    static const char *docShortcutModifiers();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseLinearSnapMultiplier
    ///
    /// How many times larger the step of a linear gizmo is while the
    /// key for coarse steps is held.
    static const long & getCoarseLinearSnapMultiplier();
    static const long & defaultCoarseLinearSnapMultiplier();
    static void removeCoarseLinearSnapMultiplier();
    static void setCoarseLinearSnapMultiplier(const long &v);
    static const char *docCoarseLinearSnapMultiplier();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseRotationSnapMultiplier
    ///
    /// How many times larger the step of a rotation gizmo is while the
    /// key for coarse steps is held.
    static const long & getCoarseRotationSnapMultiplier();
    static const long & defaultCoarseRotationSnapMultiplier();
    static void removeCoarseRotationSnapMultiplier();
    static void setCoarseRotationSnapMultiplier(const long &v);
    static const char *docCoarseRotationSnapMultiplier();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CacheLimit
    ///
    /// Size in megabytes the cache directory may grow to before the
    /// program offers to clean it.
    static const unsigned long & getCacheLimit();
    static const unsigned long & defaultCacheLimit();
    static void removeCacheLimit();
    static void setCacheLimit(const unsigned long &v);
    static const char *docCacheLimit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CachePeriod
    ///
    /// How often the size of the cache directory is checked: 0 always,
    /// 1 daily, 2 weekly, 3 monthly, 4 yearly, 5 never.
    static const long & getCachePeriod();
    static const long & defaultCachePeriod();
    static void removeCachePeriod();
    static void setCachePeriod(const long &v);
    static const char *docCachePeriod();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShortcutTimeout
    ///
    /// Milliseconds the program waits for the next key of a shortcut
    /// made of several keys before it acts on what was typed.
    static const long & getShortcutTimeout();
    static const long & defaultShortcutTimeout();
    static void removeShortcutTimeout();
    static void setShortcutTimeout(const long &v);
    static const char *docShortcutTimeout();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowTabBar
    ///
    /// Show the workbenches as a bar of tabs instead of a drop-down
    /// list.
    static const bool & getShowTabBar();
    static const bool & defaultShowTabBar();
    static void removeShowTabBar();
    static void setShowTabBar(const bool &v);
    static const char *docShowTabBar();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TabBarShowText
    ///
    /// Show the name of each workbench on its tab, beside its icon.
    static const bool & getTabBarShowText();
    static const bool & defaultTabBarShowText();
    static void removeTabBarShowText();
    static void setTabBarShowText(const bool &v);
    static const char *docTabBarShowText();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TabBarMaxLength
    ///
    /// Room in pixels the workbench tab bar may take along the way its
    /// tabs run. 0 takes what its tabs need.
    static const long & getTabBarMaxLength();
    static const long & defaultTabBarMaxLength();
    static void removeTabBarMaxLength();
    static void setTabBarMaxLength(const long &v);
    static const char *docTabBarMaxLength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DisableDpiScaling
    ///
    /// Switch Qt's scaling for high resolution screens off. Read at
    /// startup.
    static const bool & getDisableDpiScaling();
    static const bool & defaultDisableDpiScaling();
    static void removeDisableDpiScaling();
    static void setDisableDpiScaling(const bool &v);
    static const char *docDisableDpiScaling();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseSoftwareOpenGL
    ///
    /// Draw with a software implementation of OpenGL instead of the
    /// graphics driver. Read at startup.
    static const bool & getUseSoftwareOpenGL();
    static const bool & defaultUseSoftwareOpenGL();
    static void removeUseSoftwareOpenGL();
    static void setUseSoftwareOpenGL(const bool &v);
    static const char *docUseSoftwareOpenGL();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Unflatten
    ///
    /// Run the dependency graph through Graphviz's unflatten, which
    /// makes wide graphs narrower.
    static const bool & getUnflatten();
    static const bool & defaultUnflatten();
    static void removeUnflatten();
    static void setUnflatten(const bool &v);
    static const char *docUnflatten();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class MiscParams
} // namespace Gui
//[[[end]]]

#endif // GUI_MISC_PARAMS_H
