/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_NAVICUBE_PARAMS_H
#define GUI_NAVICUBE_PARAMS_H

/*[[[cog
import NaviCubeParams
NaviCubeParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the navigation cube

 * The parameters are under group "User parameter:BaseApp/Preferences/NaviCube"
 *
 * This class is auto generated by Gui/NaviCubeParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/NaviCubeParams.h Gui/NaviCubeParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/NaviCubeParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/NaviCubeParams.cpp with
 * the following signature.
 * @code
 *     void NaviCubeParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport NaviCubeParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CubeSize
    ///
    /// Size of the navigation cube in pixels, 10 to 1024.
    static const long & getCubeSize();
    static const long & defaultCubeSize();
    static void removeCubeSize();
    static void setCubeSize(const long &v);
    static const char *docCubeSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NaviRotateToNearest
    ///
    /// A click on a face of the navigation cube turns the view to that
    /// face in the nearest of its four upright positions. When off the
    /// face is shown the way its text reads.
    static const bool & getNaviRotateToNearest();
    static const bool & defaultNaviRotateToNearest();
    static void removeNaviRotateToNearest();
    static void setNaviRotateToNearest(const bool &v);
    static const char *docNaviRotateToNearest();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NaviStepByTurn
    ///
    /// Number of steps a full turn is made in with the arrow buttons of
    /// the navigation cube, 4 to 36.
    static const long & getNaviStepByTurn();
    static const long & defaultNaviStepByTurn();
    static void removeNaviStepByTurn();
    static void setNaviStepByTurn(const long &v);
    static const char *docNaviStepByTurn();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowCS
    ///
    /// Draw the X, Y and Z axes at a corner of the navigation cube.
    static const bool & getShowCS();
    static const bool & defaultShowCS();
    static void removeShowCS();
    static void setShowCS(const bool &v);
    static const char *docShowCS();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BorderWidth
    ///
    /// Width in pixels of the lines around the faces of the navigation
    /// cube.
    static const double & getBorderWidth();
    static const double & defaultBorderWidth();
    static void removeBorderWidth();
    static void setBorderWidth(const double &v);
    static const char *docBorderWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ChamferSize
    ///
    /// Size of the edge and corner faces of the navigation cube, as a
    /// fraction of the cube.
    static const double & getChamferSize();
    static const double & defaultChamferSize();
    static void removeChamferSize();
    static void setChamferSize(const double &v);
    static const char *docChamferSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoHideCube
    ///
    /// Hide the navigation cube while the mouse is away from it.
    static const bool & getAutoHideCube();
    static const bool & defaultAutoHideCube();
    static void removeAutoHideCube();
    static void setAutoHideCube(const bool &v);
    static const char *docAutoHideCube();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoHideButton
    ///
    /// Hide the arrow buttons around the navigation cube while the mouse
    /// is away from it.
    static const bool & getAutoHideButton();
    static const bool & defaultAutoHideButton();
    static void removeAutoHideButton();
    static void setAutoHideButton(const bool &v);
    static const char *docAutoHideButton();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoHideTimeout
    ///
    /// Milliseconds the mouse has to be away before the navigation cube
    /// or its buttons are hidden.
    static const long & getAutoHideTimeout();
    static const long & defaultAutoHideTimeout();
    static void removeAutoHideTimeout();
    static void setAutoHideTimeout(const long &v);
    static const char *docAutoHideTimeout();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontAutoSize
    ///
    /// Size the texts on the faces of the navigation cube to the faces,
    /// by FontScale. When off FontSize is used.
    static const bool & getFontAutoSize();
    static const bool & defaultFontAutoSize();
    static void removeFontAutoSize();
    static void setFontAutoSize(const bool &v);
    static const char *docFontAutoSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontScale
    ///
    /// Height of the texts on the navigation cube as a fraction of a
    /// face, with FontAutoSize on.
    static const double & getFontScale();
    static const double & defaultFontScale();
    static void removeFontScale();
    static void setFontScale(const double &v);
    static const char *docFontScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontString
    ///
    /// Font family of the texts on the faces of the navigation cube.
    static const std::string & getFontString();
    static const std::string & defaultFontString();
    static void removeFontString();
    static void setFontString(const std::string &v);
    static const char *docFontString();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontSize
    ///
    /// Font size of the texts on the faces of the navigation cube in
    /// points, with FontAutoSize off. 0 sizes them to the faces.
    static const long & getFontSize();
    static const long & defaultFontSize();
    static void removeFontSize();
    static void setFontSize(const long &v);
    static const char *docFontSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontWeight
    ///
    /// Weight of the font on the faces of the navigation cube, 0 to 99.
    static const long & getFontWeight();
    static const long & defaultFontWeight();
    static void removeFontWeight();
    static void setFontWeight(const long &v);
    static const char *docFontWeight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontItalic
    ///
    /// Draw the texts on the faces of the navigation cube in italics.
    static const bool & getFontItalic();
    static const bool & defaultFontItalic();
    static void removeFontItalic();
    static void setFontItalic(const bool &v);
    static const char *docFontItalic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontStretch
    ///
    /// Horizontal stretch of the font on the faces of the navigation
    /// cube in percent; 100 is the width the font has.
    static const long & getFontStretch();
    static const long & defaultFontStretch();
    static void removeFontStretch();
    static void setFontStretch(const long &v);
    static const char *docFontStretch();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisFont
    ///
    /// Font family of the axis labels of the navigation cube.
    static const std::string & getAxisFont();
    static const std::string & defaultAxisFont();
    static void removeAxisFont();
    static void setAxisFont(const std::string &v);
    static const char *docAxisFont();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisFontSize
    ///
    /// Font size of the axis labels of the navigation cube in points.
    static const long & getAxisFontSize();
    static const long & defaultAxisFontSize();
    static void removeAxisFontSize();
    static void setAxisFontSize(const long &v);
    static const char *docAxisFontSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisFontWeight
    ///
    /// Weight of the font of the axis labels of the navigation cube, 0
    /// to 99.
    static const long & getAxisFontWeight();
    static const long & defaultAxisFontWeight();
    static void removeAxisFontWeight();
    static void setAxisFontWeight(const long &v);
    static const char *docAxisFontWeight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisFontItalic
    ///
    /// Draw the axis labels of the navigation cube in italics.
    static const bool & getAxisFontItalic();
    static const bool & defaultAxisFontItalic();
    static void removeAxisFontItalic();
    static void setAxisFontItalic(const bool &v);
    static const char *docAxisFontItalic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TextColor
    ///
    /// Colour of the texts on the navigation cube, as 0xAARRGGBB.
    static const unsigned long & getTextColor();
    static const unsigned long & defaultTextColor();
    static void removeTextColor();
    static void setTextColor(const unsigned long &v);
    static const char *docTextColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HiliteColor
    ///
    /// Colour of the part of the navigation cube under the mouse, as
    /// 0xAARRGGBB.
    static const unsigned long & getHiliteColor();
    static const unsigned long & defaultHiliteColor();
    static void removeHiliteColor();
    static void setHiliteColor(const unsigned long &v);
    static const char *docHiliteColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FrontColor
    ///
    /// Colour of the six main faces of the navigation cube, as
    /// 0xAARRGGBB.
    static const unsigned long & getFrontColor();
    static const unsigned long & defaultFrontColor();
    static void removeFrontColor();
    static void setFrontColor(const unsigned long &v);
    static const char *docFrontColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgeColor
    ///
    /// Colour of the edge faces of the navigation cube, as 0xAARRGGBB.
    static const unsigned long & getEdgeColor();
    static const unsigned long & defaultEdgeColor();
    static void removeEdgeColor();
    static void setEdgeColor(const unsigned long &v);
    static const char *docEdgeColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CornerColor
    ///
    /// Colour of the corner faces of the navigation cube, as
    /// 0xAARRGGBB.
    static const unsigned long & getCornerColor();
    static const unsigned long & defaultCornerColor();
    static void removeCornerColor();
    static void setCornerColor(const unsigned long &v);
    static const char *docCornerColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ButtonColor
    ///
    /// Colour of the arrow buttons around the navigation cube, as
    /// 0xAARRGGBB.
    static const unsigned long & getButtonColor();
    static const unsigned long & defaultButtonColor();
    static void removeButtonColor();
    static void setButtonColor(const unsigned long &v);
    static const char *docButtonColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BorderColor
    ///
    /// Colour of the lines around the faces of the navigation cube, as
    /// 0xAARRGGBB.
    static const unsigned long & getBorderColor();
    static const unsigned long & defaultBorderColor();
    static void removeBorderColor();
    static void setBorderColor(const unsigned long &v);
    static const char *docBorderColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisLabelColor
    ///
    /// Colour of the axis labels of the navigation cube, as 0xAARRGGBB.
    static const unsigned long & getAxisLabelColor();
    static const unsigned long & defaultAxisLabelColor();
    static void removeAxisLabelColor();
    static void setAxisLabelColor(const unsigned long &v);
    static const char *docAxisLabelColor();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class NaviCubeParams
} // namespace Gui
//[[[end]]]

#endif // GUI_NAVICUBE_PARAMS_H
