/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_NOTIFICATIONAREA_PARAMS_H
#define GUI_NOTIFICATIONAREA_PARAMS_H

/*[[[cog
import NotificationAreaParams
NotificationAreaParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the notification area

 * The parameters are under group "User parameter:BaseApp/Preferences/NotificationArea"
 *
 * This class is auto generated by Gui/NotificationAreaParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/NotificationAreaParams.h Gui/NotificationAreaParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/NotificationAreaParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/NotificationAreaParams.cpp with
 * the following signature.
 * @code
 *     void NotificationAreaParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport NotificationAreaParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NotificationAreaEnabled
    ///
    /// Show the notification area in the status bar and collect
    /// notifications in it. Takes effect at once.
    static const bool & getNotificationAreaEnabled();
    static const bool & defaultNotificationAreaEnabled();
    static void removeNotificationAreaEnabled();
    static void setNotificationAreaEnabled(const bool &v);
    static const char *docNotificationAreaEnabled();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NonIntrusiveNotificationsEnabled
    ///
    /// Show a notification in a bubble next to the notification area
    /// instead of a dialog box that has to be answered. When off, a
    /// notification that asks for it is shown as a dialog box.
    static const bool & getNonIntrusiveNotificationsEnabled();
    static const bool & defaultNonIntrusiveNotificationsEnabled();
    static void removeNonIntrusiveNotificationsEnabled();
    static void setNonIntrusiveNotificationsEnabled(const bool &v);
    static const char *docNonIntrusiveNotificationsEnabled();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NotificationTime
    ///
    /// Seconds a non-intrusive notification stays on screen, unless a
    /// mouse button is clicked first. 0 to 120.
    static const long & getNotificationTime();
    static const long & defaultNotificationTime();
    static void removeNotificationTime();
    static void setNotificationTime(const long &v);
    static const char *docNotificationTime();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxOpenNotifications
    ///
    /// Largest number of non-intrusive notifications on screen at the
    /// same time; older ones give way.
    static const long & getMaxOpenNotifications();
    static const long & defaultMaxOpenNotifications();
    static void removeMaxOpenNotifications();
    static void setMaxOpenNotifications(const long &v);
    static const char *docMaxOpenNotifications();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NotificiationWidth
    ///
    /// Width of a non-intrusive notification in pixels. At least 300.
    static const long & getNotificiationWidth();
    static const long & defaultNotificiationWidth();
    static void removeNotificiationWidth();
    static void setNotificiationWidth(const long &v);
    static const char *docNotificiationWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideNonIntrusiveNotificationsWhenWindowDeactivated
    ///
    /// Open non-intrusive notifications disappear when another window
    /// is activated.
    static const bool & getHideNonIntrusiveNotificationsWhenWindowDeactivated();
    static const bool & defaultHideNonIntrusiveNotificationsWhenWindowDeactivated();
    static void removeHideNonIntrusiveNotificationsWhenWindowDeactivated();
    static void setHideNonIntrusiveNotificationsWhenWindowDeactivated(const bool &v);
    static const char *docHideNonIntrusiveNotificationsWhenWindowDeactivated();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreventNonIntrusiveNotificationsWhenWindowNotActive
    ///
    /// Show no non-intrusive notification while the main window is not
    /// the active window. They are still collected in the list.
    static const bool & getPreventNonIntrusiveNotificationsWhenWindowNotActive();
    static const bool & defaultPreventNonIntrusiveNotificationsWhenWindowNotActive();
    static void removePreventNonIntrusiveNotificationsWhenWindowNotActive();
    static void setPreventNonIntrusiveNotificationsWhenWindowNotActive(const bool &v);
    static const char *docPreventNonIntrusiveNotificationsWhenWindowNotActive();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxWidgetMessages
    ///
    /// Largest number of messages the notification area's list keeps;
    /// older ones are dropped. 0 means no limit.
    static const long & getMaxWidgetMessages();
    static const long & defaultMaxWidgetMessages();
    static void removeMaxWidgetMessages();
    static void setMaxWidgetMessages(const long &v);
    static const char *docMaxWidgetMessages();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRemoveUserNotifications
    ///
    /// Remove a user notification from the list once the notification
    /// duration has passed.
    static const bool & getAutoRemoveUserNotifications();
    static const bool & defaultAutoRemoveUserNotifications();
    static void removeAutoRemoveUserNotifications();
    static void setAutoRemoveUserNotifications(const bool &v);
    static const char *docAutoRemoveUserNotifications();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DeveloperErrorSubscriptionEnabled
    ///
    /// Show errors meant for developers in the notification area too.
    static const bool & getDeveloperErrorSubscriptionEnabled();
    static const bool & defaultDeveloperErrorSubscriptionEnabled();
    static void removeDeveloperErrorSubscriptionEnabled();
    static void setDeveloperErrorSubscriptionEnabled(const bool &v);
    static const char *docDeveloperErrorSubscriptionEnabled();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DeveloperWarningSubscriptionEnabled
    ///
    /// Show warnings meant for developers in the notification area too.
    static const bool & getDeveloperWarningSubscriptionEnabled();
    static const bool & defaultDeveloperWarningSubscriptionEnabled();
    static void removeDeveloperWarningSubscriptionEnabled();
    static void setDeveloperWarningSubscriptionEnabled(const bool &v);
    static const char *docDeveloperWarningSubscriptionEnabled();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class NotificationAreaParams
} // namespace Gui
//[[[end]]]

#endif // GUI_NOTIFICATIONAREA_PARAMS_H
