/****************************************************************************
 *   Copyright (c) 2026 realthunder <realthunder.dev@gmail.com>             *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_OPENVIEW_PARAMS_H
#define GUI_OPENVIEW_PARAMS_H

/*[[[cog
import OpenViewParams
OpenViewParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain view placement parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/View/OpenView"
 *
 * This class is auto generated by Gui/OpenViewParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/OpenViewParams.h Gui/OpenViewParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/OpenViewParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/OpenViewParams.cpp with
 * the following signature.
 * @code
 *     void OpenViewParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport OpenViewParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DocumentTarget
    ///
    /// Where the first view of a newly opened document lands
    static const std::string & getDocumentTarget();
    static const std::string & defaultDocumentTarget();
    static void removeDocumentTarget();
    static void setDocumentTarget(const std::string &v);
    static const char *docDocumentTarget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DocViewTarget
    ///
    /// Where a second 3D view, a drawing page, a spreadsheet or the
    /// CAM simulator of an already open document lands
    static const std::string & getDocViewTarget();
    static const std::string & defaultDocViewTarget();
    static void removeDocViewTarget();
    static void setDocViewTarget(const std::string &v);
    static const char *docDocViewTarget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UtilityTarget
    ///
    /// Where a window that shows no document data lands, such as the
    /// dependency graph
    static const std::string & getUtilityTarget();
    static const std::string & defaultUtilityTarget();
    static void removeUtilityTarget();
    static void setUtilityTarget(const std::string &v);
    static const char *docUtilityTarget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SplitDirection
    ///
    /// Which way a cell is divided when a view opens in a split
    static const std::string & getSplitDirection();
    static const std::string & defaultSplitDirection();
    static void removeSplitDirection();
    static void setSplitDirection(const std::string &v);
    static const char *docSplitDirection();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class OpenViewParams
} // namespace Gui
//[[[end]]]
#endif // GUI_OPENVIEW_PARAMS_H
