/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_PYTHONCONSOLE_PARAMS_H
#define GUI_PYTHONCONSOLE_PARAMS_H

/*[[[cog
import PythonConsoleParams
PythonConsoleParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the Python console

 * The parameters are under group "User parameter:BaseApp/Preferences/PythonConsole"
 *
 * This class is auto generated by Gui/PythonConsoleParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/PythonConsoleParams.h Gui/PythonConsoleParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/PythonConsoleParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/PythonConsoleParams.cpp with
 * the following signature.
 * @code
 *     void PythonConsoleParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport PythonConsoleParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PythonWordWrap
    ///
    /// Wrap lines of the Python console that are longer than the window
    /// is wide. Also in the console's context menu. Takes effect at once.
    static const bool & getPythonWordWrap();
    static const bool & defaultPythonWordWrap();
    static void removePythonWordWrap();
    static void setPythonWordWrap(const bool &v);
    static const char *docPythonWordWrap();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PythonBlockCursor
    ///
    /// Draw the Python console's text cursor as a block one character
    /// wide instead of a line. Takes effect at once.
    static const bool & getPythonBlockCursor();
    static const bool & defaultPythonBlockCursor();
    static void removePythonBlockCursor();
    static void setPythonBlockCursor(const bool &v);
    static const char *docPythonBlockCursor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SavePythonHistory
    ///
    /// Keep the Python console's command history between sessions: the
    /// last 100 entries, written when the program ends and read at the
    /// next start. Also in the console's context menu.
    static const bool & getSavePythonHistory();
    static const bool & defaultSavePythonHistory();
    static void removeSavePythonHistory();
    static void setSavePythonHistory(const bool &v);
    static const char *docSavePythonHistory();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProfilerInterval
    ///
    /// Interval in milliseconds at which running Python code lets the
    /// user interface process events, so that it stays responsive. 0
    /// turns that off. Read when a script or command starts.
    static const long & getProfilerInterval();
    static const long & defaultProfilerInterval();
    static void removeProfilerInterval();
    static void setProfilerInterval(const long &v);
    static const char *docProfilerInterval();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalPythonExecutable
    ///
    /// Python executable used for work done outside the program, such as
    /// installing packages with pip or debugging with debugpy. Empty lets
    /// the program look for one when it is needed, and store what it
    /// found.
    static const std::string & getExternalPythonExecutable();
    static const std::string & defaultExternalPythonExecutable();
    static void removeExternalPythonExecutable();
    static void setExternalPythonExecutable(const std::string &v);
    static const char *docExternalPythonExecutable();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class PythonConsoleParams
} // namespace Gui
//[[[end]]]

#endif // GUI_PYTHONCONSOLE_PARAMS_H
