/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_RENDER_PARAMS_H
#define GUI_RENDER_PARAMS_H

/*[[[cog
import RenderParams
RenderParams.declare_begin()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the experimental render engine parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/View/Render"
 *
 * This class is auto generated by Gui/RenderParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/RenderParams.h Gui/RenderParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/RenderParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/RenderParams.cpp with
 * the following signature.
 * @code
 *     void RenderParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport RenderParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Type
    ///
    /// Type of the experimental render engine backend. 'Default' keeps
    /// the plain GL pipeline. Only effective with render cache mode 3.
    static const std::string & getType();
    static const std::string & defaultType();
    static void removeType();
    static void setType(const std::string &v);
    static const char *docType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseTessellation
    ///
    /// Ladder level shapes are tessellated at under coarse-first
    /// (docs/SceneStreaming.md #7): the display mesh is built at this
    /// rung of the fidelity ladder and the exact tessellation is
    /// declared unbuilt, generated on demand when a camera asks for it.
    /// 0 is the coarsest rung, each level halves the error; -1 always
    /// tessellates exact up front (pre-ladder behavior).
    /// 
    /// Consulted whenever something can deliver the exact rung on
    /// demand, which is a scene stream server (its viewers ask) OR a
    /// desktop view in render cache mode 3 whose backend drives mesh
    /// levels (its own level plan asks when the camera settles) - see
    /// PartGui::coarseTessellationLevel. Plain Coin display has neither
    /// and keeps the exact tessellation, because a coarse build there
    /// would stay coarse forever. This is not a serving-only feature,
    /// and it does engage for geometry built while a document loads.
    /// 
    /// What a serving process lacks is not this setting but the local
    /// level plan, which is disabled there - its rungs refine only where
    /// a connected viewer's camera asks, so with no viewer attached they
    /// stay coarse, while a desktop view refines its own. That, not the
    /// setting, is why the two publish different geometry for one
    /// document (measured on a 40-object scene: 8310 vertices serving,
    /// 25595 on the desktop). Desktop refinement is tolerance-limited,
    /// so what it settles at is a property of the framing.
    /// 
    /// A level whose rung is already finer than a shape's exact
    /// tessellation coarsens nothing, so on small shapes the low levels
    /// do nothing visible - the default 2 is a no-op on a scene of small
    /// ellipsoids that level 0 visibly coarsens.
    /// 
    /// The FC_COARSE_TESSELLATION environment variable overrides this for
    /// a whole process and returns before the gate is evaluated, so it
    /// forces coarse-first on where the gate would have refused. Takes
    /// effect when a shape (re)tessellates.
    static const long & getCoarseTessellation();
    static const long & defaultCoarseTessellation();
    static void removeCoarseTessellation();
    static void setCoarseTessellation(const long &v);
    static const char *docCoarseTessellation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseDeferFaces
    ///
    /// During a progressive import on the bgfx renderer, a shape with
    /// more faces than this gets a bounding-box stand-in immediately and
    /// even its coarse tessellation is built on the refine worker pool,
    /// swapped in when it arrives (docs/SceneStreaming.md #13) - the
    /// import stall otherwise scales with the largest single part. -1
    /// disables the stand-in so every shape tessellates inline.
    static const long & getCoarseDeferFaces();
    static const long & defaultCoarseDeferFaces();
    static void removeCoarseDeferFaces();
    static void setCoarseDeferFaces(const long &v);
    static const char *docCoarseDeferFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshSkipRedundant
    ///
    /// Ask the shape whether it is already tessellated the way this
    /// rebuild wants it, and skip the tessellation call outright when it
    /// is (docs/SceneStreaming.md #13e).
    /// A visual rebuild always called BRepMesh_IncrementalMesh, on the
    /// assumption that a mesh already resident makes the call nearly
    /// free. Measured, it does not: half the calls of a mass descent --
    /// 2462 of 4942 -- changed no triangle at all and still cost about
    /// 19ms each, 27% of the whole descent's rebuild time, because
    /// reaching the conclusion means building OCCT's internal mesh model
    /// of the shape first.
    /// The check asks the same question that model would have answered,
    /// off the triangulations already hanging on the faces: OCCT's own
    /// consistency rule (BRepMesh_ModelPreProcessor), per face, plus the
    /// 3D polygon of every free edge. It is all-or-nothing per shape and
    /// deliberately the stricter test -- one face that would be
    /// re-tessellated, one triangulation with an index out of range, and
    /// the call runs exactly as before, because the fallback is the real
    /// thing and there is nothing to gain by guessing.
    /// A resident mesh FINER than the ask is not adequate. That is not
    /// an oversight: the descent asks for a coarser mesh on purpose, to
    /// give memory back, and OCCT would coarsen it. Skipping there would
    /// quietly hold the memory the plan asked for.
    /// Off, the call is made unconditionally, as it always was. With the
    /// level plan narrating, the off arm also reports how often the
    /// check and the call agreed, which is what says the check is safe.
    static const bool & getMeshSkipRedundant();
    static const bool & defaultMeshSkipRedundant();
    static void removeMeshSkipRedundant();
    static void setMeshSkipRedundant(const bool &v);
    static const char *docMeshSkipRedundant();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshSkipFinerResident
    ///
    /// Count a resident mesh FINER than the rebuild asked for as
    /// adequate, instead of re-tessellating to coarsen it
    /// (docs/SceneStreaming.md #13e). Only consulted when redundant
    /// tessellation is being skipped at all.
    /// Strictly, finer is not adequate: the descent asks coarse on
    /// purpose to hand memory back, and OCCT coarsens the mesh when
    /// asked with quality decrease allowed. That is why the check
    /// refuses it by default -- accepting it would be the feature
    /// quietly holding the memory the level plan asked for.
    /// Measured on the descent, though, that is what the refusal is
    /// actually costing and it is nearly all of it: 2599 of the 2765
    /// refused calls had a resident mesh exactly twice as fine as the
    /// ask -- the previous ladder rung, one dynamic scale step back --
    /// and every one of them changed no triangle when the call was
    /// made anyway. The faces were already at their floor; a face of
    /// two triangles does not coarsen.
    /// So this trades a coarsening that mostly achieves nothing for the
    /// ~19ms it costs to find that out. What it risks is the minority
    /// where the coarsening WOULD have removed triangles, which is
    /// memory the plan then has to recover some other way -- through
    /// the refine pool's own coarser rung, where it was always meant to
    /// come from.
    /// OFF BY DEFAULT, and the reason is that risk, measured. Audited
    /// with every call still made so the check can be scored against
    /// what the call actually did, this rule predicted 3381 calls
    /// redundant and 753 of them -- 22%, better than one in five --
    /// rebuilt anyway. Those are real coarsenings it would have
    /// skipped, and real memory the plan would not get back. The
    /// strict rule's own score on the same instrument is 1 in 7403.
    /// /!\ Never read that count from a run with the skip ON: a call
    /// that is skipped is never made, so nothing can say whether it
    /// would have rebuilt, and the wrong-verdict column can only
    /// count calls the check refused. A zero there is guaranteed by
    /// construction rather than earned.
    static const bool & getMeshSkipFinerResident();
    static const bool & defaultMeshSkipFinerResident();
    static void removeMeshSkipFinerResident();
    static void setMeshSkipFinerResident(const bool &v);
    static const char *docMeshSkipFinerResident();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProgressiveLoad
    ///
    /// Build the visual representation of a restored document after
    /// the load instead of inline inside it. Opening a large document
    /// otherwise tessellates every shape on the main thread while
    /// nothing paints - the visual build is the largest single stage of
    /// a load. Deferred, the window comes up first and the parts appear
    /// in bounded slices with the view painting between them. Read as
    /// each restored shape asks for its visual.
    static const bool & getProgressiveLoad();
    static const bool & defaultProgressiveLoad();
    static void removeProgressiveLoad();
    static void setProgressiveLoad(const bool &v);
    static const char *docProgressiveLoad();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProgressiveLoadBudgetMS
    ///
    /// How long one slice of deferred visual building may run before
    /// returning to the event loop, when Progressive document load is
    /// on. Larger finishes the document sooner, smaller keeps the window
    /// more responsive while it fills in. Each slice is paid for with a
    /// repaint of a large scene, which is why slices this long are worth
    /// it - much smaller and the fill is paced by redraws rather than by
    /// the building. Read at each slice.
    static const long & getProgressiveLoadBudgetMS();
    static const long & defaultProgressiveLoadBudgetMS();
    static void removeProgressiveLoadBudgetMS();
    static void setProgressiveLoadBudgetMS(const long &v);
    static const char *docProgressiveLoadBudgetMS();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelThreads
    ///
    /// How many mesh level builds (the scene server's on-demand
    /// re-tessellations, docs/SceneStreaming.md #7) may run at once.
    /// 0 sizes the pool automatically - modest, because each BRepMesh
    /// build already parallelizes internally over OCCT's shared thread
    /// pool. The FC_LEVEL_THREADS environment variable overrides it.
    /// Read when the server spawns its first level worker.
    static const long & getLevelThreads();
    static const long & defaultLevelThreads();
    static void removeLevelThreads();
    static void setLevelThreads(const long &v);
    static const char *docLevelThreads();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelMemoryFloorMB
    ///
    /// Available system memory below which an exact re-tessellation
    /// will not start (docs/SceneStreaming.md #13): the desktop refine
    /// worker checks the system's own estimate of allocatable memory
    /// before each exact build, and dropping under this floor counts as
    /// a memory-ceiling observation - the same as a caught allocation
    /// failure - after which the level plans also demote exact meshes
    /// the camera would not miss back to their resident coarse rung.
    /// 0 sizes the floor automatically (at least 512 MB, or 1/16 of
    /// physical memory if that is more). Read when the first refine is
    /// queued.
    static const long & getLevelMemoryFloorMB();
    static const long & defaultLevelMemoryFloorMB();
    static void removeLevelMemoryFloorMB();
    static void setLevelMemoryFloorMB(const long &v);
    static const char *docLevelMemoryFloorMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelDebug
    ///
    /// Narrate what each mesh-level plan decides (docs/SceneStreaming.md
    /// #13): the GPU budget it decided against and the bytes in use, how
    /// many displayed sources stand at their coarse and exact rungs, and
    /// how many refines, demotes and downgrades the plan asked for.
    /// Reported on the plan's own cadence - a camera pause - because it
    /// is a decision, not a per-frame cost.
    /// Needed to tell a ladder that will not descend apart from one that
    /// never ran: on the desktop OpenGL backend the automatic GPU budget
    /// is 0 (bgfx's GL renderer reports no limit), so the downgrade half
    /// of the plan never executed at all and nothing said so.
    /// The FC_LEVEL_DEBUG environment variable also turns it on. Read
    /// once, at the first plan.
    static const bool & getLevelDebug();
    static const bool & defaultLevelDebug();
    static void removeLevelDebug();
    static void setLevelDebug(const bool &v);
    static const char *docLevelDebug();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelCeilingSimulateMB
    ///
    /// Pretend the system ran out of memory for exact re-tessellation
    /// (docs/SceneStreaming.md #13), so the CPU-side half of the level
    /// plan can be exercised on a machine that has memory to spare.
    /// Non-zero raises the floor that the refine worker compares
    /// available memory against, so builds are refused and a memory
    /// ceiling is observed - after which the plans start demoting exact
    /// meshes the camera would not miss back to their coarse rung.
    /// A simulation knob, not a tuning one: LevelMemoryFloorMB is the
    /// real floor, and this overrides it upward only.
    /// Read when a refine is dequeued, so it takes effect live.
    static const long & getLevelCeilingSimulateMB();
    static const long & defaultLevelCeilingSimulateMB();
    static void removeLevelCeilingSimulateMB();
    static void setLevelCeilingSimulateMB(const long &v);
    static const char *docLevelCeilingSimulateMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GpuMemoryBudgetMB
    ///
    /// GPU geometry budget of the desktop mesh-level plan
    /// (docs/SceneStreaming.md #13): while the uploaded geometry exceeds
    /// it, a camera pause downgrades the *displayed* mesh of objects the
    /// camera would not miss - off screen, or coarse within half the
    /// Level tolerance - back to their coarse rung. Their exact meshes
    /// stay in CPU RAM, so zooming back in re-activates them instantly,
    /// with no re-tessellation. 0 means automatic: the graphics API's
    /// own reported GPU memory limit where it states one (Direct3D and
    /// Vulkan do; OpenGL reports nothing, and then no budget applies).
    static const long & getGpuMemoryBudgetMB();
    static const long & defaultGpuMemoryBudgetMB();
    static void removeGpuMemoryBudgetMB();
    static void setGpuMemoryBudgetMB(const long &v);
    static const char *docGpuMemoryBudgetMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelTolerance
    ///
    /// Screen-space error, in pixels, a coarse tessellation may
    /// commit before the exact one is built (docs/SceneStreaming.md
    /// #13): on a coarse-first desktop view (render cache mode 3 with
    /// a backend that drives the level plan), a camera pause re-plans
    /// the scene and only objects whose coarse mesh errs by more than
    /// this many pixels on screen re-tessellate exactly - off-screen
    /// and distant objects stay at the cheap coarse mesh until the
    /// camera makes them matter. 0 or less refines everything
    /// immediately; larger keeps more of the scene coarse. The
    /// streamed viewer's own tolerance is its lodpx URL parameter
    /// (same meaning, same default).
    static const double & getLevelTolerance();
    static const double & defaultLevelTolerance();
    static void removeLevelTolerance();
    static void setLevelTolerance(const double &v);
    static const char *docLevelTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelPressureRelease
    ///
    /// How much of the raised refine tolerance the plan keeps each
    /// time it comes in under the GPU budget (docs/SceneStreaming.md
    /// #13c.3). While the budget is exceeded the plan accepts visible
    /// error to fit the scene, and it must not hand that error straight
    /// back the moment one plan fits: measured on a 5455-object model at
    /// a 64MB budget, clearing it in one step took the tolerance from
    /// 51 pixels to 2, asked 946 objects to re-tessellate at once, broke
    /// the budget again and cycled -- 43 plans in 611 seconds with no
    /// steady state at any point.
    /// So quality comes back in steps: each plan that fits keeps this
    /// fraction of the standing tolerance, and a step that puts the
    /// scene back over budget is remembered as a floor the release never
    /// passes again, so the ladder settles at the coarsest tolerance
    /// that actually fits instead of oscillating around it. The floor is
    /// forgotten when the camera moves or the budget changes, which is
    /// when what a rung costs on screen changes.
    /// Smaller gives quality back faster and risks the cycle; larger is
    /// gentler and slower. 0 or less restores the immediate snap.
    static const double & getLevelPressureRelease();
    static const double & defaultLevelPressureRelease();
    static void removeLevelPressureRelease();
    static void setLevelPressureRelease(const double &v);
    static const char *docLevelPressureRelease();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DowngradeLedger
    ///
    /// Whether the GPU downgrade sweep carries its own unlanded
    /// orders as credit against the next plan's deficit
    /// (docs/SceneStreaming.md #13c.4). A downgrade frees exactly the
    /// bytes it prices, but not WHEN the plan next looks: the swap
    /// uploads the coarse rung immediately while the fine buffers
    /// leave the live meter only after the collection window -- on a
    /// heavy scene, seconds -- so a plan sampling mid-transition reads
    /// old+new at once, computes a larger deficit than the one just
    /// covered, and walks other sources further down. Measured on a
    /// 5455-object model at 64MB with the camera inside the assembly:
    /// single plans requesting 1500+ downgrades, live tripling during
    /// the storm, and the whole registry drained to its bottom rung
    /// while the settled memory was under budget all along.
    /// With the ledger, promised bytes hold the sweep until they are
    /// observed landing or written off after a few frames; off
    /// restores the storming behaviour for comparison.
    static const bool & getDowngradeLedger();
    static const bool & defaultDowngradeLedger();
    static void removeDowngradeLedger();
    static void setDowngradeLedger(const bool &v);
    static const char *docDowngradeLedger();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelCount
    ///
    /// How many rungs the fidelity ladder declares
    /// (docs/SceneStreaming.md #13). Rung n is tessellated at a
    /// deflection of the shape diagonal over 8<<n, so rung 0 is the
    /// coarsest and each further rung halves the error; this bounds
    /// what Coarse tessellation level may select and how far a source
    /// may climb. Raising it adds finer rungs, not coarser ones -- to
    /// go below rung 0 the plan scales an object's error instead, see
    /// Level scale.
    static const long & getLevelCount();
    static const long & defaultLevelCount();
    static void removeLevelCount();
    static void setLevelCount(const long &v);
    static const char *docLevelCount();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelScale
    ///
    /// What the level plan multiplies an object's error by when it
    /// must free memory and every ordinary descent is exhausted
    /// (docs/SceneStreaming.md #13). Rung 0 is not the floor: under a
    /// budget the plan keeps picking objects -- individually, cheapest
    /// visible error first, never the whole scene at once -- and
    /// re-tessellates each one this much coarser again, until the
    /// model fits. An object whose scaled error reaches Level scale
    /// box error is replaced by its bounding box, which is the real
    /// floor: coarsening a deflection cannot drop a planar face below
    /// the two triangles it always has, and on a measured STEP
    /// assembly a 4x coarser tessellation removed only 19% of the
    /// primitives. 1 or less turns dynamic scaling off, and then a
    /// budget under what rung 0 costs cannot be honoured.
    static const double & getLevelScale();
    static const double & defaultLevelScale();
    static void removeLevelScale();
    static void setLevelScale(const double &v);
    static const char *docLevelScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelScaleBoxError
    ///
    /// The scaled error at which an object stops being tessellated
    /// at all and is drawn as its bounding box (12 triangles whatever
    /// its face count), expressed relative to the shape diagonal. This
    /// is where the ladder stops paying for topology it can no longer
    /// resolve: past roughly a quarter of the diagonal a re-tessellated
    /// shape and its box commit similar error, and only the box
    /// actually removes the faces. 0 or less never substitutes a box.
    static const double & getLevelScaleBoxError();
    static const double & defaultLevelScaleBoxError();
    static void removeLevelScaleBoxError();
    static void setLevelScaleBoxError(const double &v);
    static const char *docLevelScaleBoxError();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SimplifyExhausted
    ///
    /// When re-tessellating an object coarser stops removing
    /// geometry, decimate the mesh it already has instead of dropping
    /// straight to its bounding box (docs/SceneStreaming.md #13c).
    /// The descent coarsens an object by asking OCCT for a larger
    /// deflection, and that saturates: a planar face is two triangles
    /// at any deflection, so a shape of flat faces answers the same
    /// mesh however coarse the ask. Past that point the only thing
    /// that removes geometry is a representation with fewer faces.
    /// Vertex clustering is the rung between the two: it keeps the
    /// object's shape, where the bounding box does not.
    /// Rewrites the display nodes only. Nothing re-tessellates and the
    /// OCCT triangulation is untouched, so the way back is one ordinary
    /// rebuild, and each further step down clusters on a coarser grid.
    /// Face and edge numbering survive: a face that decimates away to
    /// nothing keeps its (empty) slot, because those tables are read by
    /// element number.
    /// What it gives up is exactness of the decimated rung -- section
    /// caps through it can be rough, since clustering does not preserve
    /// watertightness, and the hidden-line seam filter is dropped
    /// because a welded edge may fold a seam and a non-seam together.
    static const bool & getSimplifyExhausted();
    static const bool & defaultSimplifyExhausted();
    static void removeSimplifyExhausted();
    static void setSimplifyExhausted(const bool &v);
    static const char *docSimplifyExhausted();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SimplifyMergeParts
    ///
    /// Let the decimator weld vertices across face boundaries
    /// instead of clustering each face on its own grid.
    /// Off, no output triangle spans two faces, so a modelled crease
    /// stays a crease and each face keeps at least the triangles its
    /// own cells produce. That floor is the catch: this rung is reached
    /// precisely when a shape is mostly flat faces, and per-face
    /// clustering cannot take a two-triangle face below two triangles.
    /// On, positions and attributes cluster once over the whole mesh,
    /// which is what actually removes geometry there -- at the cost of
    /// shading round creases the model really has.
    /// Face identity survives either way: a triangle still belongs to
    /// the face it came from, so per-face colour and selection keep
    /// working. Only the geometry is shared.
    static const bool & getSimplifyMergeParts();
    static const bool & defaultSimplifyMergeParts();
    static void removeSimplifyMergeParts();
    static void setSimplifyMergeParts(const bool &v);
    static const char *docSimplifyMergeParts();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SimplifyMinReduction
    ///
    /// How much of an object's triangle count a decimation pass has
    /// to remove for the result to be kept, as a percentage.
    /// Below it the pass is refused and the descent takes its next step
    /// instead, which is the bounding box. A rung that removes almost
    /// nothing is worse than not having one: it costs a node rewrite
    /// and still holds the memory that made the plan ask.
    /// This is also what stops the descent looping. Each step clusters
    /// on a coarser grid, so a mesh that has run out of things to merge
    /// keeps answering no and the object moves on to the box.
    static const double & getSimplifyMinReduction();
    static const double & defaultSimplifyMinReduction();
    static void removeSimplifyMinReduction();
    static void setSimplifyMinReduction(const double &v);
    static const char *docSimplifyMinReduction();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShapeVertices
    ///
    /// Draw the vertex points that sit on the ends of a shape's
    /// edges (docs/SceneStreaming.md #13b). Off by default: such a point
    /// lands exactly on an edge that is already drawn, so it adds
    /// nothing to look at -- and it is not cheap. A point costs the GPU
    /// a 32-byte sprite instance record plus its index, roughly nine
    /// times what the same point occupies in the heap, which is why a
    /// CPU-currency measurement made them look negligible.
    /// All or nothing per point set: it is skipped only when EVERY one
    /// of its vertices is an edge endpoint. One floating vertex -- one
    /// no edge touches, and every point of a point cloud -- and the
    /// whole set draws, because nothing else would show it. Objects are
    /// in practice all floating or none, so a per-vertex subset would
    /// buy nothing and cost an index permutation.
    /// It never applies in the Points display mode, where the vertices
    /// are what the mode exists to show.
    /// Picking, pre-selection and selection highlighting are unaffected:
    /// the point geometry stays published and resident, the highlight
    /// draws render on top as always, and only the base-pass submission
    /// is skipped.
    static const bool & getShapeVertices();
    static const bool & defaultShapeVertices();
    static void removeShapeVertices();
    static void setShapeVertices(const bool &v);
    static const char *docShapeVertices();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PressureDropEdges
    ///
    /// Stop drawing the edges that bound faces while the GPU memory
    /// budget stands exceeded (docs/SceneStreaming.md #13b), and draw
    /// them again as soon as it does not. Edge geometry is the GPU's
    /// most expensive geometry per unit of screen information: a segment
    /// is 8 bytes of index in the heap and those 8 bytes plus a 64-byte
    /// quad-expansion instance record on the GPU.
    /// All or nothing per edge set: it is skipped only when EVERY one
    /// of its edges bounds a face, because those faces still draw and
    /// their silhouettes still read. One floating edge -- a wire, a
    /// sketch, a datum line, any edge no face uses -- and the whole set
    /// draws: it is the object, and dropping it would show nothing at
    /// all.
    /// It never applies in the Wireframe display mode, where the edges
    /// are what the mode exists to show.
    /// A display gate, not a residency change -- nothing is demoted and
    /// nothing re-tessellates, so entering and leaving it costs one
    /// frame, which is why it is spent before any rung is given up.
    /// Picking, highlighting and on-top rendering are unaffected.
    static const bool & getPressureDropEdges();
    static const bool & defaultPressureDropEdges();
    static void removePressureDropEdges();
    static void setPressureDropEdges(const bool &v);
    static const char *docPressureDropEdges();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LoadDropElements
    ///
    /// Stop drawing edges AND vertices for as long as a document is
    /// still arriving (docs/SceneStreaming.md #13b), and let the two
    /// standing gates above decide again the moment it has finished.
    /// A load is when the tier can least afford those two classes and
    /// can least use them: the faces are arriving coarse-first and
    /// being replaced under the camera, nobody inspects a vertex of a
    /// model that is still half there, and every byte not uploaded to
    /// an edge instance buffer now is one the arriving geometry gets
    /// instead.
    /// MEASURED: on a .FCStd open this currently suppresses NOTHING,
    /// and not because it fails to fire. Progressive document load
    /// parks every visual build and publishes the scene in one step
    /// when the load is done, so the renderer holds an empty scene for
    /// the whole load -- 0 drawables across 17.8s on a 5455-object
    /// model. It is kept for the case that is still real, a live
    /// progressive import, which builds its visuals inline as objects
    /// appear; that case is not yet measured.
    /// It overrides both gates while it lasts -- vertices drop even
    /// with ShapeVertices on, edges drop with no pressure yet declared
    /// -- but it is subject to the same all-or-nothing classification
    /// and the same display-mode exemptions: a wire, a sketch, a datum
    /// line or a point cloud draws throughout, because nothing else on
    /// screen would show it, and neither class is dropped in the mode
    /// that exists to show it.
    /// Costs one frame to leave, like the pressure gate, so what it
    /// holds back comes straight back when the load lets go.
    /// Applies only where coarse-first is on (CoarseTessellation 0 or
    /// above): with everything tessellated exact up front there is no
    /// progressive arrival for this to make room for.
    /// A load here means a document restoring, a progressive import
    /// filling one, or the deferred view-provider drain that follows a
    /// restore -- geometry is still being built into the view in all
    /// three.
    static const bool & getLoadDropElements();
    static const bool & defaultLoadDropElements();
    static void removeLoadDropElements();
    static void setLoadDropElements(const bool &v);
    static const char *docLoadDropElements();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EffectResolution
    ///
    /// Resolution scale (0.25-1.0) of the expensive screen-space effect
    /// passes -- the planar/ground reflection scene re-render, the water
    /// body depth prepass and screen-space ambient occlusion -- relative to
    /// the main view resolution. Lowering it trades effect sharpness for
    /// speed on large windows, where those per-pixel passes dominate the
    /// frame; the main geometry, edges, text and overlays stay full
    /// resolution. 1.0 renders the effects at full resolution. The
    /// volumetric light shafts already render at half resolution.
    static const double & getEffectResolution();
    static const double & defaultEffectResolution();
    static void removeEffectResolution();
    static void setEffectResolution(const double &v);
    static const char *docEffectResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Occlusion
    ///
    /// Skip drawing what the depth buffer proves could not have
    /// reached the screen (docs/FarFieldProxies.md §12). Bounding boxes
    /// of the spatial index's nodes are tested against the depth the
    /// occluders leave behind -- by default in a software depth buffer
    /// on the CPU (Render_OcclusionSoftware), which answers within the
    /// frame that asked -- and a node that puts no pixel through has
    /// its whole subtree skipped, one test standing for thousands of
    /// draws.
    /// 
    /// Exact, not approximate: only geometry that could not have been
    /// seen is removed, so the image is unchanged and what is saved is
    /// the draw call, which measures ~1.2-1.5us of CPU submission plus
    /// ~1.5-1.7us of GPU time whatever it contains (§10.2). It pays on
    /// assemblies that hide themselves -- an enclosed chassis, a
    /// populated rack, any interior -- and does nothing for a model
    /// that is mostly silhouette. Expect roughly a fifth of the draws
    /// from a camera inside a large assembly (§10.3); the far larger
    /// figure from outside a closed model is a bound, not a promise.
    /// 
    /// Casters and reflections are judged separately: geometry hidden
    /// from the eye still casts its shadow and still appears in the
    /// ground reflection.
    static const bool & getOcclusion();
    static const bool & defaultOcclusion();
    static void removeOcclusion();
    static void setOcclusion(const bool &v);
    static const char *docOcclusion();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionVisibleTtl
    ///
    /// How many frames a node found visible is believed before it is
    /// tested again. Higher spends fewer queries and keeps drawing
    /// geometry that has since become hidden for a little longer; lower
    /// tracks the camera more closely at the cost of more tests. Purely
    /// a cost trade -- being late here draws too much, never too
    /// little, so it cannot affect the image.
    static const long & getOcclusionVisibleTtl();
    static const long & defaultOcclusionVisibleTtl();
    static void removeOcclusionVisibleTtl();
    static void setOcclusionVisibleTtl(const long &v);
    static const char *docOcclusionVisibleTtl();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionBudget
    ///
    /// How many occlusion tests one frame may issue. The GPU offers
    /// 256 for the whole process and the RenderDebug_Occlusion
    /// measurement is the other claimant, so the default leaves that
    /// measurement room to run alongside. Asking for more tests than
    /// the budget allows is not an error: hidden nodes are offered
    /// first, since a test is the only way one can come back, and the
    /// rest are offered again next frame.
    static const long & getOcclusionBudget();
    static const long & defaultOcclusionBudget();
    static void removeOcclusionBudget();
    static void setOcclusionBudget(const long &v);
    static const char *docOcclusionBudget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionMinSubtree
    ///
    /// Do not test an index node standing for fewer drawn instances
    /// than this. A test is itself a draw, so testing a node that could
    /// save one draw loses whether it answers hidden or visible.
    static const long & getOcclusionMinSubtree();
    static const long & defaultOcclusionMinSubtree();
    static void removeOcclusionMinSubtree();
    static void setOcclusionMinSubtree(const long &v);
    static const char *docOcclusionMinSubtree();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionMaxHidden
    ///
    /// How many frames a hidden node may go without an answer before
    /// it is drawn again. A hidden node is re-tested continuously and
    /// the answer is its only way back, so if answers stop arriving --
    /// no query handles left, a dropped batch -- this is what returns
    /// the geometry instead of leaving it missing. Answers that keep
    /// confirming the node is hidden keep it hidden indefinitely, so
    /// this never flickers a node the tests are still reaching.
    static const long & getOcclusionMaxHidden();
    static const long & defaultOcclusionMaxHidden();
    static void removeOcclusionMaxHidden();
    static void setOcclusionMaxHidden(const long &v);
    static const char *docOcclusionMaxHidden();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionDepthPad
    ///
    /// How far a test box is pushed towards the viewer before it is
    /// tested, in steps of the 24-bit depth buffer. A test box has to
    /// be a conservative bound, and at the last bit of the depth buffer
    /// it is not: a small part lying flush on a large panel quantizes
    /// to the same stored depth as the panel, LEQUAL loses the tie
    /// whichever way the rasterizer rounds, and the node reports itself
    /// hidden while in plain view. Measured that way, the components on
    /// a board disappeared while the board stayed. Too large costs
    /// frame time by testing visible what could have been skipped; too
    /// small deletes geometry, so err high.
    static const long & getOcclusionDepthPad();
    static const long & defaultOcclusionDepthPad();
    static void removeOcclusionDepthPad();
    static void setOcclusionDepthPad(const long &v);
    static const char *docOcclusionDepthPad();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionConfirm
    ///
    /// How many consecutive answers of 'no pixels' a node must give
    /// before its geometry is actually skipped. 1 acts on every
    /// answer, and is what an occlusion test naively does.
    /// 
    /// A test is issued against one frame's depth and read against a
    /// later one -- it does not block, because stalling for it would
    /// cost the frame time the culling exists to save -- so while an
    /// answer is in flight, other geometry is culled and the occluders
    /// move underneath it. Acted on singly, a node tested while an
    /// occluder was still drawn gets skipped after that occluder has
    /// gone; the hole it leaves tests visible; it comes back; and it
    /// oscillates, which is a picture that flickers rather than one
    /// that is merely wrong.
    /// 
    /// Confirmations DILUTE that oscillation; measured, they do not
    /// remove it (docs/FarFieldProxies.md #12.7): the false answers
    /// arrive in runs, so tripling the confirmations bought a factor
    /// of two, and the residual damage tracks how often nodes are
    /// re-tested, which this setting cannot reach. The query path is
    /// therefore not image-stable at any value here; occlusion on the
    /// CPU (the default oracle) does not read this setting at all.
    static const long & getOcclusionConfirm();
    static const long & defaultOcclusionConfirm();
    static void removeOcclusionConfirm();
    static void setOcclusionConfirm(const long &v);
    static const char *docOcclusionConfirm();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionSoftware
    ///
    /// Answer the occlusion question with a software depth buffer on
    /// the CPU instead of hardware occlusion queries
    /// (docs/FarFieldProxies.md #12.12). The default, because it is
    /// the one oracle whose picture holds still.
    /// 
    /// A hardware query cannot be asked at the moment its answer would
    /// be right. It is issued against one frame's depth and read a
    /// frame or two later, so a node is tested after the pass that drew
    /// its own geometry and is asked to win a depth comparison against
    /// itself -- measured as boxes returning no samples at all while
    /// their contents were plainly on screen. The confirmations,
    /// lifetimes and padding beside this setting all exist to contain
    /// that, and none of them reach it.
    /// 
    /// On the CPU, occluders are rasterized and nodes tested against
    /// the same buffer in one pass, so a node is asked before its own
    /// geometry joins the buffer and the answer arrives in the frame
    /// that asked. There is no latency to age, no verdict to confirm
    /// and no query pool to run out of. It costs CPU time in a frame
    /// that is already CPU-bound, which is the trade to measure, and it
    /// behaves identically in the browser, where hardware queries do
    /// not.
    static const bool & getOcclusionSoftware();
    static const bool & defaultOcclusionSoftware();
    static void removeOcclusionSoftware();
    static void setOcclusionSoftware(const bool &v);
    static const char *docOcclusionSoftware();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionOccluderTris
    ///
    /// How many triangles the CPU occlusion buffer may rasterize in one
    /// frame. Only used when occlusion runs on the CPU.
    /// 
    /// Occluders are spent largest-on-screen first, so what the budget
    /// drops is what would have hidden least. Dropping them costs
    /// culling and never pixels: an occluder that was not rasterized
    /// simply hides nothing.
    static const long & getOcclusionOccluderTris();
    static const long & defaultOcclusionOccluderTris();
    static void removeOcclusionOccluderTris();
    static void setOcclusionOccluderTris(const long &v);
    static const char *docOcclusionOccluderTris();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionMinOccluder
    ///
    /// How large a draw must appear on screen, in pixels across its
    /// bounding box diagonal, before it is worth rasterizing into the
    /// CPU occlusion buffer. Smaller draws can hide almost nothing and
    /// spend budget that a larger one could use.
    static const long & getOcclusionMinOccluder();
    static const long & defaultOcclusionMinOccluder();
    static void removeOcclusionMinOccluder();
    static void setOcclusionMinOccluder(const long &v);
    static const char *docOcclusionMinOccluder();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionThreads
    ///
    /// How many worker threads the CPU occlusion buffer may rasterize
    /// its occluders on. 0 picks automatically, leaving the submitting
    /// thread and one other alone -- this runs in the middle of a
    /// frame, not on an idle machine.
    /// 
    /// Each worker rasterizes its own slice of the occluder list into
    /// its own buffer and the buffers are merged afterwards, so there
    /// is no locking. The merge is slightly lossy -- two two-layer
    /// blocks cannot combine into one without loss -- so a higher
    /// worker count can hide marginally less. Never more.
    static const long & getOcclusionThreads();
    static const long & defaultOcclusionThreads();
    static void removeOcclusionThreads();
    static void setOcclusionThreads(const long &v);
    static const char *docOcclusionThreads();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionSimd
    ///
    /// Let the CPU occlusion buffer discard triangles four at a time
    /// with SIMD before its exact rasterizer looks at them
    /// (docs/FarFieldProxies.md #12.14).
    /// 
    /// Two thirds of the triangles offered to the buffer cover no pixel
    /// at all -- a full-detail CAD tessellation is mostly triangles
    /// smaller than the pixel grid -- and every one of them is paid for
    /// in full before being thrown away. The pre-pass transforms and
    /// projects four at once in single precision and drops the ones that
    /// land on no pixel centre.
    /// 
    /// It cannot make the buffer claim a surface that is not there:
    /// everything it does not discard is handed to the same exact path
    /// as before, recomputed from the original vertices, and a triangle
    /// it drops in error is occlusion lost rather than geometry deleted.
    /// Turn it off to measure what it saves, not to work around a
    /// suspected fault.
    static const bool & getOcclusionSimd();
    static const bool & defaultOcclusionSimd();
    static void removeOcclusionSimd();
    static void setOcclusionSimd(const bool &v);
    static const char *docOcclusionSimd();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionResolution
    ///
    /// Resolution of the CPU occlusion buffer, as a divisor of the
    /// viewport. 1 matches the viewport.
    /// 
    /// Above 1 this can remove geometry that was visible, which is the
    /// one failure this mechanism exists to avoid: a coarse pixel is
    /// marked covered when an occluder reaches its centre, but it
    /// stands for several real pixels, and the ones the occluder missed
    /// are claimed with it. Reduce it only to measure what it costs, not
    /// as a setting.
    static const long & getOcclusionResolution();
    static const long & defaultOcclusionResolution();
    static void removeOcclusionResolution();
    static void setOcclusionResolution(const long &v);
    static const char *docOcclusionResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionPerInstance
    ///
    /// Test each object against the CPU occlusion buffer, not just the
    /// group it was partitioned into
    /// (docs/FarFieldProxies.md #12.17). Only used when occlusion runs
    /// on the CPU.
    /// 
    /// The cull walk tests boxes of groups, and a group is skipped only
    /// when all of it is hidden -- so one visible object keeps its
    /// hidden neighbours on screen. Measured, that is what limits the
    /// culling rather than the quality of the depth buffer: after a
    /// cull, 91% of what is still drawn reaches no pixel, and making
    /// the occluders ten times better barely moved it.
    /// 
    /// The extra tests are read-only against a buffer that is already
    /// finished, so they run on the same worker threads the occluders
    /// used and add no state, no latency and nothing the backend has to
    /// support.
    /// 
    /// On by default: measured on the benchmark it hides 17% more for
    /// 0.4ms, against 3% for 3.4ms from making the occluders ten times
    /// better, and it over-culls nothing. It can only ever be more
    /// correct than testing the group -- a draw is skipped when its own
    /// box is covered rather than when its neighbours' collectively
    /// are.
    static const bool & getOcclusionPerInstance();
    static const bool & defaultOcclusionPerInstance();
    static void removeOcclusionPerInstance();
    static void setOcclusionPerInstance(const bool &v);
    static const char *docOcclusionPerInstance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionDemoteStreak
    ///
    /// How many consecutive frames every draw of an object must have
    /// been culled before the level plan's downgrade sweep may treat
    /// it as free -- give its GPU upload back without charging the
    /// camera any visible error. 0 never does. Only used when
    /// occlusion runs on the CPU, whose verdicts are exact per frame.
    /// 
    /// This is occlusion acting as a MEMORY mechanism: an enclosed
    /// assembly's interior is inside the view frustum, so without a
    /// hidden verdict the plan prices its downgrade as visible error
    /// and pays for it in quality somewhere that actually shows. What
    /// the sweep drops stays resident in CPU RAM; the way back is an
    /// ordinary refine, so a verdict the camera later overturns costs
    /// one upload. The streak is the hysteresis that keeps a drifting
    /// camera from paying that upload per flap.
    static const long & getOcclusionDemoteStreak();
    static const long & defaultOcclusionDemoteStreak();
    static void removeOcclusionDemoteStreak();
    static void setOcclusionDemoteStreak(const long &v);
    static const char *docOcclusionDemoteStreak();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarse
    ///
    /// Rasterize the CPU occlusion buffer's occluders from coarse
    /// hulls instead of from their meshes
    /// (docs/FarFieldProxies.md #12.16). Only used when occlusion runs
    /// on the CPU.
    /// 
    /// An occluder does not need the mesh, it needs the surface, and a
    /// hull carries that at a fraction of the triangles. What the
    /// triangle budget above buys is what this changes: measured, 1285
    /// of 1322 candidate occluders never entered the buffer because 37
    /// full-detail draws spent the whole allowance, and the buffer then
    /// hid 45% of what was there to hide.
    /// 
    /// The hulls are built by vertex clustering from the meshes the
    /// renderer already holds -- no shape, no tessellator -- a few per
    /// frame, and cached. A hull recedes by its own measured error
    /// before it is rasterized, so it cannot claim to be nearer than
    /// the surface it stands for.
    static const bool & getOcclusionCoarse();
    static const bool & defaultOcclusionCoarse();
    static void removeOcclusionCoarse();
    static void setOcclusionCoarse(const bool &v);
    static const char *docOcclusionCoarse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarseLevel
    ///
    /// Which rung of the decimation ladder an occluder hull is built
    /// at, coarsest first: the clustering grid is an eighth of the
    /// mesh's diagonal at 0 and halves per level, so 2 is a
    /// thirty-second of it. Lower is cheaper to rasterize and further
    /// from the surface; higher approaches the mesh itself.
    static const long & getOcclusionCoarseLevel();
    static const long & defaultOcclusionCoarseLevel();
    static void removeOcclusionCoarseLevel();
    static void setOcclusionCoarseLevel(const long &v);
    static const char *docOcclusionCoarseLevel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarseMinTris
    ///
    /// How many triangles a draw must carry before it is worth a
    /// hull. Below this it is rasterized from its mesh: a hull of a
    /// small mesh saves triangles that were never what spent the
    /// budget.
    static const long & getOcclusionCoarseMinTris();
    static const long & defaultOcclusionCoarseMinTris();
    static void removeOcclusionCoarseMinTris();
    static void setOcclusionCoarseMinTris(const long &v);
    static const char *docOcclusionCoarseMinTris();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarseBuilds
    ///
    /// How many occluder hulls may be built in one frame. Building is
    /// parallel but not free, so a scene that has just come into view
    /// acquires its hulls over several frames rather than stalling one.
    /// 0 freezes the cache at what it already holds.
    static const long & getOcclusionCoarseBuilds();
    static const long & defaultOcclusionCoarseBuilds();
    static void removeOcclusionCoarseBuilds();
    static void setOcclusionCoarseBuilds(const long &v);
    static const char *docOcclusionCoarseBuilds();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarseBias
    ///
    /// How far an occluder hull recedes from the camera before it is
    /// rasterized, as a percentage of its own measured displacement.
    /// 
    /// Every point of a hull lies within that displacement of a point of
    /// the mesh it was built from, so at 100 the hull cannot be nearer
    /// than the surface it stands for -- which is what makes an
    /// approximate occluder admissible at all. Below 100 it hides more
    /// and may hide geometry that was visible; above 100 it hides
    /// progressively less for nothing. 0 rasterizes the hull where it
    /// sits, which is the measurement that says whether the bias is
    /// needed.
    static const long & getOcclusionCoarseBias();
    static const long & defaultOcclusionCoarseBias();
    static void removeOcclusionCoarseBias();
    static void setOcclusionCoarseBias(const long &v);
    static const char *docOcclusionCoarseBias();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionCoarseMemory
    ///
    /// What the occluder hull cache may hold, in megabytes, before
    /// the least recently used hulls are dropped. A dropped hull costs a
    /// rebuild when its occluder comes back into view, never
    /// correctness.
    static const long & getOcclusionCoarseMemory();
    static const long & defaultOcclusionCoarseMemory();
    static void removeOcclusionCoarseMemory();
    static void setOcclusionCoarseMemory(const long &v);
    static const char *docOcclusionCoarseMemory();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OcclusionBenefitProbe
    ///
    /// Measure whether the culling pays for itself on THIS scene and
    /// camera (docs/FarFieldProxies.md 12.13): alternate stretches of
    /// frames with the whole occlusion block on and off, compare median
    /// frame cost, and print the verdict with the culling readout
    /// (Render_LevelDebug cadence). The probe is an intervention -- its
    /// off arm draws everything and pauses the hidden-streak demote
    /// feed for those frames -- so it is a measuring instrument, not a
    /// mode to leave on. The verdict gates nothing yet; it is the
    /// number the wire-or-delete decision for CullBenefitEstimator
    /// reads.
    static const bool & getOcclusionBenefitProbe();
    static const bool & defaultOcclusionBenefitProbe();
    static void removeOcclusionBenefitProbe();
    static void setOcclusionBenefitProbe(const bool &v);
    static const char *docOcclusionBenefitProbe();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AO
    ///
    /// Enable screen space ambient occlusion of the experimental render
    /// engine (render cache mode 3 with a selected renderer type).
    static const bool & getAO();
    static const bool & defaultAO();
    static void removeAO();
    static void setAO(const bool &v);
    static const char *docAO();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Shadow
    ///
    /// Render the shadow map cast by the Shadow draw style's scene
    /// light (and the god-ray shafts / caustic occlusion that depend on
    /// it). A convenience switch to drop shadows without leaving the
    /// Shadow draw style; the base headlight and environment lighting
    /// stay, so the scene remains lit, just flatter. Has no effect unless
    /// the Shadow draw style provides a scene light.
    static const bool & getShadow();
    static const bool & defaultShadow();
    static void removeShadow();
    static void setShadow(const bool &v);
    static const char *docShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOMethod
    ///
    /// Ambient occlusion algorithm. 0 = classic hemisphere-kernel
    /// SSAO (screen-space depth-difference sampling). 1 = GTAO
    /// (ground-truth ambient occlusion, XeGTAO-style horizon-based
    /// visibility integration): physically correct occlusion falloff,
    /// tight contact shadows without the wide low-contrast wash of
    /// classic SSAO at large radii.
    static const long & getAOMethod();
    static const long & defaultAOMethod();
    static void removeAOMethod();
    static void setAOMethod(const long &v);
    static const char *docAOMethod();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSlices
    ///
    /// GTAO only: number of screen-space slice directions per pixel
    /// (XeGTAO High preset = 9). The dominant quality/cost dial —
    /// direction variance shows as blotchy grain the denoiser cannot
    /// fully flatten. Cost scales linearly.
    static const long & getAOSlices();
    static const long & defaultAOSlices();
    static void removeAOSlices();
    static void setAOSlices(const long &v);
    static const char *docAOSlices();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSteps
    ///
    /// GTAO only: horizon-march samples per slice side. More steps
    /// resolve distant occluders more stably (less mid-frequency blotch
    /// on grazing surfaces), at linear cost.
    static const long & getAOSteps();
    static const long & defaultAOSteps();
    static void removeAOSteps();
    static void setAOSteps(const long &v);
    static const char *docAOSteps();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AORadius
    ///
    /// Ambient occlusion sample radius in world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getAORadius();
    static const double & defaultAORadius();
    static void removeAORadius();
    static void setAORadius(const double &v);
    static const char *docAORadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOIntensity
    ///
    /// Ambient occlusion darkening strength.
    static const double & getAOIntensity();
    static const double & defaultAOIntensity();
    static void removeAOIntensity();
    static void setAOIntensity(const double &v);
    static const char *docAOIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOResolution
    ///
    /// Resolution scale (0.25-1.0) of the ambient occlusion resolve
    /// targets relative to the main view resolution, independent of the
    /// shared Effect resolution. Ambient occlusion is resolution-sensitive
    /// (contact and crevice detail), so it has its own control; the shared
    /// Effect resolution drives only the costlier reflection re-render.
    /// 1.0 renders the occlusion at full resolution; lower trades AO
    /// sharpness for speed.
    static const double & getAOResolution();
    static const double & defaultAOResolution();
    static void removeAOResolution();
    static void setAOResolution(const double &v);
    static const char *docAOResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBR
    ///
    /// Enable physically based shading with image based lighting of
    /// the experimental render engine (render cache mode 3 with a
    /// selected renderer type). Replaces the default headlight shading
    /// of lit surfaces with a metallic/roughness material lit by a
    /// built-in studio environment.
    static const bool & getPBR();
    static const bool & defaultPBR();
    static void removePBR();
    static void setPBR(const bool &v);
    static const char *docPBR();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRMetallic
    ///
    /// Metalness of physically based shaded surfaces, 0 to 1.
    static const double & getPBRMetallic();
    static const double & defaultPBRMetallic();
    static void removePBRMetallic();
    static void setPBRMetallic(const double &v);
    static const char *docPBRMetallic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRRoughness
    ///
    /// Roughness of physically based shaded surfaces, 0 to 1.
    /// Zero means automatic (derived from each material's shininess).
    static const double & getPBRRoughness();
    static const double & defaultPBRRoughness();
    static void removePBRRoughness();
    static void setPBRRoughness(const double &v);
    static const char *docPBRRoughness();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvIntensity
    ///
    /// Brightness of the image based lighting environment.
    static const double & getPBREnvIntensity();
    static const double & defaultPBREnvIntensity();
    static void removePBREnvIntensity();
    static void setPBREnvIntensity(const double &v);
    static const char *docPBREnvIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvImage
    ///
    /// Image file used as the image based lighting environment,
    /// replacing the built-in procedural studio environment. A 2:1
    /// image is read as equirectangular (lat-long), anything squarer
    /// as a sphere map — the same convention as the Texture mapping
    /// dialog's Environment mode, so the same file works in both.
    /// Empty falls back to that dialog's current image, then to the
    /// procedural environment.
    static const std::string & getPBREnvImage();
    static const std::string & defaultPBREnvImage();
    static void removePBREnvImage();
    static void setPBREnvImage(const std::string &v);
    static const char *docPBREnvImage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvEmbed
    ///
    /// Store a copy of the environment image inside the document,
    /// so it travels with the file instead of depending on the
    /// original path. The copy lives in the view's
    /// Render_PBREnvImageData property and takes precedence over the
    /// image path while set.
    static const bool & getPBREnvEmbed();
    static const bool & defaultPBREnvEmbed();
    static void removePBREnvEmbed();
    static void setPBREnvEmbed(const bool &v);
    static const char *docPBREnvEmbed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvBackground
    ///
    /// Show the image based lighting environment itself as the view
    /// background while PBR shading is active, so reflective surfaces
    /// visibly mirror their surroundings.
    static const bool & getPBREnvBackground();
    static const bool & defaultPBREnvBackground();
    static void removePBREnvBackground();
    static void setPBREnvBackground(const bool &v);
    static const char *docPBREnvBackground();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BumpScale
    ///
    /// Strength of bump/normal mapped surfaces (SoBumpMap) of the
    /// experimental render engine: scales the slope of normal maps and
    /// the height amplitude of grayscale bump maps.
    static const double & getBumpScale();
    static const double & defaultBumpScale();
    static void removeBumpScale();
    static void setBumpScale(const double &v);
    static const char *docBumpScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Parallax
    ///
    /// Parallax-occlusion map grayscale bump maps (SoBumpMap) of the
    /// experimental render engine, shifting the texture with the view
    /// angle for a strong relief impression.
    static const bool & getParallax();
    static const bool & defaultParallax();
    static void removeParallax();
    static void setParallax(const bool &v);
    static const char *docParallax();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Volumetric
    ///
    /// Enable volumetric lighting (light shafts) of the experimental
    /// render engine: raymarch the shadow map of the Shadow draw style
    /// through a homogeneous scattering medium. Only effective while
    /// the Shadow draw style provides a scene light.
    static const bool & getVolumetric();
    static const bool & defaultVolumetric();
    static void removeVolumetric();
    static void setVolumetric(const bool &v);
    static const char *docVolumetric();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricIntensity
    ///
    /// Brightness of the inscattered (light shaft) light.
    static const double & getVolumetricIntensity();
    static const double & defaultVolumetricIntensity();
    static void removeVolumetricIntensity();
    static void setVolumetricIntensity(const double &v);
    static const char *docVolumetricIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricDensity
    ///
    /// Scattering medium density in inverse world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getVolumetricDensity();
    static const double & defaultVolumetricDensity();
    static void removeVolumetricDensity();
    static void setVolumetricDensity(const double &v);
    static const char *docVolumetricDensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Caustics
    ///
    /// Project an animated caustic light pattern onto surfaces
    /// below the water body (objects with the Render_Water property),
    /// modulated by the shadow map. Only effective while volumetric
    /// lighting and the Shadow draw style are active.
    static const bool & getCaustics();
    static const bool & defaultCaustics();
    static void removeCaustics();
    static void setCaustics(const bool &v);
    static const char *docCaustics();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsIntensity
    ///
    /// Brightness of the projected caustic pattern.
    static const double & getCausticsIntensity();
    static const double & defaultCausticsIntensity();
    static void removeCausticsIntensity();
    static void setCausticsIntensity(const double &v);
    static const char *docCausticsIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsScale
    ///
    /// Caustic pattern cell frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getCausticsScale();
    static const double & defaultCausticsScale();
    static void removeCausticsScale();
    static void setCausticsScale(const double &v);
    static const char *docCausticsScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsSpeed
    ///
    /// Animation speed of the caustic pattern; zero freezes it.
    static const double & getCausticsSpeed();
    static const double & defaultCausticsSpeed();
    static void removeCausticsSpeed();
    static void setCausticsSpeed(const double &v);
    static const char *docCausticsSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterSurface
    ///
    /// Shade water bodies (objects with the Render_Water property)
    /// as an animated water surface: screen-space refraction of the
    /// scene behind it, Fresnel-blended environment reflection and a
    /// sun glint from the Shadow draw style light.
    static const bool & getWaterSurface();
    static const bool & defaultWaterSurface();
    static void removeWaterSurface();
    static void setWaterSurface(const bool &v);
    static const char *docWaterSurface();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveStrength
    ///
    /// Amplitude of the animated wave perturbation of the water
    /// surface normal; zero gives a flat mirror-like surface.
    static const double & getWaterWaveStrength();
    static const double & defaultWaterWaveStrength();
    static void removeWaterWaveStrength();
    static void setWaterWaveStrength(const double &v);
    static const char *docWaterWaveStrength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveScale
    ///
    /// Wave frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getWaterWaveScale();
    static const double & defaultWaterWaveScale();
    static void removeWaterWaveScale();
    static void setWaterWaveScale(const double &v);
    static const char *docWaterWaveScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveSpeed
    ///
    /// Animation speed of the water surface waves; zero freezes
    /// them.
    static const double & getWaterWaveSpeed();
    static const double & defaultWaterWaveSpeed();
    static void removeWaterWaveSpeed();
    static void setWaterWaveSpeed(const double &v);
    static const char *docWaterWaveSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterAbsorption
    ///
    /// Beer-Lambert absorption strength of the water surface
    /// refraction: the refracted scene is dimmed and tinted by the
    /// water column it travels through (channels the water color lacks
    /// are absorbed most), so the water gains body and the bottom
    /// recedes with depth. Zero = crystal clear.
    static const double & getWaterAbsorption();
    static const double & defaultWaterAbsorption();
    static void removeWaterAbsorption();
    static void setWaterAbsorption(const double &v);
    static const char *docWaterAbsorption();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterInscatter
    ///
    /// How much the water's own color is added back into the
    /// depth-absorbed refraction (in-scattering); zero leaves absorbed
    /// regions dark, one fills them with the water color.
    static const double & getWaterInscatter();
    static const double & defaultWaterInscatter();
    static void removeWaterInscatter();
    static void setWaterInscatter(const double &v);
    static const char *docWaterInscatter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRefraction
    ///
    /// Screen-space refraction of the scene behind the water
    /// surface. When off the surface shows a flat water colour instead
    /// of the see-through refracted scene.
    static const bool & getWaterRefraction();
    static const bool & defaultWaterRefraction();
    static void removeWaterRefraction();
    static void setWaterRefraction(const bool &v);
    static const char *docWaterRefraction();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterReflection
    ///
    /// Reflection on the water surface (Fresnel-blended). When off
    /// the surface only refracts. See WaterPlanarReflection for the
    /// reflection method.
    static const bool & getWaterReflection();
    static const bool & defaultWaterReflection();
    static void removeWaterReflection();
    static void setWaterReflection(const bool &v);
    static const char *docWaterReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterPlanarReflection
    ///
    /// Reflection method when WaterReflection is on: planar (a
    /// mirror-camera re-render of the scene about the water plane -
    /// exact, no taper) when true, else screen-space reflection (a
    /// cheaper per-pixel ray march that can only reflect on-screen
    /// geometry and tapers past it). The environment cubemap is the
    /// fallback for both.
    static const bool & getWaterPlanarReflection();
    static const bool & defaultWaterPlanarReflection();
    static void removeWaterPlanarReflection();
    static void setWaterPlanarReflection(const bool &v);
    static const char *docWaterPlanarReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterShadow
    ///
    /// Receive the scene light's shadow on the water surface: a
    /// shadow band on the water where a caster blocks the light and
    /// the sun glint killed there. Requires the Shadow draw style
    /// with an active shadow map; off leaves the surface fully lit.
    /// The refracted scene below the surface keeps its own shadow
    /// regardless.
    static const bool & getWaterShadow();
    static const bool & defaultWaterShadow();
    static void removeWaterShadow();
    static void setWaterShadow(const bool &v);
    static const char *docWaterShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRippleType
    ///
    /// The ambient ripple pattern on the water surface - the motion
    /// the surface has of its own accord. 0 = waves: the default sum
    /// of directional wind waves. 1 = rain: circular rings expanding
    /// from randomly placed, randomly timed drop impacts, as on a pond
    /// in rainfall. 2 = none: a still surface, which leaves only what
    /// the scene disturbs - fountain splash rings and the impact rings
    /// of particles striking the water still show.
    static const long & getWaterRippleType();
    static const long & defaultWaterRippleType();
    static void removeWaterRippleType();
    static void setWaterRippleType(const long &v);
    static const char *docWaterRippleType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRippleDensity
    ///
    /// Drop density of the rain ripple type: how many drop cells
    /// fit per wave-scale unit. Higher rains harder - more, smaller
    /// rings; lower gives sparse large rings. The wave ripple type
    /// ignores it.
    static const double & getWaterRippleDensity();
    static const double & defaultWaterRippleDensity();
    static void removeWaterRippleDensity();
    static void setWaterRippleDensity(const double &v);
    static const char *docWaterRippleDensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterImpactStrength
    ///
    /// Height of the rings raised where particles actually strike
    /// the water - a fountain's droplets landing in its own basin.
    /// Unlike the rain ripple type these are not a pattern: nothing
    /// appears unless something hits the surface, and it appears
    /// where it hit. Zero turns them off. Needs a stateful emitter
    /// whose step program reports its impacts.
    static const double & getWaterImpactStrength();
    static const double & defaultWaterImpactStrength();
    static void removeWaterImpactStrength();
    static void setWaterImpactStrength(const double &v);
    static const char *docWaterImpactStrength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterImpactLife
    ///
    /// How long an impact ring lives, in seconds - which is also
    /// how far it travels, since a ring is sized to have crossed two
    /// cells of the impact map when it dies. Longer makes slower,
    /// wider-travelling rings out of the same hits.
    static const double & getWaterImpactLife();
    static const double & defaultWaterImpactLife();
    static void removeWaterImpactLife();
    static void setWaterImpactLife(const double &v);
    static const char *docWaterImpactLife();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterShadowWobble
    ///
    /// How much the shadow band on the water surface wobbles with
    /// the wave field: the shadow is looked up at the wave-displaced
    /// surface point scaled by this factor. Zero pins the shadow
    /// boundary to the flat surface (a straight edge), one is the
    /// physical wave height, larger values exaggerate the ripple.
    static const double & getWaterShadowWobble();
    static const double & defaultWaterShadowWobble();
    static void removeWaterShadowWobble();
    static void setWaterShadowWobble(const double &v);
    static const char *docWaterShadowWobble();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Bloom
    ///
    /// Bleed a blurred glow halo from bright pixels and from
    /// light-source bodies (objects with the Render_Light property)
    /// over their surroundings.
    static const bool & getBloom();
    static const bool & defaultBloom();
    static void removeBloom();
    static void setBloom(const bool &v);
    static const char *docBloom();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomThreshold
    ///
    /// Scene brightness above which a pixel feeds the glow halo
    /// (with a soft knee below it). Light-source bodies always feed
    /// it regardless, scaled by their intensity.
    static const double & getBloomThreshold();
    static const double & defaultBloomThreshold();
    static void removeBloomThreshold();
    static void setBloomThreshold(const double &v);
    static const char *docBloomThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomIntensity
    ///
    /// Brightness multiplier of the composited glow halo.
    static const double & getBloomIntensity();
    static const double & defaultBloomIntensity();
    static void removeBloomIntensity();
    static void setBloomIntensity(const double &v);
    static const char *docBloomIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomRadius
    ///
    /// Radius scale of the glow halo. One is the default gaussian
    /// footprint; larger blooms wider.
    static const double & getBloomRadius();
    static const double & defaultBloomRadius();
    static void removeBloomRadius();
    static void setBloomRadius(const double &v);
    static const char *docBloomRadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SunDisc
    ///
    /// Draw a visible sun -- a bright disc with a limb glow -- in
    /// the sky along the Shadow draw style's directional scene light,
    /// occluded by geometry and feeding the bloom glow. Perspective
    /// cameras only; spot lights have no sky direction.
    static const bool & getSunDisc();
    static const bool & defaultSunDisc();
    static void removeSunDisc();
    static void setSunDisc(const bool &v);
    static const char *docSunDisc();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SunDiscSize
    ///
    /// Angular radius of the sun disc in degrees (the real sun is
    /// about 0.27; larger reads better in a CAD scene).
    static const double & getSunDiscSize();
    static const double & defaultSunDiscSize();
    static void removeSunDiscSize();
    static void setSunDiscSize(const double &v);
    static const char *docSunDiscSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflection
    ///
    /// Mirror the model in the shadow ground plane of the
    /// experimental render engine: the opaque scene is re-rendered
    /// with a reflected camera and blended onto the ground. Only
    /// effective while the Shadow draw style shows a ground plane.
    static const bool & getGroundReflection();
    static const bool & defaultGroundReflection();
    static void removeGroundReflection();
    static void setGroundReflection(const bool &v);
    static const char *docGroundReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflectionIntensity
    ///
    /// Blend factor of the mirrored model on the ground plane.
    static const double & getGroundReflectionIntensity();
    static const double & defaultGroundReflectionIntensity();
    static void removeGroundReflectionIntensity();
    static void setGroundReflectionIntensity(const double &v);
    static const char *docGroundReflectionIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugViewMode
    ///
    /// Render debugging buffer visualization (docs/RenderDebug.md).
    /// Routes an intermediate render target to the screen instead of the
    /// shaded scene: 1 = linearized scene depth, 2 = view-space normals,
    /// 3 = ambient occlusion term only, 4 = shadow term only, 5 = shadow
    /// map / bulb-tile coverage as color, 6 = overdraw heatmap, 7 =
    /// shadow-moment filtering-precision probe, 8 = UV / texcoord,
    /// 9 = the planar reflection target, 10 = the particle impact map
    /// (green where a hit is recorded, brightness its age, red where
    /// nothing has ever struck).
    /// 0 renders normally. The on-top, highlight and overlay passes
    /// still draw on top so the view stays navigable.
    static const long & getDebugViewMode();
    static const long & defaultDebugViewMode();
    static void removeDebugViewMode();
    static void setDebugViewMode(const long &v);
    static const char *docDebugViewMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugFreezeFrame
    ///
    /// Freeze every intentionally time- or history-dependent render
    /// input: temporal accumulation and per-frame sampling jitter, and
    /// time-driven animation (water waves, fire). Two frames of the same
    /// scene, camera and parameters then render identically -- the
    /// determinism switch for golden-image comparison
    /// (docs/RenderDebug.md).
    static const bool & getDebugFreezeFrame();
    static const bool & defaultDebugFreezeFrame();
    static void removeDebugFreezeFrame();
    static void setDebugFreezeFrame(const bool &v);
    static const char *docDebugFreezeFrame();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugLabel
    ///
    /// Burn a self-describing label into a corner of the rendered
    /// frame while render debugging: the active debug view mode, the
    /// freeze-frame state and any custom RenderDebug_* parameter values.
    /// A captured PNG then documents its own settings without its
    /// sidecar (docs/RenderDebug.md).
    static const bool & getDebugLabel();
    static const bool & defaultDebugLabel();
    static void removeDebugLabel();
    static void setDebugLabel(const bool &v);
    static const char *docDebugLabel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugTiming
    ///
    /// Log where the time of a rendered frame goes, by pipeline
    /// stage: the Coin traversal, the flattening of the vertex caches,
    /// the draw-entry build, the translation to the backend, the
    /// backend's own bookkeeping and the draw itself. One summary line
    /// per second, so a long operation shows how each stage grows with
    /// the scene rather than one average (docs/IncrementalPublish.md).
    /// Those stages end at submission, so a second line reports what
    /// happens after it: the frame's cost on the CPU issuing draw
    /// commands against its cost on the GPU drawing them, and the same
    /// pair per draw call (docs/FarFieldProxies.md §10.1). Which of the
    /// two a scene is bound by is what decides whether a culling scheme
    /// has to remove the draw or may leave it to the GPU to reject.
    static const bool & getDebugTiming();
    static const bool & defaultDebugTiming();
    static void removeDebugTiming();
    static void setDebugTiming(const bool &v);
    static const char *docDebugTiming();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugDelta
    ///
    /// Log what each published frame actually changed: how many of
    /// the scene cache's children the publish reused, how many it added
    /// or dropped, and how many separators the traversal below it reused
    /// against how many it rebuilt. One summary line per second. A
    /// publish rebuilds the whole scene however little moved, and these
    /// counts are how much of that rebuild was avoidable
    /// (docs/IncrementalPublish.md §5).
    static const bool & getDebugDelta();
    static const bool & defaultDebugDelta();
    static void removeDebugDelta();
    static void setDebugDelta(const bool &v);
    static const char *docDebugDelta();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugCoverage
    ///
    /// Log how much of the screen each drawn object actually covers,
    /// as a histogram over its projected size in pixels. A camera that
    /// sees a whole assembly draws most of it at a few pixels, and every
    /// one of those parts still costs a full object; the histogram says
    /// how much of the model is in that state, which is what decides
    /// whether aggregating distant parts is worth building
    /// (docs/FarFieldProxies.md §9).
    static const bool & getDebugCoverage();
    static const bool & defaultDebugCoverage();
    static void removeDebugCoverage();
    static void setDebugCoverage(const bool &v);
    static const char *docDebugCoverage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugProxyCut
    ///
    /// Log what a far-field cut would cost this camera, without
    /// generating anything: the drawn instances are partitioned into the
    /// spatial index of docs/FarFieldProxies.md §3, a frontier is chosen
    /// by projected error at several tolerances, and the draws that cut
    /// would issue -- one per (cell, material) proxy plus whatever stays
    /// exact -- are reported against the draws issued today. This is the
    /// number that says whether generating proxies is worth building
    /// (§11.1). Also reports the distributions that size the partition:
    /// instances and material buckets per cell, per level.
    static const bool & getDebugProxyCut();
    static const bool & defaultDebugProxyCut();
    static void removeDebugProxyCut();
    static void setDebugProxyCut(const bool &v);
    static const char *docDebugProxyCut();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugOcclusion
    ///
    /// Measure how much of what the frame draws could not have
    /// reached the screen (docs/FarFieldProxies.md §10.1). Bounding
    /// boxes of the spatial index's nodes are re-rasterized against the
    /// finished depth buffer under hardware occlusion queries, writing
    /// neither colour nor depth, and every instance is attributed to the
    /// highest node that rejects it -- so a hidden subtree is counted
    /// once, not at every level it is hidden at. Boxes bound their
    /// contents loosely and the frustum's own rejections are reported
    /// separately, so the hidden share it prints is a floor rather than
    /// an estimate. A GPU offers 256 queries at a time, so a large model
    /// takes several frames to walk and a line is printed per completed
    /// walk, never for a partial one.
    static const bool & getDebugOcclusion();
    static const bool & defaultDebugOcclusion();
    static void removeDebugOcclusion();
    static void setDebugOcclusion(const bool &v);
    static const char *docDebugOcclusion();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugProxyGen
    ///
    /// Generate real proxies for a sample of the nodes a far-field
    /// cut stops on, and report what they cost and what they commit
    /// (docs/FarFieldProxies.md §11.1c). The cut estimate above selects
    /// by a node's projected *extent* because no proxy exists yet to
    /// have an error; this one merges each (cell, material) group and
    /// decimates it, so the error it commits can be measured as a
    /// fraction of that extent -- which is the ratio that says whether
    /// the estimate reads as its 16px row or its 64px row. Reports
    /// alongside it the triangle cost against what instancing already
    /// achieves (§7.1) and how much surface area survives, since
    /// clustering deletes geometry smaller than a cell rather than
    /// shrinking it. Expensive: it builds meshes. Samples a bounded
    /// number of nodes and reports how many it skipped.
    static const bool & getDebugProxyGen();
    static const bool & defaultDebugProxyGen();
    static void removeDebugProxyGen();
    static void setDebugProxyGen(const bool &v);
    static const char *docDebugProxyGen();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugCullAudit
    ///
    /// Check what the occlusion culling skipped against what the
    /// geometry actually put on screen (docs/FarFieldProxies.md §12.9).
    /// Every other measurement of the culling compares two pictures and
    /// reports how many pixels differ, which says that something is
    /// wrong without saying what: this re-rasterizes the scene with the
    /// cull mask ignored and each draw writing its own identity instead
    /// of a colour, so the ids that own a pixel are an exact answer to
    /// which draws reach the screen. Their intersection with the mask is
    /// a list of proven over-culls -- each one a named draw with a pixel
    /// count -- and the ids that own nothing while being drawn are the
    /// converse: the headroom the culling has not taken. Reads the image
    /// back to the CPU once a second, so it costs a full-resolution
    /// transfer on the frames it reports and nothing while off. Needs a
    /// backend with texture readback, which WebGL2 is not.
    static const bool & getDebugCullAudit();
    static const bool & defaultDebugCullAudit();
    static void removeDebugCullAudit();
    static void setDebugCullAudit(const bool &v);
    static const char *docDebugCullAudit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugCullBounds
    ///
    /// Measure whether a tighter occludee volume would cull more
    /// (docs/FarFieldProxies.md §12.19). After per-instance testing, 90%
    /// of the draws a frame still submits reach no pixel while each was
    /// tested and answered visible -- so the geometry is hidden and the
    /// box around it is not. This re-asks every still-drawn row three
    /// ways against the same occluder buffer: with the world box that
    /// ships, with the mesh's own box through the model matrix (an
    /// oriented box, where the shipping one is the axis-aligned box
    /// around it), and with every triangle asked separately -- which is
    /// far too slow to ship and is here as the ceiling, since nothing
    /// asked about the occludee can beat asking about its geometry. The
    /// verdicts are counted against the cull audit's id image, never
    /// acted on, so an arm that would have deleted something visible
    /// reports itself instead of being believed.
    /// Needs the cull audit on (it supplies the image) and the software
    /// occluder pass, which owns the buffer being asked. Runs on the
    /// audit's frame only, and costs far more than a frame: it is a
    /// measurement, not a mode to leave on.
    static const bool & getDebugCullBounds();
    static const bool & defaultDebugCullBounds();
    static void removeDebugCullBounds();
    static void setDebugCullBounds(const bool &v);
    static const char *docDebugCullBounds();
    //@}
//[[[end]]]

    /// Called on any parameter change: re-selects the renderer backend on
    /// a 'Type' change, otherwise schedules a redraw of all 3D views (the
    /// render configs are re-fed to the backend every frame).
    static void onRenderParamChanged(const char *sReason);

    /// One-time migration of the pre-split Renderer* keys from the parent
    /// Preferences/View group into this Preferences/View/Render group.
    /// Called once at Gui::Application startup.
    static void migrate();

/*[[[cog
RenderParams.declare_end()
]]]*/

// Auto generated code (Tools/params_utils.py:179)
}; // class RenderParams
} // namespace Gui
//[[[end]]]

#endif // GUI_RENDER_PARAMS_H
