/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_RENDER_PARAMS_H
#define GUI_RENDER_PARAMS_H

/*[[[cog
import RenderParams
RenderParams.declare_begin()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the experimental render engine parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/View/Render"
 *
 * This class is auto generated by Gui/RenderParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/RenderParams.h Gui/RenderParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/RenderParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/RenderParams.cpp with
 * the following signature.
 * @code
 *     void RenderParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport RenderParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Type
    ///
    /// Type of the experimental render engine backend. 'Default' keeps
    /// the plain GL pipeline. Only effective with render cache mode 3.
    static const std::string & getType();
    static const std::string & defaultType();
    static void removeType();
    static void setType(const std::string &v);
    static const char *docType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EffectResolution
    ///
    /// Resolution scale (0.25-1.0) of the expensive screen-space effect
    /// passes -- the planar/ground reflection scene re-render, the water
    /// body depth prepass and screen-space ambient occlusion -- relative to
    /// the main view resolution. Lowering it trades effect sharpness for
    /// speed on large windows, where those per-pixel passes dominate the
    /// frame; the main geometry, edges, text and overlays stay full
    /// resolution. 1.0 renders the effects at full resolution. The
    /// volumetric light shafts already render at half resolution.
    static const double & getEffectResolution();
    static const double & defaultEffectResolution();
    static void removeEffectResolution();
    static void setEffectResolution(const double &v);
    static const char *docEffectResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AO
    ///
    /// Enable screen space ambient occlusion of the experimental render
    /// engine (render cache mode 3 with a selected renderer type).
    static const bool & getAO();
    static const bool & defaultAO();
    static void removeAO();
    static void setAO(const bool &v);
    static const char *docAO();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Shadow
    ///
    /// Render the shadow map cast by the Shadow draw style's scene
    /// light (and the god-ray shafts / caustic occlusion that depend on
    /// it). A convenience switch to drop shadows without leaving the
    /// Shadow draw style; the base headlight and environment lighting
    /// stay, so the scene remains lit, just flatter. Has no effect unless
    /// the Shadow draw style provides a scene light.
    static const bool & getShadow();
    static const bool & defaultShadow();
    static void removeShadow();
    static void setShadow(const bool &v);
    static const char *docShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOMethod
    ///
    /// Ambient occlusion algorithm. 0 = classic hemisphere-kernel
    /// SSAO (screen-space depth-difference sampling). 1 = GTAO
    /// (ground-truth ambient occlusion, XeGTAO-style horizon-based
    /// visibility integration): physically correct occlusion falloff,
    /// tight contact shadows without the wide low-contrast wash of
    /// classic SSAO at large radii.
    static const long & getAOMethod();
    static const long & defaultAOMethod();
    static void removeAOMethod();
    static void setAOMethod(const long &v);
    static const char *docAOMethod();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSlices
    ///
    /// GTAO only: number of screen-space slice directions per pixel
    /// (XeGTAO High preset = 9). The dominant quality/cost dial —
    /// direction variance shows as blotchy grain the denoiser cannot
    /// fully flatten. Cost scales linearly.
    static const long & getAOSlices();
    static const long & defaultAOSlices();
    static void removeAOSlices();
    static void setAOSlices(const long &v);
    static const char *docAOSlices();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSteps
    ///
    /// GTAO only: horizon-march samples per slice side. More steps
    /// resolve distant occluders more stably (less mid-frequency blotch
    /// on grazing surfaces), at linear cost.
    static const long & getAOSteps();
    static const long & defaultAOSteps();
    static void removeAOSteps();
    static void setAOSteps(const long &v);
    static const char *docAOSteps();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AORadius
    ///
    /// Ambient occlusion sample radius in world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getAORadius();
    static const double & defaultAORadius();
    static void removeAORadius();
    static void setAORadius(const double &v);
    static const char *docAORadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOIntensity
    ///
    /// Ambient occlusion darkening strength.
    static const double & getAOIntensity();
    static const double & defaultAOIntensity();
    static void removeAOIntensity();
    static void setAOIntensity(const double &v);
    static const char *docAOIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOResolution
    ///
    /// Resolution scale (0.25-1.0) of the ambient occlusion resolve
    /// targets relative to the main view resolution, independent of the
    /// shared Effect resolution. Ambient occlusion is resolution-sensitive
    /// (contact and crevice detail), so it has its own control; the shared
    /// Effect resolution drives only the costlier reflection re-render.
    /// 1.0 renders the occlusion at full resolution; lower trades AO
    /// sharpness for speed.
    static const double & getAOResolution();
    static const double & defaultAOResolution();
    static void removeAOResolution();
    static void setAOResolution(const double &v);
    static const char *docAOResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBR
    ///
    /// Enable physically based shading with image based lighting of
    /// the experimental render engine (render cache mode 3 with a
    /// selected renderer type). Replaces the default headlight shading
    /// of lit surfaces with a metallic/roughness material lit by a
    /// built-in studio environment.
    static const bool & getPBR();
    static const bool & defaultPBR();
    static void removePBR();
    static void setPBR(const bool &v);
    static const char *docPBR();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRMetallic
    ///
    /// Metalness of physically based shaded surfaces, 0 to 1.
    static const double & getPBRMetallic();
    static const double & defaultPBRMetallic();
    static void removePBRMetallic();
    static void setPBRMetallic(const double &v);
    static const char *docPBRMetallic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRRoughness
    ///
    /// Roughness of physically based shaded surfaces, 0 to 1.
    /// Zero means automatic (derived from each material's shininess).
    static const double & getPBRRoughness();
    static const double & defaultPBRRoughness();
    static void removePBRRoughness();
    static void setPBRRoughness(const double &v);
    static const char *docPBRRoughness();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvIntensity
    ///
    /// Brightness of the image based lighting environment.
    static const double & getPBREnvIntensity();
    static const double & defaultPBREnvIntensity();
    static void removePBREnvIntensity();
    static void setPBREnvIntensity(const double &v);
    static const char *docPBREnvIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BumpScale
    ///
    /// Strength of bump/normal mapped surfaces (SoBumpMap) of the
    /// experimental render engine: scales the slope of normal maps and
    /// the height amplitude of grayscale bump maps.
    static const double & getBumpScale();
    static const double & defaultBumpScale();
    static void removeBumpScale();
    static void setBumpScale(const double &v);
    static const char *docBumpScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Parallax
    ///
    /// Parallax-occlusion map grayscale bump maps (SoBumpMap) of the
    /// experimental render engine, shifting the texture with the view
    /// angle for a strong relief impression.
    static const bool & getParallax();
    static const bool & defaultParallax();
    static void removeParallax();
    static void setParallax(const bool &v);
    static const char *docParallax();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Volumetric
    ///
    /// Enable volumetric lighting (light shafts) of the experimental
    /// render engine: raymarch the shadow map of the Shadow draw style
    /// through a homogeneous scattering medium. Only effective while
    /// the Shadow draw style provides a scene light.
    static const bool & getVolumetric();
    static const bool & defaultVolumetric();
    static void removeVolumetric();
    static void setVolumetric(const bool &v);
    static const char *docVolumetric();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricIntensity
    ///
    /// Brightness of the inscattered (light shaft) light.
    static const double & getVolumetricIntensity();
    static const double & defaultVolumetricIntensity();
    static void removeVolumetricIntensity();
    static void setVolumetricIntensity(const double &v);
    static const char *docVolumetricIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricDensity
    ///
    /// Scattering medium density in inverse world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getVolumetricDensity();
    static const double & defaultVolumetricDensity();
    static void removeVolumetricDensity();
    static void setVolumetricDensity(const double &v);
    static const char *docVolumetricDensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Caustics
    ///
    /// Project an animated caustic light pattern onto surfaces
    /// below the water body (objects with the Render_Water property),
    /// modulated by the shadow map. Only effective while volumetric
    /// lighting and the Shadow draw style are active.
    static const bool & getCaustics();
    static const bool & defaultCaustics();
    static void removeCaustics();
    static void setCaustics(const bool &v);
    static const char *docCaustics();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsIntensity
    ///
    /// Brightness of the projected caustic pattern.
    static const double & getCausticsIntensity();
    static const double & defaultCausticsIntensity();
    static void removeCausticsIntensity();
    static void setCausticsIntensity(const double &v);
    static const char *docCausticsIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsScale
    ///
    /// Caustic pattern cell frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getCausticsScale();
    static const double & defaultCausticsScale();
    static void removeCausticsScale();
    static void setCausticsScale(const double &v);
    static const char *docCausticsScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsSpeed
    ///
    /// Animation speed of the caustic pattern; zero freezes it.
    static const double & getCausticsSpeed();
    static const double & defaultCausticsSpeed();
    static void removeCausticsSpeed();
    static void setCausticsSpeed(const double &v);
    static const char *docCausticsSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterSurface
    ///
    /// Shade water bodies (objects with the Render_Water property)
    /// as an animated water surface: screen-space refraction of the
    /// scene behind it, Fresnel-blended environment reflection and a
    /// sun glint from the Shadow draw style light.
    static const bool & getWaterSurface();
    static const bool & defaultWaterSurface();
    static void removeWaterSurface();
    static void setWaterSurface(const bool &v);
    static const char *docWaterSurface();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveStrength
    ///
    /// Amplitude of the animated wave perturbation of the water
    /// surface normal; zero gives a flat mirror-like surface.
    static const double & getWaterWaveStrength();
    static const double & defaultWaterWaveStrength();
    static void removeWaterWaveStrength();
    static void setWaterWaveStrength(const double &v);
    static const char *docWaterWaveStrength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveScale
    ///
    /// Wave frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getWaterWaveScale();
    static const double & defaultWaterWaveScale();
    static void removeWaterWaveScale();
    static void setWaterWaveScale(const double &v);
    static const char *docWaterWaveScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveSpeed
    ///
    /// Animation speed of the water surface waves; zero freezes
    /// them.
    static const double & getWaterWaveSpeed();
    static const double & defaultWaterWaveSpeed();
    static void removeWaterWaveSpeed();
    static void setWaterWaveSpeed(const double &v);
    static const char *docWaterWaveSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterAbsorption
    ///
    /// Beer-Lambert absorption strength of the water surface
    /// refraction: the refracted scene is dimmed and tinted by the
    /// water column it travels through (channels the water color lacks
    /// are absorbed most), so the water gains body and the bottom
    /// recedes with depth. Zero = crystal clear.
    static const double & getWaterAbsorption();
    static const double & defaultWaterAbsorption();
    static void removeWaterAbsorption();
    static void setWaterAbsorption(const double &v);
    static const char *docWaterAbsorption();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterInscatter
    ///
    /// How much the water's own color is added back into the
    /// depth-absorbed refraction (in-scattering); zero leaves absorbed
    /// regions dark, one fills them with the water color.
    static const double & getWaterInscatter();
    static const double & defaultWaterInscatter();
    static void removeWaterInscatter();
    static void setWaterInscatter(const double &v);
    static const char *docWaterInscatter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRefraction
    ///
    /// Screen-space refraction of the scene behind the water
    /// surface. When off the surface shows a flat water colour instead
    /// of the see-through refracted scene.
    static const bool & getWaterRefraction();
    static const bool & defaultWaterRefraction();
    static void removeWaterRefraction();
    static void setWaterRefraction(const bool &v);
    static const char *docWaterRefraction();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterReflection
    ///
    /// Reflection on the water surface (Fresnel-blended). When off
    /// the surface only refracts. See WaterPlanarReflection for the
    /// reflection method.
    static const bool & getWaterReflection();
    static const bool & defaultWaterReflection();
    static void removeWaterReflection();
    static void setWaterReflection(const bool &v);
    static const char *docWaterReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterPlanarReflection
    ///
    /// Reflection method when WaterReflection is on: planar (a
    /// mirror-camera re-render of the scene about the water plane -
    /// exact, no taper) when true, else screen-space reflection (a
    /// cheaper per-pixel ray march that can only reflect on-screen
    /// geometry and tapers past it). The environment cubemap is the
    /// fallback for both.
    static const bool & getWaterPlanarReflection();
    static const bool & defaultWaterPlanarReflection();
    static void removeWaterPlanarReflection();
    static void setWaterPlanarReflection(const bool &v);
    static const char *docWaterPlanarReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterShadow
    ///
    /// Receive the scene light's shadow on the water surface: a
    /// shadow band on the water where a caster blocks the light and
    /// the sun glint killed there. Requires the Shadow draw style
    /// with an active shadow map; off leaves the surface fully lit.
    /// The refracted scene below the surface keeps its own shadow
    /// regardless.
    static const bool & getWaterShadow();
    static const bool & defaultWaterShadow();
    static void removeWaterShadow();
    static void setWaterShadow(const bool &v);
    static const char *docWaterShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflection
    ///
    /// Mirror the model in the shadow ground plane of the
    /// experimental render engine: the opaque scene is re-rendered
    /// with a reflected camera and blended onto the ground. Only
    /// effective while the Shadow draw style shows a ground plane.
    static const bool & getGroundReflection();
    static const bool & defaultGroundReflection();
    static void removeGroundReflection();
    static void setGroundReflection(const bool &v);
    static const char *docGroundReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflectionIntensity
    ///
    /// Blend factor of the mirrored model on the ground plane.
    static const double & getGroundReflectionIntensity();
    static const double & defaultGroundReflectionIntensity();
    static void removeGroundReflectionIntensity();
    static void setGroundReflectionIntensity(const double &v);
    static const char *docGroundReflectionIntensity();
    //@}
//[[[end]]]

    /// Called on any parameter change: re-selects the renderer backend on
    /// a 'Type' change, otherwise schedules a redraw of all 3D views (the
    /// render configs are re-fed to the backend every frame).
    static void onRenderParamChanged(const char *sReason);

    /// One-time migration of the pre-split Renderer* keys from the parent
    /// Preferences/View group into this Preferences/View/Render group.
    /// Called once at Gui::Application startup.
    static void migrate();

/*[[[cog
RenderParams.declare_end()
]]]*/

// Auto generated code (Tools/params_utils.py:179)
}; // class RenderParams
} // namespace Gui
//[[[end]]]

#endif // GUI_RENDER_PARAMS_H
