/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_RENDER_PARAMS_H
#define GUI_RENDER_PARAMS_H

/*[[[cog
import RenderParams
RenderParams.declare_begin()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the experimental render engine parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/View/Render"
 *
 * This class is auto generated by Gui/RenderParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/RenderParams.h Gui/RenderParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/RenderParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/RenderParams.cpp with
 * the following signature.
 * @code
 *     void RenderParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport RenderParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Type
    ///
    /// Type of the experimental render engine backend. 'Default' keeps
    /// the plain GL pipeline. Only effective with render cache mode 3.
    static const std::string & getType();
    static const std::string & defaultType();
    static void removeType();
    static void setType(const std::string &v);
    static const char *docType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseTessellation
    ///
    /// Ladder level shapes are tessellated at under coarse-first
    /// (docs/SceneStreaming.md #7): the display mesh is built at this
    /// rung of the fidelity ladder and the exact tessellation is
    /// declared unbuilt, generated on demand when a camera asks for it.
    /// 0 is the coarsest rung, each level halves the error; -1 always
    /// tessellates exact up front (pre-ladder behavior).
    /// 
    /// Consulted whenever something can deliver the exact rung on
    /// demand, which is a scene stream server (its viewers ask) OR a
    /// desktop view in render cache mode 3 whose backend drives mesh
    /// levels (its own level plan asks when the camera settles) - see
    /// PartGui::coarseTessellationLevel. Plain Coin display has neither
    /// and keeps the exact tessellation, because a coarse build there
    /// would stay coarse forever. This is not a serving-only feature,
    /// and it does engage for geometry built while a document loads.
    /// 
    /// What a serving process lacks is not this setting but the local
    /// level plan, which is disabled there - its rungs refine only where
    /// a connected viewer's camera asks, so with no viewer attached they
    /// stay coarse, while a desktop view refines its own. That, not the
    /// setting, is why the two publish different geometry for one
    /// document (measured on a 40-object scene: 8310 vertices serving,
    /// 25595 on the desktop). Desktop refinement is tolerance-limited,
    /// so what it settles at is a property of the framing.
    /// 
    /// A level whose rung is already finer than a shape's exact
    /// tessellation coarsens nothing, so on small shapes the low levels
    /// do nothing visible - the default 2 is a no-op on a scene of small
    /// ellipsoids that level 0 visibly coarsens.
    /// 
    /// The FC_COARSE_TESSELLATION environment variable overrides this for
    /// a whole process and returns before the gate is evaluated, so it
    /// forces coarse-first on where the gate would have refused. Takes
    /// effect when a shape (re)tessellates.
    static const long & getCoarseTessellation();
    static const long & defaultCoarseTessellation();
    static void removeCoarseTessellation();
    static void setCoarseTessellation(const long &v);
    static const char *docCoarseTessellation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseDeferFaces
    ///
    /// During a progressive import on the bgfx renderer, a shape with
    /// more faces than this gets a bounding-box stand-in immediately and
    /// even its coarse tessellation is built on the refine worker pool,
    /// swapped in when it arrives (docs/SceneStreaming.md #13) - the
    /// import stall otherwise scales with the largest single part. -1
    /// disables the stand-in so every shape tessellates inline.
    static const long & getCoarseDeferFaces();
    static const long & defaultCoarseDeferFaces();
    static void removeCoarseDeferFaces();
    static void setCoarseDeferFaces(const long &v);
    static const char *docCoarseDeferFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelThreads
    ///
    /// How many mesh level builds (the scene server's on-demand
    /// re-tessellations, docs/SceneStreaming.md #7) may run at once.
    /// 0 sizes the pool automatically - modest, because each BRepMesh
    /// build already parallelizes internally over OCCT's shared thread
    /// pool. The FC_LEVEL_THREADS environment variable overrides it.
    /// Read when the server spawns its first level worker.
    static const long & getLevelThreads();
    static const long & defaultLevelThreads();
    static void removeLevelThreads();
    static void setLevelThreads(const long &v);
    static const char *docLevelThreads();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelMemoryFloorMB
    ///
    /// Available system memory below which an exact re-tessellation
    /// will not start (docs/SceneStreaming.md #13): the desktop refine
    /// worker checks the system's own estimate of allocatable memory
    /// before each exact build, and dropping under this floor counts as
    /// a memory-ceiling observation - the same as a caught allocation
    /// failure - after which the level plans also demote exact meshes
    /// the camera would not miss back to their resident coarse rung.
    /// 0 sizes the floor automatically (at least 512 MB, or 1/16 of
    /// physical memory if that is more). Read when the first refine is
    /// queued.
    static const long & getLevelMemoryFloorMB();
    static const long & defaultLevelMemoryFloorMB();
    static void removeLevelMemoryFloorMB();
    static void setLevelMemoryFloorMB(const long &v);
    static const char *docLevelMemoryFloorMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GpuMemoryBudgetMB
    ///
    /// GPU geometry budget of the desktop mesh-level plan
    /// (docs/SceneStreaming.md #13): while the uploaded geometry exceeds
    /// it, a camera pause downgrades the *displayed* mesh of objects the
    /// camera would not miss - off screen, or coarse within half the
    /// Level tolerance - back to their coarse rung. Their exact meshes
    /// stay in CPU RAM, so zooming back in re-activates them instantly,
    /// with no re-tessellation. 0 means automatic: the graphics API's
    /// own reported GPU memory limit where it states one (Direct3D and
    /// Vulkan do; OpenGL reports nothing, and then no budget applies).
    static const long & getGpuMemoryBudgetMB();
    static const long & defaultGpuMemoryBudgetMB();
    static void removeGpuMemoryBudgetMB();
    static void setGpuMemoryBudgetMB(const long &v);
    static const char *docGpuMemoryBudgetMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LevelTolerance
    ///
    /// Screen-space error, in pixels, a coarse tessellation may
    /// commit before the exact one is built (docs/SceneStreaming.md
    /// #13): on a coarse-first desktop view (render cache mode 3 with
    /// a backend that drives the level plan), a camera pause re-plans
    /// the scene and only objects whose coarse mesh errs by more than
    /// this many pixels on screen re-tessellate exactly - off-screen
    /// and distant objects stay at the cheap coarse mesh until the
    /// camera makes them matter. 0 or less refines everything
    /// immediately; larger keeps more of the scene coarse. The
    /// streamed viewer's own tolerance is its lodpx URL parameter
    /// (same meaning, same default).
    static const double & getLevelTolerance();
    static const double & defaultLevelTolerance();
    static void removeLevelTolerance();
    static void setLevelTolerance(const double &v);
    static const char *docLevelTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EffectResolution
    ///
    /// Resolution scale (0.25-1.0) of the expensive screen-space effect
    /// passes -- the planar/ground reflection scene re-render, the water
    /// body depth prepass and screen-space ambient occlusion -- relative to
    /// the main view resolution. Lowering it trades effect sharpness for
    /// speed on large windows, where those per-pixel passes dominate the
    /// frame; the main geometry, edges, text and overlays stay full
    /// resolution. 1.0 renders the effects at full resolution. The
    /// volumetric light shafts already render at half resolution.
    static const double & getEffectResolution();
    static const double & defaultEffectResolution();
    static void removeEffectResolution();
    static void setEffectResolution(const double &v);
    static const char *docEffectResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AO
    ///
    /// Enable screen space ambient occlusion of the experimental render
    /// engine (render cache mode 3 with a selected renderer type).
    static const bool & getAO();
    static const bool & defaultAO();
    static void removeAO();
    static void setAO(const bool &v);
    static const char *docAO();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Shadow
    ///
    /// Render the shadow map cast by the Shadow display style's scene
    /// light (and the god-ray shafts / caustic occlusion that depend on
    /// it). A convenience switch to drop shadows without leaving the
    /// Shadow display style; the base headlight and environment lighting
    /// stay, so the scene remains lit, just flatter. Has no effect unless
    /// the Shadow display style provides a scene light.
    static const bool & getShadow();
    static const bool & defaultShadow();
    static void removeShadow();
    static void setShadow(const bool &v);
    static const char *docShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOMethod
    ///
    /// Ambient occlusion algorithm. 0 = classic hemisphere-kernel
    /// SSAO (screen-space depth-difference sampling). 1 = GTAO
    /// (ground-truth ambient occlusion, XeGTAO-style horizon-based
    /// visibility integration): physically correct occlusion falloff,
    /// tight contact shadows without the wide low-contrast wash of
    /// classic SSAO at large radii.
    static const long & getAOMethod();
    static const long & defaultAOMethod();
    static void removeAOMethod();
    static void setAOMethod(const long &v);
    static const char *docAOMethod();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSlices
    ///
    /// GTAO only: number of screen-space slice directions per pixel
    /// (XeGTAO High preset = 9). The dominant quality/cost dial —
    /// direction variance shows as blotchy grain the denoiser cannot
    /// fully flatten. Cost scales linearly.
    static const long & getAOSlices();
    static const long & defaultAOSlices();
    static void removeAOSlices();
    static void setAOSlices(const long &v);
    static const char *docAOSlices();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOSteps
    ///
    /// GTAO only: horizon-march samples per slice side. More steps
    /// resolve distant occluders more stably (less mid-frequency blotch
    /// on grazing surfaces), at linear cost.
    static const long & getAOSteps();
    static const long & defaultAOSteps();
    static void removeAOSteps();
    static void setAOSteps(const long &v);
    static const char *docAOSteps();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AORadius
    ///
    /// Ambient occlusion sample radius in world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getAORadius();
    static const double & defaultAORadius();
    static void removeAORadius();
    static void setAORadius(const double &v);
    static const char *docAORadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOIntensity
    ///
    /// Ambient occlusion darkening strength.
    static const double & getAOIntensity();
    static const double & defaultAOIntensity();
    static void removeAOIntensity();
    static void setAOIntensity(const double &v);
    static const char *docAOIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AOResolution
    ///
    /// Resolution scale (0.25-1.0) of the ambient occlusion resolve
    /// targets relative to the main view resolution, independent of the
    /// shared Effect resolution. Ambient occlusion is resolution-sensitive
    /// (contact and crevice detail), so it has its own control; the shared
    /// Effect resolution drives only the costlier reflection re-render.
    /// 1.0 renders the occlusion at full resolution; lower trades AO
    /// sharpness for speed.
    static const double & getAOResolution();
    static const double & defaultAOResolution();
    static void removeAOResolution();
    static void setAOResolution(const double &v);
    static const char *docAOResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Cavity
    ///
    /// Enable screen space cavity (curvature) shading of the
    /// experimental render engine (render cache mode 3 with a selected
    /// renderer type). Darkens concave creases and convex ridges found
    /// in the geometry prepass normals, which makes surface shape and
    /// small features read without relying on the lighting -- the
    /// inspection shading a CAD workbench view wants. Independent of
    /// ambient occlusion: cavity is a local curvature term, occlusion
    /// is a visibility integral over a world-space radius (contact
    /// darkening). They compose.
    static const bool & getCavity();
    static const bool & defaultCavity();
    static void removeCavity();
    static void setCavity(const bool &v);
    static const char *docCavity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CavityRadius
    ///
    /// Baseline the cavity curvature is measured over, in pixels.
    /// 
    /// This decides which features the pass can see at all. The term
    /// reads how far the surface normal turns between the two
    /// neighbours, so at 1 it sees only what turns within a single
    /// pixel -- a hard crease, and almost nothing of a smooth surface,
    /// whose normal moves by a fraction of a degree per pixel. Widening
    /// it brings broad curvature (fillets, blends, a sculpted face) in,
    /// at the cost of spreading a hard crease into a band of this
    /// width. Being in pixels it is resolution-relative: the same value
    /// covers less of the model on a high-DPI display.
    static const double & getCavityRadius();
    static const double & defaultCavityRadius();
    static void removeCavityRadius();
    static void setCavityRadius(const double &v);
    static const char *docCavityRadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CavityValley
    ///
    /// Cavity darkening strength in concave creases (inside corners,
    /// fillets, pockets). Zero disables the valley term.
    static const double & getCavityValley();
    static const double & defaultCavityValley();
    static void removeCavityValley();
    static void setCavityValley(const double &v);
    static const char *docCavityValley();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CavityRidge
    ///
    /// Cavity darkening strength on convex ridges (outside corners,
    /// chamfers). Reads as a soft contour along edges. Zero disables the
    /// ridge term.
    /// 
    /// Both terms darken: the pass multiplies the finished 8-bit scene
    /// color, which cannot brighten past white, so the ridge highlight
    /// some workbench renderers use is not available here.
    static const double & getCavityRidge();
    static const double & defaultCavityRidge();
    static void removeCavityRidge();
    static void setCavityRidge(const double &v);
    static const char *docCavityRidge();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Matcap
    ///
    /// Enable matcap shading of the experimental render engine
    /// (render cache mode 3 with a selected renderer type). Replaces
    /// the scene's lighting with a fixed studio attached to the camera,
    /// looked up by each fragment's view space normal: the shading of a
    /// surface then depends only on which way it faces the viewer, so
    /// form reads identically wherever the scene light happens to be.
    /// The classic inspection shading -- pair it with Cavity for edge
    /// definition. Overrides physically based shading while on.
    static const bool & getMatcap();
    static const bool & defaultMatcap();
    static void removeMatcap();
    static void setMatcap(const bool &v);
    static const char *docMatcap();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MatcapPreset
    ///
    /// Which matcap to shade with. The presets are computed in the
    /// shader rather than sampled from images, so they cost no assets
    /// and stay sharp at any resolution. Studio = soft key light with a
    /// rim; Clay = matte, no highlight, the most neutral read of form;
    /// Metal = banded sweep with a hard edge, exaggerates curvature;
    /// Pearl = warm/cool dual tone, shows shallow undulation.
    static const long & getMatcapPreset();
    static const long & defaultMatcapPreset();
    static void removeMatcapPreset();
    static void setMatcapPreset(const long &v);
    static const char *docMatcapPreset();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MatcapTint
    ///
    /// How much each object's own color tints the matcap, 0 to 1.
    /// Zero shades the whole scene as one uniform material, which is
    /// what makes shape comparable across parts; one multiplies the
    /// matcap by the object color, keeping the assembly's color coding
    /// at the cost of some of that uniformity.
    static const double & getMatcapTint();
    static const double & defaultMatcapTint();
    static void removeMatcapTint();
    static void setMatcapTint(const double &v);
    static const char *docMatcapTint();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBR
    ///
    /// Enable physically based shading with image based lighting of
    /// the experimental render engine (render cache mode 3 with a
    /// selected renderer type). Replaces the default headlight shading
    /// of lit surfaces with a metallic/roughness material lit by a
    /// built-in studio environment.
    static const bool & getPBR();
    static const bool & defaultPBR();
    static void removePBR();
    static void setPBR(const bool &v);
    static const char *docPBR();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRMetallic
    ///
    /// Metalness of physically based shaded surfaces, 0 to 1.
    static const double & getPBRMetallic();
    static const double & defaultPBRMetallic();
    static void removePBRMetallic();
    static void setPBRMetallic(const double &v);
    static const char *docPBRMetallic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBRRoughness
    ///
    /// Roughness of physically based shaded surfaces, 0 to 1.
    /// Zero means automatic (derived from each material's shininess).
    static const double & getPBRRoughness();
    static const double & defaultPBRRoughness();
    static void removePBRRoughness();
    static void setPBRRoughness(const double &v);
    static const char *docPBRRoughness();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvIntensity
    ///
    /// Brightness of the image based lighting environment.
    static const double & getPBREnvIntensity();
    static const double & defaultPBREnvIntensity();
    static void removePBREnvIntensity();
    static void setPBREnvIntensity(const double &v);
    static const char *docPBREnvIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvImage
    ///
    /// Image file used as the image based lighting environment,
    /// replacing the built-in procedural studio environment. A 2:1
    /// image is read as equirectangular (lat-long), anything squarer
    /// as a sphere map — the same convention as the Texture mapping
    /// dialog's Environment mode, so the same file works in both.
    /// Empty falls back to that dialog's current image, then to the
    /// procedural environment.
    static const std::string & getPBREnvImage();
    static const std::string & defaultPBREnvImage();
    static void removePBREnvImage();
    static void setPBREnvImage(const std::string &v);
    static const char *docPBREnvImage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvEmbed
    ///
    /// Store a copy of the environment image inside the document,
    /// so it travels with the file instead of depending on the
    /// original path. The copy lives in the view's
    /// Render_PBREnvImageData property and takes precedence over the
    /// image path while set.
    static const bool & getPBREnvEmbed();
    static const bool & defaultPBREnvEmbed();
    static void removePBREnvEmbed();
    static void setPBREnvEmbed(const bool &v);
    static const char *docPBREnvEmbed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PBREnvBackground
    ///
    /// Show the image based lighting environment itself as the view
    /// background while PBR shading is active, so reflective surfaces
    /// visibly mirror their surroundings.
    static const bool & getPBREnvBackground();
    static const bool & defaultPBREnvBackground();
    static void removePBREnvBackground();
    static void setPBREnvBackground(const bool &v);
    static const char *docPBREnvBackground();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BumpScale
    ///
    /// Strength of bump/normal mapped surfaces (SoBumpMap) of the
    /// experimental render engine: scales the slope of normal maps and
    /// the height amplitude of grayscale bump maps.
    static const double & getBumpScale();
    static const double & defaultBumpScale();
    static void removeBumpScale();
    static void setBumpScale(const double &v);
    static const char *docBumpScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Parallax
    ///
    /// Parallax-occlusion map grayscale bump maps (SoBumpMap) of the
    /// experimental render engine, shifting the texture with the view
    /// angle for a strong relief impression.
    static const bool & getParallax();
    static const bool & defaultParallax();
    static void removeParallax();
    static void setParallax(const bool &v);
    static const char *docParallax();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Volumetric
    ///
    /// Enable volumetric lighting (light shafts) of the experimental
    /// render engine: raymarch the shadow map of the Shadow display style
    /// through a homogeneous scattering medium. Only effective while
    /// the Shadow display style provides a scene light.
    static const bool & getVolumetric();
    static const bool & defaultVolumetric();
    static void removeVolumetric();
    static void setVolumetric(const bool &v);
    static const char *docVolumetric();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricIntensity
    ///
    /// Brightness of the inscattered (light shaft) light.
    static const double & getVolumetricIntensity();
    static const double & defaultVolumetricIntensity();
    static void removeVolumetricIntensity();
    static void setVolumetricIntensity(const double &v);
    static const char *docVolumetricIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VolumetricDensity
    ///
    /// Scattering medium density in inverse world units.
    /// Zero means automatic (a fraction of the scene size).
    static const double & getVolumetricDensity();
    static const double & defaultVolumetricDensity();
    static void removeVolumetricDensity();
    static void setVolumetricDensity(const double &v);
    static const char *docVolumetricDensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Caustics
    ///
    /// Project an animated caustic light pattern onto surfaces
    /// below the water body (objects with the Render_Water property),
    /// modulated by the shadow map. Only effective while volumetric
    /// lighting and the Shadow display style are active.
    static const bool & getCaustics();
    static const bool & defaultCaustics();
    static void removeCaustics();
    static void setCaustics(const bool &v);
    static const char *docCaustics();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsIntensity
    ///
    /// Brightness of the projected caustic pattern.
    static const double & getCausticsIntensity();
    static const double & defaultCausticsIntensity();
    static void removeCausticsIntensity();
    static void setCausticsIntensity(const double &v);
    static const char *docCausticsIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsScale
    ///
    /// Caustic pattern cell frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getCausticsScale();
    static const double & defaultCausticsScale();
    static void removeCausticsScale();
    static void setCausticsScale(const double &v);
    static const char *docCausticsScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CausticsSpeed
    ///
    /// Animation speed of the caustic pattern; zero freezes it.
    static const double & getCausticsSpeed();
    static const double & defaultCausticsSpeed();
    static void removeCausticsSpeed();
    static void setCausticsSpeed(const double &v);
    static const char *docCausticsSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterSurface
    ///
    /// Shade water bodies (objects with the Render_Water property)
    /// as an animated water surface: screen-space refraction of the
    /// scene behind it, Fresnel-blended environment reflection and a
    /// sun glint from the Shadow display style light.
    static const bool & getWaterSurface();
    static const bool & defaultWaterSurface();
    static void removeWaterSurface();
    static void setWaterSurface(const bool &v);
    static const char *docWaterSurface();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveStrength
    ///
    /// Amplitude of the animated wave perturbation of the water
    /// surface normal; zero gives a flat mirror-like surface.
    static const double & getWaterWaveStrength();
    static const double & defaultWaterWaveStrength();
    static void removeWaterWaveStrength();
    static void setWaterWaveStrength(const double &v);
    static const char *docWaterWaveStrength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveScale
    ///
    /// Wave frequency in inverse world units.
    /// Zero means automatic (a fraction of the water body size).
    static const double & getWaterWaveScale();
    static const double & defaultWaterWaveScale();
    static void removeWaterWaveScale();
    static void setWaterWaveScale(const double &v);
    static const char *docWaterWaveScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterWaveSpeed
    ///
    /// Animation speed of the water surface waves; zero freezes
    /// them.
    static const double & getWaterWaveSpeed();
    static const double & defaultWaterWaveSpeed();
    static void removeWaterWaveSpeed();
    static void setWaterWaveSpeed(const double &v);
    static const char *docWaterWaveSpeed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterAbsorption
    ///
    /// Beer-Lambert absorption strength of the water surface
    /// refraction: the refracted scene is dimmed and tinted by the
    /// water column it travels through (channels the water color lacks
    /// are absorbed most), so the water gains body and the bottom
    /// recedes with depth. Zero = crystal clear.
    static const double & getWaterAbsorption();
    static const double & defaultWaterAbsorption();
    static void removeWaterAbsorption();
    static void setWaterAbsorption(const double &v);
    static const char *docWaterAbsorption();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterInscatter
    ///
    /// How much the water's own color is added back into the
    /// depth-absorbed refraction (in-scattering); zero leaves absorbed
    /// regions dark, one fills them with the water color.
    static const double & getWaterInscatter();
    static const double & defaultWaterInscatter();
    static void removeWaterInscatter();
    static void setWaterInscatter(const double &v);
    static const char *docWaterInscatter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRefraction
    ///
    /// Screen-space refraction of the scene behind the water
    /// surface. When off the surface shows a flat water colour instead
    /// of the see-through refracted scene.
    static const bool & getWaterRefraction();
    static const bool & defaultWaterRefraction();
    static void removeWaterRefraction();
    static void setWaterRefraction(const bool &v);
    static const char *docWaterRefraction();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterReflection
    ///
    /// Reflection on the water surface (Fresnel-blended). When off
    /// the surface only refracts. See WaterPlanarReflection for the
    /// reflection method.
    static const bool & getWaterReflection();
    static const bool & defaultWaterReflection();
    static void removeWaterReflection();
    static void setWaterReflection(const bool &v);
    static const char *docWaterReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterPlanarReflection
    ///
    /// Reflection method when WaterReflection is on: planar (a
    /// mirror-camera re-render of the scene about the water plane -
    /// exact, no taper) when true, else screen-space reflection (a
    /// cheaper per-pixel ray march that can only reflect on-screen
    /// geometry and tapers past it). The environment cubemap is the
    /// fallback for both.
    static const bool & getWaterPlanarReflection();
    static const bool & defaultWaterPlanarReflection();
    static void removeWaterPlanarReflection();
    static void setWaterPlanarReflection(const bool &v);
    static const char *docWaterPlanarReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterShadow
    ///
    /// Receive the scene light's shadow on the water surface: a
    /// shadow band on the water where a caster blocks the light and
    /// the sun glint killed there. Requires the Shadow display style
    /// with an active shadow map; off leaves the surface fully lit.
    /// The refracted scene below the surface keeps its own shadow
    /// regardless.
    static const bool & getWaterShadow();
    static const bool & defaultWaterShadow();
    static void removeWaterShadow();
    static void setWaterShadow(const bool &v);
    static const char *docWaterShadow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRippleType
    ///
    /// The ambient ripple pattern on the water surface - the motion
    /// the surface has of its own accord. 0 = waves: the default sum
    /// of directional wind waves. 1 = rain: circular rings expanding
    /// from randomly placed, randomly timed drop impacts, as on a pond
    /// in rainfall. 2 = none: a still surface, which leaves only what
    /// the scene disturbs - fountain splash rings and the impact rings
    /// of particles striking the water still show.
    static const long & getWaterRippleType();
    static const long & defaultWaterRippleType();
    static void removeWaterRippleType();
    static void setWaterRippleType(const long &v);
    static const char *docWaterRippleType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterRippleDensity
    ///
    /// Drop density of the rain ripple type: how many drop cells
    /// fit per wave-scale unit. Higher rains harder - more, smaller
    /// rings; lower gives sparse large rings. The wave ripple type
    /// ignores it.
    static const double & getWaterRippleDensity();
    static const double & defaultWaterRippleDensity();
    static void removeWaterRippleDensity();
    static void setWaterRippleDensity(const double &v);
    static const char *docWaterRippleDensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterImpactStrength
    ///
    /// Height of the rings raised where particles actually strike
    /// the water - a fountain's droplets landing in its own basin.
    /// Unlike the rain ripple type these are not a pattern: nothing
    /// appears unless something hits the surface, and it appears
    /// where it hit. Zero turns them off. Needs a stateful emitter
    /// whose step program reports its impacts.
    static const double & getWaterImpactStrength();
    static const double & defaultWaterImpactStrength();
    static void removeWaterImpactStrength();
    static void setWaterImpactStrength(const double &v);
    static const char *docWaterImpactStrength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterImpactLife
    ///
    /// How long an impact ring lives, in seconds - which is also
    /// how far it travels, since a ring is sized to have crossed two
    /// cells of the impact map when it dies. Longer makes slower,
    /// wider-travelling rings out of the same hits.
    static const double & getWaterImpactLife();
    static const double & defaultWaterImpactLife();
    static void removeWaterImpactLife();
    static void setWaterImpactLife(const double &v);
    static const char *docWaterImpactLife();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WaterShadowWobble
    ///
    /// How much the shadow band on the water surface wobbles with
    /// the wave field: the shadow is looked up at the wave-displaced
    /// surface point scaled by this factor. Zero pins the shadow
    /// boundary to the flat surface (a straight edge), one is the
    /// physical wave height, larger values exaggerate the ripple.
    static const double & getWaterShadowWobble();
    static const double & defaultWaterShadowWobble();
    static void removeWaterShadowWobble();
    static void setWaterShadowWobble(const double &v);
    static const char *docWaterShadowWobble();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Bloom
    ///
    /// Bleed a blurred glow halo from bright pixels and from
    /// light-source bodies (objects with the Render_Light property)
    /// over their surroundings.
    static const bool & getBloom();
    static const bool & defaultBloom();
    static void removeBloom();
    static void setBloom(const bool &v);
    static const char *docBloom();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomThreshold
    ///
    /// Scene brightness above which a pixel feeds the glow halo
    /// (with a soft knee below it). Light-source bodies always feed
    /// it regardless, scaled by their intensity.
    static const double & getBloomThreshold();
    static const double & defaultBloomThreshold();
    static void removeBloomThreshold();
    static void setBloomThreshold(const double &v);
    static const char *docBloomThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomIntensity
    ///
    /// Brightness multiplier of the composited glow halo.
    static const double & getBloomIntensity();
    static const double & defaultBloomIntensity();
    static void removeBloomIntensity();
    static void setBloomIntensity(const double &v);
    static const char *docBloomIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BloomRadius
    ///
    /// Radius scale of the glow halo. One is the default gaussian
    /// footprint; larger blooms wider.
    static const double & getBloomRadius();
    static const double & defaultBloomRadius();
    static void removeBloomRadius();
    static void setBloomRadius(const double &v);
    static const char *docBloomRadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SunDisc
    ///
    /// Draw a visible sun -- a bright disc with a limb glow -- in
    /// the sky along the Shadow display style's directional scene light,
    /// occluded by geometry and feeding the bloom glow. Perspective
    /// cameras only; spot lights have no sky direction.
    static const bool & getSunDisc();
    static const bool & defaultSunDisc();
    static void removeSunDisc();
    static void setSunDisc(const bool &v);
    static const char *docSunDisc();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SunDiscSize
    ///
    /// Angular radius of the sun disc in degrees (the real sun is
    /// about 0.27; larger reads better in a CAD scene).
    static const double & getSunDiscSize();
    static const double & defaultSunDiscSize();
    static void removeSunDiscSize();
    static void setSunDiscSize(const double &v);
    static const char *docSunDiscSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflection
    ///
    /// Mirror the model in the shadow ground plane of the
    /// experimental render engine: the opaque scene is re-rendered
    /// with a reflected camera and blended onto the ground. Only
    /// effective while the Shadow display style shows a ground plane.
    static const bool & getGroundReflection();
    static const bool & defaultGroundReflection();
    static void removeGroundReflection();
    static void setGroundReflection(const bool &v);
    static const char *docGroundReflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GroundReflectionIntensity
    ///
    /// Blend factor of the mirrored model on the ground plane.
    static const double & getGroundReflectionIntensity();
    static const double & defaultGroundReflectionIntensity();
    static void removeGroundReflectionIntensity();
    static void setGroundReflectionIntensity(const double &v);
    static const char *docGroundReflectionIntensity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugViewMode
    ///
    /// Render debugging buffer visualization (docs/RenderDebug.md).
    /// Routes an intermediate render target to the screen instead of the
    /// shaded scene: 1 = linearized scene depth, 2 = view-space normals,
    /// 3 = ambient occlusion term only, 4 = shadow term only, 5 = shadow
    /// map / bulb-tile coverage as color, 6 = overdraw heatmap, 7 =
    /// shadow-moment filtering-precision probe, 8 = UV / texcoord,
    /// 9 = the planar reflection target, 10 = the particle impact map
    /// (green where a hit is recorded, brightness its age, red where
    /// nothing has ever struck).
    /// 0 renders normally. The on-top, highlight and overlay passes
    /// still draw on top so the view stays navigable.
    static const long & getDebugViewMode();
    static const long & defaultDebugViewMode();
    static void removeDebugViewMode();
    static void setDebugViewMode(const long &v);
    static const char *docDebugViewMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugFreezeFrame
    ///
    /// Freeze every intentionally time- or history-dependent render
    /// input: temporal accumulation and per-frame sampling jitter, and
    /// time-driven animation (water waves, fire). Two frames of the same
    /// scene, camera and parameters then render identically -- the
    /// determinism switch for golden-image comparison
    /// (docs/RenderDebug.md).
    static const bool & getDebugFreezeFrame();
    static const bool & defaultDebugFreezeFrame();
    static void removeDebugFreezeFrame();
    static void setDebugFreezeFrame(const bool &v);
    static const char *docDebugFreezeFrame();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugLabel
    ///
    /// Burn a self-describing label into a corner of the rendered
    /// frame while render debugging: the active debug view mode, the
    /// freeze-frame state and any custom RenderDebug_* parameter values.
    /// A captured PNG then documents its own settings without its
    /// sidecar (docs/RenderDebug.md).
    static const bool & getDebugLabel();
    static const bool & defaultDebugLabel();
    static void removeDebugLabel();
    static void setDebugLabel(const bool &v);
    static const char *docDebugLabel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugTiming
    ///
    /// Log where the time of a rendered frame goes, by pipeline
    /// stage: the Coin traversal, the flattening of the vertex caches,
    /// the draw-entry build, the translation to the backend, the
    /// backend's own bookkeeping and the draw itself. One summary line
    /// per second, so a long operation shows how each stage grows with
    /// the scene rather than one average (docs/IncrementalPublish.md).
    static const bool & getDebugTiming();
    static const bool & defaultDebugTiming();
    static void removeDebugTiming();
    static void setDebugTiming(const bool &v);
    static const char *docDebugTiming();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugDelta
    ///
    /// Log what each published frame actually changed: how many of
    /// the scene cache's children the publish reused, how many it added
    /// or dropped, and how many separators the traversal below it reused
    /// against how many it rebuilt. One summary line per second. A
    /// publish rebuilds the whole scene however little moved, and these
    /// counts are how much of that rebuild was avoidable
    /// (docs/IncrementalPublish.md §5).
    static const bool & getDebugDelta();
    static const bool & defaultDebugDelta();
    static void removeDebugDelta();
    static void setDebugDelta(const bool &v);
    static const char *docDebugDelta();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugCoverage
    ///
    /// Log how much of the screen each drawn object actually covers,
    /// as a histogram over its projected size in pixels. A camera that
    /// sees a whole assembly draws most of it at a few pixels, and every
    /// one of those parts still costs a full object; the histogram says
    /// how much of the model is in that state, which is what decides
    /// whether aggregating distant parts is worth building
    /// (docs/FarFieldProxies.md §9).
    static const bool & getDebugCoverage();
    static const bool & defaultDebugCoverage();
    static void removeDebugCoverage();
    static void setDebugCoverage(const bool &v);
    static const char *docDebugCoverage();
    //@}
//[[[end]]]

    /// Called on any parameter change: re-selects the renderer backend on
    /// a 'Type' change, otherwise schedules a redraw of all 3D views (the
    /// render configs are re-fed to the backend every frame).
    static void onRenderParamChanged(const char *sReason);

    /// One-time migration of the pre-split Renderer* keys from the parent
    /// Preferences/View group into this Preferences/View/Render group.
    /// Called once at Gui::Application startup.
    static void migrate();

/*[[[cog
RenderParams.declare_end()
]]]*/

// Auto generated code (Tools/params_utils.py:179)
}; // class RenderParams
} // namespace Gui
//[[[end]]]

#endif // GUI_RENDER_PARAMS_H
