/****************************************************************************
 *   Copyright (c) 2022 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_REPORTVIEW_PARAMS_H
#define GUI_REPORTVIEW_PARAMS_H

/*[[[cog
import ReportViewParams
ReportViewParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain ReportView related parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/OutputWindow"
 *
 * This class is auto generated by Gui/ReportViewParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/ReportViewParams.h Gui/ReportViewParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/ReportViewParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/ReportViewParams.cpp with
 * the following signature.
 * @code
 *     void ReportViewParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport ReportViewParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkMessage
    ///
    /// Show normal messages in the report view.
    static const bool & getcheckMessage();
    static const bool & defaultcheckMessage();
    static void removecheckMessage();
    static void setcheckMessage(const bool &v);
    static const char *doccheckMessage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkLogging
    ///
    /// Show log messages in the report view. They are many; the log file
    /// has them either way.
    static const bool & getcheckLogging();
    static const bool & defaultcheckLogging();
    static void removecheckLogging();
    static void setcheckLogging(const bool &v);
    static const char *doccheckLogging();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkWarning
    ///
    /// Show warnings in the report view.
    static const bool & getcheckWarning();
    static const bool & defaultcheckWarning();
    static void removecheckWarning();
    static void setcheckWarning(const bool &v);
    static const char *doccheckWarning();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkError
    ///
    /// Show error messages in the report view.
    static const bool & getcheckError();
    static const bool & defaultcheckError();
    static void removecheckError();
    static void setcheckError(const bool &v);
    static const char *doccheckError();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkCritical
    ///
    /// Show critical messages in the report view.
    static const bool & getcheckCritical();
    static const bool & defaultcheckCritical();
    static void removecheckCritical();
    static void setcheckCritical(const bool &v);
    static const char *doccheckCritical();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter colorText
    ///
    /// Colour of normal messages in the report view, and of the status
    /// bar's. 0 uses the window's text colour.
    static const unsigned long & getcolorText();
    static const unsigned long & defaultcolorText();
    static void removecolorText();
    static void setcolorText(const unsigned long &v);
    static const char *doccolorText();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter colorLogging
    ///
    /// Colour of log messages in the report view.
    static const unsigned long & getcolorLogging();
    static const unsigned long & defaultcolorLogging();
    static void removecolorLogging();
    static void setcolorLogging(const unsigned long &v);
    static const char *doccolorLogging();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter colorWarning
    ///
    /// Colour of warnings in the report view and in the status bar.
    static const unsigned long & getcolorWarning();
    static const unsigned long & defaultcolorWarning();
    static void removecolorWarning();
    static void setcolorWarning(const unsigned long &v);
    static const char *doccolorWarning();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter colorError
    ///
    /// Colour of error messages in the report view and in the status bar.
    static const unsigned long & getcolorError();
    static const unsigned long & defaultcolorError();
    static void removecolorError();
    static void setcolorError(const unsigned long &v);
    static const char *doccolorError();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkGoToEnd
    ///
    /// Keep the newest line of the report view in sight as messages
    /// arrive. When off the view stays where it was scrolled to.
    static const bool & getcheckGoToEnd();
    static const bool & defaultcheckGoToEnd();
    static void removecheckGoToEnd();
    static void setcheckGoToEnd(const bool &v);
    static const char *doccheckGoToEnd();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedirectPythonOutput
    ///
    /// Show what Python code prints (sys.stdout) in the report view. Also
    /// decides where the output of a macro goes.
    static const bool & getRedirectPythonOutput();
    static const bool & defaultRedirectPythonOutput();
    static void removeRedirectPythonOutput();
    static void setRedirectPythonOutput(const bool &v);
    static const char *docRedirectPythonOutput();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedirectPythonErrors
    ///
    /// Show Python's error output (sys.stderr) in the report view. Also
    /// decides where the errors of a macro go.
    static const bool & getRedirectPythonErrors();
    static const bool & defaultRedirectPythonErrors();
    static void removeRedirectPythonErrors();
    static void setRedirectPythonErrors(const bool &v);
    static const char *docRedirectPythonErrors();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportViewOnWarning
    ///
    /// Bring the report view on screen when a warning arrives.
    static const bool & getcheckShowReportViewOnWarning();
    static const bool & defaultcheckShowReportViewOnWarning();
    static void removecheckShowReportViewOnWarning();
    static void setcheckShowReportViewOnWarning(const bool &v);
    static const char *doccheckShowReportViewOnWarning();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportViewOnError
    ///
    /// Bring the report view on screen when an error arrives.
    static const bool & getcheckShowReportViewOnError();
    static const bool & defaultcheckShowReportViewOnError();
    static void removecheckShowReportViewOnError();
    static void setcheckShowReportViewOnError(const bool &v);
    static const char *doccheckShowReportViewOnError();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportViewOnNormalMessage
    ///
    /// Bring the report view on screen when a normal message arrives.
    static const bool & getcheckShowReportViewOnNormalMessage();
    static const bool & defaultcheckShowReportViewOnNormalMessage();
    static void removecheckShowReportViewOnNormalMessage();
    static void setcheckShowReportViewOnNormalMessage(const bool &v);
    static const char *doccheckShowReportViewOnNormalMessage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportViewOnLogMessage
    ///
    /// Bring the report view on screen when a log message arrives.
    static const bool & getcheckShowReportViewOnLogMessage();
    static const bool & defaultcheckShowReportViewOnLogMessage();
    static void removecheckShowReportViewOnLogMessage();
    static void setcheckShowReportViewOnLogMessage(const bool &v);
    static const char *doccheckShowReportViewOnLogMessage();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportViewOnCritical
    ///
    /// Bring the report view on screen when a critical message arrives.
    static const bool & getcheckShowReportViewOnCritical();
    static const bool & defaultcheckShowReportViewOnCritical();
    static void removecheckShowReportViewOnCritical();
    static void setcheckShowReportViewOnCritical(const bool &v);
    static const char *doccheckShowReportViewOnCritical();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter checkShowReportTimecode
    ///
    /// Put the time a message arrived in front of each line of the report
    /// view.
    static const bool & getcheckShowReportTimecode();
    static const bool & defaultcheckShowReportTimecode();
    static void removecheckShowReportTimecode();
    static void setcheckShowReportTimecode(const bool &v);
    static const char *doccheckShowReportTimecode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LogMessageSize
    ///
    /// Largest number of characters of one log message shown in the report
    /// view. A longer message is cut off. 0 uses the built-in limit of 2048
    /// characters.
    static const long & getLogMessageSize();
    static const long & defaultLogMessageSize();
    static void removeLogMessageSize();
    static void setLogMessageSize(const long &v);
    static const char *docLogMessageSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateWindow
    ///
    /// How many of the most recent lines a new line is compared with. A line
    /// that repeats one of them is held back and shown once with a count (xN)
    /// that can be clicked to expand. 0 shows every line. Affects the Report
    /// view only; the log file and other consoles get every message.
    static const long & getDuplicateWindow();
    static const long & defaultDuplicateWindow();
    static void removeDuplicateWindow();
    static void setDuplicateWindow(const long &v);
    static const char *docDuplicateWindow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateKeyLength
    ///
    /// How many leading non-digit characters two messages must share to count
    /// as the same message. Digits are skipped rather than compared, so the same
    /// sentence carrying a different source line, element index or coordinate
    /// collapses into one entry instead of one entry per number.
    static const long & getDuplicateKeyLength();
    static const long & defaultDuplicateKeyLength();
    static void removeDuplicateKeyLength();
    static void setDuplicateKeyLength(const long &v);
    static const char *docDuplicateKeyLength();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateTimeout
    ///
    /// Milliseconds a held duplicate line waits before it is shown anyway, timed
    /// from the first repeat rather than the last, so a continuous storm still
    /// reports at this interval. Set to 0 to hold until another line arrives.
    static const long & getDuplicateTimeout();
    static const long & defaultDuplicateTimeout();
    static void removeDuplicateTimeout();
    static void setDuplicateTimeout(const long &v);
    static const char *docDuplicateTimeout();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CommandRedirect
    ///
    /// Prefix for marking python command in message to be redirected to Python console
    /// This is used as a debug help for output command from external libraries
    static const QString & getCommandRedirect();
    static const QString & defaultCommandRedirect();
    static void removeCommandRedirect();
    static void setCommandRedirect(const QString &v);
    static const char *docCommandRedirect();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class ReportViewParams
} // namespace Gui
//[[[end]]]

#endif // GUI_REPORTVIEW_PARAMS_H
