/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_SPACEBALL_PARAMS_H
#define GUI_SPACEBALL_PARAMS_H

/*[[[cog
import SpaceballParams
SpaceballParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the settings of the 3D mouse

 * The parameters are under group "User parameter:BaseApp/Spaceball/Motion"
 *
 * This class is auto generated by Gui/SpaceballParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/SpaceballParams.h Gui/SpaceballParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/SpaceballParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/SpaceballParams.cpp with
 * the following signature.
 * @code
 *     void SpaceballParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport SpaceballParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GlobalSensitivity
    ///
    /// How fast the view follows the 3D mouse, for all six movements at
    /// once: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast.
    static const long & getGlobalSensitivity();
    static const long & defaultGlobalSensitivity();
    static void removeGlobalSensitivity();
    static void setGlobalSensitivity(const long &v);
    static const char *docGlobalSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Dominant
    ///
    /// Of the six movements of the 3D mouse only the strongest one is
    /// followed at a time, so that a push does not also turn the view.
    static const bool & getDominant();
    static const bool & defaultDominant();
    static void removeDominant();
    static void setDominant(const bool &v);
    static const char *docDominant();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FlipYZ
    ///
    /// Swaps the Y and Z axes of the 3D mouse: pushing the cap forward
    /// zooms where it panned up and down, and the same for the two
    /// rotations about them.
    static const bool & getFlipYZ();
    static const bool & defaultFlipYZ();
    static void removeFlipYZ();
    static void setFlipYZ(const bool &v);
    static const char *docFlipYZ();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Translations
    ///
    /// The view follows the three pushes of the 3D mouse -- pan left and
    /// right, pan up and down, zoom. Off, all three are ignored whatever
    /// each of them is set to.
    static const bool & getTranslations();
    static const bool & defaultTranslations();
    static void removeTranslations();
    static void setTranslations(const bool &v);
    static const char *docTranslations();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Rotations
    ///
    /// The view follows the three turns of the 3D mouse -- tilt, roll,
    /// spin. Off, all three are ignored whatever each of them is set to.
    static const bool & getRotations();
    static const bool & defaultRotations();
    static void removeRotations();
    static void setRotations(const bool &v);
    static const char *docRotations();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanLREnable
    ///
    /// The movement of the 3D mouse that pans the view left and right is followed.
    /// It also needs 'Enable translations'.
    static const bool & getPanLREnable();
    static const bool & defaultPanLREnable();
    static void removePanLREnable();
    static void setPanLREnable(const bool &v);
    static const char *docPanLREnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanLRReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// pans the view left and right.
    static const bool & getPanLRReverse();
    static const bool & defaultPanLRReverse();
    static void removePanLRReverse();
    static void setPanLRReverse(const bool &v);
    static const char *docPanLRReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanLRSensitivity
    ///
    /// How fast the movement of the 3D mouse that pans the view left and right
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getPanLRSensitivity();
    static const long & defaultPanLRSensitivity();
    static void removePanLRSensitivity();
    static void setPanLRSensitivity(const long &v);
    static const char *docPanLRSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanUDEnable
    ///
    /// The movement of the 3D mouse that pans the view up and down is followed.
    /// It also needs 'Enable translations'.
    static const bool & getPanUDEnable();
    static const bool & defaultPanUDEnable();
    static void removePanUDEnable();
    static void setPanUDEnable(const bool &v);
    static const char *docPanUDEnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanUDReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// pans the view up and down.
    static const bool & getPanUDReverse();
    static const bool & defaultPanUDReverse();
    static void removePanUDReverse();
    static void setPanUDReverse(const bool &v);
    static const char *docPanUDReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PanUDSensitivity
    ///
    /// How fast the movement of the 3D mouse that pans the view up and down
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getPanUDSensitivity();
    static const long & defaultPanUDSensitivity();
    static void removePanUDSensitivity();
    static void setPanUDSensitivity(const long &v);
    static const char *docPanUDSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ZoomEnable
    ///
    /// The movement of the 3D mouse that zooms the view is followed.
    /// It also needs 'Enable translations'.
    static const bool & getZoomEnable();
    static const bool & defaultZoomEnable();
    static void removeZoomEnable();
    static void setZoomEnable(const bool &v);
    static const char *docZoomEnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ZoomReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// zooms the view.
    static const bool & getZoomReverse();
    static const bool & defaultZoomReverse();
    static void removeZoomReverse();
    static void setZoomReverse(const bool &v);
    static const char *docZoomReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ZoomSensitivity
    ///
    /// How fast the movement of the 3D mouse that zooms the view
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getZoomSensitivity();
    static const long & defaultZoomSensitivity();
    static void removeZoomSensitivity();
    static void setZoomSensitivity(const long &v);
    static const char *docZoomSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TiltEnable
    ///
    /// The movement of the 3D mouse that tilts the view about its horizontal axis is followed.
    /// It also needs 'Enable rotations'.
    static const bool & getTiltEnable();
    static const bool & defaultTiltEnable();
    static void removeTiltEnable();
    static void setTiltEnable(const bool &v);
    static const char *docTiltEnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TiltReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// tilts the view about its horizontal axis.
    static const bool & getTiltReverse();
    static const bool & defaultTiltReverse();
    static void removeTiltReverse();
    static void setTiltReverse(const bool &v);
    static const char *docTiltReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TiltSensitivity
    ///
    /// How fast the movement of the 3D mouse that tilts the view about its horizontal axis
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getTiltSensitivity();
    static const long & defaultTiltSensitivity();
    static void removeTiltSensitivity();
    static void setTiltSensitivity(const long &v);
    static const char *docTiltSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RollEnable
    ///
    /// The movement of the 3D mouse that rolls the view about the axis into the screen is followed.
    /// It also needs 'Enable rotations'.
    static const bool & getRollEnable();
    static const bool & defaultRollEnable();
    static void removeRollEnable();
    static void setRollEnable(const bool &v);
    static const char *docRollEnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RollReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// rolls the view about the axis into the screen.
    static const bool & getRollReverse();
    static const bool & defaultRollReverse();
    static void removeRollReverse();
    static void setRollReverse(const bool &v);
    static const char *docRollReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RollSensitivity
    ///
    /// How fast the movement of the 3D mouse that rolls the view about the axis into the screen
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getRollSensitivity();
    static const long & defaultRollSensitivity();
    static void removeRollSensitivity();
    static void setRollSensitivity(const long &v);
    static const char *docRollSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SpinEnable
    ///
    /// The movement of the 3D mouse that spins the view about its vertical axis is followed.
    /// It also needs 'Enable rotations'.
    static const bool & getSpinEnable();
    static const bool & defaultSpinEnable();
    static void removeSpinEnable();
    static void setSpinEnable(const bool &v);
    static const char *docSpinEnable();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SpinReverse
    ///
    /// Turns round the direction of the movement of the 3D mouse that
    /// spins the view about its vertical axis.
    static const bool & getSpinReverse();
    static const bool & defaultSpinReverse();
    static void removeSpinReverse();
    static void setSpinReverse(const bool &v);
    static const char *docSpinReverse();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SpinSensitivity
    ///
    /// How fast the movement of the 3D mouse that spins the view about its vertical axis
    /// is followed: -50 slows it to a tenth, 0 leaves it as the device gives it,
    /// 50 makes it three and a half times as fast. The global sensitivity
    /// multiplies it.
    static const long & getSpinSensitivity();
    static const long & defaultSpinSensitivity();
    static void removeSpinSensitivity();
    static void setSpinSensitivity(const long &v);
    static const char *docSpinSensitivity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Remapping
    ///
    /// Which axis of the device each of the six movements is taken from:
    /// six digits, each of 0 to 5 once, in the order pan left/right, pan
    /// up/down, zoom, tilt, roll, spin. 12345 (that is 012345) takes them
    /// as the device gives them; anything that is no such number is
    /// ignored. On no page.
    static const long & getRemapping();
    static const long & defaultRemapping();
    static void removeRemapping();
    static void setRemapping(const long &v);
    static const char *docRemapping();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Calibrate
    ///
    /// A request more than a setting: the Calibrate button of the
    /// Spaceball Motion page sets it, and the next event of the device
    /// stores what the device reports at rest as the calibration and
    /// takes this away again.
    static const bool & getCalibrate();
    static const bool & defaultCalibrate();
    static void removeCalibrate();
    static void setCalibrate(const bool &v);
    static const char *docCalibrate();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationX
    ///
    /// What the device reported for pan left/right while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationX();
    static const long & defaultCalibrationX();
    static void removeCalibrationX();
    static void setCalibrationX(const long &v);
    static const char *docCalibrationX();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationY
    ///
    /// What the device reported for pan up/down while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationY();
    static const long & defaultCalibrationY();
    static void removeCalibrationY();
    static void setCalibrationY(const long &v);
    static const char *docCalibrationY();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationZ
    ///
    /// What the device reported for zoom while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationZ();
    static const long & defaultCalibrationZ();
    static void removeCalibrationZ();
    static void setCalibrationZ(const long &v);
    static const char *docCalibrationZ();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationXr
    ///
    /// What the device reported for tilt while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationXr();
    static const long & defaultCalibrationXr();
    static void removeCalibrationXr();
    static void setCalibrationXr(const long &v);
    static const char *docCalibrationXr();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationYr
    ///
    /// What the device reported for roll while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationYr();
    static const long & defaultCalibrationYr();
    static void removeCalibrationYr();
    static void setCalibrationYr(const long &v);
    static const char *docCalibrationYr();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CalibrationZr
    ///
    /// What the device reported for spin while at rest when it
    /// was last calibrated; taken off every reading. Stored by the
    /// program after Calibrate, not meant to be set by hand.
    static const long & getCalibrationZr();
    static const long & defaultCalibrationZr();
    static void removeCalibrationZr();
    static void setCalibrationZr(const long &v);
    static const char *docCalibrationZr();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Model
    ///
    /// The device chosen in the Spaceball Buttons page of the Customize
    /// dialog, whose buttons the page lists. Stored when the page's
    /// Reset button is pressed, not when the choice changes.
    static const std::string & getModel();
    static const std::string & defaultModel();
    static void removeModel();
    static void setModel(const std::string &v);
    static const char *docModel();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class SpaceballParams
} // namespace Gui
//[[[end]]]

#endif // GUI_SPACEBALL_PARAMS_H
