/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_THEME_PARAMS_H
#define GUI_THEME_PARAMS_H

/*[[[cog
import ThemeParams
ThemeParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace Gui {
/** Convenient class to obtain the accent colours of the theme

 * The parameters are under group "User parameter:BaseApp/Preferences/Themes"
 *
 * This class is auto generated by Gui/ThemeParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/ThemeParams.h Gui/ThemeParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Gui/ThemeParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Gui/ThemeParams.cpp with
 * the following signature.
 * @code
 *     void ThemeParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport ThemeParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeAccentColor1
    ///
    /// Highlight colour of the style sheets: hovered, selected and
    /// checked items. Applied shortly after a change.
    static const unsigned long & getThemeAccentColor1();
    static const unsigned long & defaultThemeAccentColor1();
    static void removeThemeAccentColor1();
    static void setThemeAccentColor1(const unsigned long &v);
    static const char *docThemeAccentColor1();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeAccentColor2
    ///
    /// Colour the style sheets use for the engaged state: focus, a
    /// pressed button, an open combo box. The Dark theme sets a lighter
    /// one. Applied shortly after a change.
    static const unsigned long & getThemeAccentColor2();
    static const unsigned long & defaultThemeAccentColor2();
    static void removeThemeAccentColor2();
    static void setThemeAccentColor2(const unsigned long &v);
    static const char *docThemeAccentColor2();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThemeAccentColor3
    ///
    /// Far end of the gradients the style sheets draw from accent colour
    /// 1. Applied shortly after a change.
    static const unsigned long & getThemeAccentColor3();
    static const unsigned long & defaultThemeAccentColor3();
    static void removeThemeAccentColor3();
    static void setThemeAccentColor3(const unsigned long &v);
    static const char *docThemeAccentColor3();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class ThemeParams
} // namespace Gui
//[[[end]]]

#endif // GUI_THEME_PARAMS_H
