/***************************************************************************
 *   Copyright (c) 2006 Werner Mayer <wmayer[at]users.sourceforge.net>     *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#include "PreCompiled.h"

#ifndef _PreComp_
# include <sstream>
# include <QApplication>
# include <QEvent>
# include <QFileInfo>
# include <QMenu>
# include <QPixmap>
# include <QMouseEvent>
# include <Inventor/SoPickedPoint.h>
# include <Inventor/details/SoDetail.h>
#endif

#include <App/DocumentObjectPy.h>
#include <Base/Interpreter.h>
#include <Base/Tools.h>

#include "ViewProviderFeaturePython.h"
#include "Application.h"
#include "BitmapFactory.h"
#include "Document.h"
#include "PythonWrapper.h"
#include "View3DInventorViewer.h"
#include "ViewProviderDocumentObjectPy.h"


FC_LOG_LEVEL_INIT("ViewProviderFeaturePython", true, true)


using namespace Gui;

using App::PyHookState;

// The hook enum and the PyHookDef table, generated by cog into the build tree
// from FeaturePythonHookView.cog.h and the table in src/App/FeaturePythonHooks.py.
#include "FeaturePythonHookView.h"

// ----------------------------------------------------------------------------

ViewProviderFeaturePythonImp::ViewProviderFeaturePythonImp(
        ViewProviderDocumentObject* vp, App::PropertyPythonObject &proxy)
  : App::PyHookImp(viewHookTable, HookCount)
  , object(vp)
  , Proxy(proxy)
{
}

ViewProviderFeaturePythonImp::~ViewProviderFeaturePythonImp() = default;

Py::Object ViewProviderFeaturePythonImp::hookSelf(int hook) const
{
    if (hook == HookUpdateData) {
        // the one view hook whose first argument is the document object rather
        // than the view provider
        return Py::asObject(object->getObject()->getPyObject());
    }
    return Py::asObject(object->getPyObject());
}

static QPixmap getPixmapFromPython(Py::Object pyobj)
{
    if(pyobj.isString()) {
        std::string content = Py::String(pyobj).as_std_string("utf-8");
        QPixmap icon = BitmapFactory().pixmap(content.c_str(), true);
        if (!icon.isNull())
            return icon;

        // Check if the passed string is a filename, otherwise treat as xpm data
        QFileInfo fi(QString::fromUtf8(content.c_str()));
        if (fi.isFile() && fi.exists()) {
            icon.load(fi.absoluteFilePath());
        } else {
            QByteArray ary;
            int strlen = (int)content.size();
            ary.resize(strlen);
            for (int j=0; j<strlen; j++)
                ary[j]=content[j];
            // Make sure to remove crap around the XPM data
            QList<QByteArray> lines = ary.split('\n');
            QByteArray buffer;
            buffer.reserve(ary.size()+lines.size());
            for (QList<QByteArray>::iterator it = lines.begin(); it != lines.end(); ++it) {
                QByteArray trim = it->trimmed();
                if (!trim.isEmpty()) {
                    buffer.append(trim);
                    buffer.append('\n');
                }
            }
            icon.loadFromData(buffer, "XPM");
        }
        if (!icon.isNull()) {
            return icon;
        }
    } else {
        PythonWrapper wrap;
        wrap.loadGuiModule();
        QPixmap *px = wrap.toQPixmap(pyobj.ptr());
        if(px)
            return *px;
    }
    return QPixmap();
}

/** Wrap a Coin pointer for pivy
 *
 * The conversion throws a Base::Exception rather than a Python error, and every
 * hook that uses it reported that and carried on rather than letting it escape
 * into Coin. Keep that here, where the argument is built.
 */
static bool swigPointer(Py::Object &out, const char *type, void *ptr, int own)
{
    try {
        out = Py::asObject(Base::Interpreter().createSWIGPointerObj(
                    "pivy.coin", type, ptr, own));
        return true;
    }
    catch (const Base::Exception& e) {
        e.ReportException();
        return false;
    }
}

QIcon ViewProviderFeaturePythonImp::getIcon() const
{
    QIcon icon;
    callHook(HookGetIcon, [&](const Py::Object& ret) {
        if (ret.isNone())
            return true;

        std::string _type;
        const char *type = nullptr;
        if (object && object->getObject()) {
            auto prop = Base::freecad_dynamic_cast<App::PropertyPythonObject>(
                    object->getObject()->getPropertyByName("Proxy"));
            if (prop) {
                try {
                    auto proxy = prop->getValue();
                    if(!proxy.isNone() && !proxy.isString() && !proxy.isNumeric()) {
                        if (proxy.hasAttr("__class__")) {
                            _type = proxy.getAttr("__class__").as_string();
                            type = _type.c_str();
                        } else
                            type = proxy.ptr()->ob_type->tp_name;
                    }
                } catch (Py::Exception &) {
                    Base::PyException e;
                    e.ReportException();
                }
            }
        }
        BitmapCacheContext ctx(type);

        QPixmap px = getPixmapFromPython(ret);
        if (!px.isNull()) {
            icon = px;
            return true;
        }

        PythonWrapper wrap;
        wrap.loadGuiModule();
        wrap.loadWidgetsModule();
        QIcon *picon = wrap.toQIcon(ret.ptr());
        if(picon)
            icon = *picon;
        return true;
    });
    return icon;
}

void ViewProviderFeaturePythonImp::getExtraIcons(
        std::vector<std::pair<QByteArray, QPixmap> > &icons) const
{
    if (!canCallHook(HookGetExtraIcons))
        return;

    Base::PyGILStateLocker lock;
    Py::List list;
    PythonWrapper wrap;
    wrap.loadGuiModule();
    for (auto &v : icons)
        list.append(Py::TupleN(Py::String(v.first.constData()),
                               wrap.fromQPixmap(&v.second)));

    callHook(HookGetExtraIcons, [&icons](const Py::Object& ret) {
        if (ret.isNone())
            return true;

        std::vector<std::pair<QByteArray, QPixmap> >res;
        if (ret.isSequence() && !ret.isString()) {
            Py::Sequence seq(ret);
            if (seq.size() == 2) {
                Py::Object first(seq[0].ptr());
                if (first.isString()) {
                    QPixmap px = getPixmapFromPython(Py::Object(seq[1].ptr()));
                    if (!px.isNull())
                        res.emplace_back(first.as_string().c_str(), px);
                    // note this leaves icons untouched, as it always has
                    return true;
                }
            }
            for (int i=0, c=seq.size(); i<c; ++i) {
                std::string tag;
                QPixmap px;
                if (PySequence_Check(seq[i].ptr())) {
                    Py::Sequence s(seq[i].ptr());
                    if (s.size() == 2) {
                        Py::Object first(s[0].ptr());
                        if (first.isString()) {
                            tag = first.as_string();
                            px = getPixmapFromPython(Py::Object(s[1]));
                        }
                    }
                } else
                    px = getPixmapFromPython(Py::Object(seq[i]));
                if (!px.isNull())
                    res.emplace_back(tag.c_str(), px);
            }
        }
        else {
            QPixmap px = getPixmapFromPython(ret);
            if (!px.isNull())
                res.emplace_back(QByteArray(), px);
        }
        icons = std::move(res);
        return true;
    }, Py::Object(list));
}

bool ViewProviderFeaturePythonImp::claimChildren(std::vector<App::DocumentObject*> &children) const
{
    auto state = callHook(HookClaimChildren, [&children](const Py::Object& res) {
        Py::Sequence list(res);
        for (Py::Sequence::iterator it = list.begin(); it != list.end(); ++it) {
            Py::Object item(*it);
            if (PyObject_TypeCheck(item.ptr(), &(App::DocumentObjectPy::Type))) {
                App::DocumentObject* obj =
                    static_cast<App::DocumentObjectPy*>(item.ptr())->getDocumentObjectPtr();
                children.push_back(obj);
            }
        }
        return true;
    });
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::useNewSelectionModel() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookUseNewSelectionModel, App::pyHookDecodeValueT(ret))
            == PyHookState::Failed)
        return Accepted;
    return ret;
}

bool ViewProviderFeaturePythonImp::getElement(const SoDetail *det, std::string &res) const
{
    if (!canCallHook(HookGetElement))
        return false;

    Base::PyGILStateLocker lock;
    Py::Object pivy;
    // Note: As there is no ref'counting mechanism for the SoDetail class we must
    // pass '0' as the last parameter so that the Python object does not 'own'
    // the detail object.
    if (!swigPointer(pivy, "SoDetail *",
                     const_cast<void*>(static_cast<const void*>(det)), 0))
        return true;

    auto state = callHook(HookGetElement, [&res](const Py::Object& ret) {
        Py::String name(ret);
        res = name;
        return true;
    }, pivy);
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::getElementPicked(const SoPickedPoint *pp, std::string &subname) const
{
    if (!canCallHook(HookGetElementPicked))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    Py::Object pivy;
    if (!swigPointer(pivy, "SoPickedPoint *",
                     const_cast<void*>(static_cast<const void*>(pp)), 0))
        return Rejected;

    ValueT ret = Rejected;
    auto state = callHook(HookGetElementPicked, [&](const Py::Object& res) {
        if (!res.isString()) {
            ret = Rejected;
            return true;
        }
        subname = res.as_string();
        ret = Accepted;
        return true;
    }, pivy);
    if (state == PyHookState::Failed)
        return Rejected;
    if (state == PyHookState::NotHandled)
        return NotImplemented;
    return ret;
}

bool ViewProviderFeaturePythonImp::getDetail(const char* name, SoDetail *&det) const
{
    auto state = callHook(HookGetDetail, [&det](const Py::Object& pydet) {
        void* ptr = nullptr;
        Base::Interpreter().convertSWIGPointerObj("pivy.coin", "SoDetail *",
                                                  pydet.ptr(), &ptr, 0);
        auto detail = static_cast<SoDetail*>(ptr);
        det = detail ? detail->copy() : nullptr;
        return true;
    }, name);
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::getDetailPath(
        const char* name, SoFullPath *path, bool append, SoDetail *&det) const
{
    if (!canCallHook(HookGetDetailPath))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    auto length = path->getLength();

    Py::Object pivy;
    if (!swigPointer(pivy, "SoFullPath *", static_cast<void*>(path), 1)) {
        path->truncate(length);
        return Rejected;
    }
    path->ref();

    ValueT ret = Rejected;
    bool truncate = true;
    auto state = callHook(HookGetDetailPath, [&](const Py::Object& pyDet) {
        if (!pyDet.isTrue()) {
            ret = Rejected;
            truncate = false;
            return true;
        }
        if (pyDet.isBoolean()) {
            ret = Accepted;
            truncate = false;
            return true;
        }
        void* ptr = nullptr;
        Base::Interpreter().convertSWIGPointerObj("pivy.coin", "SoDetail *",
                                                  pyDet.ptr(), &ptr, 0);
        auto detail = static_cast<SoDetail*>(ptr);
        det = detail ? detail->copy() : nullptr;
        if (det) {
            ret = Accepted;
            truncate = false;
            return true;
        }
        delete det;
        return true;
    }, name, pivy, append);

    if (state == PyHookState::NotHandled)
        return NotImplemented;
    if (truncate)
        path->truncate(length);
    return state == PyHookState::Failed ? Rejected : ret;
}


std::vector<Base::Vector3d> ViewProviderFeaturePythonImp::getSelectionShape(const char* /*Element*/) const
{
    return {};
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::setEdit(int ModNum)
{
    ValueT ret = NotImplemented;
    auto state = callHook(HookSetEdit, [&ret](const Py::Object& res) {
        if (res.isNone())
            return false;
        Py::Boolean ok(res);
        ret = static_cast<bool>(ok) ? Accepted : Rejected;
        return true;
    }, ModNum);
    if (state == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::unsetEdit(int ModNum)
{
    ValueT ret = NotImplemented;
    auto state = callHook(HookUnsetEdit, [&ret](const Py::Object& res) {
        if (res.isNone())
            return false;
        Py::Boolean ok(res);
        ret = static_cast<bool>(ok) ? Accepted : Rejected;
        return true;
    }, ModNum);
    if (state == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::setEditViewer(ViewerContext *viewer, int ModNum)
{
    if (!canCallHook(HookSetEditViewer))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    Py::Object pyViewer(Py::asObject(viewer->getPyObject()));

    ValueT ret = NotImplemented;
    auto state = callHook(HookSetEditViewer, [&ret](const Py::Object& res) {
        ret = res.isTrue() ? Accepted : Rejected;
        return true;
    }, pyViewer, ModNum);
    if (state == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::unsetEditViewer(ViewerContext *viewer)
{
    if (!canCallHook(HookUnsetEditViewer))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    Py::Object pyViewer(Py::asObject(viewer->getPyObject()));

    ValueT ret = NotImplemented;
    auto state = callHook(HookUnsetEditViewer, [&ret](const Py::Object& res) {
        ret = res.isTrue() ? Accepted : Rejected;
        return true;
    }, pyViewer);
    if (state == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::doubleClicked()
{
    ValueT ret = NotImplemented;
    if (callHook(HookDoubleClicked, App::pyHookDecodeValueT(ret)) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::iconMouseEvent(QMouseEvent *ev, const QByteArray &tag)
{
    if (!canCallHook(HookIconMouseEvent))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    PythonWrapper wrap;
    wrap.loadCoreModule();
    Py::Object pyEvent(wrap.fromQEvent(ev, "QMouseEvent"));

    ValueT ret = NotImplemented;
    if (callHook(HookIconMouseEvent, App::pyHookDecodeValueT(ret), pyEvent, tag.constData())
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

bool ViewProviderFeaturePythonImp::getToolTip(const QByteArray &tag, QString &tooltip) const
{
    auto state = callHook(HookGetToolTip, [&tooltip](const Py::Object& res) {
        if (!res.isString())
            return false;
        tooltip = QString::fromUtf8(res.as_string().c_str());
        return true;
    }, tag.constData());
    if (state == PyHookState::Failed)
        return false;
    return state == PyHookState::Handled;
}

bool ViewProviderFeaturePythonImp::setupContextMenu(QMenu* menu)
{
    if (!canCallHook(HookSetupContextMenu))
        return false;

    Base::PyGILStateLocker lock;
    PythonWrapper wrap;
    wrap.loadGuiModule();
    wrap.loadWidgetsModule();
    Py::Object pyMenu(wrap.fromQWidget(menu, "QMenu"));

    bool ret = false;
    auto state = callHook(HookSetupContextMenu, [&ret](const Py::Object& res) {
        ret = res.isTrue();
        return true;
    }, pyMenu);
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled ? ret : false;
}

void ViewProviderFeaturePythonImp::attach(App::DocumentObject *pcObject)
{
    if (callHook(HookAttach, App::pyHookDecodeNotify()) == PyHookState::Handled) {
        // #0000415: Now simulate a property change event to call
        // claimChildren if implemented.
        pcObject->Label.touch();
    }
}

void ViewProviderFeaturePythonImp::updateData(const App::Property* prop)
{
    if (!canCallHook(HookUpdateData))
        return;
    const char* prop_name = object->getObject()->getPropertyName(prop);
    if (!prop_name)
        return;
    callHook(HookUpdateData, App::pyHookDecodeNotify(), prop_name);
}

void ViewProviderFeaturePythonImp::onChanged(const App::Property* prop)
{
    if (!canCallHook(HookOnChanged))
        return;
    const char* prop_name = object->getPropertyName(prop);
    if (!prop_name)
        return;
    callHook(HookOnChanged, App::pyHookDecodeNotify(), prop_name);
}

void ViewProviderFeaturePythonImp::startRestoring()
{
}

void ViewProviderFeaturePythonImp::finishRestoring()
{
    {
        Base::PyGILStateLocker lock;
        try {
            Py::Object vp = Proxy.getValue();
            if (vp.isNone()) {
                object->show();
                Proxy.setValue(Py::Int(1));
                return;
            }
        }
        catch (Py::Exception&) {
            Base::PyException e; // extract the Python error text
            e.ReportException();
            return;
        }
    }
    callHook(HookFinishRestoring, App::pyHookDecodeNotify());
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::onDelete(const std::vector<std::string> & sub)
{
    ValueT ret = NotImplemented;
    if (callHook(HookOnDelete, App::pyHookDecodeValueT(ret), sub) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDelete(App::DocumentObject *obj) const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDelete, App::pyHookDecodeValueT(ret), obj) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canAddToSceneGraph() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanAddToSceneGraph, App::pyHookDecodeValueT(ret)) == PyHookState::Failed)
        return Accepted;
    return ret;
}

bool ViewProviderFeaturePythonImp::getDefaultDisplayMode(std::string &mode) const
{
    auto state = callHook(HookGetDefaultDisplayMode, [&mode](const Py::Object& res) {
        Py::String str(res);
        mode = str.as_std_string("ascii");
        return true;
    });
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

std::vector<std::string> ViewProviderFeaturePythonImp::getDisplayModes() const
{
    std::vector<std::string> modes;
    callHook(HookGetDisplayModes, [&modes](const Py::Object& res) {
        Py::Sequence list(res);
        for (Py::Sequence::iterator it = list.begin(); it != list.end(); ++it) {
            Py::String str(*it);
            modes.push_back(str.as_std_string("ascii"));
        }
        return true;
    });
    return modes;
}

std::string ViewProviderFeaturePythonImp::setDisplayMode(const char* ModeName)
{
    std::string ret = ModeName ? ModeName : "";
    callHook(HookSetDisplayMode, [&ret](const Py::Object& res) {
        Py::String str(res);
        ret = str.as_std_string("ascii");
        return true;
    }, ModeName);
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDragObjects() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDragObjects, App::pyHookDecodeValueT(ret)) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDragObject(App::DocumentObject* obj) const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDragObject, App::pyHookDecodeValueT(ret), obj) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::dragObject(App::DocumentObject* obj)
{
    auto state = callHook(HookDragObject, App::pyHookDecodeNotify(), obj);
    if (state == PyHookState::Failed)
        return Rejected;
    return state == PyHookState::Handled ? Accepted : NotImplemented;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDropObjects() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDropObjects, App::pyHookDecodeValueT(ret)) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDropObject(App::DocumentObject* obj) const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDropObject, App::pyHookDecodeValueT(ret), obj) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::dropObject(App::DocumentObject* obj)
{
    // a Python error here throws rather than reporting: the drop is a user
    // action and its failure belongs in the transaction
    auto state = callHook(HookDropObject, App::pyHookDecodeNotify(), obj);
    return state == PyHookState::Handled ? Accepted : NotImplemented;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDragAndDropObject(App::DocumentObject *obj) const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanDragAndDropObject, App::pyHookDecodeValueT(ret), obj)
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canDropObjectEx(App::DocumentObject* obj,
        App::DocumentObject *owner, const char *subname, const std::vector<std::string> &elements) const
{
    ValueT ret = NotImplemented;
    callHook(HookCanDropObjectEx, App::pyHookDecodeValueT(ret),
             obj, owner, subname, elements);
    return ret;
}

bool ViewProviderFeaturePythonImp::dropObjectEx(App::DocumentObject* obj, App::DocumentObject *owner,
        const char *subname, const std::vector<std::string> &elements,std::string &ret)
{
    auto state = callHook(HookDropObjectEx, [&ret](const Py::Object& res) {
        if (!res.isNone())
            ret = res.as_string();
        return true;
    }, obj, owner, subname, elements);
    return state != PyHookState::NotHandled;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::isShow() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookIsShow, App::pyHookDecodeValueT(ret)) == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canRemoveChildrenFromRoot() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanRemoveChildrenFromRoot, App::pyHookDecodeValueT(ret))
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

bool ViewProviderFeaturePythonImp::getDropPrefix(std::string &prefix) const
{
    auto state = callHook(HookGetDropPrefix, [&prefix](const Py::Object& res) {
        if (res.isNone())
            return false;
        prefix = res.as_string();
        return true;
    });
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::replaceObject(
        App::DocumentObject *oldObj, App::DocumentObject *newObj)
{
    if(!oldObj || !oldObj->isAttachedToDocument()
            || !newObj || !newObj->isAttachedToDocument())
        return NotImplemented;

    ValueT ret = NotImplemented;
    if (callHook(HookReplaceObject, App::pyHookDecodeValueT(ret), oldObj, newObj)
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canReplaceObject(
        App::DocumentObject *oldObj, App::DocumentObject *newObj)
{
    if(!oldObj || !oldObj->getNameInDocument()
            || !newObj || !newObj->getNameInDocument())
        return NotImplemented;

    ValueT ret = NotImplemented;
    if (callHook(HookCanReplaceObject, App::pyHookDecodeValueT(ret), oldObj, newObj)
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::reorderObjects(
        const std::vector<App::DocumentObject *> &objs, App::DocumentObject *before)
{
    if (!canCallHook(HookReorderObjects))
        return NotImplemented;

    Base::PyGILStateLocker lock;
    Py::List list;
    for (auto obj : objs) {
        if (obj && obj->getNameInDocument())
            list.append(Py::asObject(obj->getPyObject()));
    }

    ValueT ret = NotImplemented;
    if (callHook(HookReorderObjects, App::pyHookDecodeValueT(ret), Py::Object(list), before)
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

ViewProviderFeaturePythonImp::ValueT
ViewProviderFeaturePythonImp::canReorderObject(
        App::DocumentObject *obj, App::DocumentObject *before)
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanReorderObject, App::pyHookDecodeValueT(ret), obj, before)
            == PyHookState::Failed)
        return Rejected;
    return ret;
}

bool ViewProviderFeaturePythonImp::getLinkedViewProvider(
        ViewProviderDocumentObject *&vp, std::string *subname, bool recursive) const
{
    auto state = callHook(HookGetLinkedViewProvider, [&](const Py::Object& res) {
        if(res.isNone())
            return true;
        if(PyObject_TypeCheck(res.ptr(),&ViewProviderDocumentObjectPy::Type)) {
            vp = static_cast<ViewProviderDocumentObjectPy*>(
                    res.ptr())->getViewProviderDocumentObjectPtr();
            return true;
        } else if (PySequence_Check(res.ptr()) && PySequence_Length(res.ptr())==2) {
            Py::Sequence seq(res);
            Py::Object item0(seq[0].ptr());
            Py::Object item1(seq[1].ptr());
            if(PyObject_TypeCheck(item0.ptr(), &ViewProviderDocumentObjectPy::Type) && item1.isString()) {
                if(subname)
                    *subname = Py::String(item1).as_std_string("utf-8");
                vp = static_cast<ViewProviderDocumentObjectPy*>(
                        item0.ptr())->getViewProviderDocumentObjectPtr();
                return true;
            }
        }
        FC_ERR("getLinkedViewProvider(): invalid return type, expects ViewObject or (ViewObject, subname)");
        return true;
    }, recursive);
    if (state == PyHookState::Failed)
        return true;
    return state == PyHookState::Handled;
}

bool ViewProviderFeaturePythonImp::editProperty(const char *name)
{
    bool ret = false;
    callHook(HookEditProperty, [&ret](const Py::Object& res) {
        ret = res.isTrue();
        return true;
    }, name);
    return ret;
}
// ---------------------------------------------------------

namespace Gui {
PROPERTY_SOURCE_TEMPLATE(Gui::ViewProviderFeaturePython, Gui::ViewProviderDocumentObject)
// explicit template instantiation
template class GuiExport ViewProviderFeaturePythonT<ViewProviderDocumentObject>;
}

// ---------------------------------------------------------

namespace Gui {
PROPERTY_SOURCE_TEMPLATE(Gui::ViewProviderGeometryPython, Gui::ViewProviderGeometryObject)
// explicit template instantiation
template class GuiExport ViewProviderFeaturePythonT<ViewProviderGeometryObject>;
}


