# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com>
#
# This file is part of FreeCAD.
#
# FreeCAD is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 2.1 of the License, or (at your
# option) any later version.
#
# FreeCAD is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FreeCAD. If not, see <https://www.gnu.org/licenses/>.

"""Render the bundled appearance and surface finish icons.

The icons beside the cards in the material tree are renders of the
materials themselves, and the ones for the presets that ship with FreeCAD
ship with it too, so that every installation shows the same picture and
one without a usable GPU still shows a picture at all. This is what makes
them. It writes into this directory and rewrites the matching block of
Material.qrc, so the whole set is regenerated by running it and
committing what changes.

Run it whenever the answer would come out different: a preset's colours
change, the shading model changes, the engine's output changes. Nothing
breaks if you forget -- each file states the digest of the appearance it
was rendered from, and one that no longer matches is ignored in favour of
a fresh render -- but every stale icon then costs a render on first sight.

It needs a real GPU. The renderer draws these, so a software GL stack
gives you either nothing or something that is not what users will see.

    cd <build>
    GALLIUM_DRIVER=d3d12 MESA_LOADER_DRIVER_OVERRIDE=d3d12 \\
    LIBGL_ALWAYS_SOFTWARE=0 \\
        timeout 300 ./bin/FreeCAD \\
            ../../src/Mod/Material/Gui/Resources/icons/materials/generate.py

FreeCAD exits by itself when it is done. Pass FC_ICON_DIR to write
somewhere else, and FC_ICON_KEEP=1 to leave the GUI up afterwards.
"""

import os

import FreeCAD as App
import FreeCADGui as Gui
import MatGui
import Materials

from PySide import QtCore

# Where the icons live, and the block of Material.qrc that lists them.
# Both are relative to this file so that running the script from anywhere
# writes to the right place.
HERE = os.path.dirname(os.path.abspath(__file__))
QRC = os.path.normpath(os.path.join(HERE, "..", "..", "Material.qrc"))
QRC_PREFIX = "icons/materials/"
BEGIN = "        <!-- rendered by icons/materials/generate.py -->\n"
END = "        <!-- end rendered icons -->\n"

# Every surface finish pattern App::SurfaceFinish knows, by the name its
# Python API uses. Each is rendered on the neutral material and at the
# pitch and depth MaterialIcons::defaultFinish states; a finish the user
# has given a scale of its own no longer matches and renders at runtime.
FINISHES = ["knurl", "knurl-straight", "brushed", "blasted", "turned"]


# The shipped library the appearance presets live in. Not every material
# with an appearance is a preset: of the 215 that ship, 191 carry an
# appearance model, but the other 168 are steels and pattern files whose
# appearance is incidental to what they are for, they collapse to a
# handful of distinct renders between them, and nobody picks one for how
# it looks. These are the ones the appearance dialog offers.
PRESET_DIRECTORY = "Appearance"


def bundled_materials():
    """The materials whose icons ship: the presets, not the user's own.

    A preset is a card in the Appearance library that came out of
    FreeCAD's own resource directory. Anything else -- a material the
    user wrote, or one from an installed library -- is rendered on
    demand and cached, which is where a material nobody but its author
    has ever seen belongs.
    """
    resources = os.path.normcase(os.path.abspath(App.getResourceDir()))
    manager = Materials.MaterialManager()
    found = []
    for uuid, material in manager.Materials.items():
        if material.Directory != PRESET_DIRECTORY:
            continue
        if not material.AppearanceModels:
            continue
        root = material.LibraryRoot
        if not root:
            continue
        if not os.path.normcase(os.path.abspath(root)).startswith(resources):
            continue
        found.append((material.Name, uuid))
    return sorted(found)


def safe_name(name):
    """The file name a material's icon is bundled under.

    Must agree with MatGui::MaterialIcons::resourceName, which is what
    looks the file up again: an ordinary icon name, prefixed because it
    shares a namespace with every other icon in FreeCAD, and stripped of
    anything that does not survive being a file name.
    """
    kept = [c if (c.isalnum() and c.isascii()) or c in "._-" else " " for c in name]
    return "Appearance_" + "_".join("".join(kept).split())


def rewrite_qrc(files):
    """State the generated icons in Material.qrc, between the markers.

    Rewritten rather than appended so that a preset that goes away takes
    its icon out of the binary with it.
    """
    with open(QRC, encoding="utf-8", newline="") as handle:
        text = handle.read()
    block = BEGIN + "".join(
        "        <file>%s%s</file>\n" % (QRC_PREFIX, name) for name in sorted(files)
    ) + END
    start = text.find(BEGIN)
    if start >= 0:
        stop = text.find(END, start) + len(END)
        text = text[:start] + block + text[stop:]
    else:
        # First run: put the block just before the qresource closes.
        marker = "    </qresource>"
        text = text.replace(marker, block + marker, 1)
    with open(QRC, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def generate():
    target = os.environ.get("FC_ICON_DIR", HERE)
    if not os.path.isdir(target):
        os.makedirs(target)

    written = []
    failed = []

    for name, uuid in bundled_materials():
        path = os.path.join(target, safe_name(name) + ".png")
        if MatGui.renderMaterialIcon(uuid, path):
            written.append(os.path.basename(path))
        else:
            failed.append(name)

    for pattern in FINISHES:
        path = os.path.join(target, "Finish_" + pattern + ".png")
        if MatGui.renderFinishIcon(pattern, path):
            written.append(os.path.basename(path))
        else:
            failed.append("finish " + pattern)

    if failed:
        # Nothing rendered at all means no GPU, which is worth saying
        # plainly rather than leaving as an empty directory.
        App.Console.PrintError(
            "Material icons: %d of %d did not render (%s)\n"
            % (len(failed), len(failed) + len(written), ", ".join(failed[:5]))
        )
    if written:
        # Anything of ours the run did not write is left over from a
        # naming that no longer holds, and would otherwise sit in the
        # binary for good under a name nothing looks up.
        keep = set(written)
        for stale in os.listdir(target):
            if stale in keep or not stale.endswith(".png"):
                continue
            if stale.startswith("Appearance_") or stale.startswith("Finish_"):
                os.remove(os.path.join(target, stale))
                App.Console.PrintMessage("Material icons: dropped %s\n" % stale)
        rewrite_qrc(written)
        App.Console.PrintMessage(
            "Material icons: wrote %d into %s\n" % (len(written), target)
        )

    if not os.environ.get("FC_ICON_KEEP"):
        Gui.getMainWindow().close()


# The scene these are rendered from is a widget with a GL context, so
# there has to be an event loop first: schedule and let startup finish.
QtCore.QTimer.singleShot(0, generate)
