/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef MATERIAL_APP_PARAMS_H
#define MATERIAL_APP_PARAMS_H

#include <Mod/Material/MaterialGlobal.h>

/*[[[cog
import MaterialParams
MaterialParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Materials {
/** Convenient class to obtain the settings of the Material module

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Material"
 *
 * This class is auto generated by Mod/Material/App/MaterialParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Material/App/MaterialParams.h Mod/Material/App/MaterialParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Material/App/MaterialParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Material/App/MaterialParams.cpp with
 * the following signature.
 * @code
 *     void MaterialParams:on<parameter_name>Changed()
 * @endcode
 */
class MaterialsExport MaterialParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultMaterial
    ///
    /// Material used wherever the default material is asked for, such as
    /// for objects that have none of their own. Takes effect at the next
    /// use.
    static const std::string & getDefaultMaterial();
    static const std::string & defaultDefaultMaterial();
    static void removeDefaultMaterial();
    static void setDefaultMaterial(const std::string &v);
    static const char *docDefaultMaterial();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditorShowFavorites
    ///
    /// Shows the Favourites group in the tree of the materials editor.
    /// Takes effect the next time the editor is opened.
    static const bool & getEditorShowFavorites();
    static const bool & defaultEditorShowFavorites();
    static void removeEditorShowFavorites();
    static void setEditorShowFavorites(const bool &v);
    static const char *docEditorShowFavorites();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditorShowRecent
    ///
    /// Shows the group of recently used materials in the tree of the
    /// materials editor. Takes effect the next time the editor is opened.
    static const bool & getEditorShowRecent();
    static const bool & defaultEditorShowRecent();
    static void removeEditorShowRecent();
    static void setEditorShowRecent(const bool &v);
    static const char *docEditorShowRecent();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditorShowEmptyFolders
    ///
    /// Shows folders that hold no material in the tree of the materials
    /// editor. Takes effect the next time the editor is opened.
    static const bool & getEditorShowEmptyFolders();
    static const bool & defaultEditorShowEmptyFolders();
    static void removeEditorShowEmptyFolders();
    static void setEditorShowEmptyFolders(const bool &v);
    static const char *docEditorShowEmptyFolders();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditorShowEmptyLibraries
    ///
    /// Shows libraries that hold no material in the tree of the materials
    /// editor. Takes effect the next time the editor is opened.
    static const bool & getEditorShowEmptyLibraries();
    static const bool & defaultEditorShowEmptyLibraries();
    static void removeEditorShowEmptyLibraries();
    static void setEditorShowEmptyLibraries(const bool &v);
    static const char *docEditorShowEmptyLibraries();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditorShowLegacy
    ///
    /// Shows material cards that are still in the old file format in the
    /// tree of the materials editor. Takes effect the next time the
    /// editor is opened.
    static const bool & getEditorShowLegacy();
    static const bool & defaultEditorShowLegacy();
    static void removeEditorShowLegacy();
    static void setEditorShowLegacy(const bool &v);
    static const char *docEditorShowLegacy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorShowFavorites
    ///
    /// Shows the Favourites group in the list of the material selector.
    /// Takes effect the next time a material selector is created.
    static const bool & getSelectorShowFavorites();
    static const bool & defaultSelectorShowFavorites();
    static void removeSelectorShowFavorites();
    static void setSelectorShowFavorites(const bool &v);
    static const char *docSelectorShowFavorites();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorShowRecent
    ///
    /// Shows the group of recently used materials in the list of the
    /// material selector. Takes effect the next time a material selector
    /// is created.
    static const bool & getSelectorShowRecent();
    static const bool & defaultSelectorShowRecent();
    static void removeSelectorShowRecent();
    static void setSelectorShowRecent(const bool &v);
    static const char *docSelectorShowRecent();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorShowEmptyFolders
    ///
    /// Shows folders that hold no material in the list of the material
    /// selector. Takes effect the next time a material selector is
    /// created.
    static const bool & getSelectorShowEmptyFolders();
    static const bool & defaultSelectorShowEmptyFolders();
    static void removeSelectorShowEmptyFolders();
    static void setSelectorShowEmptyFolders(const bool &v);
    static const char *docSelectorShowEmptyFolders();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorShowEmptyLibraries
    ///
    /// Shows libraries that hold no material in the list of the material
    /// selector. Takes effect the next time a material selector is
    /// created.
    static const bool & getSelectorShowEmptyLibraries();
    static const bool & defaultSelectorShowEmptyLibraries();
    static void removeSelectorShowEmptyLibraries();
    static void setSelectorShowEmptyLibraries(const bool &v);
    static const char *docSelectorShowEmptyLibraries();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorShowLegacy
    ///
    /// Shows material cards that are still in the old file format in the
    /// list of the material selector. Takes effect the next time a
    /// material selector is created.
    static const bool & getSelectorShowLegacy();
    static const bool & defaultSelectorShowLegacy();
    static void removeSelectorShowLegacy();
    static void setSelectorShowLegacy(const bool &v);
    static const char *docSelectorShowLegacy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectorIconSize
    ///
    /// Size in pixels of the material previews in the list of the
    /// material selector, kept within a legible range. Takes effect the
    /// next time a material selector is created.
    static const long & getSelectorIconSize();
    static const long & defaultSelectorIconSize();
    static void removeSelectorIconSize();
    static void setSelectorIconSize(const long &v);
    static const char *docSelectorIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecentMax
    ///
    /// Greatest number of recently used materials that is remembered.
    /// Takes effect the next time the materials editor or a material
    /// selector is opened.
    static const long & getRecentMax();
    static const long & defaultRecentMax();
    static void removeRecentMax();
    static void setRecentMax(const long &v);
    static const char *docRecentMax();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ModelsRecentMax
    ///
    /// Greatest number of recently used material models that is
    /// remembered. Takes effect the next time the model selection
    /// dialogue is opened.
    static const long & getModelsRecentMax();
    static const long & defaultModelsRecentMax();
    static void removeModelsRecentMax();
    static void setModelsRecentMax(const long &v);
    static const char *docModelsRecentMax();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseBuiltInMaterials
    ///
    /// Lists the material cards and models that come with FreeCAD. Takes
    /// effect when the material libraries are next loaded.
    static const bool & getUseBuiltInMaterials();
    static const bool & defaultUseBuiltInMaterials();
    static void removeUseBuiltInMaterials();
    static void setUseBuiltInMaterials(const bool &v);
    static const char *docUseBuiltInMaterials();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseMaterialsFromWorkbenches
    ///
    /// Lists the material cards and models added by external workbenches.
    /// Takes effect when the material libraries are next loaded.
    static const bool & getUseMaterialsFromWorkbenches();
    static const bool & defaultUseMaterialsFromWorkbenches();
    static void removeUseMaterialsFromWorkbenches();
    static void setUseMaterialsFromWorkbenches(const bool &v);
    static const char *docUseMaterialsFromWorkbenches();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseMaterialsFromConfigDir
    ///
    /// Lists the material cards and models found in the Material and
    /// Models folders of the user's FreeCAD data directory. Takes effect
    /// when the material libraries are next loaded.
    static const bool & getUseMaterialsFromConfigDir();
    static const bool & defaultUseMaterialsFromConfigDir();
    static void removeUseMaterialsFromConfigDir();
    static void setUseMaterialsFromConfigDir(const bool &v);
    static const char *docUseMaterialsFromConfigDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseMaterialsFromCustomDir
    ///
    /// Lists the material cards and models found in the user-defined
    /// directory. Takes effect when the material libraries are next
    /// loaded.
    static const bool & getUseMaterialsFromCustomDir();
    static const bool & defaultUseMaterialsFromCustomDir();
    static void removeUseMaterialsFromCustomDir();
    static void setUseMaterialsFromCustomDir(const bool &v);
    static const char *docUseMaterialsFromCustomDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CustomMaterialsDir
    ///
    /// Directory with the user's own material cards. Takes effect when
    /// the material libraries are next loaded.
    static const std::string & getCustomMaterialsDir();
    static const std::string & defaultCustomMaterialsDir();
    static void removeCustomMaterialsDir();
    static void setCustomMaterialsDir(const std::string &v);
    static const char *docCustomMaterialsDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseExternal
    ///
    /// Uses an external material interface in addition to the local
    /// material libraries. Takes effect at once.
    static const bool & getUseExternal();
    static const bool & defaultUseExternal();
    static void removeUseExternal();
    static void setUseExternal(const bool &v);
    static const char *docUseExternal();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalInterface
    ///
    /// Name of the external material interface to use, or None. Takes
    /// effect at once: the connection is made again when the value
    /// changes.
    static const std::string & getExternalInterface();
    static const std::string & defaultExternalInterface();
    static void removeExternalInterface();
    static void setExternalInterface(const std::string &v);
    static const char *docExternalInterface();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ModelCacheSize
    ///
    /// Number of material models kept in the cache of the external
    /// material interface. Takes effect after restart.
    static const long & getModelCacheSize();
    static const long & defaultModelCacheSize();
    static void removeModelCacheSize();
    static void setModelCacheSize(const long &v);
    static const char *docModelCacheSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaterialCacheSize
    ///
    /// Number of materials kept in the cache of the external material
    /// interface. Takes effect after restart.
    static const long & getMaterialCacheSize();
    static const long & defaultMaterialCacheSize();
    static void removeMaterialCacheSize();
    static void setMaterialCacheSize(const long &v);
    static const char *docMaterialCacheSize();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class MaterialParams
} // namespace Materials
//[[[end]]]

#endif // MATERIAL_APP_PARAMS_H
