/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef ASSEMBLY_APP_PARAMS_H
#define ASSEMBLY_APP_PARAMS_H

#include <Mod/Assembly/AssemblyGlobal.h>

/*[[[cog
import AssemblyParams
AssemblyParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Assembly {
/** Convenient class to obtain the settings of the Assembly workbench

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Assembly"
 *
 * This class is auto generated by Mod/Assembly/App/AssemblyParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Assembly/App/AssemblyParams.h Mod/Assembly/App/AssemblyParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Assembly/App/AssemblyParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Assembly/App/AssemblyParams.cpp with
 * the following signature.
 * @code
 *     void AssemblyParams:on<parameter_name>Changed()
 * @endcode
 */
class AssemblyExport AssemblyParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SolveOnRecompute
    ///
    /// Solves the joints of an assembly every time the assembly is
    /// recomputed. Takes effect at the next recompute.
    static const bool & getSolveOnRecompute();
    static const bool & defaultSolveOnRecompute();
    static void removeSolveOnRecompute();
    static void setSolveOnRecompute(const bool &v);
    static const char *docSolveOnRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SolveOnMove
    ///
    /// Solves the joints continuously while a part is dragged, so that
    /// connected parts follow. When off, only the joint markers are
    /// redrawn during the drag. Takes effect at the next drag.
    static const bool & getSolveOnMove();
    static const bool & defaultSolveOnMove();
    static void removeSolveOnMove();
    static void setSolveOnMove(const bool &v);
    static const char *docSolveOnMove();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LeaveEditWithEscape
    ///
    /// Lets the Esc key leave the edit mode of an assembly when no task
    /// dialogue is open. Takes effect at once.
    static const bool & getLeaveEditWithEscape();
    static const bool & defaultLeaveEditWithEscape();
    static void removeLeaveEditWithEscape();
    static void setLeaveEditWithEscape(const bool &v);
    static const char *docLeaveEditWithEscape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SwitchToWB
    ///
    /// Switches to the Assembly workbench when an assembly is double-
    /// clicked for editing. Takes effect at the next double-click.
    static const bool & getSwitchToWB();
    static const bool & defaultSwitchToWB();
    static void removeSwitchToWB();
    static void setSwitchToWB(const bool &v);
    static const char *docSwitchToWB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter JointHighlightColor
    ///
    /// Colour the elements a joint connects are shown in while the
    /// joint is selected or edited: a red, unless set. Takes effect at
    /// the next highlight.
    static const unsigned long & getJointHighlightColor();
    static const unsigned long & defaultJointHighlightColor();
    static void removeJointHighlightColor();
    static void setJointHighlightColor(const unsigned long &v);
    static const char *docJointHighlightColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LogSolverDebug
    ///
    /// Writes the dragging steps of the solver to the files
    /// runPreDrag.asmt and dragging.log, which helps when reporting a
    /// solver problem. Takes effect the next time the assembly is solved.
    static const bool & getLogSolverDebug();
    static const bool & defaultLogSolverDebug();
    static void removeLogSolverDebug();
    static void setLogSolverDebug(const bool &v);
    static const char *docLogSolverDebug();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BomMirroredSuffix
    ///
    /// Text appended to the name of a mirrored part in a bill of
    /// materials. Takes effect the next time the bill of materials is
    /// generated.
    static const std::string & getBomMirroredSuffix();
    static const std::string & defaultBomMirroredSuffix();
    static void removeBomMirroredSuffix();
    static void setBomMirroredSuffix(const std::string &v);
    static const char *docBomMirroredSuffix();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class AssemblyParams
} // namespace Assembly
//[[[end]]]

#endif // ASSEMBLY_APP_PARAMS_H
