/****************************************************************************
 *   Copyright (c) 2022 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef PART_APP_PARAMS_H
#define PART_APP_PARAMS_H

#include <Mod/Part/PartGlobal.h>

/*[[[cog
import PartParams
PartParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Part {
/** Convenient class to obtain Part/PartDesign related parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Part"
 *
 * This class is auto generated by Mod/Part/App/PartParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Part/App/PartParams.h Mod/Part/App/PartParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Part/App/PartParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Part/App/PartParams.cpp with
 * the following signature.
 * @code
 *     void PartParams:on<parameter_name>Changed()
 * @endcode
 */
class PartExport PartParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShapePropertyCopy
    ///
    /// Make a full geometric copy whenever a shape property is copied,
    /// instead of sharing the shape. Uses much more memory on complex
    /// models.
    static const bool & getShapePropertyCopy();
    static const bool & defaultShapePropertyCopy();
    static void removeShapePropertyCopy();
    static void setShapePropertyCopy(const bool &v);
    static const char *docShapePropertyCopy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DisableShapeCache
    ///
    /// Do not keep the shapes computed for an object and its sub-objects
    /// for reuse. They are rebuilt on every request, which is slower;
    /// meant for troubleshooting.
    static const bool & getDisableShapeCache();
    static const bool & defaultDisableShapeCache();
    static void removeDisableShapeCache();
    static void setDisableShapeCache(const bool &v);
    static const char *docDisableShapeCache();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CommandOverride
    ///
    /// Run the PartDesign equivalent when a Part command is used with a
    /// PartDesign body active or one of its features selected. 0 never,
    /// 1 always, 2 ask each time.
    static const long & getCommandOverride();
    static const long & defaultCommandOverride();
    static void removeCommandOverride();
    static void setCommandOverride(const long &v);
    static const char *docCommandOverride();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EnableWrapFeature
    ///
    /// Bring a non-PartDesign object that references features of the
    /// active body into that body through a wrap feature. 0 never,
    /// 1 always, 2 ask each time.
    static const long & getEnableWrapFeature();
    static const long & defaultEnableWrapFeature();
    static void removeEnableWrapFeature();
    static void setEnableWrapFeature(const long &v);
    static const char *docEnableWrapFeature();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CopySubShape
    ///
    /// Copy the geometry when a placed sub-shape of an object is handed
    /// to Python, instead of only moving it. Slower, but avoids kernel
    /// errors on some transformed shapes.
    static const bool & getCopySubShape();
    static const bool & defaultCopySubShape();
    static void removeCopySubShape();
    static void setCopySubShape(const bool &v);
    static const char *docCopySubShape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseBrepToolsOuterWire
    ///
    /// Find the outer wire of a face in Python (Face.OuterWire) with the
    /// kernel's BRepTools. When off its ShapeAnalysis is used; the two
    /// can differ on unusual faces.
    static const bool & getUseBrepToolsOuterWire();
    static const bool & defaultUseBrepToolsOuterWire();
    static void removeUseBrepToolsOuterWire();
    static void setUseBrepToolsOuterWire(const bool &v);
    static const char *docUseBrepToolsOuterWire();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseBaseObjectName
    ///
    /// Label a new body after the object selected as its base feature.
    /// The question asked when the body is created has the same checkbox.
    static const bool & getUseBaseObjectName();
    static const bool & defaultUseBaseObjectName();
    static void removeUseBaseObjectName();
    static void setUseBaseObjectName(const bool &v);
    static const char *docUseBaseObjectName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoGroupSolids
    ///
    /// Turn on Auto Group Solids in new bodies, which groups the features
    /// of each solid under its latest feature.
    static const bool & getAutoGroupSolids();
    static const bool & defaultAutoGroupSolids();
    static void removeAutoGroupSolids();
    static void setAutoGroupSolids(const bool &v);
    static const char *docAutoGroupSolids();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SingleSolid
    ///
    /// Turn on Single Solid in new bodies, so that every feature must
    /// result in one solid.
    static const bool & getSingleSolid();
    static const bool & defaultSingleSolid();
    static void removeSingleSolid();
    static void setSingleSolid(const bool &v);
    static const char *docSingleSolid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UsePipeForExtrusionDraft
    ///
    /// Build the draft angle of new pads, pockets and Part extrusions
    /// with a sweep instead of a loft. Each object keeps its own switch.
    static const bool & getUsePipeForExtrusionDraft();
    static const bool & defaultUsePipeForExtrusionDraft();
    static void removeUsePipeForExtrusionDraft();
    static void setUsePipeForExtrusionDraft(const bool &v);
    static const char *docUsePipeForExtrusionDraft();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LinearizeExtrusionDraft
    ///
    /// Turn flat spline faces into planes and straight spline edges into
    /// lines in new lofts, sweeps and drafted extrusions, in Part and
    /// PartDesign. Each object keeps its own switch.
    static const bool & getLinearizeExtrusionDraft();
    static const bool & defaultLinearizeExtrusionDraft();
    static void removeLinearizeExtrusionDraft();
    static void setLinearizeExtrusionDraft(const bool &v);
    static const char *docLinearizeExtrusionDraft();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoCorrectLink
    ///
    /// While a PartDesign feature is edited, replace a reference it is
    /// given by a sub-shape binder imported into the body automatically.
    static const bool & getAutoCorrectLink();
    static const bool & defaultAutoCorrectLink();
    static void removeAutoCorrectLink();
    static void setAutoCorrectLink(const bool &v);
    static const char *docAutoCorrectLink();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RefineModel
    ///
    /// Turn on Refine in new sub-shape binders, which merges faces lying
    /// on the same surface. Part booleans and PartDesign features have
    /// their own settings.
    static const bool & getRefineModel();
    static const bool & defaultRefineModel();
    static void removeRefineModel();
    static void setRefineModel(const bool &v);
    static const char *docRefineModel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AuxGroupUniqueLabel
    ///
    /// Give the Sketches, Datums and Misc groups of each body a unique
    /// label such as Datums001. When off they can all carry the same
    /// label.
    static const bool & getAuxGroupUniqueLabel();
    static const bool & defaultAuxGroupUniqueLabel();
    static void removeAuxGroupUniqueLabel();
    static void setAuxGroupUniqueLabel(const bool &v);
    static const char *docAuxGroupUniqueLabel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SplitEllipsoid
    ///
    /// Turn on Split in new ellipsoids, which cuts the surface in the
    /// middle to avoid errors in later boolean operations.
    static const bool & getSplitEllipsoid();
    static const bool & defaultSplitEllipsoid();
    static void removeSplitEllipsoid();
    static void setSplitEllipsoid(const bool &v);
    static const char *docSplitEllipsoid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ParallelRunThreshold
    ///
    /// Run boolean operations on several processor threads. Any value
    /// above 0 turns this on, 0 or less turns it off.
    static const long & getParallelRunThreshold();
    static const long & defaultParallelRunThreshold();
    static void removeParallelRunThreshold();
    static void setParallelRunThreshold(const long &v);
    static const char *docParallelRunThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoValidateShape
    ///
    /// Turn on Validate Shape in new PartDesign features. An invalid
    /// result then gets a warning icon in the tree. Can slow down complex
    /// models.
    static const bool & getAutoValidateShape();
    static const bool & defaultAutoValidateShape();
    static void removeAutoValidateShape();
    static void setAutoValidateShape(const bool &v);
    static const char *docAutoValidateShape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FixShape
    ///
    /// Set Fix Shape to Enabled in new Part objects, so that a result
    /// found invalid is repaired. When off new objects are left as they
    /// are computed.
    static const bool & getFixShape();
    static const bool & defaultFixShape();
    static void removeFixShape();
    static void setFixShape(const bool &v);
    static const char *docFixShape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShareStoredSubShapes
    ///
    /// Let a stored shape borrow a sub-shape from another object's file instead
    /// of writing its geometry again (docs/SharedShapeStorage.md sec 12.4).
    /// Turning this off writes every file whole, which is what the format did
    /// before external references; the files stay readable either way.
    static const bool & getShareStoredSubShapes();
    static const bool & defaultShareStoredSubShapes();
    static void removeShareStoredSubShapes();
    static void setShareStoredSubShapes(const bool &v);
    static const char *docShareStoredSubShapes();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BorrowBelowFace
    ///
    /// Which sub-shapes a shape file may borrow from another below the level
    /// of a shell, as a sum: 1 a face in a shell, 2 an edge in a face or
    /// wire, 4 a vertex in an edge. 0, the default, none.
    static const long & getBorrowBelowFace();
    static const long & defaultBorrowBelowFace();
    static void removeBorrowBelowFace();
    static void setBorrowBelowFace(const long &v);
    static const char *docBorrowBelowFace();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LoftMaxDegree
    ///
    /// Maximum surface degree given to new PartDesign lofts. Kept between
    /// 2 and the highest degree the kernel supports.
    static const unsigned long & getLoftMaxDegree();
    static const unsigned long & defaultLoftMaxDegree();
    static void removeLoftMaxDegree();
    static void setLoftMaxDegree(const unsigned long &v);
    static const char *docLoftMaxDegree();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WarnUnnamedInput
    ///
    /// Report shape operations whose inputs carry no element names, so the
    /// result cannot be named either. For workbench developers. 0 off, 1 once
    /// per operation and recompute, 2 every occurrence.
    static const long & getWarnUnnamedInput();
    static const long & defaultWarnUnnamedInput();
    static void removeWarnUnnamedInput();
    static void setWarnUnnamedInput(const long &v);
    static const char *docWarnUnnamedInput();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MinimumDeviation
    ///
    /// Lower limit of the tessellation deviation of shapes, in percent of
    /// the object size. Objects asking for a finer mesh are drawn with
    /// this value instead.
    static const double & getMinimumDeviation();
    static const double & defaultMinimumDeviation();
    static void removeMinimumDeviation();
    static void setMinimumDeviation(const double &v);
    static const char *docMinimumDeviation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshDeviation
    ///
    /// Accuracy of the mesh that shapes are drawn with, as the largest
    /// deviation in percent of the object size. Lower is finer and
    /// slower. Sets the Deviation of new objects; a change is applied to
    /// all open objects.
    static const double & getMeshDeviation();
    static const double & defaultMeshDeviation();
    static void removeMeshDeviation();
    static void setMeshDeviation(const double &v);
    static const char *docMeshDeviation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshAngularDeflection
    ///
    /// Largest angle between neighbouring segments of the mesh that
    /// shapes are drawn with, in degrees. Lower is smoother and slower.
    /// Sets the Angular Deflection of new objects; a change is applied to
    /// all open objects.
    static const double & getMeshAngularDeflection();
    static const double & defaultMeshAngularDeflection();
    static void removeMeshAngularDeflection();
    static void setMeshAngularDeflection(const double &v);
    static const char *docMeshAngularDeflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MinimumAngularDeflection
    ///
    /// Lower limit of the angular deflection used to mesh shapes, in
    /// degrees. Objects asking for a smaller angle are drawn with this
    /// value instead.
    static const double & getMinimumAngularDeflection();
    static const double & defaultMinimumAngularDeflection();
    static void removeMinimumAngularDeflection();
    static void setMinimumAngularDeflection(const double &v);
    static const char *docMinimumAngularDeflection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BooleanRefineModel
    ///
    /// New Part Boolean features get Refine switched on: faces that lie
    /// on the same surface are merged after the operation. Read when a
    /// feature is created.
    static const bool & getBooleanRefineModel();
    static const bool & defaultBooleanRefineModel();
    static void removeBooleanRefineModel();
    static void setBooleanRefineModel(const bool &v);
    static const char *docBooleanRefineModel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BooleanCheckModel
    ///
    /// Check the result of every Part Boolean operation for validity,
    /// and fail the feature when it is not valid.
    static const bool & getBooleanCheckModel();
    static const bool & defaultBooleanCheckModel();
    static void removeBooleanCheckModel();
    static void setBooleanCheckModel(const bool &v);
    static const char *docBooleanCheckModel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BooleanFuzzy
    ///
    /// Factor of the tolerance a Boolean operation is given when it is
    /// told to choose one itself: this times the size of the shapes times
    /// the kernel's precision.
    static const double & getBooleanFuzzy();
    static const double & defaultBooleanFuzzy();
    static void removeBooleanFuzzy();
    static void setBooleanFuzzy(const double &v);
    static const char *docBooleanFuzzy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoElementMap
    ///
    /// Give a shape that arrives without element names -- read from a
    /// file, set by a script -- names of its own. Read once, at the first
    /// such shape of a session.
    static const bool & getAutoElementMap();
    static const bool & defaultAutoElementMap();
    static void removeAutoElementMap();
    static void setAutoElementMap(const bool &v);
    static const char *docAutoElementMap();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class PartParams
} // namespace Part
//[[[end]]]

#endif // PART_APP_PARAMS_H
