/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef PARTDESIGN_APP_PARAMS_H
#define PARTDESIGN_APP_PARAMS_H

#include <Mod/PartDesign/PartDesignGlobal.h>

/*[[[cog
import PartDesignParams
PartDesignParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace PartDesign {
/** Convenient class to obtain the settings of PartDesign

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/PartDesign"
 *
 * This class is auto generated by Mod/PartDesign/App/PartDesignParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/PartDesign/App/PartDesignParams.h Mod/PartDesign/App/PartDesignParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/PartDesign/App/PartDesignParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/PartDesign/App/PartDesignParams.cpp with
 * the following signature.
 * @code
 *     void PartDesignParams:on<parameter_name>Changed()
 * @endcode
 */
class PartDesignExport PartDesignParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RefineModel
    ///
    /// New PartDesign features get Refine switched on: faces that lie
    /// on the same surface are merged after the feature is computed.
    /// Read when a feature is created.
    static const bool & getRefineModel();
    static const bool & defaultRefineModel();
    static void removeRefineModel();
    static void setRefineModel(const bool &v);
    static const char *docRefineModel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter defaultBaseTypeHole
    ///
    /// What a new Hole takes from its sketch: 0 circles and arcs, 1
    /// points, circles and arcs, 2 points. Read when a Hole is created.
    static const long & getdefaultBaseTypeHole();
    static const long & defaultdefaultBaseTypeHole();
    static void removedefaultBaseTypeHole();
    static void setdefaultBaseTypeHole(const long &v);
    static const char *docdefaultBaseTypeHole();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NewSketchUseAttachmentDialog
    ///
    /// Open the attachment panel for every new sketch, also when a
    /// single planar face or plane is selected, which is otherwise
    /// sketched on at once.
    static const bool & getNewSketchUseAttachmentDialog();
    static const bool & defaultNewSketchUseAttachmentDialog();
    static void removeNewSketchUseAttachmentDialog();
    static void setNewSketchUseAttachmentDialog(const bool &v);
    static const char *docNewSketchUseAttachmentDialog();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BooleanDeleteOnRemove
    ///
    /// Removing a body from a PartDesign Boolean also deletes the body.
    /// The check box of the Boolean task panel.
    static const bool & getBooleanDeleteOnRemove();
    static const bool & defaultBooleanDeleteOnRemove();
    static void removeBooleanDeleteOnRemove();
    static void setBooleanDeleteOnRemove(const bool &v);
    static const char *docBooleanDeleteOnRemove();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SwitchToWB
    ///
    /// Activate the PartDesign workbench when a body is double-clicked.
    static const bool & getSwitchToWB();
    static const bool & defaultSwitchToWB();
    static void removeSwitchToWB();
    static void setSwitchToWB(const bool &v);
    static const char *docSwitchToWB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SwitchToTask
    ///
    /// Bring the task view to the front when the PartDesign workbench is
    /// activated.
    static const bool & getSwitchToTask();
    static const bool & defaultSwitchToTask();
    static void removeSwitchToTask();
    static void setSwitchToTask(const bool &v);
    static const char *docSwitchToTask();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoordinateSystemFontSize
    ///
    /// Font size of the axis labels of a new local coordinate system.
    static const long & getCoordinateSystemFontSize();
    static const long & defaultCoordinateSystemFontSize();
    static void removeCoordinateSystemFontSize();
    static void setCoordinateSystemFontSize(const long &v);
    static const char *docCoordinateSystemFontSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoordinateSystemZoom
    ///
    /// Size factor of a new local coordinate system.
    static const double & getCoordinateSystemZoom();
    static const double & defaultCoordinateSystemZoom();
    static void removeCoordinateSystemZoom();
    static void setCoordinateSystemZoom(const double &v);
    static const char *docCoordinateSystemZoom();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoordinateSystemShowLabel
    ///
    /// Show the axis labels of a new local coordinate system.
    static const bool & getCoordinateSystemShowLabel();
    static const bool & defaultCoordinateSystemShowLabel();
    static void removeCoordinateSystemShowLabel();
    static void setCoordinateSystemShowLabel(const bool &v);
    static const char *docCoordinateSystemShowLabel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoordinateSystemSelectOnTop
    ///
    /// Draw a new local coordinate system on top of everything else
    /// while it is selected.
    static const bool & getCoordinateSystemSelectOnTop();
    static const bool & defaultCoordinateSystemSelectOnTop();
    static void removeCoordinateSystemSelectOnTop();
    static void setCoordinateSystemSelectOnTop(const bool &v);
    static const char *docCoordinateSystemSelectOnTop();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class PartDesignParams
} // namespace PartDesign
//[[[end]]]

#endif // PARTDESIGN_APP_PARAMS_H
