/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_DIALOG_DLGSETTINGSRENDER_H
#define GUI_DIALOG_DLGSETTINGSRENDER_H

/*[[[cog
import DlgSettingsRender
DlgSettingsRender.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:519)
#include <Gui/PropertyPage.h>
#include <Gui/PrefWidgets.h>
// Auto generated code (Tools/params_utils.py:526)
class QLabel;
class QGroupBox;

namespace Gui {
namespace Dialog {
/** Preference dialog for the experimental render engine settings

 * This class is auto generated by Gui/PreferencePages/DlgSettingsRender.py. Modify that file
 * instead of this one, if you want to make any change. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/PreferencePages/DlgSettingsRender.h Gui/PreferencePages/DlgSettingsRender.cpp
 * @endcode
 */
class DlgSettingsRender : public Gui::Dialog::PreferencePage
{
    Q_OBJECT

public:
    DlgSettingsRender( QWidget* parent = 0 );
    ~DlgSettingsRender();

    void saveSettings();
    void loadSettings();
    void retranslateUi();

protected:
    void changeEvent(QEvent *e);

private:

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupGeneral = nullptr;
    QLabel *labelType = nullptr;
    Gui::PrefLineEdit *Type = nullptr;
    QLabel *labelOutputTransform = nullptr;
    Gui::PrefComboBox *OutputTransform = nullptr;
    QLabel *labelExposure = nullptr;
    Gui::PrefDoubleSpinBox *Exposure = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupIdlerefinement = nullptr;
    Gui::PrefCheckBox *TemporalAccum = nullptr;
    QLabel *labelTemporalAccumSamples = nullptr;
    Gui::PrefSpinBox *TemporalAccumSamples = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupScenestreaming = nullptr;
    QLabel *labelCoarseTessellation = nullptr;
    Gui::PrefSpinBox *CoarseTessellation = nullptr;
    QLabel *labelLevelTolerance = nullptr;
    Gui::PrefDoubleSpinBox *LevelTolerance = nullptr;
    QLabel *labelLevelThreads = nullptr;
    Gui::PrefSpinBox *LevelThreads = nullptr;
    QLabel *labelLevelMemoryFloorMB = nullptr;
    Gui::PrefSpinBox *LevelMemoryFloorMB = nullptr;
    QLabel *labelGpuMemoryBudgetMB = nullptr;
    Gui::PrefSpinBox *GpuMemoryBudgetMB = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupAmbientocclusion = nullptr;
    Gui::PrefCheckBox *AO = nullptr;
    QLabel *labelAOMethod = nullptr;
    Gui::PrefComboBox *AOMethod = nullptr;
    QLabel *labelAOSlices = nullptr;
    Gui::PrefSpinBox *AOSlices = nullptr;
    QLabel *labelAOSteps = nullptr;
    Gui::PrefSpinBox *AOSteps = nullptr;
    QLabel *labelAORadius = nullptr;
    Gui::PrefDoubleSpinBox *AORadius = nullptr;
    QLabel *labelAOIntensity = nullptr;
    Gui::PrefDoubleSpinBox *AOIntensity = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupPhysicallybasedshading = nullptr;
    Gui::PrefCheckBox *PBR = nullptr;
    QLabel *labelPBRMetallic = nullptr;
    Gui::PrefDoubleSpinBox *PBRMetallic = nullptr;
    QLabel *labelPBRRoughness = nullptr;
    Gui::PrefDoubleSpinBox *PBRRoughness = nullptr;
    Gui::PrefCheckBox *PBRFromSpecular = nullptr;
    QLabel *labelShininessMapping = nullptr;
    Gui::PrefComboBox *ShininessMapping = nullptr;
    QLabel *labelPBREnvIntensity = nullptr;
    Gui::PrefDoubleSpinBox *PBREnvIntensity = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupBumpmapping = nullptr;
    QLabel *labelBumpScale = nullptr;
    Gui::PrefDoubleSpinBox *BumpScale = nullptr;
    Gui::PrefCheckBox *Parallax = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupVolumetriclighting = nullptr;
    Gui::PrefCheckBox *Volumetric = nullptr;
    QLabel *labelVolumetricIntensity = nullptr;
    Gui::PrefDoubleSpinBox *VolumetricIntensity = nullptr;
    QLabel *labelVolumetricDensity = nullptr;
    Gui::PrefDoubleSpinBox *VolumetricDensity = nullptr;
    Gui::PrefCheckBox *Caustics = nullptr;
    QLabel *labelCausticsIntensity = nullptr;
    Gui::PrefDoubleSpinBox *CausticsIntensity = nullptr;
    QLabel *labelCausticsScale = nullptr;
    Gui::PrefDoubleSpinBox *CausticsScale = nullptr;
    QLabel *labelCausticsSpeed = nullptr;
    Gui::PrefDoubleSpinBox *CausticsSpeed = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupWatersurface = nullptr;
    Gui::PrefCheckBox *WaterSurface = nullptr;
    QLabel *labelWaterWaveStrength = nullptr;
    Gui::PrefDoubleSpinBox *WaterWaveStrength = nullptr;
    QLabel *labelWaterWaveScale = nullptr;
    Gui::PrefDoubleSpinBox *WaterWaveScale = nullptr;
    QLabel *labelWaterWaveSpeed = nullptr;
    Gui::PrefDoubleSpinBox *WaterWaveSpeed = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupBloom = nullptr;
    Gui::PrefCheckBox *Bloom = nullptr;
    QLabel *labelBloomThreshold = nullptr;
    Gui::PrefDoubleSpinBox *BloomThreshold = nullptr;
    QLabel *labelBloomIntensity = nullptr;
    Gui::PrefDoubleSpinBox *BloomIntensity = nullptr;
    QLabel *labelBloomRadius = nullptr;
    Gui::PrefDoubleSpinBox *BloomRadius = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupScenelightextras = nullptr;
    Gui::PrefCheckBox *SunDisc = nullptr;
    QLabel *labelSunDiscSize = nullptr;
    Gui::PrefDoubleSpinBox *SunDiscSize = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupGroundreflection = nullptr;
    Gui::PrefCheckBox *GroundReflection = nullptr;
    QLabel *labelGroundReflectionIntensity = nullptr;
    Gui::PrefDoubleSpinBox *GroundReflectionIntensity = nullptr;

    // Auto generated code (Tools/params_utils.py:426)
    QGroupBox * groupExternalshadingCycles = nullptr;
    QLabel *labelCyclesDevice = nullptr;
    Gui::PrefLineEdit *CyclesDevice = nullptr;
    QLabel *labelCyclesSamples = nullptr;
    Gui::PrefSpinBox *CyclesSamples = nullptr;
    QLabel *labelCyclesTimeLimit = nullptr;
    Gui::PrefDoubleSpinBox *CyclesTimeLimit = nullptr;
    Gui::PrefCheckBox *CyclesDenoise = nullptr;
    QLabel *labelCyclesPixelSize = nullptr;
    Gui::PrefSpinBox *CyclesPixelSize = nullptr;
    QLabel *labelCyclesMaxStreams = nullptr;
    Gui::PrefSpinBox *CyclesMaxStreams = nullptr;
// Auto generated code (Tools/params_utils.py:573)
};
} // namespace Dialog
} // namespace Gui
//[[[end]]]

#endif // GUI_DIALOG_DLGSETTINGSRENDER_H
