/****************************************************************************
 *   Copyright (c) 2024 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_DIALOG_DLGSETTINGS_SELECTION_H
#define GUI_DIALOG_DLGSETTINGS_SELECTION_H

/*[[[cog
import DlgSettingsSelection
DlgSettingsSelection.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:516)
#include <Gui/PropertyPage.h>
#include <Gui/PrefWidgets.h>
// Auto generated code (Tools/params_utils.py:523)
class QLabel;
class QGroupBox;

namespace Gui {
namespace Dialog {
/** Preference dialog for various tree and 3D view selection related settings

 * This class is auto generated by Gui/PreferencePages/DlgSettingsSelection.py. Modify that file
 * instead of this one, if you want to make any change. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Gui/PreferencePages/DlgSettingsSelection.h Gui/PreferencePages/DlgSettingsSelection.cpp
 * @endcode
 */
class DlgSettingsSelection : public Gui::Dialog::PreferencePage
{
    Q_OBJECT

public:
    DlgSettingsSelection( QWidget* parent = 0 );
    ~DlgSettingsSelection();

    void saveSettings();
    void loadSettings();
    void retranslateUi();

protected:
    void changeEvent(QEvent *e);

private:

    // Auto generated code (Tools/params_utils.py:423)
    QGroupBox * groupTreeViewSelection = nullptr;
    Gui::PrefCheckBox *SyncView = nullptr;
    Gui::PrefCheckBox *SyncSelection = nullptr;
    Gui::PrefCheckBox *CheckBoxesSelection = nullptr;
    Gui::PrefCheckBox *RecordSelection = nullptr;
    Gui::PrefCheckBox *PreSelection = nullptr;

    // Auto generated code (Tools/params_utils.py:423)
    QGroupBox * groupDViewSelection = nullptr;
    Gui::PrefCheckBox *EnablePreselection = nullptr;
    Gui::PrefSpinBox *HighlightColor = nullptr;
    Gui::PrefCheckBox *EnableSelection = nullptr;
    Gui::PrefSpinBox *SelectionColor = nullptr;
    QLabel *labelPickRadius = nullptr;
    Gui::PrefDoubleSpinBox *PickRadius = nullptr;
    Gui::PrefCheckBox *ShowSelectionOnTop = nullptr;
    Gui::PrefCheckBox *ShowPreSelectedFaceOnTop = nullptr;
    Gui::PrefCheckBox *ShowSelectionBoundingBox = nullptr;
    QLabel *labelShowSelectionBoundingBoxThreshold = nullptr;
    Gui::PrefSpinBox *ShowSelectionBoundingBoxThreshold = nullptr;
    Gui::PrefCheckBox *HiddenLineSelectionOnTop = nullptr;
    Gui::PrefCheckBox *SelectElementOnTop = nullptr;
    QLabel *labelSelectionColorDifference = nullptr;
    Gui::PrefDoubleSpinBox *SelectionColorDifference = nullptr;

    // Auto generated code (Tools/params_utils.py:423)
    QGroupBox * groupPreselectionToolTip = nullptr;
    QLabel *labelPreselectionToolTipCorner = nullptr;
    Gui::PrefComboBox *PreselectionToolTipCorner = nullptr;
    QLabel *labelPreselectionToolTipOffsetX = nullptr;
    Gui::PrefSpinBox *PreselectionToolTipOffsetX = nullptr;
    QLabel *labelPreselectionToolTipOffsetY = nullptr;
    Gui::PrefSpinBox *PreselectionToolTipOffsetY = nullptr;
    QLabel *labelPreselectionToolTipFontSize = nullptr;
    Gui::PrefSpinBox *PreselectionToolTipFontSize = nullptr;
// Auto generated code (Tools/params_utils.py:570)
};
} // namespace Dialog
} // namespace Gui
//[[[end]]]
#endif // GUI_DIALOG_DLGSETTINGS_SELECTION_H
