/****************************************************************************
 *   Copyright (c) 2022 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef PART_PARAMS_H
#define PART_PARAMS_H

#include <Mod/Part/PartGlobal.h>

/*[[[cog
import PartGuiParams
PartGuiParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace PartGui {
/** Convenient class to obtain Part/PartDesign visual related parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Part"
 *
 * This class is auto generated by Mod/Part/Gui/PartParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Part/Gui/PartParams.h Mod/Part/Gui/PartParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Part/Gui/PartParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Part/Gui/PartParams.cpp with
 * the following signature.
 * @code
 *     void PartParams:on<parameter_name>Changed()
 * @endcode
 */
class PartGuiExport PartParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NormalsFromUVNodes
    ///
    /// Take the shading normals of a shape from its exact surface instead
    /// of from the display triangles. Gives smoother shading of curved
    /// faces.
    static const bool & getNormalsFromUVNodes();
    static const bool & defaultNormalsFromUVNodes();
    static void removeNormalsFromUVNodes();
    static void setNormalsFromUVNodes(const bool &v);
    static const char *docNormalsFromUVNodes();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TwoSideRendering
    ///
    /// Light new shapes from both sides, so the back of a face looks like
    /// the front. When off the back shows the backlight colour or black.
    static const bool & getTwoSideRendering();
    static const bool & defaultTwoSideRendering();
    static void removeTwoSideRendering();
    static void setTwoSideRendering(const bool &v);
    static const char *docTwoSideRendering();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MinimumDeviation
    ///
    /// Lower limit of the tessellation deviation of shapes, in percent of
    /// the object size. Objects asking for a finer mesh are drawn with
    /// this value instead.
    static const double & getMinimumDeviation();
    static const double & defaultMinimumDeviation();
    static void removeMinimumDeviation();
    static void setMinimumDeviation(const double &v);
    static const char *docMinimumDeviation();
    static void onMinimumDeviationChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshDeviation
    ///
    /// Accuracy of the mesh that shapes are drawn with, as the largest
    /// deviation in percent of the object size. Lower is finer and
    /// slower. Sets the Deviation of new objects; a change is applied to
    /// all open objects.
    static const double & getMeshDeviation();
    static const double & defaultMeshDeviation();
    static void removeMeshDeviation();
    static void setMeshDeviation(const double &v);
    static const char *docMeshDeviation();
    static void onMeshDeviationChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshAngularDeflection
    ///
    /// Largest angle between neighbouring segments of the mesh that
    /// shapes are drawn with, in degrees. Lower is smoother and slower.
    /// Sets the Angular Deflection of new objects; a change is applied to
    /// all open objects.
    static const double & getMeshAngularDeflection();
    static const double & defaultMeshAngularDeflection();
    static void removeMeshAngularDeflection();
    static void setMeshAngularDeflection(const double &v);
    static const char *docMeshAngularDeflection();
    static void onMeshAngularDeflectionChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MinimumAngularDeflection
    ///
    /// Lower limit of the angular deflection used to mesh shapes, in
    /// degrees. Objects asking for a smaller angle are drawn with this
    /// value instead.
    static const double & getMinimumAngularDeflection();
    static const double & defaultMinimumAngularDeflection();
    static void removeMinimumAngularDeflection();
    static void setMinimumAngularDeflection(const double &v);
    static const char *docMinimumAngularDeflection();
    static void onMinimumAngularDeflectionChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OverrideTessellation
    ///
    /// Draw every shape with the deviation and angular deflection set
    /// here, ignoring the values stored in each object. When off a change
    /// of those two settings is written into the open objects instead.
    static const bool & getOverrideTessellation();
    static const bool & defaultOverrideTessellation();
    static void removeOverrideTessellation();
    static void setOverrideTessellation(const bool &v);
    static const char *docOverrideTessellation();
    static void onOverrideTessellationChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MapFaceColor
    ///
    /// Let new shapes take their face colours from the shapes they were
    /// made from. Turn off to give all faces of an object one colour.
    static const bool & getMapFaceColor();
    static const bool & defaultMapFaceColor();
    static void removeMapFaceColor();
    static void setMapFaceColor(const bool &v);
    static const char *docMapFaceColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MapLineColor
    ///
    /// Let new shapes take their edge colours from the shapes they were
    /// made from. Turn off to give all edges of an object one colour.
    static const bool & getMapLineColor();
    static const bool & defaultMapLineColor();
    static void removeMapLineColor();
    static void setMapLineColor(const bool &v);
    static const char *docMapLineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MapPointColor
    ///
    /// Let new shapes take their vertex colours from the shapes they were
    /// made from. Turn off to give all vertices of an object one colour.
    static const bool & getMapPointColor();
    static const bool & defaultMapPointColor();
    static void removeMapPointColor();
    static void setMapPointColor(const bool &v);
    static const char *docMapPointColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MapTransparency
    ///
    /// Let new shapes take the transparency of their faces from the
    /// shapes they were made from. Turn off for one transparency per
    /// object.
    static const bool & getMapTransparency();
    static const bool & defaultMapTransparency();
    static void removeMapTransparency();
    static void setMapTransparency(const bool &v);
    static const char *docMapTransparency();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoGridScale
    ///
    /// Double or halve the grid size of a sketch being edited as the view
    /// is zoomed, so that the grid keeps a similar spacing on screen.
    static const bool & getAutoGridScale();
    static const bool & defaultAutoGridScale();
    static void removeAutoGridScale();
    static void setAutoGridScale(const bool &v);
    static const char *docAutoGridScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewAddColor
    ///
    /// Colour of the preview of a feature that adds material. Its alpha
    /// part sets how transparent the preview is.
    static const unsigned long & getPreviewAddColor();
    static const unsigned long & defaultPreviewAddColor();
    static void removePreviewAddColor();
    static void setPreviewAddColor(const unsigned long &v);
    static const char *docPreviewAddColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewSubColor
    ///
    /// Colour of the preview of a feature that removes material. Its
    /// alpha part sets how transparent the preview is.
    static const unsigned long & getPreviewSubColor();
    static const unsigned long & defaultPreviewSubColor();
    static void removePreviewSubColor();
    static void setPreviewSubColor(const unsigned long &v);
    static const char *docPreviewSubColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewDressColor
    ///
    /// Colour of the preview of a dress-up feature such as a fillet or a
    /// chamfer. Its alpha part sets how transparent the preview is.
    static const unsigned long & getPreviewDressColor();
    static const unsigned long & defaultPreviewDressColor();
    static void removePreviewDressColor();
    static void setPreviewDressColor(const unsigned long &v);
    static const char *docPreviewDressColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewIntersectColor
    ///
    /// Colour of the preview of a feature that keeps what it has in
    /// common with the body. Its alpha part sets how transparent the
    /// preview is.
    static const unsigned long & getPreviewIntersectColor();
    static const unsigned long & defaultPreviewIntersectColor();
    static void removePreviewIntersectColor();
    static void setPreviewIntersectColor(const unsigned long &v);
    static const char *docPreviewIntersectColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewOnEdit
    ///
    /// Show a preview of the result while a PartDesign feature is edited,
    /// and hold back the recompute of the feature until the preview is
    /// turned off or the edit ends.
    static const bool & getPreviewOnEdit();
    static const bool & defaultPreviewOnEdit();
    static void removePreviewOnEdit();
    static void setPreviewOnEdit(const bool &v);
    static const char *docPreviewOnEdit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreviewWithTransparency
    ///
    /// Draw the preview of an edited PartDesign feature transparent. When
    /// off it is drawn opaque.
    static const bool & getPreviewWithTransparency();
    static const bool & defaultPreviewWithTransparency();
    static void removePreviewWithTransparency();
    static void setPreviewWithTransparency(const bool &v);
    static const char *docPreviewWithTransparency();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditOnTop
    ///
    /// Draw the PartDesign feature being edited on top of everything else
    /// in the 3D view.
    static const bool & getEditOnTop();
    static const bool & defaultEditOnTop();
    static void removeEditOnTop();
    static void setEditOnTop(const bool &v);
    static const char *docEditOnTop();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditRecomputeWait
    ///
    /// Delay between a change in a PartDesign task panel and the update
    /// of the feature, in milliseconds. A third of it is used while the
    /// preview is shown.
    static const long & getEditRecomputeWait();
    static const long & defaultEditRecomputeWait();
    static void removeEditRecomputeWait();
    static void setEditRecomputeWait(const long &v);
    static const char *docEditRecomputeWait();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AdjustCameraForNewFeature
    ///
    /// Move the camera to bring a newly created feature into view. Used
    /// by Part offset and thickness, by PartDesign features made from a
    /// selected profile, and by new bodies.
    static const bool & getAdjustCameraForNewFeature();
    static const bool & defaultAdjustCameraForNewFeature();
    static void removeAdjustCameraForNewFeature();
    static void setAdjustCameraForNewFeature(const bool &v);
    static const char *docAdjustCameraForNewFeature();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultDatumColor
    ///
    /// Default face colour of shape binders, of sub-shape binders shown
    /// in binder style, and of PartDesign extrusions. Datum planes, lines
    /// and points take theirs from the PartDesign settings.
    static const unsigned long & getDefaultDatumColor();
    static const unsigned long & defaultDefaultDatumColor();
    static void removeDefaultDatumColor();
    static void setDefaultDatumColor(const unsigned long &v);
    static const char *docDefaultDatumColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultDatumLineColor
    ///
    /// Line and point color of a shape binder, darker than DefaultDatumColor
    /// so that its outline shows against the model (upstream 5dbb4d7c7e)
    static const unsigned long & getDefaultDatumLineColor();
    static const unsigned long & defaultDefaultDatumLineColor();
    static void removeDefaultDatumLineColor();
    static void setDefaultDatumLineColor(const unsigned long &v);
    static const char *docDefaultDatumLineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RespectSystemDPI
    ///
    /// Scale the line width and point size of shapes by the pixel ratio
    /// of the display. May look wrong with monitors of different scaling.
    static const bool & getRespectSystemDPI();
    static const bool & defaultRespectSystemDPI();
    static void removeRespectSystemDPI();
    static void setRespectSystemDPI(const bool &v);
    static const char *docRespectSystemDPI();
    static void onRespectSystemDPIChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShapeInstancing
    ///
    /// Share the tessellation of repeated sub-shapes (same TopoDS_TShape)
    /// inside a compound and render them as GPU instances. Only takes
    /// effect when the renderer supports instanced draws; otherwise the
    /// geometry is flattened as before.
    static const bool & getShapeInstancing();
    static const bool & defaultShapeInstancing();
    static void removeShapeInstancing();
    static void setShapeInstancing(const bool &v);
    static const char *docShapeInstancing();
    static void onShapeInstancingChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectionPickThreshold
    ///
    /// Size of a shape above which picking first narrows the search with
    /// bounding boxes, counted in face, edge or point indices. Smaller
    /// shapes are tested whole. 0 or less always tests everything.
    static const long & getSelectionPickThreshold();
    static const long & defaultSelectionPickThreshold();
    static void removeSelectionPickThreshold();
    static void setSelectionPickThreshold(const long &v);
    static const char *docSelectionPickThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectionPickThreshold2
    ///
    /// Size above which a single face or edge gets a search structure of
    /// its own for picking: the triangles of a face, the points of an
    /// edge. 0 or less turns it off for faces.
    static const long & getSelectionPickThreshold2();
    static const long & defaultSelectionPickThreshold2();
    static void removeSelectionPickThreshold2();
    static void setSelectionPickThreshold2(const long &v);
    static const char *docSelectionPickThreshold2();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SelectionPickRTree
    ///
    /// Pick with a spatial index of a part's triangles instead of testing
    /// every triangle. Much faster on dense parts; the index is built on the
    /// first pick that reaches a part. Parts smaller than
    /// SelectionPickThreshold2 are picked directly.
    static const bool & getSelectionPickRTree();
    static const bool & defaultSelectionPickRTree();
    static void removeSelectionPickRTree();
    static void setSelectionPickRTree(const bool &v);
    static const char *docSelectionPickRTree();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Dimensions3dColor
    ///
    /// Colour of the direct distance of a Part measurement in the 3D view.
    /// The measurements shown follow a change.
    static const unsigned long & getDimensions3dColor();
    static const unsigned long & defaultDimensions3dColor();
    static void removeDimensions3dColor();
    static void setDimensions3dColor(const unsigned long &v);
    static const char *docDimensions3dColor();
    static void onDimensions3dColorChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsDeltaColor
    ///
    /// Colour of the X, Y and Z components of a Part distance measurement
    /// in the 3D view. The measurements shown follow a change.
    static const unsigned long & getDimensionsDeltaColor();
    static const unsigned long & defaultDimensionsDeltaColor();
    static void removeDimensionsDeltaColor();
    static void setDimensionsDeltaColor(const unsigned long &v);
    static const char *docDimensionsDeltaColor();
    static void onDimensionsDeltaColorChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsAngularColor
    ///
    /// Colour of a Part angle measurement in the 3D view. The
    /// measurements shown follow a change.
    static const unsigned long & getDimensionsAngularColor();
    static const unsigned long & defaultDimensionsAngularColor();
    static void removeDimensionsAngularColor();
    static void setDimensionsAngularColor(const unsigned long &v);
    static const char *docDimensionsAngularColor();
    static void onDimensionsAngularColorChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsFontSize
    ///
    /// Size of the text of Part measurements in the 3D view. The
    /// measurements shown follow a change.
    static const long & getDimensionsFontSize();
    static const long & defaultDimensionsFontSize();
    static void removeDimensionsFontSize();
    static void setDimensionsFontSize(const long &v);
    static const char *docDimensionsFontSize();
    static void onDimensionsFontSizeChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsFontName
    ///
    /// Font of the text of Part measurements in the 3D view; defaultFont
    /// is the 3D view's own. The measurements shown follow a change.
    static const std::string & getDimensionsFontName();
    static const std::string & defaultDimensionsFontName();
    static void removeDimensionsFontName();
    static void setDimensionsFontName(const std::string &v);
    static const char *docDimensionsFontName();
    static void onDimensionsFontNameChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsFontStyleBold
    ///
    /// Draw the text of Part measurements in the 3D view in bold.
    static const bool & getDimensionsFontStyleBold();
    static const bool & defaultDimensionsFontStyleBold();
    static void removeDimensionsFontStyleBold();
    static void setDimensionsFontStyleBold(const bool &v);
    static const char *docDimensionsFontStyleBold();
    static void onDimensionsFontStyleBoldChanged();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionsFontStyleItalic
    ///
    /// Draw the text of Part measurements in the 3D view in italic.
    static const bool & getDimensionsFontStyleItalic();
    static const bool & defaultDimensionsFontStyleItalic();
    static void removeDimensionsFontStyleItalic();
    static void setDimensionsFontStyleItalic(const bool &v);
    static const char *docDimensionsFontStyleItalic();
    static void onDimensionsFontStyleItalicChanged();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class PartParams
} // namespace PartGui
//[[[end]]]
#endif // PART_PARAMS_H
