/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef PATH_APP_CAM_PARAMS_H
#define PATH_APP_CAM_PARAMS_H

#include <Mod/CAM/PathGlobal.h>

/*[[[cog
import CAMParams
CAMParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Path {
/** Convenient class to obtain the settings of the CAM workbench that C++ reads

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/CAM"
 *
 * This class is auto generated by Mod/CAM/App/CAMParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/CAM/App/CAMParams.h Mod/CAM/App/CAMParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/CAM/App/CAMParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/CAM/App/CAMParams.cpp with
 * the following signature.
 * @code
 *     void CAMParams:on<parameter_name>Changed()
 * @endcode
 */
class PathExport CAMParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultNormalPathColor
    ///
    /// Colour of the feed moves of a toolpath. Path objects take it when
    /// they are created; the CAM simulator follows a change at once.
    static const unsigned long & getDefaultNormalPathColor();
    static const unsigned long & defaultDefaultNormalPathColor();
    static void removeDefaultNormalPathColor();
    static void setDefaultNormalPathColor(const unsigned long &v);
    static const char *docDefaultNormalPathColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultRapidPathColor
    ///
    /// Colour of the rapid moves of a toolpath. Paths in the 3D view pick
    /// it up the next time their colours are rebuilt; the CAM simulator
    /// follows a change at once.
    static const unsigned long & getDefaultRapidPathColor();
    static const unsigned long & defaultDefaultRapidPathColor();
    static void removeDefaultRapidPathColor();
    static void setDefaultRapidPathColor(const unsigned long &v);
    static const char *docDefaultRapidPathColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultProbePathColor
    ///
    /// Colour of the probe moves of a toolpath. Paths in the 3D view pick
    /// it up the next time their colours are rebuilt.
    static const unsigned long & getDefaultProbePathColor();
    static const unsigned long & defaultDefaultProbePathColor();
    static void removeDefaultProbePathColor();
    static void setDefaultProbePathColor(const unsigned long &v);
    static const char *docDefaultProbePathColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultPathMarkerColor
    ///
    /// Colour of the node markers of a toolpath. Applies to path objects
    /// created afterwards.
    static const unsigned long & getDefaultPathMarkerColor();
    static const unsigned long & defaultDefaultPathMarkerColor();
    static void removeDefaultPathMarkerColor();
    static void setDefaultPathMarkerColor(const unsigned long &v);
    static const char *docDefaultPathMarkerColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultPathLineWidth
    ///
    /// Line width in pixels of a toolpath in the 3D view. Applies to path
    /// objects created afterwards.
    static const long & getDefaultPathLineWidth();
    static const long & defaultDefaultPathLineWidth();
    static void removeDefaultPathLineWidth();
    static void setDefaultPathLineWidth(const long &v);
    static const char *docDefaultPathLineWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultArrowScale
    ///
    /// Size factor of the direction arrow drawn on a toolpath. Applies to
    /// path objects created afterwards.
    static const double & getDefaultArrowScale();
    static const double & defaultDefaultArrowScale();
    static void removeDefaultArrowScale();
    static void setDefaultArrowScale(const double &v);
    static const char *docDefaultArrowScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultSelectionStyle
    ///
    /// How a toolpath is selected in the 3D view: 0 by its shape, 1 by
    /// its bounding box, 2 not at all. Applies to path objects created
    /// afterwards.
    static const long & getDefaultSelectionStyle();
    static const long & defaultDefaultSelectionStyle();
    static void removeDefaultSelectionStyle();
    static void setDefaultSelectionStyle(const long &v);
    static const char *docDefaultSelectionStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultBBoxNormalColor
    ///
    /// Colour of the bounding box of a toolpath that is selected by shape
    /// or cannot be selected. Takes effect the next time the bounding box
    /// is drawn.
    static const unsigned long & getDefaultBBoxNormalColor();
    static const unsigned long & defaultDefaultBBoxNormalColor();
    static void removeDefaultBBoxNormalColor();
    static void setDefaultBBoxNormalColor(const unsigned long &v);
    static const char *docDefaultBBoxNormalColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultBBoxSelectionColor
    ///
    /// Colour of the bounding box of a toolpath that is selected by its
    /// bounding box. Takes effect the next time the bounding box is
    /// drawn.
    static const unsigned long & getDefaultBBoxSelectionColor();
    static const unsigned long & defaultDefaultBBoxSelectionColor();
    static void removeDefaultBBoxSelectionColor();
    static void setDefaultBBoxSelectionColor(const unsigned long &v);
    static const char *docDefaultBBoxSelectionColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideFirstRapid
    ///
    /// Hides the initial rapid move of a toolpath by starting the display
    /// at the first feed move. Takes effect the next time the path
    /// changes.
    static const bool & getHideFirstRapid();
    static const bool & defaultHideFirstRapid();
    static void removeHideFirstRapid();
    static void setHideFirstRapid(const bool &v);
    static const char *docHideFirstRapid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WarningSuppressAllSpeeds
    ///
    /// Suppresses the warning that a tool controller has no feed rate
    /// when the cycle time of a toolpath is estimated. Takes effect at
    /// the next estimate.
    static const bool & getWarningSuppressAllSpeeds();
    static const bool & defaultWarningSuppressAllSpeeds();
    static void removeWarningSuppressAllSpeeds();
    static void setWarningSuppressAllSpeeds(const bool &v);
    static const char *docWarningSuppressAllSpeeds();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SimulatorShowInDocumentView
    ///
    /// Shows the simulated stock in the 3D view of the document while the
    /// CAM simulator runs. The button in the simulator follows a change
    /// at once; the view is attached at the next simulation.
    static const bool & getSimulatorShowInDocumentView();
    static const bool & defaultSimulatorShowInDocumentView();
    static void removeSimulatorShowInDocumentView();
    static void setSimulatorShowInDocumentView(const bool &v);
    static const char *docSimulatorShowInDocumentView();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ForceLegacyGLRender
    ///
    /// Makes the CAM simulator draw with its legacy OpenGL renderer
    /// instead of the render backend. Takes effect the next time the
    /// simulator is opened.
    static const bool & getForceLegacyGLRender();
    static const bool & defaultForceLegacyGLRender();
    static void removeForceLegacyGLRender();
    static void setForceLegacyGLRender(const bool &v);
    static const char *docForceLegacyGLRender();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class CAMParams
} // namespace Path
//[[[end]]]

#endif // PATH_APP_CAM_PARAMS_H
