/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef TECHDRAW_APP_PARAMS_H
#define TECHDRAW_APP_PARAMS_H

#include <Mod/TechDraw/TechDrawGlobal.h>

/*[[[cog
import TechDrawParams
TechDrawParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace TechDraw {
/** Convenient class to obtain the settings of TechDraw

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/TechDraw"
 *
 * This class is auto generated by Mod/TechDraw/App/TechDrawParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/TechDraw/App/TechDrawParams.h Mod/TechDraw/App/TechDrawParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/TechDraw/App/TechDrawParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/TechDraw/App/TechDrawParams.cpp with
 * the following signature.
 * @code
 *     void TechDrawParams:on<parameter_name>Changed()
 * @endcode
 */
class TechDrawExport TechDrawParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AllowPageOverride
    ///
    /// When updating of drawings is switched off globally, let a page
    /// whose Keep Updated property is on update anyway. Read each time a
    /// page decides whether to update.
    static const bool & getAllowPageOverride();
    static const bool & defaultAllowPageOverride();
    static void removeAllowPageOverride();
    static void setAllowPageOverride(const bool &v);
    static const char *docAllowPageOverride();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoDist
    ///
    /// New projection groups position their secondary views
    /// automatically. Applies to groups created afterwards; each group
    /// has its own AutoDistribute property.
    static const bool & getAutoDist();
    static const bool & defaultAutoDist();
    static void removeAutoDist();
    static void setAutoDist(const bool &v);
    static const char *docAutoDist();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultScale
    ///
    /// Scale of a new drawing page. Applies to pages created afterwards.
    static const double & getDefaultScale();
    static const double & defaultDefaultScale();
    static void removeDefaultScale();
    static void setDefaultScale(const double &v);
    static const char *docDefaultScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultScaleType
    ///
    /// Scale type of a new view: 0 Page (follow the page scale), 1
    /// Automatic (fit the page), 2 Custom. Applies to views created
    /// afterwards.
    static const long & getDefaultScaleType();
    static const long & defaultDefaultScaleType();
    static void removeDefaultScaleType();
    static void setDefaultScaleType(const long &v);
    static const char *docDefaultScaleType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultViewScale
    ///
    /// Scale of a new view whose scale type is Custom. Applies to views
    /// created afterwards.
    static const double & getDefaultViewScale();
    static const double & defaultDefaultViewScale();
    static void removeDefaultViewScale();
    static void setDefaultViewScale(const double &v);
    static const char *docDefaultViewScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DrawFaceEdges
    ///
    /// Draw the outline of each detected face in addition to its fill.
    /// Takes effect when a view is redrawn.
    static const bool & getDrawFaceEdges();
    static const bool & defaultDrawFaceEdges();
    static void removeDrawFaceEdges();
    static void setDrawFaceEdges(const bool &v);
    static const char *docDrawFaceEdges();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgeFuzz
    ///
    /// Size of the area around an edge in which a click selects it.
    /// Larger makes edges easier to pick but may catch a neighbouring
    /// edge. the unit.
    static const double & getEdgeFuzz();
    static const double & defaultEdgeFuzz();
    static void removeEdgeFuzz();
    static void setEdgeFuzz(const double &v);
    static const char *docEdgeFuzz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FixColorAlphaOnLoad
    ///
    /// When opening a document, read colours stored with zero opacity as
    /// opaque; older files saved an unused transparency of 0. Applies to
    /// documents opened afterwards.
    static const bool & getFixColorAlphaOnLoad();
    static const bool & defaultFixColorAlphaOnLoad();
    static void removeFixColorAlphaOnLoad();
    static void setFixColorAlphaOnLoad(const bool &v);
    static const char *docFixColorAlphaOnLoad();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FocusDistance
    ///
    /// Focus distance of a new perspective view. Applies to views created
    /// afterwards.
    static const double & getFocusDistance();
    static const double & defaultFocusDistance();
    static void removeFocusDistance();
    static void setFocusDistance(const double &v);
    static const char *docFocusDistance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GlobalUpdateDrawings
    ///
    /// Keep all drawing pages in step with the 3D model. Off stops pages
    /// updating unless page override is allowed. Read each time a page
    /// decides whether to update.
    static const bool & getGlobalUpdateDrawings();
    static const bool & defaultGlobalUpdateDrawings();
    static void removeGlobalUpdateDrawings();
    static void setGlobalUpdateDrawings(const bool &v);
    static const char *docGlobalUpdateDrawings();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HandleFaces
    ///
    /// Find the faces of each view, needed for hatching and face colours.
    /// Off is faster. Takes effect when a view is recomputed.
    static const bool & getHandleFaces();
    static const bool & defaultHandleFaces();
    static void removeHandleFaces();
    static void setHandleFaces(const bool &v);
    static const char *docHandleFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KbPan
    ///
    /// Direction of horizontal movement of a drawing page with the arrow
    /// keys: 1 normal, -1 reversed (used as a multiplier). Read when a
    /// page view is opened.
    static const long & getKbPan();
    static const long & defaultKbPan();
    static void removeKbPan();
    static void setKbPan(const long &v);
    static const char *docKbPan();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KbScroll
    ///
    /// Direction of vertical movement of a drawing page with the arrow
    /// keys: 1 normal, -1 reversed. Read when a page view is opened.
    static const long & getKbScroll();
    static const long & defaultKbScroll();
    static void removeKbScroll();
    static void setKbScroll(const long &v);
    static const char *docKbScroll();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KeepPagesUpToDate
    ///
    /// New pages keep themselves in step with the model. Applies to pages
    /// created afterwards; each page has its own Keep Updated property.
    static const bool & getKeepPagesUpToDate();
    static const bool & defaultKeepPagesUpToDate();
    static void removeKeepPagesUpToDate();
    static void setKeepPagesUpToDate(const bool &v);
    static const char *docKeepPagesUpToDate();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MarkFuzz
    ///
    /// Size of the selection area around a centre mark. Larger makes
    /// marks easier to pick.
    static const double & getMarkFuzz();
    static const double & defaultMarkFuzz();
    static void removeMarkFuzz();
    static void setMarkFuzz(const double &v);
    static const char *docMarkFuzz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NewFaceFinder
    ///
    /// Use the newer algorithm to find the faces of a view. Takes effect
    /// when a view is recomputed.
    static const bool & getNewFaceFinder();
    static const bool & defaultNewFaceFinder();
    static void removeNewFaceFinder();
    static void setNewFaceFinder(const bool &v);
    static const char *docNewFaceFinder();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVg
    ///
    /// Draw drawing pages with the rendering backend instead of the Qt
    /// scene items. Applies at once to open pages.
    static const bool & getPageRendererVg();
    static const bool & defaultPageRendererVg();
    static void removePageRendererVg();
    static void setPageRendererVg(const bool &v);
    static const char *docPageRendererVg();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVgComposite
    ///
    /// With the backend page renderer, compose its picture on the
    /// graphics card instead of reading it back as an image. Applies at
    /// once.
    static const bool & getPageRendererVgComposite();
    static const bool & defaultPageRendererVgComposite();
    static void removePageRendererVgComposite();
    static void setPageRendererVgComposite(const bool &v);
    static const char *docPageRendererVgComposite();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVgVerify
    ///
    /// Also paint the Qt scene items over the backend's picture of the
    /// page, so that differences between the two show. Applies at once.
    static const bool & getPageRendererVgVerify();
    static const bool & defaultPageRendererVgVerify();
    static void removePageRendererVgVerify();
    static void setPageRendererVgVerify(const bool &v);
    static const char *docPageRendererVgVerify();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProjectionAngle
    ///
    /// Projection convention of new pages and projection groups: 0 first
    /// angle, 1 third angle. The third choice on the page, Page,
    /// currently reads as first angle.
    static const long & getProjectionAngle();
    static const long & defaultProjectionAngle();
    static void removeProjectionAngle();
    static void setProjectionAngle(const long &v);
    static const char *docProjectionAngle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter restoreCosmetic
    ///
    /// Read cosmetic vertices, edges and centre lines when a document is
    /// opened. Off skips them, to open a file whose cosmetic data is
    /// damaged.
    static const bool & getrestoreCosmetic();
    static const bool & defaultrestoreCosmetic();
    static void removerestoreCosmetic();
    static void setrestoreCosmetic(const bool &v);
    static const char *docrestoreCosmetic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ScrubCount
    ///
    /// Number of extra clean-up passes over the edges produced by hidden
    /// line removal in a new view. Applies to views created afterwards.
    static const long & getScrubCount();
    static const long & defaultScrubCount();
    static void removeScrubCount();
    static void setScrubCount(const long &v);
    static const char *docScrubCount();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionFuseFirst
    ///
    /// New section views fuse the source shapes into one before cutting.
    /// Slower, but needed for some overlapping shapes. Applies to
    /// sections created afterwards.
    static const bool & getSectionFuseFirst();
    static const bool & defaultSectionFuseFirst();
    static void removeSectionFuseFirst();
    static void setSectionFuseFirst(const bool &v);
    static const char *docSectionFuseFirst();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionUsePreviousCut
    ///
    /// A new section whose base view is itself a section cuts the already
    /// cut shape instead of the original. Applies to sections created
    /// afterwards.
    static const bool & getSectionUsePreviousCut();
    static const bool & defaultSectionUsePreviousCut();
    static void removeSectionUsePreviousCut();
    static void setSectionUsePreviousCut(const bool &v);
    static const char *docSectionUsePreviousCut();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShadedUnderlayBackend
    ///
    /// Render the shaded picture under a view with the rendering backend;
    /// off falls back to capturing it from the 3D view.
    static const bool & getShadedUnderlayBackend();
    static const bool & defaultShadedUnderlayBackend();
    static void removeShadedUnderlayBackend();
    static void setShadedUnderlayBackend(const bool &v);
    static const char *docShadedUnderlayBackend();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShadedUnderlayMaxFaces
    ///
    /// Largest number of faces of a shape for which the shaded underlay
    /// works out a colour per face; above it the shape gets one colour.
    static const long & getShadedUnderlayMaxFaces();
    static const long & defaultShadedUnderlayMaxFaces();
    static void removeShadedUnderlayMaxFaces();
    static void setShadedUnderlayMaxFaces(const long &v);
    static const char *docShadedUnderlayMaxFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDetailHighlight
    ///
    /// New detail views show the highlight outline in their source view.
    /// Applies to detail views created afterwards.
    static const bool & getShowDetailHighlight();
    static const bool & defaultShowDetailHighlight();
    static void removeShowDetailHighlight();
    static void setShowDetailHighlight(const bool &v);
    static const char *docShowDetailHighlight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDetailMatting
    ///
    /// New detail views show the matting, the frame around the detail.
    /// Applies to detail views created afterwards.
    static const bool & getShowDetailMatting();
    static const bool & defaultShowDetailMatting();
    static void removeShowDetailMatting();
    static void setShowDetailMatting(const bool &v);
    static const char *docShowDetailMatting();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSectionEdges
    ///
    /// Draw the edges of the cut surface in section views. Takes effect
    /// when a section is redrawn.
    static const bool & getShowSectionEdges();
    static const bool & defaultShowSectionEdges();
    static void removeShowSectionEdges();
    static void setShowSectionEdges(const bool &v);
    static const char *docShowSectionEdges();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StoreProjectedGeometry
    ///
    /// Keep each view's projected geometry in the document so that
    /// reopening it does not project again. Off makes pages rebuild when
    /// opened and keeps files smaller.
    static const bool & getStoreProjectedGeometry();
    static const bool & defaultStoreProjectedGeometry();
    static void removeStoreProjectedGeometry();
    static void setStoreProjectedGeometry(const bool &v);
    static const char *docStoreProjectedGeometry();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TemplateDotSize
    ///
    /// Size in mm of the click boxes that mark the editable texts of a
    /// page template. Takes effect when a template is loaded again.
    static const double & getTemplateDotSize();
    static const double & defaultTemplateDotSize();
    static void removeTemplateDotSize();
    static void setTemplateDotSize(const double &v);
    static const char *docTemplateDotSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VertexScale
    ///
    /// Size of vertex dots as a multiple of the visible line width.
    /// Applies to views and cosmetic vertices created afterwards.
    static const double & getVertexScale();
    static const double & defaultVertexScale();
    static void removeVertexScale();
    static void setVertexScale(const double &v);
    static const char *docVertexScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter gridSpacing
    ///
    /// Spacing in mm of the grid on a new drawing page. Applies to pages
    /// created afterwards; each page has its own Grid Spacing property.
    static const double & getgridSpacing();
    static const double & defaultgridSpacing();
    static void removegridSpacing();
    static void setgridSpacing(const double &v);
    static const char *docgridSpacing();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter multiSelection
    ///
    /// Clicking adds to the selection without holding Ctrl. Applies at
    /// once.
    static const bool & getmultiSelection();
    static const bool & defaultmultiSelection();
    static void removemultiSelection();
    static void setmultiSelection(const bool &v);
    static const char *docmultiSelection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter showGrid
    ///
    /// New drawing pages show a grid. Applies to pages created
    /// afterwards; each page has its own Show Grid property.
    static const bool & getshowGrid();
    static const bool & defaultshowGrid();
    static void removeshowGrid();
    static void setshowGrid(const bool &v);
    static const char *docshowGrid();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class TechDrawParams
} // namespace TechDraw
//[[[end]]]

#endif // TECHDRAW_APP_PARAMS_H
