/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef TECHDRAW_APP_PARAMS_H
#define TECHDRAW_APP_PARAMS_H

#include <Mod/TechDraw/TechDrawGlobal.h>

/*[[[cog
import TechDrawParams
TechDrawParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace TechDraw {
/** Convenient class to obtain the settings of TechDraw

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/TechDraw"
 *
 * This class is auto generated by Mod/TechDraw/App/TechDrawParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/TechDraw/App/TechDrawParams.h Mod/TechDraw/App/TechDrawParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/TechDraw/App/TechDrawParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/TechDraw/App/TechDrawParams.cpp with
 * the following signature.
 * @code
 *     void TechDrawParams:on<parameter_name>Changed()
 * @endcode
 */
class TechDrawExport TechDrawParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AllowPageOverride
    ///
    /// When updating of drawings is switched off globally, let a page
    /// whose Keep Updated property is on update anyway. Read each time a
    /// page decides whether to update.
    static const bool & getAllowPageOverride();
    static const bool & defaultAllowPageOverride();
    static void removeAllowPageOverride();
    static void setAllowPageOverride(const bool &v);
    static const char *docAllowPageOverride();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoDist
    ///
    /// New projection groups position their secondary views
    /// automatically. Applies to groups created afterwards; each group
    /// has its own AutoDistribute property.
    static const bool & getAutoDist();
    static const bool & defaultAutoDist();
    static void removeAutoDist();
    static void setAutoDist(const bool &v);
    static const char *docAutoDist();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultScale
    ///
    /// Scale of a new drawing page. Applies to pages created afterwards.
    static const double & getDefaultScale();
    static const double & defaultDefaultScale();
    static void removeDefaultScale();
    static void setDefaultScale(const double &v);
    static const char *docDefaultScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultScaleType
    ///
    /// Scale type of a new view: 0 Page (follow the page scale), 1
    /// Automatic (fit the page), 2 Custom. Applies to views created
    /// afterwards.
    static const long & getDefaultScaleType();
    static const long & defaultDefaultScaleType();
    static void removeDefaultScaleType();
    static void setDefaultScaleType(const long &v);
    static const char *docDefaultScaleType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultViewScale
    ///
    /// Scale of a new view whose scale type is Custom. Applies to views
    /// created afterwards.
    static const double & getDefaultViewScale();
    static const double & defaultDefaultViewScale();
    static void removeDefaultViewScale();
    static void setDefaultViewScale(const double &v);
    static const char *docDefaultViewScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DrawFaceEdges
    ///
    /// Draw the outline of each detected face in addition to its fill.
    /// Takes effect when a view is redrawn.
    static const bool & getDrawFaceEdges();
    static const bool & defaultDrawFaceEdges();
    static void removeDrawFaceEdges();
    static void setDrawFaceEdges(const bool &v);
    static const char *docDrawFaceEdges();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgeFuzz
    ///
    /// Size of the area around an edge in which a click selects it.
    /// Larger makes edges easier to pick but may catch a neighbouring
    /// edge. the unit.
    static const double & getEdgeFuzz();
    static const double & defaultEdgeFuzz();
    static void removeEdgeFuzz();
    static void setEdgeFuzz(const double &v);
    static const char *docEdgeFuzz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FixColorAlphaOnLoad
    ///
    /// When opening a document, read colours stored with zero opacity as
    /// opaque; older files saved an unused transparency of 0. Applies to
    /// documents opened afterwards.
    static const bool & getFixColorAlphaOnLoad();
    static const bool & defaultFixColorAlphaOnLoad();
    static void removeFixColorAlphaOnLoad();
    static void setFixColorAlphaOnLoad(const bool &v);
    static const char *docFixColorAlphaOnLoad();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FocusDistance
    ///
    /// Focus distance of a new perspective view. Applies to views created
    /// afterwards.
    static const double & getFocusDistance();
    static const double & defaultFocusDistance();
    static void removeFocusDistance();
    static void setFocusDistance(const double &v);
    static const char *docFocusDistance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GlobalUpdateDrawings
    ///
    /// Keep all drawing pages in step with the 3D model. Off stops pages
    /// updating unless page override is allowed. Read each time a page
    /// decides whether to update.
    static const bool & getGlobalUpdateDrawings();
    static const bool & defaultGlobalUpdateDrawings();
    static void removeGlobalUpdateDrawings();
    static void setGlobalUpdateDrawings(const bool &v);
    static const char *docGlobalUpdateDrawings();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HandleFaces
    ///
    /// Find the faces of each view, needed for hatching and face colours.
    /// Off is faster. Takes effect when a view is recomputed.
    static const bool & getHandleFaces();
    static const bool & defaultHandleFaces();
    static void removeHandleFaces();
    static void setHandleFaces(const bool &v);
    static const char *docHandleFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KbPan
    ///
    /// Direction of horizontal movement of a drawing page with the arrow
    /// keys: 1 normal, -1 reversed (used as a multiplier). Read when a
    /// page view is opened.
    static const long & getKbPan();
    static const long & defaultKbPan();
    static void removeKbPan();
    static void setKbPan(const long &v);
    static const char *docKbPan();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KbScroll
    ///
    /// Direction of vertical movement of a drawing page with the arrow
    /// keys: 1 normal, -1 reversed. Read when a page view is opened.
    static const long & getKbScroll();
    static const long & defaultKbScroll();
    static void removeKbScroll();
    static void setKbScroll(const long &v);
    static const char *docKbScroll();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter KeepPagesUpToDate
    ///
    /// New pages keep themselves in step with the model. Applies to pages
    /// created afterwards; each page has its own Keep Updated property.
    static const bool & getKeepPagesUpToDate();
    static const bool & defaultKeepPagesUpToDate();
    static void removeKeepPagesUpToDate();
    static void setKeepPagesUpToDate(const bool &v);
    static const char *docKeepPagesUpToDate();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MarkFuzz
    ///
    /// Size of the selection area around a centre mark. Larger makes
    /// marks easier to pick.
    static const double & getMarkFuzz();
    static const double & defaultMarkFuzz();
    static void removeMarkFuzz();
    static void setMarkFuzz(const double &v);
    static const char *docMarkFuzz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NewFaceFinder
    ///
    /// Use the newer algorithm to find the faces of a view. Takes effect
    /// when a view is recomputed.
    static const bool & getNewFaceFinder();
    static const bool & defaultNewFaceFinder();
    static void removeNewFaceFinder();
    static void setNewFaceFinder(const bool &v);
    static const char *docNewFaceFinder();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVg
    ///
    /// Draw drawing pages with the rendering backend instead of the Qt
    /// scene items. Applies at once to open pages.
    static const bool & getPageRendererVg();
    static const bool & defaultPageRendererVg();
    static void removePageRendererVg();
    static void setPageRendererVg(const bool &v);
    static const char *docPageRendererVg();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVgComposite
    ///
    /// With the backend page renderer, compose its picture on the
    /// graphics card instead of reading it back as an image. Applies at
    /// once.
    static const bool & getPageRendererVgComposite();
    static const bool & defaultPageRendererVgComposite();
    static void removePageRendererVgComposite();
    static void setPageRendererVgComposite(const bool &v);
    static const char *docPageRendererVgComposite();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageRendererVgVerify
    ///
    /// Also paint the Qt scene items over the backend's picture of the
    /// page, so that differences between the two show. Applies at once.
    static const bool & getPageRendererVgVerify();
    static const bool & defaultPageRendererVgVerify();
    static void removePageRendererVgVerify();
    static void setPageRendererVgVerify(const bool &v);
    static const char *docPageRendererVgVerify();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ProjectionAngle
    ///
    /// Projection convention of new pages and projection groups: 0 first
    /// angle, 1 third angle. The third choice on the page, Page,
    /// currently reads as first angle.
    static const long & getProjectionAngle();
    static const long & defaultProjectionAngle();
    static void removeProjectionAngle();
    static void setProjectionAngle(const long &v);
    static const char *docProjectionAngle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter restoreCosmetic
    ///
    /// Read cosmetic vertices, edges and centre lines when a document is
    /// opened. Off skips them, to open a file whose cosmetic data is
    /// damaged.
    static const bool & getrestoreCosmetic();
    static const bool & defaultrestoreCosmetic();
    static void removerestoreCosmetic();
    static void setrestoreCosmetic(const bool &v);
    static const char *docrestoreCosmetic();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ScrubCount
    ///
    /// Number of extra clean-up passes over the edges produced by hidden
    /// line removal in a new view. Applies to views created afterwards.
    static const long & getScrubCount();
    static const long & defaultScrubCount();
    static void removeScrubCount();
    static void setScrubCount(const long &v);
    static const char *docScrubCount();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionFuseFirst
    ///
    /// New section views fuse the source shapes into one before cutting.
    /// Slower, but needed for some overlapping shapes. Applies to
    /// sections created afterwards.
    static const bool & getSectionFuseFirst();
    static const bool & defaultSectionFuseFirst();
    static void removeSectionFuseFirst();
    static void setSectionFuseFirst(const bool &v);
    static const char *docSectionFuseFirst();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionUsePreviousCut
    ///
    /// A new section whose base view is itself a section cuts the already
    /// cut shape instead of the original. Applies to sections created
    /// afterwards.
    static const bool & getSectionUsePreviousCut();
    static const bool & defaultSectionUsePreviousCut();
    static void removeSectionUsePreviousCut();
    static void setSectionUsePreviousCut(const bool &v);
    static const char *docSectionUsePreviousCut();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShadedUnderlayBackend
    ///
    /// Render the shaded picture under a view with the rendering backend;
    /// off falls back to capturing it from the 3D view.
    static const bool & getShadedUnderlayBackend();
    static const bool & defaultShadedUnderlayBackend();
    static void removeShadedUnderlayBackend();
    static void setShadedUnderlayBackend(const bool &v);
    static const char *docShadedUnderlayBackend();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShadedUnderlayMaxFaces
    ///
    /// Largest number of faces of a shape for which the shaded underlay
    /// works out a colour per face; above it the shape gets one colour.
    static const long & getShadedUnderlayMaxFaces();
    static const long & defaultShadedUnderlayMaxFaces();
    static void removeShadedUnderlayMaxFaces();
    static void setShadedUnderlayMaxFaces(const long &v);
    static const char *docShadedUnderlayMaxFaces();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDetailHighlight
    ///
    /// New detail views show the highlight outline in their source view.
    /// Applies to detail views created afterwards.
    static const bool & getShowDetailHighlight();
    static const bool & defaultShowDetailHighlight();
    static void removeShowDetailHighlight();
    static void setShowDetailHighlight(const bool &v);
    static const char *docShowDetailHighlight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDetailMatting
    ///
    /// New detail views show the matting, the frame around the detail.
    /// Applies to detail views created afterwards.
    static const bool & getShowDetailMatting();
    static const bool & defaultShowDetailMatting();
    static void removeShowDetailMatting();
    static void setShowDetailMatting(const bool &v);
    static const char *docShowDetailMatting();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSectionEdges
    ///
    /// Draw the edges of the cut surface in section views. Takes effect
    /// when a section is redrawn.
    static const bool & getShowSectionEdges();
    static const bool & defaultShowSectionEdges();
    static void removeShowSectionEdges();
    static void setShowSectionEdges(const bool &v);
    static const char *docShowSectionEdges();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StoreProjectedGeometry
    ///
    /// Keep each view's projected geometry in the document so that
    /// reopening it does not project again. Off makes pages rebuild when
    /// opened and keeps files smaller.
    static const bool & getStoreProjectedGeometry();
    static const bool & defaultStoreProjectedGeometry();
    static void removeStoreProjectedGeometry();
    static void setStoreProjectedGeometry(const bool &v);
    static const char *docStoreProjectedGeometry();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TemplateDotSize
    ///
    /// Size in mm of the click boxes that mark the editable texts of a
    /// page template. Takes effect when a template is loaded again.
    static const double & getTemplateDotSize();
    static const double & defaultTemplateDotSize();
    static void removeTemplateDotSize();
    static void setTemplateDotSize(const double &v);
    static const char *docTemplateDotSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VertexScale
    ///
    /// Size of vertex dots as a multiple of the visible line width.
    /// Applies to views and cosmetic vertices created afterwards.
    static const double & getVertexScale();
    static const double & defaultVertexScale();
    static void removeVertexScale();
    static void setVertexScale(const double &v);
    static const char *docVertexScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter gridSpacing
    ///
    /// Spacing in mm of the grid on a new drawing page. Applies to pages
    /// created afterwards; each page has its own Grid Spacing property.
    static const double & getgridSpacing();
    static const double & defaultgridSpacing();
    static void removegridSpacing();
    static void setgridSpacing(const double &v);
    static const char *docgridSpacing();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter multiSelection
    ///
    /// Clicking adds to the selection without holding Ctrl. Applies at
    /// once.
    static const bool & getmultiSelection();
    static const bool & defaultmultiSelection();
    static void removemultiSelection();
    static void setmultiSelection(const bool &v);
    static const char *docmultiSelection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter showGrid
    ///
    /// New drawing pages show a grid. Applies to pages created
    /// afterwards; each page has its own Show Grid property.
    static const bool & getshowGrid();
    static const bool & defaultshowGrid();
    static void removeshowGrid();
    static void setshowGrid(const bool &v);
    static const char *docshowGrid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BalloonArrow
    ///
    /// Arrowhead at the end of a new balloon's leader line, as an index
    /// into the list of arrow styles. Applies to balloons created
    /// afterwards.
    static const long & getBalloonArrow();
    static const long & defaultBalloonArrow();
    static void removeBalloonArrow();
    static void setBalloonArrow(const long &v);
    static const char *docBalloonArrow();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BalloonShape
    ///
    /// Shape of a new balloon: 0 circular, 1 none, 2 triangle, 3
    /// inspection, 4 hexagon, 5 square, 6 rectangle, 7 line. Applies to
    /// balloons created afterwards.
    static const long & getBalloonShape();
    static const long & defaultBalloonShape();
    static void removeBalloonShape();
    static void setBalloonShape(const long &v);
    static const char *docBalloonShape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CenterMarkScale
    ///
    /// Size of the centre marks of arcs and circles in a new view, as a
    /// factor. Applies to views created afterwards.
    static const double & getCenterMarkScale();
    static const double & defaultCenterMarkScale();
    static void removeCenterMarkScale();
    static void setCenterMarkScale(const double &v);
    static const char *docCenterMarkScale();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CosmoCLExtend
    ///
    /// Distance in mm by which a new cosmetic centre line extends beyond
    /// the geometry it is drawn on.
    static const double & getCosmoCLExtend();
    static const double & defaultCosmoCLExtend();
    static void removeCosmoCLExtend();
    static void setCosmoCLExtend(const double &v);
    static const char *docCosmoCLExtend();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CutSurfaceDisplay
    ///
    /// How a new section shows its cut surface: 0 hidden, 1 solid colour,
    /// 2 SVG hatch, 3 PAT hatch. Applies to sections created afterwards.
    static const long & getCutSurfaceDisplay();
    static const long & defaultCutSurfaceDisplay();
    static void removeCutSurfaceDisplay();
    static void setCutSurfaceDisplay(const long &v);
    static const char *docCutSurfaceDisplay();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MattingStyle
    ///
    /// Outline of detail views and of their highlight in the source view:
    /// 0 circle, 1 square. Takes effect when detail views are recomputed.
    static const long & getMattingStyle();
    static const long & defaultMattingStyle();
    static void removeMattingStyle();
    static void setMattingStyle(const long &v);
    static const char *docMattingStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxSVGTile
    ///
    /// Largest number of SVG tiles used to hatch one face. 1 to 1000000.
    /// A limit that keeps a very fine hatch from freezing the program.
    static const long & getMaxSVGTile();
    static const long & defaultMaxSVGTile();
    static void removeMaxSVGTile();
    static void setMaxSVGTile(const long &v);
    static const char *docMaxSVGTile();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PrintCenterMarks
    ///
    /// Include centre marks when a page is printed or exported. Takes
    /// effect at the next print or redraw.
    static const bool & getPrintCenterMarks();
    static const bool & defaultPrintCenterMarks();
    static void removePrintCenterMarks();
    static void setPrintCenterMarks(const bool &v);
    static const char *docPrintCenterMarks();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyramidOrtho
    ///
    /// Keep a filled-triangle balloon end symbol upright instead of
    /// turning it with the leader line. Takes effect when balloons are
    /// redrawn.
    static const bool & getPyramidOrtho();
    static const bool & defaultPyramidOrtho();
    static void removePyramidOrtho();
    static void setPyramidOrtho(const bool &v);
    static const char *docPyramidOrtho();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionLineMarks
    ///
    /// New views show marks where the section line of a complex section
    /// changes direction. Applies to views created afterwards.
    static const bool & getSectionLineMarks();
    static const bool & defaultSectionLineMarks();
    static void removeSectionLineMarks();
    static void setSectionLineMarks(const bool &v);
    static const char *docSectionLineMarks();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowCenterMarks
    ///
    /// New views show centre marks on arcs and circles. Applies to views
    /// created afterwards.
    static const bool & getShowCenterMarks();
    static const bool & defaultShowCenterMarks();
    static void removeShowCenterMarks();
    static void setShowCenterMarks(const bool &v);
    static const char *docShowCenterMarks();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SvgOverlapFactor
    ///
    /// How far the tiled SVG hatch reaches beyond the face it fills, as a
    /// factor of the face size. Raise it if a hatch leaves gaps at the
    /// edge of a face.
    static const double & getSvgOverlapFactor();
    static const double & defaultSvgOverlapFactor();
    static void removeSvgOverlapFactor();
    static void setSvgOverlapFactor(const double &v);
    static const char *docSvgOverlapFactor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SymbolFactor
    ///
    /// Size factor for welding symbols. Takes effect when welding symbols
    /// are redrawn.
    static const double & getSymbolFactor();
    static const double & defaultSymbolFactor();
    static void removeSymbolFactor();
    static void setSymbolFactor(const double &v);
    static const char *docSymbolFactor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AltDecimals
    ///
    /// Number of decimals in dimension values when Use Global Decimals is
    /// off. Takes effect when dimensions are recomputed.
    static const long & getAltDecimals();
    static const long & defaultAltDecimals();
    static void removeAltDecimals();
    static void setAltDecimals(const long &v);
    static const char *docAltDecimals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArrowStyle
    ///
    /// Arrowhead style for dimensions, as an index into the list of arrow
    /// styles. Takes effect when dimensions are redrawn.
    static const long & getArrowStyle();
    static const long & defaultArrowStyle();
    static void removeArrowStyle();
    static void setArrowStyle(const long &v);
    static const char *docArrowStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoCorrectRefs
    ///
    /// When the geometry a dimension refers to has changed, try to find
    /// the matching geometry again. Read each time a dimension is
    /// recomputed.
    static const bool & getAutoCorrectRefs();
    static const bool & defaultAutoCorrectRefs();
    static void removeAutoCorrectRefs();
    static void setAutoCorrectRefs(const bool &v);
    static const char *docAutoCorrectRefs();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BalloonKink
    ///
    /// Length in mm of the short segment between a new balloon and the
    /// bend of its leader line. Applies to balloons created afterwards.
    static const double & getBalloonKink();
    static const double & defaultBalloonKink();
    static void removeBalloonKink();
    static void setBalloonKink(const double &v);
    static const char *docBalloonKink();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GapASME
    ///
    /// Gap between the measured point and the start of the extension line
    /// for ASME dimensions, as a factor. Applies to dimensions created
    /// afterwards.
    static const double & getGapASME();
    static const double & defaultGapASME();
    static void removeGapASME();
    static void setGapASME(const double &v);
    static const char *docGapASME();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GapISO
    ///
    /// Gap between the measured point and the start of the extension line
    /// for ISO dimensions, as a factor. Applies to dimensions created
    /// afterwards.
    static const double & getGapISO();
    static const double & defaultGapISO();
    static void removeGapISO();
    static void setGapISO(const double &v);
    static const char *docGapISO();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowUnits
    ///
    /// Append the unit to dimension values. Takes effect when dimensions
    /// are recomputed.
    static const bool & getShowUnits();
    static const bool & defaultShowUnits();
    static void removeShowUnits();
    static void setShowUnits(const bool &v);
    static const char *docShowUnits();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SymbolSize
    ///
    /// Nominal size of the welding symbol pictures; the supplied symbols
    /// are drawn at 64. Change only for a symbol set drawn at another
    /// size.
    static const double & getSymbolSize();
    static const double & defaultSymbolSize();
    static void removeSymbolSize();
    static void setSymbolSize(const double &v);
    static const char *docSymbolSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TileTextAdjust
    ///
    /// Text size of a new welding symbol relative to the dimension font
    /// size. Applies to welding symbols created afterwards.
    static const double & getTileTextAdjust();
    static const double & defaultTileTextAdjust();
    static void removeTileTextAdjust();
    static void setTileTextAdjust(const double &v);
    static const char *docTileTextAdjust();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TolSizeAdjust
    ///
    /// Size of tolerance text relative to the dimension text. Takes
    /// effect when dimensions are redrawn.
    static const double & getTolSizeAdjust();
    static const double & defaultTolSizeAdjust();
    static void removeTolSizeAdjust();
    static void setTolSizeAdjust(const double &v);
    static const char *docTolSizeAdjust();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseGlobalDecimals
    ///
    /// Show dimension values with the number of decimals set for the
    /// whole program. Off uses the alternate decimals instead.
    static const bool & getUseGlobalDecimals();
    static const bool & defaultUseGlobalDecimals();
    static void removeUseGlobalDecimals();
    static void setUseGlobalDecimals(const bool &v);
    static const char *docUseGlobalDecimals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter formatSpec
    ///
    /// Format of dimension values when global decimals are not used, in
    /// printf style, for example %.2f; with w in place of f trailing
    /// zeros are dropped.
    static const std::string & getformatSpec();
    static const std::string & defaultformatSpec();
    static void removeformatSpec();
    static void setformatSpec(const std::string &v);
    static const char *docformatSpec();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HardHid
    ///
    /// New views show hidden hard edges. Applies to views created
    /// afterwards; each view has its own property.
    static const bool & getHardHid();
    static const bool & defaultHardHid();
    static void removeHardHid();
    static void setHardHid(const bool &v);
    static const char *docHardHid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IsoHid
    ///
    /// New views show hidden iso-parameter lines. Applies to views
    /// created afterwards.
    static const bool & getIsoHid();
    static const bool & defaultIsoHid();
    static void removeIsoHid();
    static void setIsoHid(const bool &v);
    static const char *docIsoHid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IsoViz
    ///
    /// New views show visible iso-parameter lines. Applies to views
    /// created afterwards.
    static const bool & getIsoViz();
    static const bool & defaultIsoViz();
    static void removeIsoViz();
    static void setIsoViz(const bool &v);
    static const char *docIsoViz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SeamHid
    ///
    /// New views show hidden seam lines. Applies to views created
    /// afterwards.
    static const bool & getSeamHid();
    static const bool & defaultSeamHid();
    static void removeSeamHid();
    static void setSeamHid(const bool &v);
    static const char *docSeamHid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SeamViz
    ///
    /// New views show visible seam lines. Applies to views created
    /// afterwards.
    static const bool & getSeamViz();
    static const bool & defaultSeamViz();
    static void removeSeamViz();
    static void setSeamViz(const bool &v);
    static const char *docSeamViz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SmoothHid
    ///
    /// New views show hidden smooth edges, where faces meet tangentially.
    /// Applies to views created afterwards.
    static const bool & getSmoothHid();
    static const bool & defaultSmoothHid();
    static void removeSmoothHid();
    static void setSmoothHid(const bool &v);
    static const char *docSmoothHid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SmoothViz
    ///
    /// New views show visible smooth edges, where faces meet
    /// tangentially. Applies to views created afterwards.
    static const bool & getSmoothViz();
    static const bool & defaultSmoothViz();
    static void removeSmoothViz();
    static void setSmoothViz(const bool &v);
    static const char *docSmoothViz();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GeomWeight
    ///
    /// Line width of the PAT hatch on the cut surface of a new section.
    /// Applies to sections created afterwards.
    static const double & getGeomWeight();
    static const double & defaultGeomWeight();
    static void removeGeomWeight();
    static void setGeomWeight(const double &v);
    static const char *docGeomWeight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxSeg
    ///
    /// Largest number of line segments used to draw the PAT hatch of one
    /// face. 1 to 1000000. A limit that keeps a very fine hatch from
    /// freezing the program.
    static const long & getMaxSeg();
    static const long & defaultMaxSeg();
    static void removeMaxSeg();
    static void setMaxSeg(const long &v);
    static const char *docMaxSeg();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NamePattern
    ///
    /// Name of the pattern, within the PAT file, used for new geometric
    /// hatches. Applies to hatches created afterwards.
    static const std::string & getNamePattern();
    static const std::string & defaultNamePattern();
    static void removeNamePattern();
    static void setNamePattern(const std::string &v);
    static const char *docNamePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ClearFace
    ///
    /// Faces of new views are transparent instead of filled with the face
    /// colour. Applies to views created afterwards.
    static const bool & getClearFace();
    static const bool & defaultClearFace();
    static void removeClearFace();
    static void setClearFace(const bool &v);
    static const char *docClearFace();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LightOnDark
    ///
    /// Draw pages in light colours for a dark page background. Printing
    /// and export always use the normal colours. Takes effect when a page
    /// is redrawn.
    static const bool & getLightOnDark();
    static const bool & defaultLightOnDark();
    static void removeLightOnDark();
    static void setLightOnDark(const bool &v);
    static const char *docLightOnDark();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Monochrome
    ///
    /// With Light on dark, draw everything in the single light text
    /// colour instead of lightened colours. Takes effect when a page is
    /// redrawn.
    static const bool & getMonochrome();
    static const bool & defaultMonochrome();
    static void removeMonochrome();
    static void setMonochrome(const bool &v);
    static const char *docMonochrome();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LabelFont
    ///
    /// Font of view labels, and the font new dimensions, balloons and
    /// annotations start with.
    static const std::string & getLabelFont();
    static const std::string & defaultLabelFont();
    static void removeLabelFont();
    static void setLabelFont(const std::string &v);
    static const char *docLabelFont();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LabelSize
    ///
    /// Text size of view labels in mm, and the size new annotations start
    /// with.
    static const double & getLabelSize();
    static const double & defaultLabelSize();
    static void removeLabelSize();
    static void setLabelSize(const double &v);
    static const char *docLabelSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoHorizontal
    ///
    /// New leader lines end in a horizontal segment.
    static const bool & getAutoHorizontal();
    static const bool & defaultAutoHorizontal();
    static void removeAutoHorizontal();
    static void setAutoHorizontal(const bool &v);
    static const char *docAutoHorizontal();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Resolution
    ///
    /// Scene units per millimetre of a drawing page. Read once when the
    /// TechDraw user interface is loaded.
    static const double & getResolution();
    static const double & defaultResolution();
    static void removeResolution();
    static void setResolution(const double &v);
    static const char *docResolution();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TrackerWeight
    ///
    /// Line width of the rubber band lines drawn while a tool tracks the
    /// mouse on a page.
    static const double & getTrackerWeight();
    static const double & defaultTrackerWeight();
    static void removeTrackerWeight();
    static void setTrackerWeight(const double &v);
    static const char *docTrackerWeight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter allowCrazyEdge
    ///
    /// Keep edges of unreasonable length that projection sometimes
    /// produces instead of dropping them. For developers.
    static const bool & getallowCrazyEdge();
    static const bool & defaultallowCrazyEdge();
    static void removeallowCrazyEdge();
    static void setallowCrazyEdge(const bool &v);
    static const char *docallowCrazyEdge();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter debugDetail
    ///
    /// Write the intermediate shapes of a detail view to files while it
    /// is recomputed. For developers.
    static const bool & getdebugDetail();
    static const bool & defaultdebugDetail();
    static void removedebugDetail();
    static void setdebugDetail(const bool &v);
    static const char *docdebugDetail();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter debugSection
    ///
    /// Write the intermediate shapes of a section view to files while it
    /// is recomputed. For developers.
    static const bool & getdebugSection();
    static const bool & defaultdebugSection();
    static void removedebugSection();
    static void setdebugSection(const bool &v);
    static const char *docdebugSection();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Background
    ///
    /// Colour of the area around the sheet in a page view. Read when a
    /// page view is opened.
    static const unsigned long & getBackground();
    static const unsigned long & defaultBackground();
    static void removeBackground();
    static void setBackground(const unsigned long &v);
    static const char *docBackground();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CutSurfaceColor
    ///
    /// Colour of the cut surface of new sections that show it as a solid
    /// colour. Applies to sections created afterwards.
    static const unsigned long & getCutSurfaceColor();
    static const unsigned long & defaultCutSurfaceColor();
    static void removeCutSurfaceColor();
    static void setCutSurfaceColor(const unsigned long &v);
    static const char *docCutSurfaceColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FaceColor
    ///
    /// Fill colour of the faces of new views. Applies to views created
    /// afterwards; each view has its own Face Color property.
    static const unsigned long & getFaceColor();
    static const unsigned long & defaultFaceColor();
    static void removeFaceColor();
    static void setFaceColor(const unsigned long &v);
    static const char *docFaceColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GeomHatch
    ///
    /// Line colour of new geometric (PAT) hatches. Applies to hatches
    /// created afterwards.
    static const unsigned long & getGeomHatch();
    static const unsigned long & defaultGeomHatch();
    static void removeGeomHatch();
    static void setGeomHatch(const unsigned long &v);
    static const char *docGeomHatch();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Hatch
    ///
    /// Colour of new SVG hatches. Applies to hatches created afterwards.
    static const unsigned long & getHatch();
    static const unsigned long & defaultHatch();
    static void removeHatch();
    static void setHatch(const unsigned long &v);
    static const char *docHatch();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HiddenColor
    ///
    /// Colour of hidden lines. Takes effect when a view is redrawn.
    static const unsigned long & getHiddenColor();
    static const unsigned long & defaultHiddenColor();
    static void removeHiddenColor();
    static void setHiddenColor(const unsigned long &v);
    static const char *docHiddenColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LightTextColor
    ///
    /// The one colour everything is drawn in while Light on dark and
    /// Monochrome are both on.
    static const unsigned long & getLightTextColor();
    static const unsigned long & defaultLightTextColor();
    static void removeLightTextColor();
    static void setLightTextColor(const unsigned long &v);
    static const char *docLightTextColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NormalColor
    ///
    /// Colour of lines and text that are not selected, and the colour new
    /// cosmetic lines and annotations start with.
    static const unsigned long & getNormalColor();
    static const unsigned long & defaultNormalColor();
    static void removeNormalColor();
    static void setNormalColor(const unsigned long &v);
    static const char *docNormalColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PageColor
    ///
    /// Colour of the sheet in a page view.
    static const unsigned long & getPageColor();
    static const unsigned long & defaultPageColor();
    static void removePageColor();
    static void setPageColor(const unsigned long &v);
    static const char *docPageColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TemplateUnderlineColor
    ///
    /// Colour of the click boxes on the editable texts of a template.
    /// Read when a template is loaded.
    static const unsigned long & getTemplateUnderlineColor();
    static const unsigned long & defaultTemplateUnderlineColor();
    static void removeTemplateUnderlineColor();
    static void setTemplateUnderlineColor(const unsigned long &v);
    static const char *docTemplateUnderlineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter gridColor
    ///
    /// Colour of the page grid.
    static const unsigned long & getgridColor();
    static const unsigned long & defaultgridColor();
    static void removegridColor();
    static void setgridColor(const unsigned long &v);
    static const char *docgridColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BreaklineColor
    ///
    /// Colour of the break lines of broken views.
    static const unsigned long & getBreaklineColor();
    static const unsigned long & defaultBreaklineColor();
    static void removeBreaklineColor();
    static void setBreaklineColor(const unsigned long &v);
    static const char *docBreaklineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CenterColor
    ///
    /// Colour of centre lines and centre marks.
    static const unsigned long & getCenterColor();
    static const unsigned long & defaultCenterColor();
    static void removeCenterColor();
    static void setCenterColor(const unsigned long &v);
    static const char *docCenterColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HighlightColor
    ///
    /// Colour of the detail highlight in new views. Applies to views
    /// created afterwards.
    static const unsigned long & getHighlightColor();
    static const unsigned long & defaultHighlightColor();
    static void removeHighlightColor();
    static void setHighlightColor(const unsigned long &v);
    static const char *docHighlightColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionColor
    ///
    /// Colour of section lines.
    static const unsigned long & getSectionColor();
    static const unsigned long & defaultSectionColor();
    static void removeSectionColor();
    static void setSectionColor(const unsigned long &v);
    static const char *docSectionColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VertexColor
    ///
    /// Colour of vertex dots, and the colour new cosmetic vertices start
    /// with.
    static const unsigned long & getVertexColor();
    static const unsigned long & defaultVertexColor();
    static void removeVertexColor();
    static void setVertexColor(const unsigned long &v);
    static const char *docVertexColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionColor
    ///
    /// Colour of dimensions and balloons.
    static const unsigned long & getDimensionColor();
    static const unsigned long & defaultDimensionColor();
    static void removeDimensionColor();
    static void setDimensionColor(const unsigned long &v);
    static const char *docDimensionColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LeaderLineColor
    ///
    /// Colour of leader lines; new leaders and rich annotations start
    /// with it.
    static const unsigned long & getLeaderLineColor();
    static const unsigned long & defaultLeaderLineColor();
    static void removeLeaderLineColor();
    static void setLeaderLineColor(const unsigned long &v);
    static const char *docLeaderLineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TrackerColor
    ///
    /// Colour of the rubber band lines drawn while a tool tracks the
    /// mouse on a page.
    static const unsigned long & getTrackerColor();
    static const unsigned long & defaultTrackerColor();
    static void removeTrackerColor();
    static void setTrackerColor(const unsigned long &v);
    static const char *docTrackerColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineGroup
    ///
    /// Index of the line group -- a set of thin, graphic and thick line
    /// widths -- in the line group file. Read at each width lookup.
    static const long & getLineGroup();
    static const long & defaultLineGroup();
    static void removeLineGroup();
    static void setLineGroup(const long &v);
    static const char *docLineGroup();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineStyleCenter
    ///
    /// Line style of centre lines, as an index into the lines of the
    /// active line standard, counted from 0. Takes effect when views are
    /// redrawn.
    static const long & getLineStyleCenter();
    static const long & defaultLineStyleCenter();
    static void removeLineStyleCenter();
    static void setLineStyleCenter(const long &v);
    static const char *docLineStyleCenter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineStyleHidden
    ///
    /// Line style of hidden lines, as an index into the lines of the
    /// active line standard, counted from 0. Takes effect when views are
    /// redrawn.
    static const long & getLineStyleHidden();
    static const long & defaultLineStyleHidden();
    static void removeLineStyleHidden();
    static void setLineStyleHidden(const long &v);
    static const char *docLineStyleHidden();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineStyleBreak
    ///
    /// Line style of the break lines of new broken views, as an index
    /// into the lines of the active line standard, counted from 0.
    /// Applies to views created afterwards.
    static const long & getLineStyleBreak();
    static const long & defaultLineStyleBreak();
    static void removeLineStyleBreak();
    static void setLineStyleBreak(const long &v);
    static const char *docLineStyleBreak();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BreakType
    ///
    /// How breaks are drawn in new broken views: 0 not at all, 1 zig-zag,
    /// 2 simple. Applies to views created afterwards.
    static const long & getBreakType();
    static const long & defaultBreakType();
    static void removeBreakType();
    static void setBreakType(const long &v);
    static const char *docBreakType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionLine
    ///
    /// Line style of section lines: for a new view the number of a line
    /// of the active line standard, where a section line or a highlight
    /// is drawn a pen style -- 1 solid, 2 dashed, 3 dotted, 4 dash-dot.
    /// The Section Line Style list of the Annotation page stores another
    /// key, which nothing that draws reads.
    static const long & getSectionLine();
    static const long & defaultSectionLine();
    static void removeSectionLine();
    static void setSectionLine(const long &v);
    static const char *docSectionLine();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HighlightStyle
    ///
    /// Line style of the detail highlight in new views, as the number of
    /// a line of the active line standard. Applies to views created
    /// afterwards. The Detail Highlight Style list of the Annotation page
    /// stores another key, which nothing that draws reads.
    static const long & getHighlightStyle();
    static const long & defaultHighlightStyle();
    static void removeHighlightStyle();
    static void setHighlightStyle(const long &v);
    static const char *docHighlightStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CenterLine
    ///
    /// Pen style of centre line items: 1 solid, 2 dashed, 3 dotted, 4
    /// dash-dot, 5 dash-dot-dot. Read as each centre line item is made.
    static const long & getCenterLine();
    static const long & defaultCenterLine();
    static void removeCenterLine();
    static void setCenterLine(const long &v);
    static const char *docCenterLine();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CenterLineStyle
    ///
    /// Line style new cosmetic edges and centre lines start with, as the
    /// number of a line of the active line standard. Applies to lines
    /// created afterwards.
    static const long & getCenterLineStyle();
    static const long & defaultCenterLineStyle();
    static void removeCenterLineStyle();
    static void setCenterLineStyle(const long &v);
    static const char *docCenterLineStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HiddenLine
    ///
    /// Pen style of an edge marked hidden: 0 solid, 1 dashed, 2 dotted, 3
    /// dash-dot, 4 dash-dot-dot. Read when an edge is marked hidden.
    static const long & getHiddenLine();
    static const long & defaultHiddenLine();
    static void removeHiddenLine();
    static void setHiddenLine(const long &v);
    static const char *docHiddenLine();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgeCapStyle
    ///
    /// Shape of line ends: 0 round, 1 square, 2 flat. Flat or square ends
    /// suit drawings printed 1:1 as cutting guides. Read as pens are
    /// made.
    static const long & getEdgeCapStyle();
    static const long & defaultEdgeCapStyle();
    static void removeEdgeCapStyle();
    static void setEdgeCapStyle(const long &v);
    static const char *docEdgeCapStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineStandard
    ///
    /// Line standard in use, as an index into the standards found in the
    /// line definition folder. Read each time line definitions are
    /// loaded.
    static const long & getLineStandard();
    static const long & defaultLineStandard();
    static void removeLineStandard();
    static void setLineStandard(const long &v);
    static const char *docLineStandard();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionLineStandard
    ///
    /// Where the arrows and letters of a section line sit: 0 as ANSI and
    /// ASME have them, 1 as ISO has them. Read each time a section line
    /// is drawn.
    static const long & getSectionLineStandard();
    static const long & defaultSectionLineStandard();
    static void removeSectionLineStandard();
    static void setSectionLineStandard(const long &v);
    static const char *docSectionLineStandard();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IsoCount
    ///
    /// Number of iso-parameter lines per face in new views. Applies to
    /// views created afterwards.
    static const long & getIsoCount();
    static const long & defaultIsoCount();
    static void removeIsoCount();
    static void setIsoCount(const long &v);
    static const char *docIsoCount();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CoarseView
    ///
    /// New views use the fast polygon approximation for hidden lines:
    /// quicker, but curves become short straight segments and faces are
    /// not found. Applies to views created afterwards; each view has its
    /// own Coarse View property.
    static const bool & getCoarseView();
    static const bool & defaultCoarseView();
    static void removeCoarseView();
    static void setCoarseView(const bool &v);
    static const char *docCoarseView();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineSpacingFactorISO
    ///
    /// Space between the dimension line and the text of new ISO
    /// dimensions, as a multiple of the line width. Applies to dimensions
    /// created afterwards.
    static const double & getLineSpacingFactorISO();
    static const double & defaultLineSpacingFactorISO();
    static void removeLineSpacingFactorISO();
    static void setLineSpacingFactorISO(const double &v);
    static const char *docLineSpacingFactorISO();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionUpdateDelay
    ///
    /// Time in milliseconds between a change in the section view dialog
    /// and the update of the section while live update is on. At least
    /// 100.
    static const long & getSectionUpdateDelay();
    static const long & defaultSectionUpdateDelay();
    static void removeSectionUpdateDelay();
    static void setSectionUpdateDelay(const long &v);
    static const char *docSectionUpdateDelay();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArrowSize
    ///
    /// Size in mm of dimension arrowheads. Applies to dimensions created
    /// afterwards; each dimension has its own Arrow Size property.
    static const double & getArrowSize();
    static const double & defaultArrowSize();
    static void removeArrowSize();
    static void setArrowSize(const double &v);
    static const char *docArrowSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FontSize
    ///
    /// Text size in mm of dimensions and of other annotation text that
    /// follows it. Applies to dimensions created afterwards.
    static const double & getFontSize();
    static const double & defaultFontSize();
    static void removeFontSize();
    static void setFontSize(const double &v);
    static const char *docFontSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DiameterSymbol
    ///
    /// Character put in front of diameter dimensions; the diameter sign
    /// unless another is given. Takes effect when dimensions are
    /// recomputed.
    static const std::string & getDiameterSymbol();
    static const std::string & defaultDiameterSymbol();
    static void removeDiameterSymbol();
    static void setDiameterSymbol(const std::string &v);
    static const char *docDiameterSymbol();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StandardAndStyle
    ///
    /// Standard and text placement of new dimensions: 0 ISO oriented, 1
    /// ISO referencing, 2 ASME inlined, 3 ASME referencing. Applies to
    /// dimensions created afterwards.
    static const long & getStandardAndStyle();
    static const long & defaultStandardAndStyle();
    static void removeStandardAndStyle();
    static void setStandardAndStyle(const long &v);
    static const char *docStandardAndStyle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TemplateFile
    ///
    /// Template of a new page. Empty uses A4_LandscapeTD.svg, supplied
    /// with the program.
    static const std::string & getTemplateFile();
    static const std::string & defaultTemplateFile();
    static void removeTemplateFile();
    static void setTemplateFile(const std::string &v);
    static const char *docTemplateFile();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TemplateDir
    ///
    /// Folder the template chooser opens in. Empty uses the one supplied
    /// with the program.
    static const std::string & getTemplateDir();
    static const std::string & defaultTemplateDir();
    static void removeTemplateDir();
    static void setTemplateDir(const std::string &v);
    static const char *docTemplateDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineGroupFile
    ///
    /// File of line groups -- sets of line widths. Empty uses the one
    /// supplied with the program.
    static const std::string & getLineGroupFile();
    static const std::string & defaultLineGroupFile();
    static void removeLineGroupFile();
    static void setLineGroupFile(const std::string &v);
    static const char *docLineGroupFile();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileHatch
    ///
    /// SVG file new hatches take their pattern from. Empty uses
    /// simple.svg, supplied with the program.
    static const std::string & getFileHatch();
    static const std::string & defaultFileHatch();
    static void removeFileHatch();
    static void setFileHatch(const std::string &v);
    static const char *docFileHatch();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WeldingDir
    ///
    /// Folder of welding symbols. Empty uses the AWS symbols supplied
    /// with the program.
    static const std::string & getWeldingDir();
    static const std::string & defaultWeldingDir();
    static void removeWeldingDir();
    static void setWeldingDir(const std::string &v);
    static const char *docWeldingDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineDefLocation
    ///
    /// Folder of the line standard definitions. Empty uses the one
    /// supplied with the program.
    static const std::string & getLineDefLocation();
    static const std::string & defaultLineDefLocation();
    static void removeLineDefLocation();
    static void setLineDefLocation(const std::string &v);
    static const char *docLineDefLocation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LineElementLocation
    ///
    /// Folder of the line element definitions of the line standards.
    /// Empty uses the one supplied with the program.
    static const std::string & getLineElementLocation();
    static const std::string & defaultLineElementLocation();
    static void removeLineElementLocation();
    static void setLineElementLocation(const std::string &v);
    static const char *docLineElementLocation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FilePattern
    ///
    /// PAT file new geometric hatches take their pattern from. Empty uses
    /// FCPAT.pat, supplied with the program.
    static const std::string & getFilePattern();
    static const std::string & defaultFilePattern();
    static void removeFilePattern();
    static void setFilePattern(const std::string &v);
    static const char *docFilePattern();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class TechDrawParams
} // namespace TechDraw
//[[[end]]]

#endif // TECHDRAW_APP_PARAMS_H
