/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef SKETCHER_APP_PARAMS_H
#define SKETCHER_APP_PARAMS_H

#include <Mod/Sketcher/SketcherGlobal.h>

/*[[[cog
import SketcherParams
SketcherParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Sketcher {
/** Convenient class to obtain the settings of the Sketcher

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Sketcher"
 *
 * This class is auto generated by Mod/Sketcher/App/SketcherParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Sketcher/App/SketcherParams.h Mod/Sketcher/App/SketcherParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Sketcher/App/SketcherParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Sketcher/App/SketcherParams.cpp with
 * the following signature.
 * @code
 *     void SketcherParams:on<parameter_name>Changed()
 * @endcode
 */
class SketcherExport SketcherParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRecompute
    ///
    /// Recompute the active document after every sketch action. Set from
    /// the Auto-update box of the solver messages panel; applies at once.
    static const bool & getAutoRecompute();
    static const bool & defaultAutoRecompute();
    static void removeAutoRecompute();
    static void setAutoRecompute(const bool &v);
    static const char *docAutoRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRemoveRedundants
    ///
    /// Remove redundant constraints automatically when they are detected.
    /// Works only while Auto-update is on. Applies at once.
    static const bool & getAutoRemoveRedundants();
    static const bool & defaultAutoRemoveRedundants();
    static void removeAutoRemoveRedundants();
    static void setAutoRemoveRedundants(const bool &v);
    static const char *docAutoRemoveRedundants();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ContinuousCreationMode
    ///
    /// Keep a geometry tool active after it creates an element, so the
    /// next one can be drawn at once. Applies to the next element.
    static const bool & getContinuousCreationMode();
    static const bool & defaultContinuousCreationMode();
    static void removeContinuousCreationMode();
    static void setContinuousCreationMode(const bool &v);
    static const char *docContinuousCreationMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ContinuousConstraintMode
    ///
    /// Keep a constraint tool active after it creates a constraint.
    /// Applies the next time a constraint tool is started.
    static const bool & getContinuousConstraintMode();
    static const bool & defaultContinuousConstraintMode();
    static void removeContinuousConstraintMode();
    static void setContinuousConstraintMode(const bool &v);
    static const char *docContinuousConstraintMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDialogOnDistanceConstraint
    ///
    /// Ask for the value right after a dimensional constraint is created.
    /// Applies to the next constraint.
    static const bool & getShowDialogOnDistanceConstraint();
    static const bool & defaultShowDialogOnDistanceConstraint();
    static void removeShowDialogOnDistanceConstraint();
    static void setShowDialogOnDistanceConstraint(const bool &v);
    static const char *docShowDialogOnDistanceConstraint();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RadiusDiameterConstraintDisplayBaseAngle
    ///
    /// Angle in degrees at which the label of a new radius or diameter
    /// constraint is placed. Applies to new constraints.
    static const double & getRadiusDiameterConstraintDisplayBaseAngle();
    static const double & defaultRadiusDiameterConstraintDisplayBaseAngle();
    static void removeRadiusDiameterConstraintDisplayBaseAngle();
    static void setRadiusDiameterConstraintDisplayBaseAngle(const double &v);
    static const char *docRadiusDiameterConstraintDisplayBaseAngle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RadiusDiameterConstraintDisplayAngleRandomness
    ///
    /// Random spread in degrees added around the base angle of new radius
    /// or diameter labels, so labels overlap less.
    static const double & getRadiusDiameterConstraintDisplayAngleRandomness();
    static const double & defaultRadiusDiameterConstraintDisplayAngleRandomness();
    static void removeRadiusDiameterConstraintDisplayAngleRandomness();
    static void setRadiusDiameterConstraintDisplayAngleRandomness(const double &v);
    static const char *docRadiusDiameterConstraintDisplayAngleRandomness();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GeometryHistoryLevel
    ///
    /// How much geometry history a sketch keeps for stable element names:
    /// 0 none, 1 default, above 1 keeps more. Read when a sketch object
    /// is created or loaded.
    static const long & getGeometryHistoryLevel();
    static const long & defaultGeometryHistoryLevel();
    static void removeGeometryHistoryLevel();
    static void setGeometryHistoryLevel(const long &v);
    static const char *docGeometryHistoryLevel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArcFitTolerance
    ///
    /// Tolerance used to fit arcs for a new sketch; copied into the
    /// sketch's ArcFitTolerance property when it is created.
    static const double & getArcFitTolerance();
    static const double & defaultArcFitTolerance();
    static void removeArcFitTolerance();
    static void setArcFitTolerance(const double &v);
    static const char *docArcFitTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalBSplineMaxDegree
    ///
    /// Maximum degree of B-splines made from external geometry in a new
    /// sketch. Copied into the sketch when it is created.
    static const long & getExternalBSplineMaxDegree();
    static const long & defaultExternalBSplineMaxDegree();
    static void removeExternalBSplineMaxDegree();
    static void setExternalBSplineMaxDegree(const long &v);
    static const char *docExternalBSplineMaxDegree();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalBSplineTolerance
    ///
    /// Tolerance of B-splines made from external geometry in a new
    /// sketch.0001. Copied into the sketch when it is created.
    static const double & getExternalBSplineTolerance();
    static const double & defaultExternalBSplineTolerance();
    static void removeExternalBSplineTolerance();
    static void setExternalBSplineTolerance(const double &v);
    static const char *docExternalBSplineTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MakeInternals
    ///
    /// Generate internal faces from the closed regions of a new sketch.
    /// Copied into the sketch's MakeInternals property when it is
    /// created.
    static const bool & getMakeInternals();
    static const bool & defaultMakeInternals();
    static void removeMakeInternals();
    static void setMakeInternals(const bool &v);
    static const char *docMakeInternals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LeaveSketchWithEscape
    ///
    /// Let the Esc key leave sketch edit mode. Takes effect the next time
    /// a sketch is edited.
    static const bool & getLeaveSketchWithEscape();
    static const bool & defaultLeaveSketchWithEscape();
    static void removeLeaveSketchWithEscape();
    static void setLeaveSketchWithEscape(const bool &v);
    static const char *docLeaveSketchWithEscape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSolverAdvancedWidget
    ///
    /// Show the Advanced solver control section in the sketch task panel.
    /// Takes effect the next time a sketch is edited.
    static const bool & getShowSolverAdvancedWidget();
    static const bool & defaultShowSolverAdvancedWidget();
    static void removeShowSolverAdvancedWidget();
    static void setShowSolverAdvancedWidget(const bool &v);
    static const char *docShowSolverAdvancedWidget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecalculateInitialSolutionWhileDragging
    ///
    /// Recalculate the solver's starting point while a point is dragged,
    /// which improves solving. Takes effect the next time a sketch is
    /// edited.
    static const bool & getRecalculateInitialSolutionWhileDragging();
    static const bool & defaultRecalculateInitialSolutionWhileDragging();
    static void removeRecalculateInitialSolutionWhileDragging();
    static void setRecalculateInitialSolutionWhileDragging(const bool &v);
    static const char *docRecalculateInitialSolutionWhileDragging();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExtendedConstraintInformation
    ///
    /// Show extended information for each entry of the constraint list.
    /// Applies at once.
    static const bool & getExtendedConstraintInformation();
    static const bool & defaultExtendedConstraintInformation();
    static void removeExtendedConstraintInformation();
    static void setExtendedConstraintInformation(const bool &v);
    static const char *docExtendedConstraintInformation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideInternalAlignment
    ///
    /// Hide internal alignment constraints in the constraint list.
    /// Applies at once.
    static const bool & getHideInternalAlignment();
    static const bool & defaultHideInternalAlignment();
    static void removeHideInternalAlignment();
    static void setHideInternalAlignment(const bool &v);
    static const char *docHideInternalAlignment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VisualisationTrackingFilter
    ///
    /// Show in the 3D view only the constraints that pass the constraint
    /// list filter. Applies at once.
    static const bool & getVisualisationTrackingFilter();
    static const bool & defaultVisualisationTrackingFilter();
    static void removeVisualisationTrackingFilter();
    static void setVisualisationTrackingFilter(const bool &v);
    static const char *docVisualisationTrackingFilter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideUnits
    ///
    /// Hide the base length unit in dimension labels and cursor
    /// coordinates for unit systems that support it. Shown at the next
    /// redraw.
    static const bool & getHideUnits();
    static const bool & defaultHideUnits();
    static void removeHideUnits();
    static void setHideUnits(const bool &v);
    static const char *docHideUnits();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDimensionalName
    ///
    /// Show the name of a named dimensional constraint in its label,
    /// using the format string. Shown at the next redraw.
    static const bool & getShowDimensionalName();
    static const bool & defaultShowDimensionalName();
    static void removeShowDimensionalName();
    static void setShowDimensionalName(const bool &v);
    static const char *docShowDimensionalName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionalStringFormat
    ///
    /// Format of a named dimension's label: %N is the constraint name, %V
    /// its value. Shown at the next redraw.
    static const std::string & getDimensionalStringFormat();
    static const std::string & defaultDimensionalStringFormat();
    static void removeDimensionalStringFormat();
    static void setDimensionalStringFormat(const std::string &v);
    static const char *docDimensionalStringFormat();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowCursorCoords
    ///
    /// Show the coordinates next to the cursor while drawing in a sketch.
    /// Applies at once.
    static const bool & getShowCursorCoords();
    static const bool & defaultShowCursorCoords();
    static void removeShowCursorCoords();
    static void setShowCursorCoords(const bool &v);
    static const char *docShowCursorCoords();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseSystemDecimals
    ///
    /// Show cursor coordinates with the number of decimals of the unit
    /// settings instead of a short form. Applies at once.
    static const bool & getUseSystemDecimals();
    static const bool & defaultUseSystemDecimals();
    static void removeUseSystemDecimals();
    static void setUseSystemDecimals(const bool &v);
    static const char *docUseSystemDecimals();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class SketcherParams
} // namespace Sketcher
//[[[end]]]

#endif // SKETCHER_APP_PARAMS_H
