/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef SKETCHER_APP_PARAMS_H
#define SKETCHER_APP_PARAMS_H

#include <Mod/Sketcher/SketcherGlobal.h>

/*[[[cog
import SketcherParams
SketcherParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Sketcher {
/** Convenient class to obtain the settings of the Sketcher

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Sketcher"
 *
 * This class is auto generated by Mod/Sketcher/App/SketcherParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Sketcher/App/SketcherParams.h Mod/Sketcher/App/SketcherParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Sketcher/App/SketcherParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Sketcher/App/SketcherParams.cpp with
 * the following signature.
 * @code
 *     void SketcherParams:on<parameter_name>Changed()
 * @endcode
 */
class SketcherExport SketcherParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRecompute
    ///
    /// Recompute the active document after every sketch action. Set from
    /// the Auto-update box of the solver messages panel; applies at once.
    static const bool & getAutoRecompute();
    static const bool & defaultAutoRecompute();
    static void removeAutoRecompute();
    static void setAutoRecompute(const bool &v);
    static const char *docAutoRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRemoveRedundants
    ///
    /// Remove redundant constraints automatically when they are detected.
    /// Works only while Auto-update is on. Applies at once.
    static const bool & getAutoRemoveRedundants();
    static const bool & defaultAutoRemoveRedundants();
    static void removeAutoRemoveRedundants();
    static void setAutoRemoveRedundants(const bool &v);
    static const char *docAutoRemoveRedundants();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ContinuousCreationMode
    ///
    /// Keep a geometry tool active after it creates an element, so the
    /// next one can be drawn at once. Applies to the next element.
    static const bool & getContinuousCreationMode();
    static const bool & defaultContinuousCreationMode();
    static void removeContinuousCreationMode();
    static void setContinuousCreationMode(const bool &v);
    static const char *docContinuousCreationMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ContinuousConstraintMode
    ///
    /// Keep a constraint tool active after it creates a constraint.
    /// Applies the next time a constraint tool is started.
    static const bool & getContinuousConstraintMode();
    static const bool & defaultContinuousConstraintMode();
    static void removeContinuousConstraintMode();
    static void setContinuousConstraintMode(const bool &v);
    static const char *docContinuousConstraintMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDialogOnDistanceConstraint
    ///
    /// Ask for the value right after a dimensional constraint is created.
    /// Applies to the next constraint.
    static const bool & getShowDialogOnDistanceConstraint();
    static const bool & defaultShowDialogOnDistanceConstraint();
    static void removeShowDialogOnDistanceConstraint();
    static void setShowDialogOnDistanceConstraint(const bool &v);
    static const char *docShowDialogOnDistanceConstraint();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RadiusDiameterConstraintDisplayBaseAngle
    ///
    /// Angle in degrees at which the label of a new radius or diameter
    /// constraint is placed. Applies to new constraints.
    static const double & getRadiusDiameterConstraintDisplayBaseAngle();
    static const double & defaultRadiusDiameterConstraintDisplayBaseAngle();
    static void removeRadiusDiameterConstraintDisplayBaseAngle();
    static void setRadiusDiameterConstraintDisplayBaseAngle(const double &v);
    static const char *docRadiusDiameterConstraintDisplayBaseAngle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RadiusDiameterConstraintDisplayAngleRandomness
    ///
    /// Random spread in degrees added around the base angle of new radius
    /// or diameter labels, so labels overlap less.
    static const double & getRadiusDiameterConstraintDisplayAngleRandomness();
    static const double & defaultRadiusDiameterConstraintDisplayAngleRandomness();
    static void removeRadiusDiameterConstraintDisplayAngleRandomness();
    static void setRadiusDiameterConstraintDisplayAngleRandomness(const double &v);
    static const char *docRadiusDiameterConstraintDisplayAngleRandomness();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GeometryHistoryLevel
    ///
    /// How much geometry history a sketch keeps for stable element names:
    /// 0 none, 1 default, above 1 keeps more. Read when a sketch object
    /// is created or loaded.
    static const long & getGeometryHistoryLevel();
    static const long & defaultGeometryHistoryLevel();
    static void removeGeometryHistoryLevel();
    static void setGeometryHistoryLevel(const long &v);
    static const char *docGeometryHistoryLevel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArcFitTolerance
    ///
    /// Tolerance used to fit arcs for a new sketch; copied into the
    /// sketch's ArcFitTolerance property when it is created.
    static const double & getArcFitTolerance();
    static const double & defaultArcFitTolerance();
    static void removeArcFitTolerance();
    static void setArcFitTolerance(const double &v);
    static const char *docArcFitTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalBSplineMaxDegree
    ///
    /// Maximum degree of B-splines made from external geometry in a new
    /// sketch. Copied into the sketch when it is created.
    static const long & getExternalBSplineMaxDegree();
    static const long & defaultExternalBSplineMaxDegree();
    static void removeExternalBSplineMaxDegree();
    static void setExternalBSplineMaxDegree(const long &v);
    static const char *docExternalBSplineMaxDegree();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalBSplineTolerance
    ///
    /// Tolerance of B-splines made from external geometry in a new
    /// sketch.0001. Copied into the sketch when it is created.
    static const double & getExternalBSplineTolerance();
    static const double & defaultExternalBSplineTolerance();
    static void removeExternalBSplineTolerance();
    static void setExternalBSplineTolerance(const double &v);
    static const char *docExternalBSplineTolerance();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MakeInternals
    ///
    /// Generate internal faces from the closed regions of a new sketch.
    /// Copied into the sketch's MakeInternals property when it is
    /// created.
    static const bool & getMakeInternals();
    static const bool & defaultMakeInternals();
    static void removeMakeInternals();
    static void setMakeInternals(const bool &v);
    static const char *docMakeInternals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LeaveSketchWithEscape
    ///
    /// Let the Esc key leave sketch edit mode. Takes effect the next time
    /// a sketch is edited.
    static const bool & getLeaveSketchWithEscape();
    static const bool & defaultLeaveSketchWithEscape();
    static void removeLeaveSketchWithEscape();
    static void setLeaveSketchWithEscape(const bool &v);
    static const char *docLeaveSketchWithEscape();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSolverAdvancedWidget
    ///
    /// Show the Advanced solver control section in the sketch task panel.
    /// Takes effect the next time a sketch is edited.
    static const bool & getShowSolverAdvancedWidget();
    static const bool & defaultShowSolverAdvancedWidget();
    static void removeShowSolverAdvancedWidget();
    static void setShowSolverAdvancedWidget(const bool &v);
    static const char *docShowSolverAdvancedWidget();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecalculateInitialSolutionWhileDragging
    ///
    /// Recalculate the solver's starting point while a point is dragged,
    /// which improves solving. Takes effect the next time a sketch is
    /// edited.
    static const bool & getRecalculateInitialSolutionWhileDragging();
    static const bool & defaultRecalculateInitialSolutionWhileDragging();
    static void removeRecalculateInitialSolutionWhileDragging();
    static void setRecalculateInitialSolutionWhileDragging(const bool &v);
    static const char *docRecalculateInitialSolutionWhileDragging();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExtendedConstraintInformation
    ///
    /// Show extended information for each entry of the constraint list.
    /// Applies at once.
    static const bool & getExtendedConstraintInformation();
    static const bool & defaultExtendedConstraintInformation();
    static void removeExtendedConstraintInformation();
    static void setExtendedConstraintInformation(const bool &v);
    static const char *docExtendedConstraintInformation();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideInternalAlignment
    ///
    /// Hide internal alignment constraints in the constraint list.
    /// Applies at once.
    static const bool & getHideInternalAlignment();
    static const bool & defaultHideInternalAlignment();
    static void removeHideInternalAlignment();
    static void setHideInternalAlignment(const bool &v);
    static const char *docHideInternalAlignment();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter VisualisationTrackingFilter
    ///
    /// Show in the 3D view only the constraints that pass the constraint
    /// list filter. Applies at once.
    static const bool & getVisualisationTrackingFilter();
    static const bool & defaultVisualisationTrackingFilter();
    static void removeVisualisationTrackingFilter();
    static void setVisualisationTrackingFilter(const bool &v);
    static const char *docVisualisationTrackingFilter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideUnits
    ///
    /// Hide the base length unit in dimension labels and cursor
    /// coordinates for unit systems that support it. Shown at the next
    /// redraw.
    static const bool & getHideUnits();
    static const bool & defaultHideUnits();
    static void removeHideUnits();
    static void setHideUnits(const bool &v);
    static const char *docHideUnits();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDimensionalName
    ///
    /// Show the name of a named dimensional constraint in its label,
    /// using the format string. Shown at the next redraw.
    static const bool & getShowDimensionalName();
    static const bool & defaultShowDimensionalName();
    static void removeShowDimensionalName();
    static void setShowDimensionalName(const bool &v);
    static const char *docShowDimensionalName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionalStringFormat
    ///
    /// Format of a named dimension's label: %N is the constraint name, %V
    /// its value. Shown at the next redraw.
    static const std::string & getDimensionalStringFormat();
    static const std::string & defaultDimensionalStringFormat();
    static void removeDimensionalStringFormat();
    static void setDimensionalStringFormat(const std::string &v);
    static const char *docDimensionalStringFormat();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowCursorCoords
    ///
    /// Show the coordinates next to the cursor while drawing in a sketch.
    /// Applies at once.
    static const bool & getShowCursorCoords();
    static const bool & defaultShowCursorCoords();
    static void removeShowCursorCoords();
    static void setShowCursorCoords(const bool &v);
    static const char *docShowCursorCoords();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseSystemDecimals
    ///
    /// Show cursor coordinates with the number of decimals of the unit
    /// settings instead of a short form. Applies at once.
    static const bool & getUseSystemDecimals();
    static const bool & defaultUseSystemDecimals();
    static void removeUseSystemDecimals();
    static void setUseSystemDecimals(const bool &v);
    static const char *docUseSystemDecimals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AllowFaceExternalPick
    ///
    /// Allow picking a face as external geometry. Set in the Edit
    /// controls of the sketch task panel; applies at once.
    static const bool & getAllowFaceExternalPick();
    static const bool & defaultAllowFaceExternalPick();
    static void removeAllowFaceExternalPick();
    static void setAllowFaceExternalPick(const bool &v);
    static const char *docAllowFaceExternalPick();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ViewBottomOnEdit
    ///
    /// Look at the sketch from below instead of from above when it is
    /// edited. Set by the view-sketch-from-bottom commands.
    static const bool & getViewBottomOnEdit();
    static const bool & defaultViewBottomOnEdit();
    static void removeViewBottomOnEdit();
    static void setViewBottomOnEdit(const bool &v);
    static const char *docViewBottomOnEdit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AdjustCamera
    ///
    /// Turn the camera to face the sketch plane when a sketch is opened
    /// for editing. Applies the next time a sketch is edited.
    static const bool & getAdjustCamera();
    static const bool & defaultAdjustCamera();
    static void removeAdjustCamera();
    static void setAdjustCamera(const bool &v);
    static const char *docAdjustCamera();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FitSketchOnEdit
    ///
    /// Fit the view to the sketch's geometry when it is opened for
    /// editing. Applies the next time a sketch is edited.
    static const bool & getFitSketchOnEdit();
    static const bool & defaultFitSketchOnEdit();
    static void removeFitSketchOnEdit();
    static void setFitSketchOnEdit(const bool &v);
    static const char *docFitSketchOnEdit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HideDependent
    ///
    /// Hide the objects that depend on a sketch while it is edited, for
    /// new sketches.
    static const bool & getHideDependent();
    static const bool & defaultHideDependent();
    static void removeHideDependent();
    static void setHideDependent(const bool &v);
    static const char *docHideDependent();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowLinks
    ///
    /// Keep the objects a sketch links to visible while it is edited, for
    /// new sketches.
    static const bool & getShowLinks();
    static const bool & defaultShowLinks();
    static void removeShowLinks();
    static void setShowLinks(const bool &v);
    static const char *docShowLinks();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowSupport
    ///
    /// Keep the object a sketch is attached to visible while it is
    /// edited, for new sketches.
    static const bool & getShowSupport();
    static const bool & defaultShowSupport();
    static void removeShowSupport();
    static void setShowSupport(const bool &v);
    static const char *docShowSupport();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RestoreCamera
    ///
    /// Put the camera back where it was when editing of a sketch ends,
    /// for new sketches.
    static const bool & getRestoreCamera();
    static const bool & defaultRestoreCamera();
    static void removeRestoreCamera();
    static void setRestoreCamera(const bool &v);
    static const char *docRestoreCamera();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ForceOrtho
    ///
    /// Switch the view to an orthographic camera while a sketch is
    /// edited, and back afterwards, for new sketches. Needs
    /// RestoreCamera.
    static const bool & getForceOrtho();
    static const bool & defaultForceOrtho();
    static void removeForceOrtho();
    static void setForceOrtho(const bool &v);
    static const char *docForceOrtho();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SectionView
    ///
    /// Clip everything in front of the sketch plane while a sketch is
    /// edited, for new sketches.
    static const bool & getSectionView();
    static const bool & defaultSectionView();
    static void removeSectionView();
    static void setSectionView(const bool &v);
    static const char *docSectionView();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoConstraints
    ///
    /// Suggest and apply automatic constraints while drawing, for new
    /// sketches.
    static const bool & getAutoConstraints();
    static const bool & defaultAutoConstraints();
    static void removeAutoConstraints();
    static void setAutoConstraints(const bool &v);
    static const char *docAutoConstraints();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AvoidRedundantAutoconstraints
    ///
    /// Do not create automatic constraints that would be redundant, for
    /// new sketches.
    static const bool & getAvoidRedundantAutoconstraints();
    static const bool & defaultAvoidRedundantAutoconstraints();
    static void removeAvoidRedundantAutoconstraints();
    static void setAvoidRedundantAutoconstraints(const bool &v);
    static const char *docAvoidRedundantAutoconstraints();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowOriginalColor
    ///
    /// Draw the sketch in its original colours instead of the constraint-
    /// status colours while editing. Applies at once.
    static const bool & getShowOriginalColor();
    static const bool & defaultShowOriginalColor();
    static void removeShowOriginalColor();
    static void setShowOriginalColor(const bool &v);
    static const char *docShowOriginalColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SketchAutoTransparentPick
    ///
    /// While picking external geometry, make objects transparent to
    /// picking so hidden edges can be chosen. Applies at once while the
    /// tool is active.
    static const bool & getSketchAutoTransparentPick();
    static const bool & defaultSketchAutoTransparentPick();
    static void removeSketchAutoTransparentPick();
    static void setSketchAutoTransparentPick(const bool &v);
    static const char *docSketchAutoTransparentPick();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ZHeight
    ///
    /// Height step between the drawing layers of a sketch in edit mode
    /// (lines, constraints, points). Raise it if elements flicker through
    /// each other. Applies at once.
    static const double & getZHeight();
    static const double & defaultZHeight();
    static void removeZHeight();
    static void setZHeight(const double &v);
    static const char *docZHeight();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisTransparency
    ///
    /// Transparency of the sketch axes in edit mode, in percent. 0 to
    /// 100. Applies at once.
    static const long & getAxisTransparency();
    static const long & defaultAxisTransparency();
    static void removeAxisTransparency();
    static void setAxisTransparency(const long &v);
    static const char *docAxisTransparency();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FaceColor
    ///
    /// Colour and opacity of the faces shown inside a sketch's closed
    /// regions. Applies at once to sketches that use automatic colours.
    static const unsigned long & getFaceColor();
    static const unsigned long & defaultFaceColor();
    static void removeFaceColor();
    static void setFaceColor(const unsigned long &v);
    static const char *docFaceColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowGrid
    ///
    /// Show a grid in new sketches while they are edited. An existing
    /// sketch keeps its own setting.
    static const bool & getShowGrid();
    static const bool & defaultShowGrid();
    static void removeShowGrid();
    static void setShowGrid(const bool &v);
    static const char *docShowGrid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridSize
    ///
    /// Distance in millimetres between two grid lines of a new sketch;
    /// with automatic spacing, the spacing it starts from. A sketch that
    /// exists keeps its own.
    static const double & getGridSize();
    static const double & defaultGridSize();
    static void removeGridSize();
    static void setGridSize(const double &v);
    static const char *docGridSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridAuto
    ///
    /// Let the grid spacing of new sketches adapt to the zoom level.
    static const bool & getGridAuto();
    static const bool & defaultGridAuto();
    static void removeGridAuto();
    static void setGridAuto(const bool &v);
    static const char *docGridAuto();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridSizePixelThreshold
    ///
    /// With auto spacing, the smallest distance in pixels between two
    /// grid lines before the grid switches to a coarser spacing. 3 to
    /// 10000. Applies at once.
    static const long & getGridSizePixelThreshold();
    static const long & defaultGridSizePixelThreshold();
    static void removeGridSizePixelThreshold();
    static void setGridSizePixelThreshold(const long &v);
    static const char *docGridSizePixelThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridNumberSubdivision
    ///
    /// Number of grid cells between two major (division) lines. 1 to
    /// 10000. Applies at once.
    static const long & getGridNumberSubdivision();
    static const long & defaultGridNumberSubdivision();
    static void removeGridNumberSubdivision();
    static void setGridNumberSubdivision(const long &v);
    static const char *docGridNumberSubdivision();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridLinePattern
    ///
    /// Line pattern of the minor grid lines, as a 16 bit stipple mask.
    /// Applies at once.
    static const long & getGridLinePattern();
    static const long & defaultGridLinePattern();
    static void removeGridLinePattern();
    static void setGridLinePattern(const long &v);
    static const char *docGridLinePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridDivLinePattern
    ///
    /// Line pattern of the major grid lines, as a 16 bit stipple mask.
    /// Applies at once.
    static const long & getGridDivLinePattern();
    static const long & defaultGridDivLinePattern();
    static void removeGridDivLinePattern();
    static void setGridDivLinePattern(const long &v);
    static const char *docGridDivLinePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridLineWidth
    ///
    /// Width of the minor grid lines in pixels. 1 to 99. Applies at once.
    static const long & getGridLineWidth();
    static const long & defaultGridLineWidth();
    static void removeGridLineWidth();
    static void setGridLineWidth(const long &v);
    static const char *docGridLineWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridDivLineWidth
    ///
    /// Width of the major grid lines in pixels. 1 to 99. Applies at once.
    static const long & getGridDivLineWidth();
    static const long & defaultGridDivLineWidth();
    static void removeGridDivLineWidth();
    static void setGridDivLineWidth(const long &v);
    static const char *docGridDivLineWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridLineColor
    ///
    /// Colour of the minor grid lines. Applies at once.
    static const unsigned long & getGridLineColor();
    static const unsigned long & defaultGridLineColor();
    static void removeGridLineColor();
    static void setGridLineColor(const unsigned long &v);
    static const char *docGridLineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridDivLineColor
    ///
    /// Colour of the major grid lines. Applies at once.
    static const unsigned long & getGridDivLineColor();
    static const unsigned long & defaultGridDivLineColor();
    static void removeGridDivLineColor();
    static void setGridDivLineColor(const unsigned long &v);
    static const char *docGridDivLineColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GridTransparency
    ///
    /// Transparency of the grid lines in percent, 0 is opaque. 0 to 100.
    /// Applies at once.
    static const long & getGridTransparency();
    static const long & defaultGridTransparency();
    static void removeGridTransparency();
    static void setGridTransparency(const long &v);
    static const char *docGridTransparency();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TopRenderGeometryId
    ///
    /// Which kind of geometry is drawn on top in sketch edit mode: 1
    /// normal, 2 construction, 3 external. Set by dragging in the
    /// Rendering order list; applies at once.
    static const long & getTopRenderGeometryId();
    static const long & defaultTopRenderGeometryId();
    static void removeTopRenderGeometryId();
    static void setTopRenderGeometryId(const long &v);
    static const char *docTopRenderGeometryId();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MidRenderGeometryId
    ///
    /// Which kind of geometry is drawn in the middle: 1 normal, 2
    /// construction, 3 external.
    static const long & getMidRenderGeometryId();
    static const long & defaultMidRenderGeometryId();
    static void removeMidRenderGeometryId();
    static void setMidRenderGeometryId(const long &v);
    static const char *docMidRenderGeometryId();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LowRenderGeometryId
    ///
    /// Which kind of geometry is drawn at the bottom: 1 normal, 2
    /// construction, 3 external.
    static const long & getLowRenderGeometryId();
    static const long & defaultLowRenderGeometryId();
    static void removeLowRenderGeometryId();
    static void setLowRenderGeometryId(const long &v);
    static const char *docLowRenderGeometryId();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BSplineExternalVisible
    ///
    /// Show the B-spline information overlays for external B-splines too.
    static const bool & getBSplineExternalVisible();
    static const bool & defaultBSplineExternalVisible();
    static void removeBSplineExternalVisible();
    static void setBSplineExternalVisible(const bool &v);
    static const char *docBSplineExternalVisible();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditDatumInPlace
    ///
    /// Edit a dimension's value in a field at its label instead of in a
    /// dialog. Applies to the next edit.
    static const bool & getEditDatumInPlace();
    static const bool & defaultEditDatumInPlace();
    static void removeEditDatumInPlace();
    static void setEditDatumInPlace(const bool &v);
    static const char *docEditDatumInPlace();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DatumEscapeTakesBack
    ///
    /// Esc cancels the dimension value being typed at a label instead of
    /// leaving the field with the value entered.
    static const bool & getDatumEscapeTakesBack();
    static const bool & defaultDatumEscapeTakesBack();
    static void removeDatumEscapeTakesBack();
    static void setDatumEscapeTakesBack(const bool &v);
    static const char *docDatumEscapeTakesBack();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowDirectionalAutoConstraintHints
    ///
    /// Show helper lines for direction based automatic constraints (line
    /// extension, parallel, perpendicular) while drawing. Applies at
    /// once.
    static const bool & getShowDirectionalAutoConstraintHints();
    static const bool & defaultShowDirectionalAutoConstraintHints();
    static void removeShowDirectionalAutoConstraintHints();
    static void setShowDirectionalAutoConstraintHints(const bool &v);
    static const char *docShowDirectionalAutoConstraintHints();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DragAutoConstraintDelay
    ///
    /// Time in milliseconds the pointer must rest while dragging before
    /// an automatic constraint is offered. 0 to 5000.
    static const long & getDragAutoConstraintDelay();
    static const long & defaultDragAutoConstraintDelay();
    static void removeDragAutoConstraintDelay();
    static void setDragAutoConstraintDelay(const long &v);
    static const char *docDragAutoConstraintDelay();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NotifyConstraintSubstitutions
    ///
    /// Show a message when the Sketcher replaces constraints
    /// automatically, for example a coincident and a tangent by an
    /// endpoint tangency.
    static const bool & getNotifyConstraintSubstitutions();
    static const bool & defaultNotifyConstraintSubstitutions();
    static void removeNotifyConstraintSubstitutions();
    static void setNotifyConstraintSubstitutions(const bool &v);
    static const char *docNotifyConstraintSubstitutions();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgeWidth
    ///
    /// Line width of normal geometry in edit mode, in pixels. 1 to 99.
    /// Applies at once.
    static const long & getEdgeWidth();
    static const long & defaultEdgeWidth();
    static void removeEdgeWidth();
    static void setEdgeWidth(const long &v);
    static const char *docEdgeWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EdgePattern
    ///
    /// Line pattern of normal geometry in edit mode, a 16 bit stipple
    /// mask.
    static const long & getEdgePattern();
    static const long & defaultEdgePattern();
    static void removeEdgePattern();
    static void setEdgePattern(const long &v);
    static const char *docEdgePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstructionWidth
    ///
    /// Line width of construction geometry in edit mode, in pixels.
    static const long & getConstructionWidth();
    static const long & defaultConstructionWidth();
    static void removeConstructionWidth();
    static void setConstructionWidth(const long &v);
    static const char *docConstructionWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstructionPattern
    ///
    /// Line pattern of construction geometry in edit mode.
    static const long & getConstructionPattern();
    static const long & defaultConstructionPattern();
    static void removeConstructionPattern();
    static void setConstructionPattern(const long &v);
    static const char *docConstructionPattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InternalWidth
    ///
    /// Line width of internal alignment geometry in edit mode, in pixels.
    static const long & getInternalWidth();
    static const long & defaultInternalWidth();
    static void removeInternalWidth();
    static void setInternalWidth(const long &v);
    static const char *docInternalWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InternalPattern
    ///
    /// Line pattern of internal alignment geometry in edit mode.
    static const long & getInternalPattern();
    static const long & defaultInternalPattern();
    static void removeInternalPattern();
    static void setInternalPattern(const long &v);
    static const char *docInternalPattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalWidth
    ///
    /// Line width of external geometry in edit mode, in pixels.
    static const long & getExternalWidth();
    static const long & defaultExternalWidth();
    static void removeExternalWidth();
    static void setExternalWidth(const long &v);
    static const char *docExternalWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalPattern
    ///
    /// Line pattern of external geometry in edit mode.
    static const long & getExternalPattern();
    static const long & defaultExternalPattern();
    static void removeExternalPattern();
    static void setExternalPattern(const long &v);
    static const char *docExternalPattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalDefiningWidth
    ///
    /// Line width of defining external geometry in edit mode, in pixels.
    static const long & getExternalDefiningWidth();
    static const long & defaultExternalDefiningWidth();
    static void removeExternalDefiningWidth();
    static void setExternalDefiningWidth(const long &v);
    static const char *docExternalDefiningWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalDefiningPattern
    ///
    /// Line pattern of defining external geometry in edit mode.
    static const long & getExternalDefiningPattern();
    static const long & defaultExternalDefiningPattern();
    static void removeExternalDefiningPattern();
    static void setExternalDefiningPattern(const long &v);
    static const char *docExternalDefiningPattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InformationWidth
    ///
    /// Line width of the information layer (B-spline polygons, combs,
    /// hints), in pixels.
    static const long & getInformationWidth();
    static const long & defaultInformationWidth();
    static void removeInformationWidth();
    static void setInformationWidth(const long &v);
    static const char *docInformationWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InformationPattern
    ///
    /// Line pattern of the information layer.
    static const long & getInformationPattern();
    static const long & defaultInformationPattern();
    static void removeInformationPattern();
    static void setInformationPattern(const long &v);
    static const char *docInformationPattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionalConstraintLineWidth
    ///
    /// Line width of dimensional constraints, in pixels. 1 to 4.
    static const long & getDimensionalConstraintLineWidth();
    static const long & defaultDimensionalConstraintLineWidth();
    static void removeDimensionalConstraintLineWidth();
    static void setDimensionalConstraintLineWidth(const long &v);
    static const char *docDimensionalConstraintLineWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensionalConstraintLinePattern
    ///
    /// Line pattern of dimensional constraints.
    static const long & getDimensionalConstraintLinePattern();
    static const long & defaultDimensionalConstraintLinePattern();
    static void removeDimensionalConstraintLinePattern();
    static void setDimensionalConstraintLinePattern(const long &v);
    static const char *docDimensionalConstraintLinePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisLineWidth
    ///
    /// Line width of the sketch axes in edit mode, in pixels.
    static const long & getAxisLineWidth();
    static const long & defaultAxisLineWidth();
    static void removeAxisLineWidth();
    static void setAxisLineWidth(const long &v);
    static const char *docAxisLineWidth();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AxisLinePattern
    ///
    /// Line pattern of the sketch axes in edit mode.
    static const long & getAxisLinePattern();
    static const long & defaultAxisLinePattern();
    static void removeAxisLinePattern();
    static void setAxisLinePattern(const long &v);
    static const char *docAxisLinePattern();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SingleDimensioningTool
    ///
    /// Put the single Dimension tool on the Sketcher tool bar. Together
    /// with the separated tools option this gives the modes Single tool,
    /// Separated tools, Both. Tool bars are rebuilt when the page is
    /// saved.
    static const bool & getSingleDimensioningTool();
    static const bool & defaultSingleDimensioningTool();
    static void removeSingleDimensioningTool();
    static void setSingleDimensioningTool(const bool &v);
    static const char *docSingleDimensioningTool();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SeparatedDimensioningTools
    ///
    /// Put the separate dimension tools (horizontal, vertical, distance,
    /// radius/diameter, angle, lock) on the Sketcher tool bar.
    static const bool & getSeparatedDimensioningTools();
    static const bool & defaultSeparatedDimensioningTools();
    static void removeSeparatedDimensioningTools();
    static void setSeparatedDimensioningTools(const bool &v);
    static const char *docSeparatedDimensioningTools();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensioningDiameter
    ///
    /// Let the Dimension tool create diameters. With radius also on the
    /// tool picks: diameter for circles, radius for arcs.
    static const bool & getDimensioningDiameter();
    static const bool & defaultDimensioningDiameter();
    static void removeDimensioningDiameter();
    static void setDimensioningDiameter(const bool &v);
    static const char *docDimensioningDiameter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DimensioningRadius
    ///
    /// Let the Dimension tool create radii. With diameter also on the
    /// tool picks: diameter for circles, radius for arcs.
    static const bool & getDimensioningRadius();
    static const bool & defaultDimensioningRadius();
    static void removeDimensioningRadius();
    static void setDimensioningRadius(const bool &v);
    static const char *docDimensioningRadius();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoScaleMode
    ///
    /// Scale the whole sketch to the value of its first dimension: 0
    /// always, 1 never, 2 only when no feature that fixes the scale is
    /// visible. Applies to the next dimension.
    static const long & getAutoScaleMode();
    static const long & defaultAutoScaleMode();
    static void removeAutoScaleMode();
    static void setAutoScaleMode(const long &v);
    static const char *docAutoScaleMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OnViewParameterVisibility
    ///
    /// Which on-view parameters a drawing tool shows at the cursor: 0
    /// none, 1 dimensions only, 2 position and dimensions. Applies to the
    /// next tool started.
    static const long & getOnViewParameterVisibility();
    static const long & defaultOnViewParameterVisibility();
    static void removeOnViewParameterVisibility();
    static void setOnViewParameterVisibility(const long &v);
    static const char *docOnViewParameterVisibility();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UnifiedCoincident
    ///
    /// Use one tool for coincident and point-on-object constraints. Tool
    /// bars and menus follow when the page is saved; the shortcuts follow
    /// after a restart.
    static const bool & getUnifiedCoincident();
    static const bool & defaultUnifiedCoincident();
    static void removeUnifiedCoincident();
    static void setUnifiedCoincident(const bool &v);
    static const char *docUnifiedCoincident();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoHorVer
    ///
    /// Use one tool that chooses between a horizontal and a vertical
    /// constraint. Tool bars follow when the page is saved.
    static const bool & getAutoHorVer();
    static const bool & defaultAutoHorVer();
    static void removeAutoHorVer();
    static void setAutoHorVer(const bool &v);
    static const char *docAutoHorVer();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UnifiedLineCommands
    ///
    /// Group the polyline and line commands under one tool bar button.
    /// Tool bars follow when the page is saved.
    static const bool & getUnifiedLineCommands();
    static const bool & defaultUnifiedLineCommands();
    static void removeUnifiedLineCommands();
    static void setUnifiedLineCommands(const bool &v);
    static const char *docUnifiedLineCommands();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Snap
    ///
    /// Master switch for snapping in sketch edit mode. Toggled by the
    /// Snap tool bar button; applies at once.
    static const bool & getSnap();
    static const bool & defaultSnap();
    static void removeSnap();
    static void setSnap(const bool &v);
    static const char *docSnap();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SnapToObjects
    ///
    /// Snap new points to the preselected object, and to the middle of
    /// lines and arcs. Applies at once.
    static const bool & getSnapToObjects();
    static const bool & defaultSnapToObjects();
    static void removeSnapToObjects();
    static void setSnapToObjects(const bool &v);
    static const char *docSnapToObjects();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SnapToGrid
    ///
    /// Snap new points to the nearest grid line when closer than a fifth
    /// of the grid spacing. Applies at once.
    static const bool & getSnapToGrid();
    static const bool & defaultSnapToGrid();
    static void removeSnapToGrid();
    static void setSnapToGrid(const bool &v);
    static const char *docSnapToGrid();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SnapAngle
    ///
    /// Angular step in degrees for tools that snap at an angle while Ctrl
    /// is held, measured from the sketch's positive X axis. Applies at
    /// once.
    static const double & getSnapAngle();
    static const double & defaultSnapAngle();
    static void removeSnapAngle();
    static void setSnapAngle(const double &v);
    static const char *docSnapAngle();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ElementIconSize
    ///
    /// Size in pixels of the icons in the element list of the sketch task
    /// panel. 16 to 128. Takes effect the next time a sketch is edited.
    static const long & getElementIconSize();
    static const long & defaultElementIconSize();
    static void removeElementIconSize();
    static void setElementIconSize(const long &v);
    static const char *docElementIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditSketcherFontName
    ///
    /// Font family of the dimension labels in sketch edit mode. Empty
    /// means the labels' own font. Applies at once.
    static const std::string & getEditSketcherFontName();
    static const std::string & defaultEditSketcherFontName();
    static void removeEditSketcherFontName();
    static void setEditSketcherFontName(const std::string &v);
    static const char *docEditSketcherFontName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstraintIconLabelsPerLine
    ///
    /// How many constraint numbers fit on one line of the label beside a
    /// combined constraint icon, 1 to 100.
    static const long & getConstraintIconLabelsPerLine();
    static const long & defaultConstraintIconLabelsPerLine();
    static void removeConstraintIconLabelsPerLine();
    static void setConstraintIconLabelsPerLine(const long &v);
    static const char *docConstraintIconLabelsPerLine();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstraintIconLabelLines
    ///
    /// Largest number of lines of the label beside a combined constraint
    /// icon, 1 to 100.
    static const long & getConstraintIconLabelLines();
    static const long & defaultConstraintIconLabelLines();
    static void removeConstraintIconLabelLines();
    static void setConstraintIconLabelLines(const long &v);
    static const char *docConstraintIconLabelLines();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ViewScalingFactor
    ///
    /// Scale factor of the fixed pixel sizes of sketch edit mode (points,
    /// constraint lines), 0.5 to 5. Applies at once.
    static const double & getViewScalingFactor();
    static const double & defaultViewScalingFactor();
    static void removeViewScalingFactor();
    static void setViewScalingFactor(const double &v);
    static const char *docViewScalingFactor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SegmentsPerGeometry
    ///
    /// Number of straight segments a curve is drawn with in sketch edit
    /// mode. Applies at once.
    static const long & getSegmentsPerGeometry();
    static const long & defaultSegmentsPerGeometry();
    static void removeSegmentsPerGeometry();
    static void setSegmentsPerGeometry(const long &v);
    static const char *docSegmentsPerGeometry();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CursorTextColor
    ///
    /// Colour of the coordinate text shown at the cursor in sketch edit
    /// mode. Takes effect the next time a sketch is edited.
    static const unsigned long & getCursorTextColor();
    static const unsigned long & defaultCursorTextColor();
    static void removeCursorTextColor();
    static void setCursorTextColor(const unsigned long &v);
    static const char *docCursorTextColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SketchEdgeColor
    ///
    /// Colour of a sketch's edges outside edit mode, for sketches that
    /// use automatic colours. Applies at once.
    static const unsigned long & getSketchEdgeColor();
    static const unsigned long & defaultSketchEdgeColor();
    static void removeSketchEdgeColor();
    static void setSketchEdgeColor(const unsigned long &v);
    static const char *docSketchEdgeColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SketchVertexColor
    ///
    /// Colour of a sketch's vertices outside edit mode, for sketches that
    /// use automatic colours. Applies at once.
    static const unsigned long & getSketchVertexColor();
    static const unsigned long & defaultSketchVertexColor();
    static void removeSketchVertexColor();
    static void setSketchVertexColor(const unsigned long &v);
    static const char *docSketchVertexColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EditedEdgeColor
    ///
    /// Colour of normal geometry in sketch edit mode. Applies at once.
    static const unsigned long & getEditedEdgeColor();
    static const unsigned long & defaultEditedEdgeColor();
    static void removeEditedEdgeColor();
    static void setEditedEdgeColor(const unsigned long &v);
    static const char *docEditedEdgeColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstructionColor
    ///
    /// Colour of construction geometry in sketch edit mode. Applies at
    /// once.
    static const unsigned long & getConstructionColor();
    static const unsigned long & defaultConstructionColor();
    static void removeConstructionColor();
    static void setConstructionColor(const unsigned long &v);
    static const char *docConstructionColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InternalAlignedGeoColor
    ///
    /// Colour of internal alignment geometry in sketch edit mode. Applies
    /// at once.
    static const unsigned long & getInternalAlignedGeoColor();
    static const unsigned long & defaultInternalAlignedGeoColor();
    static void removeInternalAlignedGeoColor();
    static void setInternalAlignedGeoColor(const unsigned long &v);
    static const char *docInternalAlignedGeoColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FullyConstraintElementColor
    ///
    /// Colour of a fully constrained element of normal geometry in sketch
    /// edit mode. Applies at once.
    static const unsigned long & getFullyConstraintElementColor();
    static const unsigned long & defaultFullyConstraintElementColor();
    static void removeFullyConstraintElementColor();
    static void setFullyConstraintElementColor(const unsigned long &v);
    static const char *docFullyConstraintElementColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FullyConstraintConstructionElementColor
    ///
    /// Colour of a fully constrained element of construction geometry in
    /// sketch edit mode. Applies at once.
    static const unsigned long & getFullyConstraintConstructionElementColor();
    static const unsigned long & defaultFullyConstraintConstructionElementColor();
    static void removeFullyConstraintConstructionElementColor();
    static void setFullyConstraintConstructionElementColor(const unsigned long &v);
    static const char *docFullyConstraintConstructionElementColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FullyConstraintInternalAlignmentColor
    ///
    /// Colour of a fully constrained element of internal alignment
    /// geometry in sketch edit mode. Applies at once.
    static const unsigned long & getFullyConstraintInternalAlignmentColor();
    static const unsigned long & defaultFullyConstraintInternalAlignmentColor();
    static void removeFullyConstraintInternalAlignmentColor();
    static void setFullyConstraintInternalAlignmentColor(const unsigned long &v);
    static const char *docFullyConstraintInternalAlignmentColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InvalidSketchColor
    ///
    /// Colour of the geometry of a sketch with conflicting or redundant
    /// constraints in sketch edit mode. Applies at once.
    static const unsigned long & getInvalidSketchColor();
    static const unsigned long & defaultInvalidSketchColor();
    static void removeInvalidSketchColor();
    static void setInvalidSketchColor(const unsigned long &v);
    static const char *docInvalidSketchColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FullyConstrainedColor
    ///
    /// Colour of the geometry of a fully constrained sketch in sketch
    /// edit mode. Applies at once.
    static const unsigned long & getFullyConstrainedColor();
    static const unsigned long & defaultFullyConstrainedColor();
    static void removeFullyConstrainedColor();
    static void setFullyConstrainedColor(const unsigned long &v);
    static const char *docFullyConstrainedColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstrainedDimColor
    ///
    /// Colour of dimensional constraints in sketch edit mode. Applies at
    /// once.
    static const unsigned long & getConstrainedDimColor();
    static const unsigned long & defaultConstrainedDimColor();
    static void removeConstrainedDimColor();
    static void setConstrainedDimColor(const unsigned long &v);
    static const char *docConstrainedDimColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ConstrainedIcoColor
    ///
    /// Colour of constraint symbols in sketch edit mode. Applies at once.
    static const unsigned long & getConstrainedIcoColor();
    static const unsigned long & defaultConstrainedIcoColor();
    static void removeConstrainedIcoColor();
    static void setConstrainedIcoColor(const unsigned long &v);
    static const char *docConstrainedIcoColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NonDrivingConstrDimColor
    ///
    /// Colour of reference (non-driving) dimensional constraints in
    /// sketch edit mode. Applies at once.
    static const unsigned long & getNonDrivingConstrDimColor();
    static const unsigned long & defaultNonDrivingConstrDimColor();
    static void removeNonDrivingConstrDimColor();
    static void setNonDrivingConstrDimColor(const unsigned long &v);
    static const char *docNonDrivingConstrDimColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExprBasedConstrDimColor
    ///
    /// Colour of dimensional constraints whose value is an expression in
    /// sketch edit mode. Applies at once.
    static const unsigned long & getExprBasedConstrDimColor();
    static const unsigned long & defaultExprBasedConstrDimColor();
    static void removeExprBasedConstrDimColor();
    static void setExprBasedConstrDimColor(const unsigned long &v);
    static const char *docExprBasedConstrDimColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DeactivatedConstrDimColor
    ///
    /// Colour of deactivated constraints in sketch edit mode. Applies at
    /// once.
    static const unsigned long & getDeactivatedConstrDimColor();
    static const unsigned long & defaultDeactivatedConstrDimColor();
    static void removeDeactivatedConstrDimColor();
    static void setDeactivatedConstrDimColor(const unsigned long &v);
    static const char *docDeactivatedConstrDimColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalColor
    ///
    /// Colour of external geometry in sketch edit mode. Applies at once.
    static const unsigned long & getExternalColor();
    static const unsigned long & defaultExternalColor();
    static void removeExternalColor();
    static void setExternalColor(const unsigned long &v);
    static const char *docExternalColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ExternalDefiningColor
    ///
    /// Colour of defining external geometry in sketch edit mode. Applies
    /// at once.
    static const unsigned long & getExternalDefiningColor();
    static const unsigned long & defaultExternalDefiningColor();
    static void removeExternalDefiningColor();
    static void setExternalDefiningColor(const unsigned long &v);
    static const char *docExternalDefiningColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InformationColor
    ///
    /// Colour of the information layer -- B-spline polygons, combs, hints
    /// -- in sketch edit mode. Applies at once.
    static const unsigned long & getInformationColor();
    static const unsigned long & defaultInformationColor();
    static void removeInformationColor();
    static void setInformationColor(const unsigned long &v);
    static const char *docInformationColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FrozenColor
    ///
    /// Colour of frozen external geometry in sketch edit mode. Applies at
    /// once.
    static const unsigned long & getFrozenColor();
    static const unsigned long & defaultFrozenColor();
    static void removeFrozenColor();
    static void setFrozenColor(const unsigned long &v);
    static const char *docFrozenColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DetachedColor
    ///
    /// Colour of detached external geometry in sketch edit mode. Applies
    /// at once.
    static const unsigned long & getDetachedColor();
    static const unsigned long & defaultDetachedColor();
    static void removeDetachedColor();
    static void setDetachedColor(const unsigned long &v);
    static const char *docDetachedColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MissingColor
    ///
    /// Colour of external geometry whose source is missing in sketch edit
    /// mode. Applies at once.
    static const unsigned long & getMissingColor();
    static const unsigned long & defaultMissingColor();
    static void removeMissingColor();
    static void setMissingColor(const unsigned long &v);
    static const char *docMissingColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultSolver
    ///
    /// Algorithm a sketch is solved with: 0 BFGS, 1 Levenberg-Marquardt,
    /// 2 DogLeg. Used at the next solve.
    static const long & getDefaultSolver();
    static const long & defaultDefaultSolver();
    static void removeDefaultSolver();
    static void setDefaultSolver(const long &v);
    static const char *docDefaultSolver();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DogLegGaussStep
    ///
    /// Gauss step of the DogLeg solver: 0 FullPivLU, 1
    /// LeastNormFullPivLU, 2 LeastNormLdlt.
    static const long & getDogLegGaussStep();
    static const long & defaultDogLegGaussStep();
    static void removeDogLegGaussStep();
    static void setDogLegGaussStep(const long &v);
    static const char *docDogLegGaussStep();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxIter
    ///
    /// Largest number of iterations of the sketch solver, up to 999.
    static const long & getMaxIter();
    static const long & defaultMaxIter();
    static void removeMaxIter();
    static void setMaxIter(const long &v);
    static const char *docMaxIter();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SketchSizeMultiplier
    ///
    /// Multiply the iteration limit of the sketch solver by the number of
    /// parameters of the sketch.
    static const bool & getSketchSizeMultiplier();
    static const bool & defaultSketchSizeMultiplier();
    static void removeSketchSizeMultiplier();
    static void setSketchSizeMultiplier(const bool &v);
    static const char *docSketchSizeMultiplier();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Convergence
    ///
    /// Squared error below which a solution of the sketch solver counts
    /// as converged. Text, read as a number.
    static const std::string & getConvergence();
    static const std::string & defaultConvergence();
    static void removeConvergence();
    static void setConvergence(const std::string &v);
    static const char *docConvergence();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter QRMethod
    ///
    /// QR decomposition used to diagnose a sketch: 0 dense, 1 sparse.
    static const long & getQRMethod();
    static const long & defaultQRMethod();
    static void removeQRMethod();
    static void setQRMethod(const long &v);
    static const char *docQRMethod();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter QRPivotThreshold
    ///
    /// Values below this are taken for zero while a sketch is diagnosed
    /// by QR decomposition. Text, read as a number.
    static const std::string & getQRPivotThreshold();
    static const std::string & defaultQRPivotThreshold();
    static void removeQRPivotThreshold();
    static void setQRPivotThreshold(const std::string &v);
    static const char *docQRPivotThreshold();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedundantDefaultSolver
    ///
    /// Algorithm used to find redundant constraints: 0 BFGS, 1 Levenberg-
    /// Marquardt, 2 DogLeg.
    static const long & getRedundantDefaultSolver();
    static const long & defaultRedundantDefaultSolver();
    static void removeRedundantDefaultSolver();
    static void setRedundantDefaultSolver(const long &v);
    static const char *docRedundantDefaultSolver();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedundantSolverMaxIterations
    ///
    /// Largest number of iterations of the solver that finds redundant
    /// constraints, up to 999.
    static const long & getRedundantSolverMaxIterations();
    static const long & defaultRedundantSolverMaxIterations();
    static void removeRedundantSolverMaxIterations();
    static void setRedundantSolverMaxIterations(const long &v);
    static const char *docRedundantSolverMaxIterations();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedundantSketchSizeMultiplier
    ///
    /// Multiply the iteration limit of the solver that finds redundant
    /// constraints by the number of parameters of the sketch.
    static const bool & getRedundantSketchSizeMultiplier();
    static const bool & defaultRedundantSketchSizeMultiplier();
    static void removeRedundantSketchSizeMultiplier();
    static void setRedundantSketchSizeMultiplier(const bool &v);
    static const char *docRedundantSketchSizeMultiplier();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RedundantConvergence
    ///
    /// Squared error below which a solution counts as converged, for the
    /// solver that finds redundant constraints. Text, read as a number.
    static const std::string & getRedundantConvergence();
    static const std::string & defaultRedundantConvergence();
    static void removeRedundantConvergence();
    static void setRedundantConvergence(const std::string &v);
    static const char *docRedundantConvergence();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DebugMode
    ///
    /// Messages of the sketch solver in the report view: 0 none, 1
    /// minimal, 2 at every iteration.
    static const long & getDebugMode();
    static const long & defaultDebugMode();
    static void removeDebugMode();
    static void setDebugMode(const long &v);
    static const char *docDebugMode();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LM_eps
    ///
    /// Tolerance eps of the Levenberg-Marquardt solver. Text, read as a
    /// number.
    static const std::string & getLM_eps();
    static const std::string & defaultLM_eps();
    static void removeLM_eps();
    static void setLM_eps(const std::string &v);
    static const char *docLM_eps();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LM_eps1
    ///
    /// Tolerance eps1 of the Levenberg-Marquardt solver. Text, read as a
    /// number.
    static const std::string & getLM_eps1();
    static const std::string & defaultLM_eps1();
    static void removeLM_eps1();
    static void setLM_eps1(const std::string &v);
    static const char *docLM_eps1();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter LM_tau
    ///
    /// Factor tau of the Levenberg-Marquardt solver. Text, read as a
    /// number.
    static const std::string & getLM_tau();
    static const std::string & defaultLM_tau();
    static void removeLM_tau();
    static void setLM_tau(const std::string &v);
    static const char *docLM_tau();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DL_tolg
    ///
    /// Tolerance tolg of the DogLeg solver. Text, read as a number.
    static const std::string & getDL_tolg();
    static const std::string & defaultDL_tolg();
    static void removeDL_tolg();
    static void setDL_tolg(const std::string &v);
    static const char *docDL_tolg();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DL_tolx
    ///
    /// Tolerance tolx of the DogLeg solver. Text, read as a number.
    static const std::string & getDL_tolx();
    static const std::string & defaultDL_tolx();
    static void removeDL_tolx();
    static void setDL_tolx(const std::string &v);
    static const char *docDL_tolx();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DL_tolf
    ///
    /// Tolerance tolf of the DogLeg solver. Text, read as a number.
    static const std::string & getDL_tolf();
    static const std::string & defaultDL_tolf();
    static void removeDL_tolf();
    static void setDL_tolf(const std::string &v);
    static const char *docDL_tolf();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_LM_eps
    ///
    /// Tolerance eps of Levenberg-Marquardt when it looks for redundant
    /// constraints. Text, read as a number.
    static const std::string & getRedundant_LM_eps();
    static const std::string & defaultRedundant_LM_eps();
    static void removeRedundant_LM_eps();
    static void setRedundant_LM_eps(const std::string &v);
    static const char *docRedundant_LM_eps();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_LM_eps1
    ///
    /// Tolerance eps1 of Levenberg-Marquardt when it looks for redundant
    /// constraints. Text, read as a number.
    static const std::string & getRedundant_LM_eps1();
    static const std::string & defaultRedundant_LM_eps1();
    static void removeRedundant_LM_eps1();
    static void setRedundant_LM_eps1(const std::string &v);
    static const char *docRedundant_LM_eps1();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_LM_tau
    ///
    /// Factor tau of Levenberg-Marquardt when it looks for redundant
    /// constraints. Text, read as a number.
    static const std::string & getRedundant_LM_tau();
    static const std::string & defaultRedundant_LM_tau();
    static void removeRedundant_LM_tau();
    static void setRedundant_LM_tau(const std::string &v);
    static const char *docRedundant_LM_tau();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_DL_tolg
    ///
    /// Tolerance tolg of DogLeg when it looks for redundant constraints.
    /// Text, read as a number.
    static const std::string & getRedundant_DL_tolg();
    static const std::string & defaultRedundant_DL_tolg();
    static void removeRedundant_DL_tolg();
    static void setRedundant_DL_tolg(const std::string &v);
    static const char *docRedundant_DL_tolg();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_DL_tolx
    ///
    /// Tolerance tolx of DogLeg when it looks for redundant constraints.
    /// Text, read as a number.
    static const std::string & getRedundant_DL_tolx();
    static const std::string & defaultRedundant_DL_tolx();
    static void removeRedundant_DL_tolx();
    static void setRedundant_DL_tolx(const std::string &v);
    static const char *docRedundant_DL_tolx();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Redundant_DL_tolf
    ///
    /// Tolerance tolf of DogLeg when it looks for redundant constraints.
    /// Text, read as a number.
    static const std::string & getRedundant_DL_tolf();
    static const std::string & defaultRedundant_DL_tolf();
    static void removeRedundant_DL_tolf();
    static void setRedundant_DL_tolf(const std::string &v);
    static const char *docRedundant_DL_tolf();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ParameterQRKeepsColumnOrder
    ///
    /// Keep the order of the columns when a sketch's parameters are
    /// diagnosed by QR decomposition. For comparing results.
    static const bool & getParameterQRKeepsColumnOrder();
    static const bool & defaultParameterQRKeepsColumnOrder();
    static void removeParameterQRKeepsColumnOrder();
    static void setParameterQRKeepsColumnOrder(const bool &v);
    static const char *docParameterQRKeepsColumnOrder();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SkipUnneededConstraintQR
    ///
    /// Skip the QR decomposition of the constraints when a sketch is
    /// diagnosed and it is not needed. For comparing results.
    static const bool & getSkipUnneededConstraintQR();
    static const bool & defaultSkipUnneededConstraintQR();
    static void removeSkipUnneededConstraintQR();
    static void setSkipUnneededConstraintQR(const bool &v);
    static const char *docSkipUnneededConstraintQR();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FillJacobianFromConstraintParams
    ///
    /// Fill the Jacobian of a sketch from the parameters each constraint
    /// names instead of from all of them. For comparing results.
    static const bool & getFillJacobianFromConstraintParams();
    static const bool & defaultFillJacobianFromConstraintParams();
    static void removeFillJacobianFromConstraintParams();
    static void setFillJacobianFromConstraintParams(const bool &v);
    static const char *docFillJacobianFromConstraintParams();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class SketcherParams
} // namespace Sketcher
//[[[end]]]

#endif // SKETCHER_APP_PARAMS_H
