/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef START_APP_PARAMS_H
#define START_APP_PARAMS_H

#include <Mod/Start/StartGlobal.h>

/*[[[cog
import StartParams
StartParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Start {
/** Convenient class to obtain the settings of the Start page

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Start"
 *
 * This class is auto generated by Mod/Start/App/StartParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Start/App/StartParams.h Mod/Start/App/StartParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Start/App/StartParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Start/App/StartParams.cpp with
 * the following signature.
 * @code
 *     void StartParams:on<parameter_name>Changed()
 * @endcode
 */
class StartExport StartParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ShowOnStartup
    ///
    /// Opens the Start page when FreeCAD starts. Takes effect at the next
    /// start.
    static const bool & getShowOnStartup();
    static const bool & defaultShowOnStartup();
    static void removeShowOnStartup();
    static void setShowOnStartup(const bool &v);
    static const char *docShowOnStartup();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoloadModule
    ///
    /// Workbench activated after Empty file or Open File is used on the
    /// Start page; $LastModule means the workbench used last, empty
    /// leaves the workbench as it is. Takes effect at the next use.
    static const std::string & getAutoloadModule();
    static const std::string & defaultAutoloadModule();
    static void removeAutoloadModule();
    static void setAutoloadModule(const std::string &v);
    static const char *docAutoloadModule();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter closeStart
    ///
    /// Closes the Start page after a document has been created or opened
    /// from it. Takes effect at the next use.
    static const bool & getcloseStart();
    static const bool & defaultcloseStart();
    static void removecloseStart();
    static void setcloseStart(const bool &v);
    static const char *doccloseStart();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileThumbnailIconsSize
    ///
    /// Size in pixels of the file thumbnails on the Start page. Takes
    /// effect at the next repaint of the page.
    static const long & getFileThumbnailIconsSize();
    static const long & defaultFileThumbnailIconsSize();
    static void removeFileThumbnailIconsSize();
    static void setFileThumbnailIconsSize(const long &v);
    static const char *docFileThumbnailIconsSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardSpacing
    ///
    /// Spacing in pixels between the file cards of the Start page. The
    /// file lists follow at the next layout. The New File cards and the
    /// page layout read the same key, with a spacing of their own while
    /// it is not stored.
    static const long & getFileCardSpacing();
    static const long & defaultFileCardSpacing();
    static void removeFileCardSpacing();
    static void setFileCardSpacing(const long &v);
    static const char *docFileCardSpacing();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NewFileIconSize
    ///
    /// Size in pixels of the icons on the New File cards of the Start
    /// page. Takes effect when the Start page is next created.
    static const long & getNewFileIconSize();
    static const long & defaultNewFileIconSize();
    static void removeNewFileIconSize();
    static void setNewFileIconSize(const long &v);
    static const char *docNewFileIconSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardLabelWith
    ///
    /// Width in pixels reserved for the text of a New File card on the
    /// Start page. Takes effect when the Start page is next created.
    static const long & getFileCardLabelWith();
    static const long & defaultFileCardLabelWith();
    static void removeFileCardLabelWith();
    static void setFileCardLabelWith(const long &v);
    static const char *docFileCardLabelWith();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardDescriptionLines
    ///
    /// Number of lines the description of a New File card may wrap to
    /// before it is cut short. Takes effect when the Start page is next
    /// created.
    static const long & getFileCardDescriptionLines();
    static const long & defaultFileCardDescriptionLines();
    static void removeFileCardDescriptionLines();
    static void setFileCardDescriptionLines(const long &v);
    static const char *docFileCardDescriptionLines();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardUseStyleSheet
    ///
    /// Gives the New File cards of the Start page their own colours while
    /// no theme style sheet is loaded. When off, the cards are drawn as
    /// ordinary buttons. Takes effect at the next style change or when
    /// the Start page is next created.
    static const bool & getFileCardUseStyleSheet();
    static const bool & defaultFileCardUseStyleSheet();
    static void removeFileCardUseStyleSheet();
    static void setFileCardUseStyleSheet(const bool &v);
    static const char *docFileCardUseStyleSheet();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardBackgroundColor
    ///
    /// Background colour of the New File cards on the Start page. Only
    /// used while no style sheet is loaded. Takes effect at the next
    /// style change or when the Start page is next created.
    static const unsigned long & getFileCardBackgroundColor();
    static const unsigned long & defaultFileCardBackgroundColor();
    static void removeFileCardBackgroundColor();
    static void setFileCardBackgroundColor(const unsigned long &v);
    static const char *docFileCardBackgroundColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardBorderColor
    ///
    /// Border colour of a New File card under the mouse pointer. Only
    /// used while no style sheet is loaded. Takes effect at the next
    /// style change or when the Start page is next created.
    static const unsigned long & getFileCardBorderColor();
    static const unsigned long & defaultFileCardBorderColor();
    static void removeFileCardBorderColor();
    static void setFileCardBorderColor(const unsigned long &v);
    static const char *docFileCardBorderColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileCardSelectionColor
    ///
    /// Border colour of a New File card while it is pressed. Only used
    /// while no style sheet is loaded. Takes effect at the next style
    /// change or when the Start page is next created.
    static const unsigned long & getFileCardSelectionColor();
    static const unsigned long & defaultFileCardSelectionColor();
    static void removeFileCardSelectionColor();
    static void setFileCardSelectionColor(const unsigned long &v);
    static const char *docFileCardSelectionColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileThumbnailBackgroundColor
    ///
    /// Background colour of the file thumbnails on the Start page. Only
    /// used while no style sheet is loaded. Takes effect at the next
    /// repaint.
    static const unsigned long & getFileThumbnailBackgroundColor();
    static const unsigned long & defaultFileThumbnailBackgroundColor();
    static void removeFileThumbnailBackgroundColor();
    static void setFileThumbnailBackgroundColor(const unsigned long &v);
    static const char *docFileThumbnailBackgroundColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileThumbnailBorderColor
    ///
    /// Border colour of a file thumbnail under the mouse pointer on the
    /// Start page. Only used while no style sheet is loaded. Takes effect
    /// at the next repaint.
    static const unsigned long & getFileThumbnailBorderColor();
    static const unsigned long & defaultFileThumbnailBorderColor();
    static void removeFileThumbnailBorderColor();
    static void setFileThumbnailBorderColor(const unsigned long &v);
    static const char *docFileThumbnailBorderColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FileThumbnailSelectionColor
    ///
    /// Border colour of the selected file thumbnail on the Start page.
    /// Only used while no style sheet is loaded. Takes effect at the next
    /// repaint.
    static const unsigned long & getFileThumbnailSelectionColor();
    static const unsigned long & defaultFileThumbnailSelectionColor();
    static void removeFileThumbnailSelectionColor();
    static void setFileThumbnailSelectionColor(const unsigned long &v);
    static const char *docFileThumbnailSelectionColor();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class StartParams
} // namespace Start
//[[[end]]]

#endif // START_APP_PARAMS_H
