/****************************************************************************
 *   Copyright (c) 2020 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef DOCUMENT_PARAMS_H
#define DOCUMENT_PARAMS_H

/*[[[cog
import DocumentParams
DocumentParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace App {
/** Convenient class to obtain App::Document related parameters

 * The parameters are under group "User parameter:BaseApp/Preferences/Document"
 *
 * This class is auto generated by App/DocumentParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r App/DocumentParams.h App/DocumentParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in App/DocumentParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in App/DocumentParams.cpp with
 * the following signature.
 * @code
 *     void DocumentParams:on<parameter_name>Changed()
 * @endcode
 */
class AppExport DocumentParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter prefAuthor
    ///
    /// Author name given to new documents as their creator. Also written as
    /// the last modifier on save when that option is on. Leave empty to stay
    /// anonymous.
    static const std::string & getprefAuthor();
    static const std::string & defaultprefAuthor();
    static void removeprefAuthor();
    static void setprefAuthor(const std::string &v);
    static const char *docprefAuthor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter prefSetAuthorOnSave
    ///
    /// Write the author name from the preferences into a document's 'Last
    /// modified by' field each time it is saved.
    static const bool & getprefSetAuthorOnSave();
    static const bool & defaultprefSetAuthorOnSave();
    static void removeprefSetAuthorOnSave();
    static void setprefSetAuthorOnSave(const bool &v);
    static const char *docprefSetAuthorOnSave();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter prefCompany
    ///
    /// Company name given to new documents.
    static const std::string & getprefCompany();
    static const std::string & defaultprefCompany();
    static void removeprefCompany();
    static void setprefCompany(const std::string &v);
    static const char *docprefCompany();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter prefLicenseType
    ///
    /// License given to new documents, as a position in the license list.
    /// 0 is All rights reserved, 1 to 12 the Creative Commons licenses,
    /// 13 Public Domain, 14 FreeArt, 15 to 17 the CERN hardware licences;
    /// 18 (Other) leaves the license empty.
    static const long & getprefLicenseType();
    static const long & defaultprefLicenseType();
    static void removeprefLicenseType();
    static void setprefLicenseType(const long &v);
    static const char *docprefLicenseType();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter prefLicenseUrl
    ///
    /// Address of the license text given to new documents. Empty uses the
    /// address that belongs to the license chosen from the list.
    static const std::string & getprefLicenseUrl();
    static const std::string & defaultprefLicenseUrl();
    static void removeprefLicenseUrl();
    static void setprefLicenseUrl(const std::string &v);
    static const char *docprefLicenseUrl();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CompressionLevel
    ///
    /// How hard a document file is compressed when saved, from 0 (none,
    /// fastest) to 9 (smallest, slowest). Has no effect on a document saved
    /// as a directory.
    static const long & getCompressionLevel();
    static const long & defaultCompressionLevel();
    static void removeCompressionLevel();
    static void setCompressionLevel(const long &v);
    static const char *docCompressionLevel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CheckExtension
    ///
    /// Add .FCStd to the file name when a document is saved under a name
    /// without that extension, so that a save cannot overwrite an unrelated
    /// file by accident.
    static const bool & getCheckExtension();
    static const bool & defaultCheckExtension();
    static void removeCheckExtension();
    static void setCheckExtension(const bool &v);
    static const char *docCheckExtension();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ForceXML
    ///
    /// How much object data new documents keep inside the XML when saved
    /// as a directory. 0 none, 1 lists, 2 also meshes, points and text
    /// shapes, 3 also binary shapes, 4 and up also included files.
    static const long & getForceXML();
    static const long & defaultForceXML();
    static void removeForceXML();
    static void setForceXML(const long &v);
    static const char *docForceXML();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SplitXML
    ///
    /// Give each object an XML file of its own in new documents saved as a
    /// directory, instead of one file for the whole document. Has no effect
    /// on a document saved as a single file.
    static const bool & getSplitXML();
    static const bool & defaultSplitXML();
    static void removeSplitXML();
    static void setSplitXML(const bool &v);
    static const char *docSplitXML();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PreferBinary
    ///
    /// Save the object data of new documents in binary instead of text
    /// form. Files get smaller but compare poorly under version control.
    /// Each document carries its own copy of this choice.
    static const bool & getPreferBinary();
    static const bool & defaultPreferBinary();
    static void removePreferBinary();
    static void setPreferBinary(const bool &v);
    static const char *docPreferBinary();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter InlineListSize
    ///
    /// Largest list property, in bytes, still written inside the document
    /// XML instead of as a separate entry of the file. Small lists are
    /// cheaper inline. 0 gives every list its own entry.
    static const long & getInlineListSize();
    static const long & defaultInlineListSize();
    static void removeInlineListSize();
    static void setInlineListSize(const long &v);
    static const char *docInlineListSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArchiveRandomAccess
    ///
    /// Restore a document archive through its zip central directory
    /// instead of one forward-only stream. Entries are then opened
    /// independently and served in registration order whatever their
    /// archive order, nothing pays for inflating entries nobody reads,
    /// and an entry can be reopened after the restore. Turn off to
    /// fall back to the forward-only walk.
    static const bool & getArchiveRandomAccess();
    static const bool & defaultArchiveRandomAccess();
    static void removeArchiveRandomAccess();
    static void setArchiveRandomAccess(const bool &v);
    static const char *docArchiveRandomAccess();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ArchiveBlobStore
    ///
    /// Serve the included files of a document archive out of one copy
    /// of the archive in the transient directory, and give each its own
    /// file only when something asks for a path. Requires
    /// ArchiveRandomAccess. Turn off to write every included file out
    /// during the restore, which on a monitored filesystem costs a file
    /// create per entry.
    static const bool & getArchiveBlobStore();
    static const bool & defaultArchiveBlobStore();
    static void removeArchiveBlobStore();
    static void setArchiveBlobStore(const bool &v);
    static const char *docArchiveBlobStore();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DeferShapeLoad
    ///
    /// When opening a document, read each shape on first use instead of
    /// before the window comes up. Requires ArchiveRandomAccess. The file
    /// must not be rewritten by another program while shapes are still to be
    /// read. Off by default.
    static const bool & getDeferShapeLoad();
    static const bool & defaultDeferShapeLoad();
    static void removeDeferShapeLoad();
    static void setDeferShapeLoad(const bool &v);
    static const char *docDeferShapeLoad();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SaveMaterialCards
    ///
    /// Write every material card used into the document, including the
    /// stock ones, so the document does not depend on the installed material
    /// library. Off writes only a reference to a stock card, which is lost
    /// if the library changes.
    static const bool & getSaveMaterialCards();
    static const bool & defaultSaveMaterialCards();
    static void removeSaveMaterialCards();
    static void setSaveMaterialCards(const bool &v);
    static const char *docSaveMaterialCards();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DedupShapePCurves
    ///
    /// Write each 2D curve of a shape once, and leave out those on planar
    /// faces, which are computed again on reading. The geometry read back is
    /// the same. Applies to shapes written as ASCII BRep.
    static const bool & getDedupShapePCurves();
    static const bool & defaultDedupShapePCurves();
    static void removeDedupShapePCurves();
    static void setDedupShapePCurves(const bool &v);
    static const char *docDedupShapePCurves();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DedupCongruentShapes
    ///
    /// Store one shape file for parts that are the same shape in different
    /// places, and record the motion between them. Parts are merged only
    /// after the motion has been checked sub-shape by sub-shape.
    static const bool & getDedupCongruentShapes();
    static const bool & defaultDedupCongruentShapes();
    static void removeDedupCongruentShapes();
    static void setDedupCongruentShapes(const bool &v);
    static const char *docDedupCongruentShapes();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DedupCrossFileGeometry
    ///
    /// Let a shape file refer to surfaces and curves another shape file of
    /// the same document already holds instead of writing them again.
    /// Smaller files, but a shape file then depends on another for its
    /// geometry. Off by default.
    static const bool & getDedupCrossFileGeometry();
    static const bool & defaultDedupCrossFileGeometry();
    static void removeDedupCrossFileGeometry();
    static void setDedupCrossFileGeometry(const bool &v);
    static const char *docDedupCrossFileGeometry();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoRemoveFile
    ///
    /// Delete the files a document no longer uses from its directory when
    /// it is saved as a directory. Turn off to leave the files of removed
    /// objects in place.
    static const bool & getAutoRemoveFile();
    static const bool & defaultAutoRemoveFile();
    static void removeAutoRemoveFile();
    static void setAutoRemoveFile(const bool &v);
    static const char *docAutoRemoveFile();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoNameDynamicProperty
    ///
    /// Rename a property added to an object when its name is empty, not a
    /// valid name or already taken, instead of refusing to add it. A
    /// warning reports the name chosen.
    static const bool & getAutoNameDynamicProperty();
    static const bool & defaultAutoNameDynamicProperty();
    static void removeAutoNameDynamicProperty();
    static void setAutoNameDynamicProperty(const bool &v);
    static const char *docAutoNameDynamicProperty();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BackupPolicy
    ///
    /// Save a document to a temporary file first and move it over the old
    /// file only once the write succeeded, keeping backups as configured.
    /// Turn off to write straight over the file, with no backup.
    static const bool & getBackupPolicy();
    static const bool & defaultBackupPolicy();
    static void removeBackupPolicy();
    static void setBackupPolicy(const bool &v);
    static const char *docBackupPolicy();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CreateBackupFiles
    ///
    /// Keep the previous version of a document file as a backup each time
    /// it is saved. When off the old file is deleted once the new one is
    /// written.
    static const bool & getCreateBackupFiles();
    static const bool & defaultCreateBackupFiles();
    static void removeCreateBackupFiles();
    static void setCreateBackupFiles(const bool &v);
    static const char *docCreateBackupFiles();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseFCBakExtension
    ///
    /// Name a backup after the document, with the date of the replaced
    /// file and the extension .FCBak. When off a backup is the document
    /// file name followed by a number, as in Part.FCStd1.
    static const bool & getUseFCBakExtension();
    static const bool & defaultUseFCBakExtension();
    static void removeUseFCBakExtension();
    static void setUseFCBakExtension(const bool &v);
    static const char *docUseFCBakExtension();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SaveBackupDateFormat
    ///
    /// Date format used in the names of .FCBak backup files, in strftime
    /// notation. A dot in the format is written as a dash.
    static const std::string & getSaveBackupDateFormat();
    static const std::string & defaultSaveBackupDateFormat();
    static void removeSaveBackupDateFormat();
    static void setSaveBackupDateFormat(const std::string &v);
    static const char *docSaveBackupDateFormat();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CountBackupFiles
    ///
    /// How many backup files are kept for one document. The oldest are
    /// deleted when a save would exceed the number. 0 keeps none.
    static const long & getCountBackupFiles();
    static const long & defaultCountBackupFiles();
    static void removeCountBackupFiles();
    static void setCountBackupFiles(const long &v);
    static const char *docCountBackupFiles();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter OptimizeRecompute
    ///
    /// Recompute an object only when one of its properties really changed.
    /// Writing a property the value it already has then leaves the object
    /// untouched. Turn off to recompute on every write.
    static const bool & getOptimizeRecompute();
    static const bool & defaultOptimizeRecompute();
    static void removeOptimizeRecompute();
    static void setOptimizeRecompute(const bool &v);
    static const char *docOptimizeRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CanAbortRecompute
    ///
    /// Show progress while a document recomputes and let Esc abort it.
    /// Costs a little recompute time.
    static const bool & getCanAbortRecompute();
    static const bool & defaultCanAbortRecompute();
    static void removeCanAbortRecompute();
    static void setCanAbortRecompute(const bool &v);
    static const char *docCanAbortRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseHasher
    ///
    /// Store the generated element names of new documents as short
    /// references into a string table of the document instead of in full.
    /// Each document carries its own copy of this choice.
    static const bool & getUseHasher();
    static const bool & defaultUseHasher();
    static void removeUseHasher();
    static void setUseHasher(const bool &v);
    static const char *docUseHasher();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ViewObjectTransaction
    ///
    /// Let a change to a view property alone, such as colour or visibility,
    /// create an undo step whatever command made it. When off only the
    /// commands that ask for it do.
    static const bool & getViewObjectTransaction();
    static const bool & defaultViewObjectTransaction();
    static void removeViewObjectTransaction();
    static void setViewObjectTransaction(const bool &v);
    static const char *docViewObjectTransaction();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter WarnRecomputeOnRestore
    ///
    /// Ask to recompute after opening a document that needs it to be
    /// brought up to date with this version. When off the document opens
    /// without the question and is left as it is.
    static const bool & getWarnRecomputeOnRestore();
    static const bool & defaultWarnRecomputeOnRestore();
    static void removeWarnRecomputeOnRestore();
    static void setWarnRecomputeOnRestore(const bool &v);
    static const char *docWarnRecomputeOnRestore();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter NoPartialLoading
    ///
    /// Load every externally linked document in full. When off a document
    /// opened only because another links to it loads just the linked
    /// objects and what they depend on, and cannot be edited until
    /// reloaded.
    static const bool & getNoPartialLoading();
    static const bool & defaultNoPartialLoading();
    static void removeNoPartialLoading();
    static void setNoPartialLoading(const bool &v);
    static const char *docNoPartialLoading();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SaveThumbnail
    ///
    /// Save a preview picture of the 3D view into new documents each time
    /// they are saved. Each document carries its own copy of this choice.
    static const bool & getSaveThumbnail();
    static const bool & defaultSaveThumbnail();
    static void removeSaveThumbnail();
    static void setSaveThumbnail(const bool &v);
    static const char *docSaveThumbnail();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThumbnailNoBackground
    ///
    /// Leave the view background out of the thumbnail saved with a
    /// document, so the picture has a transparent background.
    static const bool & getThumbnailNoBackground();
    static const bool & defaultThumbnailNoBackground();
    static void removeThumbnailNoBackground();
    static void setThumbnailNoBackground(const bool &v);
    static const char *docThumbnailNoBackground();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AddThumbnailLogo
    ///
    /// Put the application icon in the bottom right corner of the thumbnail
    /// saved with a document.
    static const bool & getAddThumbnailLogo();
    static const bool & defaultAddThumbnailLogo();
    static void removeAddThumbnailLogo();
    static void setAddThumbnailLogo(const bool &v);
    static const char *docAddThumbnailLogo();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThumbnailSampleSize
    ///
    /// Number of antialiasing samples used to render the thumbnail saved
    /// with a document. 0 renders without antialiasing.
    static const long & getThumbnailSampleSize();
    static const long & defaultThumbnailSampleSize();
    static void removeThumbnailSampleSize();
    static void setThumbnailSampleSize(const long &v);
    static const char *docThumbnailSampleSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ThumbnailSize
    ///
    /// Width and height, in pixels, of the thumbnail saved with a document.
    /// Values outside 64 to 1024 are brought into that range.
    static const long & getThumbnailSize();
    static const long & defaultThumbnailSize();
    static void removeThumbnailSize();
    static void setThumbnailSize(const long &v);
    static const char *docThumbnailSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DuplicateLabels
    ///
    /// Allow several objects of one document to carry the same label. When
    /// off a label already in use gets a number added to make it unique.
    static const bool & getDuplicateLabels();
    static const bool & defaultDuplicateLabels();
    static void removeDuplicateLabels();
    static void setDuplicateLabels(const bool &v);
    static const char *docDuplicateLabels();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter TransactionOnRecompute
    ///
    /// Record a recompute started with the Refresh command as an undo step.
    /// When off, refreshing leaves the undo and redo history alone.
    static const bool & getTransactionOnRecompute();
    static const bool & defaultTransactionOnRecompute();
    static void removeTransactionOnRecompute();
    static void setTransactionOnRecompute(const bool &v);
    static const char *docTransactionOnRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RelativeStringID
    ///
    /// Write the ids in a document's string table as differences from the
    /// id before, which makes the saved file smaller. Turn off to write
    /// every id in full.
    static const bool & getRelativeStringID();
    static const bool & defaultRelativeStringID();
    static void removeRelativeStringID();
    static void setRelativeStringID(const bool &v);
    static const char *docRelativeStringID();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter HashIndexedName
    ///
    /// Encode a mapped name's trailing index apart from its text, as upstream
    /// FreeCAD does. Sets the mode of new documents only: a document keeps the
    /// mode it was saved in, and one saved before the mode was stored gets the
    /// one its string table was written in.
    static const bool & getHashIndexedName();
    static const bool & defaultHashIndexedName();
    static void removeHashIndexedName();
    static void setHashIndexedName(const bool &v);
    static const char *docHashIndexedName();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EnableMaterialEdit
    ///
    /// Show appearance properties in the property view with an editor for
    /// their colours, shininess and transparency. When off they are not
    /// listed. Applies to objects created or loaded afterwards.
    static const bool & getEnableMaterialEdit();
    static const bool & defaultEnableMaterialEdit();
    static void removeEnableMaterialEdit();
    static void setEnableMaterialEdit(const bool &v);
    static const char *docEnableMaterialEdit();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MCPServerAutoStart
    ///
    /// Start the MCP debug console server (freecad.mcp_console) when the
    /// application starts. Toggled by the Tools -> MCP Server menu action.
    static const bool & getMCPServerAutoStart();
    static const bool & defaultMCPServerAutoStart();
    static void removeMCPServerAutoStart();
    static void setMCPServerAutoStart(const bool &v);
    static const char *docMCPServerAutoStart();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MCPServerPort
    ///
    /// Port the MCP debug console server listens on. If it is already in
    /// use the server takes the next free port after it, so the port it
    /// ends up on is reported in the console and in the Tools -> MCP
    /// Server tooltip.
    static const long & getMCPServerPort();
    static const long & defaultMCPServerPort();
    static void removeMCPServerPort();
    static void setMCPServerPort(const long &v);
    static const char *docMCPServerPort();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoSaveEnabled
    ///
    /// Save auto-recovery information of the open documents at regular
    /// intervals. Takes effect at once.
    static const bool & getAutoSaveEnabled();
    static const bool & defaultAutoSaveEnabled();
    static void removeAutoSaveEnabled();
    static void setAutoSaveEnabled(const bool &v);
    static const char *docAutoSaveEnabled();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoSaveTimeout
    ///
    /// Minutes between two saves of auto-recovery information. 1 to 60.
    /// Takes effect at once.
    static const long & getAutoSaveTimeout();
    static const long & defaultAutoSaveTimeout();
    static void removeAutoSaveTimeout();
    static void setAutoSaveTimeout(const long &v);
    static const char *docAutoSaveTimeout();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AutoSaveCompressed
    ///
    /// Write auto-recovery information as one compressed file per
    /// document instead of separate uncompressed files. Takes effect at
    /// the next save of it.
    static const bool & getAutoSaveCompressed();
    static const bool & defaultAutoSaveCompressed();
    static void removeAutoSaveCompressed();
    static void setAutoSaveCompressed(const bool &v);
    static const char *docAutoSaveCompressed();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter SaveBinaryBrep
    ///
    /// Write shapes in binary BREP format into a compressed
    /// auto-recovery file. Read at each save of it.
    static const bool & getSaveBinaryBrep();
    static const bool & defaultSaveBinaryBrep();
    static void removeSaveBinaryBrep();
    static void setSaveBinaryBrep(const bool &v);
    static const char *docSaveBinaryBrep();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter RecoveryEnabled
    ///
    /// Look at startup for documents a crashed session left behind and
    /// offer to recover them.
    static const bool & getRecoveryEnabled();
    static const bool & defaultRecoveryEnabled();
    static void removeRecoveryEnabled();
    static void setRecoveryEnabled(const bool &v);
    static const char *docRecoveryEnabled();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CreateNewDoc
    ///
    /// Create an empty document when the program starts with none
    /// open.
    static const bool & getCreateNewDoc();
    static const bool & defaultCreateNewDoc();
    static void removeCreateNewDoc();
    static void setCreateNewDoc(const bool &v);
    static const char *docCreateNewDoc();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UsingUndo
    ///
    /// Record undo and redo steps for documents. Applies to documents
    /// created or opened afterwards.
    static const bool & getUsingUndo();
    static const bool & defaultUsingUndo();
    static void removeUsingUndo();
    static void setUsingUndo(const bool &v);
    static const char *docUsingUndo();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MaxUndoSize
    ///
    /// Largest number of undo steps kept for a document. Applies to
    /// documents created or opened afterwards.
    static const long & getMaxUndoSize();
    static const long & defaultMaxUndoSize();
    static void removeMaxUndoSize();
    static void setMaxUndoSize(const long &v);
    static const char *docMaxUndoSize();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ChangeViewProviderTouchDocument
    ///
    /// Mark a document as modified when a view property of one of its
    /// objects changes. Applies to documents created or opened
    /// afterwards.
    static const bool & getChangeViewProviderTouchDocument();
    static const bool & defaultChangeViewProviderTouchDocument();
    static void removeChangeViewProviderTouchDocument();
    static void setChangeViewProviderTouchDocument(const bool &v);
    static const char *docChangeViewProviderTouchDocument();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter JsonIndent
    ///
    /// Indentation of the JSON text the properties of Python objects are
    /// saved as.
    static const long & getJsonIndent();
    static const long & defaultJsonIndent();
    static void removeJsonIndent();
    static void setJsonIndent(const long &v);
    static const char *docJsonIndent();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class DocumentParams
} // namespace App
//[[[end]]]

#endif // DOCUMENT_PARAMS_H
