/***************************************************************************
 *   Copyright (c) 2026 Zheng, Lei <realthunder.dev@gmail.com>             *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

// This file is GENERATED by cog from FeaturePythonHookApp.cog.h and the table
// in FeaturePythonHooks.py.  It lands in the build tree and is not committed;
// edit the table or the template, never this.  Include it once, from
// FeaturePython.cpp.

/*[[[cog
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(cog.inFile)))
import FeaturePythonHooks as table
table.emit(cog, table.APP_HOOKS, table.APP_PREFIX, "AppHook", "appHookTable", "App")
]]]*/
//[[[end]]]
