/***************************************************************************
 *   Copyright (c) 2002 Jürgen Riegel <juergen.riegel@web.de>              *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/


#include "PreCompiled.h"
#ifndef _PreComp_
# include <sstream>
#endif

#include <App/DocumentObjectPy.h>
#include <Base/Interpreter.h>
#include <Base/MatrixPy.h>
#include <Base/Tools.h>

#include "FeaturePython.h"
#include "FeaturePythonPyImp.h"


using namespace App;

// The hook enum and the PyHookDef table, generated by cog into the build tree
// from FeaturePythonHookApp.cog.h and the table in FeaturePythonHooks.py.
#include "FeaturePythonHookApp.h"

FeaturePythonImp::FeaturePythonImp(App::DocumentObject* o)
    : PyHookImp(appHookTable, HookCount)
    , object(o)
{
}

FeaturePythonImp::~FeaturePythonImp() = default;

Py::Object FeaturePythonImp::hookSelf(int) const
{
    return Py::asObject(object->getPyObject());
}

/*!
 Calls the execute() method of the Python feature class. If the Python feature class
 doesn't have an execute() method or if it returns False this method also return false
 and true otherwise.
 */
bool FeaturePythonImp::execute()
{
    return callHook(HookExecute,
                    [](const Py::Object& res) {
                        // False means "not mine"; anything else is handled
                        return !(res.isBoolean() && !res.isTrue());
                    })
        == PyHookState::Handled;
}

bool FeaturePythonImp::mustExecute() const
{
    bool ret = false;
    callHook(HookMustExecute, [&ret](const Py::Object& res) {
        ret = res.isTrue();
        return true;
    });
    return ret;
}

bool FeaturePythonImp::skipRecompute()
{
    // absent, blocked or not implemented all mean "the base decides alone"
    bool ret = true;
    callHook(HookSkipRecompute, [&ret](const Py::Object& res) {
        ret = res.isTrue();
        return true;
    });
    return ret;
}

void FeaturePythonImp::onBeforeChange(const Property* prop)
{
    if (!canCallHook(HookOnBeforeChange)) {
        return;
    }
    const char* prop_name = object->getPropertyName(prop);
    if (!prop_name) {
        return;
    }
    callHook(HookOnBeforeChange, pyHookDecodeNotify(), prop_name);
}

bool FeaturePythonImp::onBeforeChangeLabel(std::string& newLabel)
{
    return callHook(
               HookOnBeforeChangeLabel,
               [&newLabel](const Py::Object& res) {
                   if (res.isNone()) {
                       return false;
                   }
                   if (!res.isString()) {
                       throw Py::TypeError("onBeforeChangeLabel expects to return a string");
                   }
                   newLabel = res.as_string();
                   return true;
               },
               newLabel)
        == PyHookState::Handled;
}

void FeaturePythonImp::onChanged(const Property* prop)
{
    if (!canCallHook(HookOnChanged)) {
        return;
    }
    const char* prop_name = object->getPropertyName(prop);
    if (!prop_name) {
        return;
    }
    callHook(HookOnChanged, pyHookDecodeNotify(), prop_name);
}

void FeaturePythonImp::onDocumentRestored()
{
    callHook(HookOnDocumentRestored, pyHookDecodeNotify());
}

void FeaturePythonImp::unsetupObject()
{
    callHook(HookUnsetupObject, pyHookDecodeNotify());
}

bool FeaturePythonImp::getSubObject(DocumentObject*& ret, const char* subname,
    PyObject** pyObj, Base::Matrix4D* _mat, bool transform, int depth) const
{
    if (!canCallHook(HookGetSubObject)) {
        return false;
    }

    Base::PyGILStateLocker lock;
    auto* pyMat = new Base::MatrixPy(new Base::Matrix4D);
    if (_mat) {
        *pyMat->getMatrixPtr() = *_mat;
    }
    Py::Object matrix(Py::asObject(pyMat));

    auto state = callHook(
        HookGetSubObject,
        [&](const Py::Object& res) {
            if (res.isNone()) {
                ret = nullptr;
                return true;
            }
            if (!res.isTrue()) {
                return false;
            }
            if (!res.isSequence()) {
                throw Py::TypeError("getSubObject expects return type of tuple");
            }
            Py::Sequence seq(res);
            if (seq.length() < 2
                || (!seq.getItem(0).isNone()
                    && !PyObject_TypeCheck(seq.getItem(0).ptr(), &DocumentObjectPy::Type))
                || !PyObject_TypeCheck(seq.getItem(1).ptr(), &Base::MatrixPy::Type)) {
                throw Py::TypeError("getSubObject expects return type of (obj,matrix,pyobj)");
            }
            if (_mat) {
                *_mat = *static_cast<Base::MatrixPy*>(seq.getItem(1).ptr())->getMatrixPtr();
            }
            if (pyObj) {
                *pyObj = seq.length() > 2 ? Py::new_reference_to(seq.getItem(2))
                                          : Py::new_reference_to(Py::None());
            }
            ret = seq.getItem(0).isNone()
                ? nullptr
                : static_cast<DocumentObjectPy*>(seq.getItem(0).ptr())->getDocumentObjectPtr();
            return true;
        },
        subname ? subname : "", pyObj ? 2 : 1, matrix, transform, depth);

    if (state == PyHookState::Failed) {
        ret = nullptr;
        return true;
    }
    return state == PyHookState::Handled;
}

bool FeaturePythonImp::getSubObjects(std::vector<std::string> &ret, int reason) const
{
    auto state = callHook(
        HookGetSubObjects,
        [&ret](const Py::Object& res) {
            if (!res.isTrue()) {
                return true;
            }
            if (!res.isSequence()) {
                throw Py::TypeError("getSubObjects expects return type of tuple");
            }
            Py::Sequence seq(res);
            for (Py_ssize_t i = 0; i < seq.length(); ++i) {
                Py::Object name(seq[i].ptr());
                if (!name.isString()) {
                    throw Py::TypeError("getSubObjects expects string in returned sequence");
                }
                ret.push_back(name.as_string());
            }
            return true;
        },
        reason);

    if (state == PyHookState::Failed) {
        return true;
    }
    return state == PyHookState::Handled;
}

bool FeaturePythonImp::getLinkedObject(DocumentObject*& ret, bool recurse,
        Base::Matrix4D* _mat, bool transform, int depth) const
{
    if (!canCallHook(HookGetLinkedObject)) {
        return false;
    }

    Base::PyGILStateLocker lock;
    auto* pyMat = new Base::MatrixPy(new Base::Matrix4D);
    if (_mat) {
        *pyMat->getMatrixPtr() = *_mat;
    }
    Py::Object matrix(Py::asObject(pyMat));

    auto state = callHook(
        HookGetLinkedObject,
        [&](const Py::Object& res) {
            if (!res.isTrue()) {
                ret = object;
                return true;
            }
            if (!res.isSequence()) {
                throw Py::TypeError("getLinkedObject expects return type of (object,matrix)");
            }
            Py::Sequence seq(res);
            if (seq.length() != 2
                || (!seq.getItem(0).isNone()
                    && !PyObject_TypeCheck(seq.getItem(0).ptr(), &DocumentObjectPy::Type))
                || !PyObject_TypeCheck(seq.getItem(1).ptr(), &Base::MatrixPy::Type)) {
                throw Py::TypeError("getLinkedObject expects return type of (object,matrix)");
            }
            if (_mat) {
                *_mat = *static_cast<Base::MatrixPy*>(seq.getItem(1).ptr())->getMatrixPtr();
            }
            ret = seq.getItem(0).isNone()
                ? object
                : static_cast<DocumentObjectPy*>(seq.getItem(0).ptr())->getDocumentObjectPtr();
            return true;
        },
        recurse, matrix, transform, depth);

    if (state == PyHookState::Failed) {
        ret = nullptr;
        return true;
    }
    return state == PyHookState::Handled;
}

PyObject *FeaturePythonImp::getPyObject()
{
    // ref counter is set to 1
    return new FeaturePythonPyT<DocumentObjectPy>(object);
}

FeaturePythonImp::ValueT
FeaturePythonImp::hasChildElement() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookHasChildElement, pyHookDecodeValueT(ret)) == PyHookState::Failed) {
        return Rejected;
    }
    return ret;
}

int FeaturePythonImp::isElementVisible(const char *element) const
{
    int ret = -2;
    if (callHook(HookIsElementVisible, pyHookDecodeInt(ret), element) == PyHookState::Failed) {
        return -1;
    }
    return ret;
}

int FeaturePythonImp::isElementVisibleEx(const char *subname, int reason) const
{
    int ret = -2;
    if (callHook(HookIsElementVisibleEx, pyHookDecodeInt(ret), subname, reason)
        == PyHookState::Failed) {
        return -1;
    }
    return ret;
}

int FeaturePythonImp::setElementVisible(const char *element, bool visible)
{
    int ret = -2;
    if (callHook(HookSetElementVisible, pyHookDecodeInt(ret), element, visible)
        == PyHookState::Failed) {
        return -1;
    }
    return ret;
}

std::string FeaturePythonImp::getViewProviderName()
{
    std::string ret;
    callHook(HookGetViewProviderName, [&ret](const Py::Object& res) {
        ret = Py::String(res).as_string();
        return true;
    });
    return ret;
}

FeaturePythonImp::ValueT
FeaturePythonImp::canLinkProperties() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookCanLinkProperties, pyHookDecodeValueT(ret)) == PyHookState::Failed) {
        return Rejected;
    }
    return ret;
}

FeaturePythonImp::ValueT
FeaturePythonImp::allowDuplicateLabel() const
{
    ValueT ret = NotImplemented;
    if (callHook(HookAllowDuplicateLabel, pyHookDecodeValueT(ret)) == PyHookState::Failed) {
        return Rejected;
    }
    return ret;
}

int FeaturePythonImp::canLoadPartial() const
{
    int ret = -1;
    if (callHook(HookCanLoadPartial, pyHookDecodeInt(ret)) == PyHookState::Failed) {
        return 0;
    }
    return ret;
}

FeaturePythonImp::ValueT
FeaturePythonImp::redirectSubName(std::ostringstream &ss,
                                  App::DocumentObject *topParent,
                                  App::DocumentObject *child) const
{
    ValueT ret = NotImplemented;
    auto state = callHook(
        HookRedirectSubName,
        [&](const Py::Object& res) {
            if (res.isNone()) {
                ret = Rejected;
                return true;
            }
            ss.str("");
            ss << res.as_string();
            ret = Accepted;
            return true;
        },
        ss.str(), topParent, child);

    if (state == PyHookState::Failed) {
        return Rejected;
    }
    return ret;
}

void FeaturePythonImp::getElementMapVersion(std::string &ver, const App::Property *prop,
                                            bool restored) const
{
    callHook(
        HookGetElementMapVersion,
        [&ver](const Py::Object& res) {
            if (res.isString()) {
                ver = res.as_string();
            }
            return true;
        },
        ver, prop && prop->hasName() ? prop->getName() : "", restored);
}

bool FeaturePythonImp::editProperty(const char *name)
{
    bool ret = false;
    callHook(
        HookEditProperty,
        [&ret](const Py::Object& res) {
            ret = res.isTrue();
            return true;
        },
        name);
    return ret;
}
// ---------------------------------------------------------

namespace App {
PROPERTY_SOURCE_TEMPLATE(App::FeaturePython, App::DocumentObject)
template<> const char* App::FeaturePython::getViewProviderName() const {
    return "Gui::ViewProviderFeaturePython";
}
template<> PyObject* App::FeaturePython::getPyObject() {
    if (PythonObject.is(Py::_None())) {
        // ref counter is set to 1
        PythonObject = Py::Object(new FeaturePythonPyT<DocumentObjectPy>(this),true);
    }
    return Py::new_reference_to(PythonObject);
}
// explicit template instantiation
template class AppExport FeaturePythonT<DocumentObject>;
}

// ---------------------------------------------------------

namespace App {
PROPERTY_SOURCE_TEMPLATE(App::GeometryPython, App::GeoFeature)
template<> const char* App::GeometryPython::getViewProviderName() const {
    return "Gui::ViewProviderGeometryPython";
}
// explicit template instantiation
template class AppExport FeaturePythonT<GeoFeature>;
}
