/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef APP_SANDBOX_PARAMS_H
#define APP_SANDBOX_PARAMS_H

/*[[[cog
import SandboxParams
SandboxParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace App {
/** Convenient class to obtain the settings of the expression sandbox

 * The parameters are under group "User parameter:BaseApp/Preferences/Expression"
 *
 * This class is auto generated by App/SandboxParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r App/SandboxParams.h App/SandboxParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in App/SandboxParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in App/SandboxParams.cpp with
 * the following signature.
 * @code
 *     void SandboxParams:on<parameter_name>Changed()
 * @endcode
 */
class AppExport SandboxParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Evaluate
    ///
    /// Expressions that call Python, and the Python objects of a document,
    /// are evaluated in the sandbox instead of the program's own
    /// interpreter, when the sandbox is there. The sandbox indicator of
    /// the status bar switches it. Takes effect at once.
    static const bool & getEvaluate();
    static const bool & defaultEvaluate();
    static void removeEvaluate();
    static void setEvaluate(const bool &v);
    static const char *docEvaluate();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Runtime
    ///
    /// Which runtime carries the sandbox: "pyodide" or "wasi". Empty, the
    /// environment variable FCX_RUNTIME decides, and then the build:
    /// pyodide where it has it. Read when the sandbox starts.
    static const std::string & getRuntime();
    static const std::string & defaultRuntime();
    static void removeRuntime();
    static void setRuntime(const std::string &v);
    static const char *docRuntime();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter BudgetMs
    ///
    /// Milliseconds one evaluation in the sandbox may take before it is
    /// interrupted. Takes effect at the next evaluation.
    static const long & getBudgetMs();
    static const long & defaultBudgetMs();
    static void removeBudgetMs();
    static void setBudgetMs(const long &v);
    static const char *docBudgetMs();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GraceMs
    ///
    /// Milliseconds an interrupted evaluation is given to stop by itself
    /// after its time budget, before the sandbox is stopped. Takes effect
    /// at the next evaluation.
    static const long & getGraceMs();
    static const long & defaultGraceMs();
    static void removeGraceMs();
    static void setGraceMs(const long &v);
    static const char *docGraceMs();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MemoryMB
    ///
    /// Megabytes of memory the sandbox may use; an evaluation that takes
    /// it past that stops the sandbox. Takes effect the next time the
    /// sandbox's memory grows.
    static const long & getMemoryMB();
    static const long & defaultMemoryMB();
    static void removeMemoryMB();
    static void setMemoryMB(const long &v);
    static const char *docMemoryMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter EngineHeapMB
    ///
    /// Megabytes of heap the engine that runs the sandbox may use for
    /// itself; 0 leaves it to the engine. Takes effect when the sandbox
    /// next starts.
    static const long & getEngineHeapMB();
    static const long & defaultEngineHeapMB();
    static void removeEngineHeapMB();
    static void setEngineHeapMB(const long &v);
    static const char *docEngineHeapMB();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter ImagePath
    ///
    /// Path of the sandbox image the wasi runtime loads. Empty, the
    /// environment variable FCX_IMAGE is used, and then the image that
    /// comes with the program. Read when the sandbox starts.
    static const std::string & getImagePath();
    static const std::string & defaultImagePath();
    static void removeImagePath();
    static void setImagePath(const std::string &v);
    static const char *docImagePath();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter StdlibPath
    ///
    /// Folder of the Python standard library of the wasi image. Empty,
    /// the environment variable FCX_STDLIB is used, and then the one that
    /// comes with the program. Read when the sandbox starts.
    static const std::string & getStdlibPath();
    static const std::string & defaultStdlibPath();
    static void removeStdlibPath();
    static void setStdlibPath(const std::string &v);
    static const char *docStdlibPath();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyodideDir
    ///
    /// Folder of the Pyodide runtime the sandbox boots. Empty, the
    /// environment variable FCX_PYODIDE is used, and then what is
    /// installed for the user or comes with the program. Read when the
    /// sandbox starts.
    static const std::string & getPyodideDir();
    static const std::string & defaultPyodideDir();
    static void removePyodideDir();
    static void setPyodideDir(const std::string &v);
    static const char *docPyodideDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyodideWheel
    ///
    /// Path of the wheel that holds the sandbox's own Python package.
    /// Empty, the environment variable FCX_PYODIDE_WHEEL is used, and then
    /// the one that comes with the runtime. Read when the sandbox starts.
    static const std::string & getPyodideWheel();
    static const std::string & defaultPyodideWheel();
    static void removePyodideWheel();
    static void setPyodideWheel(const std::string &v);
    static const char *docPyodideWheel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyodideUserDir
    ///
    /// Folder the sandbox keeps what is installed for the user in. Empty,
    /// the environment variable FCX_PYODIDE_USER is used, and then the
    /// folder Pyodide of the user's application data.
    static const std::string & getPyodideUserDir();
    static const std::string & defaultPyodideUserDir();
    static void removePyodideUserDir();
    static void setPyodideUserDir(const std::string &v);
    static const char *docPyodideUserDir();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyodidePackages
    ///
    /// Folder of the packages installed into the sandbox. Empty, the
    /// environment variable FCX_PYODIDE_PACKAGES is used, and then the
    /// folder packages of the Pyodide user folder.
    static const std::string & getPyodidePackages();
    static const std::string & defaultPyodidePackages();
    static void removePyodidePackages();
    static void setPyodidePackages(const std::string &v);
    static const char *docPyodidePackages();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PyodideUnpinned
    ///
    /// For development only: boots a Pyodide release that is not in the
    /// table of releases the program was pinned to, or whose files differ
    /// from it, and says so at every boot. The environment variable
    /// FCX_PYODIDE_UNPINNED does the same. Read when the sandbox starts.
    static const bool & getPyodideUnpinned();
    static const bool & defaultPyodideUnpinned();
    static void removePyodideUnpinned();
    static void setPyodideUnpinned(const bool &v);
    static const char *docPyodideUnpinned();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Enforce
    ///
    /// The permission rules of a document are enforced: what its
    /// expressions and Python objects may reach is checked against what
    /// the user granted. Off, nothing is checked. On no page. Takes
    /// effect at once.
    static const bool & getEnforce();
    static const bool & defaultEnforce();
    static void removeEnforce();
    static void setEnforce(const bool &v);
    static const char *docEnforce();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class SandboxParams
} // namespace App
//[[[end]]]

#endif // APP_SANDBOX_PARAMS_H
