/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef APP_UNITS_PARAMS_H
#define APP_UNITS_PARAMS_H

/*[[[cog
import UnitsParams
UnitsParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>
#include <fastsignals/signal.h>

// Auto generated code (Tools/params_utils.py:90)
namespace App {
/** Convenient class to obtain the settings of units and number display

 * The parameters are under group "User parameter:BaseApp/Preferences/Units"
 *
 * This class is auto generated by App/UnitsParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r App/UnitsParams.h App/UnitsParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in App/UnitsParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in App/UnitsParams.cpp with
 * the following signature.
 * @code
 *     void UnitsParams:on<parameter_name>Changed()
 * @endcode
 */
class AppExport UnitsParams {
public:
    static ParameterGrp::handle getHandle();

    static fastsignals::signal<void (const char*)> &signalParamChanged();
    static void signalAll();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UserSchema
    ///
    /// Unit system quantities are shown in, and the one a new document
    /// starts with: 0 mm/kg/s, 1 m/kg/s, 2 US customary, 3 imperial
    /// decimal, 4 building Euro, 5 building US, 6 metric CNC (mm,
    /// mm/min), 7 imperial civil, 8 FEM (mm, N, s), 9 meter decimal. A
    /// saved document shows its own unless told otherwise.
    static const long & getUserSchema();
    static const long & defaultUserSchema();
    static void removeUserSchema();
    static void setUserSchema(const long &v);
    static const char *docUserSchema();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Decimals
    ///
    /// Number of decimals numbers and dimensions are shown with. Takes
    /// effect at once; a field already on screen follows when it is next
    /// redrawn.
    static const long & getDecimals();
    static const long & defaultDecimals();
    static void removeDecimals();
    static void setDecimals(const long &v);
    static const char *docDecimals();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter FracInch
    ///
    /// Smallest fraction of an inch the building US unit system shows,
    /// as its denominator: 2, 4, 8, 16, 32, 64 or 128.
    static const long & getFracInch();
    static const long & defaultFracInch();
    static void removeFracInch();
    static void setFracInch(const long &v);
    static const char *docFracInch();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter IgnoreProjectSchema
    ///
    /// Show every document in the unit system of the UserSchema setting
    /// and ignore the one stored in the document.
    static const bool & getIgnoreProjectSchema();
    static const bool & defaultIgnoreProjectSchema();
    static void removeIgnoreProjectSchema();
    static void setIgnoreProjectSchema(const bool &v);
    static const char *docIgnoreProjectSchema();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DecimalsPreSel
    ///
    /// Number of decimals of the coordinates shown in the status bar for
    /// the point under the mouse. -1 uses the general number of
    /// decimals.
    static const long & getDecimalsPreSel();
    static const long & defaultDecimalsPreSel();
    static void removeDecimalsPreSel();
    static void setDecimalsPreSel(const long &v);
    static const char *docDecimalsPreSel();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class UnitsParams
} // namespace App
//[[[end]]]

#endif // APP_UNITS_PARAMS_H
