#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Generate the expression-sandbox facade/dispatch pair from the
<Sandbox tier="value|handle|call"/> annotations in the Py binding XMLs
(docs/ExpressionSandbox.md sec 7.5).

Two outputs, both derived from the SAME annotation set so the host and
the image cannot drift:

  --host-out FcxDispatch.inc   C table rows compiled into
                               src/App/ExpressionImageBridge.cpp: the
                               closed member set the host dispatcher
                               will serve.  An op naming any other
                               member is a protocol error, never a
                               getattr.
  --image-out FcxFacades.inc   A C string literal of Python source
                               defining the in-image proxy classes --
                               exactly the declared members, each
                               forwarding (handle, member, args) over
                               the _fcx bridge -- consumed by
                               src/App/ExpressionImage/ImageMarshal.cpp.

The annotated XML list below is the canonical one; a member without a
<Sandbox/> annotation does not exist across the boundary (DENY by
default).  The security review of the whole bridge is "diff the
annotations": git log -p on these XML files.
"""

import argparse
import os
import sys
import xml.etree.ElementTree as ET

# Canonical annotated binding definitions, relative to the repo root
# (this script lives in src/Tools/bindings).  Keep this list sorted and
# append-only; the CMake custom commands in src/App/CMakeLists.txt and
# src/App/ExpressionImage/CMakeLists.txt list the same files as deps.
ANNOTATED_XMLS = [
    "src/App/ComplexGeoDataPy.xml",
    "src/App/DocumentObjectPy.xml",
    "src/App/DocumentPy.xml",
    "src/Mod/Part/App/TopoShapePy.xml",
    "src/Mod/Spreadsheet/App/SheetPy.xml",
]

VALID_ATTRIBUTE_TIERS = ("value", "handle")
VALID_METHODE_TIERS = ("call",)


class Facade:
    def __init__(self, name, type_key, father_name):
        self.name = name            # XML Name, e.g. DocumentObjectPy
        self.type_key = type_key    # tp_name, e.g. App.DocumentObject
        self.father_name = father_name
        self.attributes = []        # (member, tier)
        self.methods = []           # (member,)


def repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.normpath(os.path.join(here, "..", "..", ".."))
    if not os.path.isfile(os.path.join(root, "src", "Tools", "bindings", "generate.py")):
        sys.exit("generateSandboxFacades: cannot locate the repo root from %s" % here)
    return root


def parse_export(path):
    tree = ET.parse(path)
    export = tree.getroot()
    if export.tag != "PythonExport":
        export = export.find("PythonExport")
    if export is None:
        sys.exit("%s: no PythonExport element" % path)
    name = export.get("Name")
    twin = export.get("Twin")
    namespace = export.get("Namespace")
    python_name = export.get("PythonName")
    type_key = python_name if python_name else "%s.%s" % (namespace, twin)
    facade = Facade(name, type_key, export.get("Father"))
    for member in export:
        if member.tag not in ("Methode", "Attribute"):
            continue
        sandbox = member.find("Sandbox")
        if sandbox is None:
            continue
        tier = sandbox.get("tier")
        mname = member.get("Name")
        if member.tag == "Attribute":
            if tier not in VALID_ATTRIBUTE_TIERS:
                sys.exit("%s: attribute %s: bad Sandbox tier '%s' (want value|handle)"
                         % (path, mname, tier))
            facade.attributes.append((mname, tier))
        else:
            if tier not in VALID_METHODE_TIERS:
                sys.exit("%s: method %s: bad Sandbox tier '%s' (want call)"
                         % (path, mname, tier))
            facade.methods.append((mname,))
    return facade


def topo_sort(facades):
    """Fathers before children so the generated class statements work."""
    by_name = {f.name: f for f in facades}
    ordered, seen = [], set()

    def visit(f):
        if f.name in seen:
            return
        seen.add(f.name)
        father = by_name.get(f.father_name)
        if father is not None:
            visit(father)
        ordered.append(f)

    for f in facades:
        visit(f)
    return ordered


def emit_host(facades, out):
    lines = [
        "// Generated by src/Tools/bindings/generateSandboxFacades.py from the",
        "// <Sandbox tier=.../> annotations in the binding XMLs -- do not edit.",
        "// Included by ExpressionImageBridge.cpp; one row per declared member.",
    ]
    lines.append("static const FacadeMember FacadeTable[] = {")
    for f in facades:
        for mname, tier in f.attributes:
            lines.append('    {"%s", "%s", FacadeKind::Attribute, FacadeTier::%s},'
                         % (f.type_key, mname, tier.capitalize()))
        for (mname,) in f.methods:
            lines.append('    {"%s", "%s", FacadeKind::Method, FacadeTier::Call},'
                         % (f.type_key, mname))
    lines.append("};")
    with open(out, "w") as fp:
        fp.write("\n".join(lines) + "\n")


def emit_image(facades, out):
    py = [
        "# Generated facades: exactly the declared members, nothing else.",
        "# HostHandle, _attr and _method come from the hand-written prelude",
        "# in ImageMarshal.cpp; undeclared attribute access falls through to",
        "# HostHandle.__getattr__ = the host's C++ property system (read_prop).",
    ]
    proxy_name = {f.name: f.name.replace("Py", "") + "Proxy" for f in facades}
    for f in facades:
        base = proxy_name.get(f.father_name, "HostHandle")
        py.append("")
        py.append("class %s(%s):" % (proxy_name[f.name], base))
        py.append("    __slots__ = ()")
        for mname, _tier in f.attributes:
            py.append("    %s = _attr('%s')" % (mname, mname))
        for (mname,) in f.methods:
            py.append("    %s = _method('%s')" % (mname, mname))
    py.append("")
    py.append("FACADES = {")
    for f in facades:
        py.append("    '%s': %s," % (f.type_key, proxy_name[f.name]))
    py.append("}")

    lines = [
        "// Generated by src/Tools/bindings/generateSandboxFacades.py from the",
        "// <Sandbox tier=.../> annotations in the binding XMLs -- do not edit.",
        "// Included by ImageMarshal.cpp and exec'd over the proxy prelude.",
        'static const char FcxFacadesSource[] = R"FCXPY(',
    ]
    lines.extend(py)
    lines.append(')FCXPY";')
    with open(out, "w") as fp:
        fp.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host-out", help="write the host dispatch table (.inc)")
    ap.add_argument("--image-out", help="write the embedded image facades (.inc)")
    args = ap.parse_args()
    if not args.host_out and not args.image_out:
        ap.error("nothing to do: give --host-out and/or --image-out")

    root = repo_root()
    facades = [parse_export(os.path.join(root, rel)) for rel in ANNOTATED_XMLS]
    facades = topo_sort(facades)
    total = sum(len(f.attributes) + len(f.methods) for f in facades)
    if total == 0:
        sys.exit("generateSandboxFacades: no <Sandbox/> annotations found")

    if args.host_out:
        emit_host(facades, args.host_out)
    if args.image_out:
        emit_image(facades, args.image_out)
    print("generateSandboxFacades: %d members across %d facades" % (total, len(facades)))


if __name__ == "__main__":
    main()
