/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef POINTS_APP_PARAMS_H
#define POINTS_APP_PARAMS_H

#include <Mod/Points/PointsGlobal.h>

/*[[[cog
import PointsParams
PointsParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Points {
/** Convenient class to obtain the settings of the Points module

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Points"
 *
 * This class is auto generated by Mod/Points/App/PointsParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Points/App/PointsParams.h Mod/Points/App/PointsParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Points/App/PointsParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Points/App/PointsParams.cpp with
 * the following signature.
 * @code
 *     void PointsParams:on<parameter_name>Changed()
 * @endcode
 */
class PointsExport PointsParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter UseColor
    ///
    /// Reads the colour of each point when an E57 file that has colours
    /// is imported. Takes effect at the next import.
    static const bool & getUseColor();
    static const bool & defaultUseColor();
    static void removeUseColor();
    static void setUseColor(const bool &v);
    static const char *docUseColor();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter CheckInvalidState
    ///
    /// Takes the invalid-point flag of an E57 file into account when the
    /// file is imported. Takes effect at the next import.
    static const bool & getCheckInvalidState();
    static const bool & defaultCheckInvalidState();
    static void removeCheckInvalidState();
    static void setCheckInvalidState(const bool &v);
    static const char *docCheckInvalidState();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MinDistance
    ///
    /// Leaves out a point of an E57 file that lies closer than this
    /// distance to the point read before it; a negative value keeps every
    /// point. Takes effect at the next import.
    static const double & getMinDistance();
    static const double & defaultMinDistance();
    static void removeMinDistance();
    static void setMinDistance(const double &v);
    static const char *docMinDistance();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class PointsParams
} // namespace Points
//[[[end]]]

#endif // POINTS_APP_PARAMS_H
