# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com>
#
# This file is part of FreeCAD.
#
# FreeCAD is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 2.1 of the License, or (at your
# option) any later version.
#
# FreeCAD is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FreeCAD. If not, see <https://www.gnu.org/licenses/>.

"""Render the bundled appearance and surface finish icons.

The icons beside the cards in the material tree are renders of the
materials themselves, and the ones that ship with FreeCAD ship with it
too, so that every installation shows the same picture and one without a
usable GPU still shows a picture at all. This is what makes them. It
writes into src/Mod/Material/Gui/Resources/icons/materials and rewrites
the matching block of Material.qrc there, so the whole set is
regenerated by running it and committing what changes.

**One icon per look, not per card.** The bundled cards resolve to far
fewer distinct appearances than there are cards -- 102 of them are the
same steel -- so each icon is named by the digest of the appearance it
shows, "Look_<digest>.png", and every card whose appearance hashes to
that digest finds it. That is the whole of how they are shared.

The per-card name that used to be bundled, "Appearance_<Name>.png", is
still looked up FIRST, and is now purely the override: drop a file of
that name (with no digest text chunk) anywhere earlier on the "icons:"
search path and that one card takes it, whatever the shared look says.

Run it whenever the answer would come out different: a preset's colours
change, the shading model changes, the engine's output changes. Nothing
breaks if you forget -- each file states the digest of the appearance it
was rendered from, and one that no longer matches is ignored in favour of
a fresh render -- but every stale icon then costs a render on first sight.

Render it on a real GPU. The renderer draws these, and what a user
sees is a GPU drawing them.

Measured, though, the stack matters far less than that warning used to
claim: the same 33 icons rendered here through llvmpipe instead of the
GPU come out with byte-identical COVERAGE -- every alpha pixel of the
33 -- and differ only in shading, by 0.68 levels of 255 on average.
What does move the picture is a preference the scene forgets to pin;
see IconSamples in MaterialIcons.cpp for the one that bit.

    cd <build>
    GALLIUM_DRIVER=d3d12 MESA_LOADER_DRIVER_OVERRIDE=d3d12 \\
    LIBGL_ALWAYS_SOFTWARE=0 \\
        timeout 300 ./bin/FreeCAD ../../scripts/material-icons.py

FreeCAD exits by itself when it is done. Pass FC_ICON_DIR to write
somewhere else, and FC_ICON_KEEP=1 to leave the GUI up afterwards.
"""

import os

import FreeCAD as App
import FreeCADGui as Gui
import MatGui
import Materials

from PySide import QtCore

# Where the icons live, and the block of Material.qrc that lists them.
# Both are found from this file's place in the tree, so that running the
# script from anywhere writes to the right place.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESOURCES = os.path.join(ROOT, "src", "Mod", "Material", "Gui", "Resources")
HERE = os.path.join(RESOURCES, "icons", "materials")
QRC = os.path.join(RESOURCES, "Material.qrc")
QRC_PREFIX = "icons/materials/"
BEGIN = "        <!-- rendered by scripts/material-icons.py -->\n"
END = "        <!-- end rendered icons -->\n"

# Every surface finish pattern App::SurfaceFinish knows, by the name its
# Python API uses. Each is rendered on the neutral material and at the
# pitch and depth MaterialIcons::defaultFinish states; a finish the user
# has given a scale of its own no longer matches and renders at runtime.
FINISHES = ["knurl", "knurl-straight", "brushed", "blasted", "turned"]


# Libraries whose cards never want a rendered sphere, whatever they
# state. Patterns are 2D hatch definitions for TechDraw section fill --
# there is nothing for a shader to read in a hatch, and one wrapped on a
# ball says nothing -- and they get flat swatches instead, from
# scripts/pattern-icons.py. Fluids are gases and water: four of the six
# have no surface at all and one of them is the absence of a fluid.
# Test is the suite's fixture and is not a card anyone picks.
# Directory states its parts with "/" on every platform, so it is split
# on that and not on os.sep.
SKIP_LIBRARIES = ("Patterns", "Fluid", "Test")


def bundled_looks():
    """The distinct looks that ship, and the cards that share each.

    Every card FreeCAD's own resource directory supplies, grouped by the
    digest of its appearance -- which is exactly what "these two look
    the same" means, and what the runtime looks an icon up by. The 219
    bundled cards resolve to 28 looks between them and 102 of them to
    the one steel, so grouping is the difference between 28 icons in the
    binary and 219 copies of a hundred-fold duplicate.

    A card from anywhere else -- one the user wrote, one from an
    installed library -- is rendered on demand and cached, which is
    where a material nobody but its author has ever seen belongs.
    """
    resources = os.path.normcase(os.path.abspath(App.getResourceDir()))
    manager = Materials.MaterialManager()
    looks = {}
    for uuid, material in manager.Materials.items():
        if material.Directory.split("/")[0] in SKIP_LIBRARIES:
            continue
        if not material.AppearanceModels:
            continue
        root = material.LibraryRoot
        if not root:
            continue
        if not os.path.normcase(os.path.abspath(root)).startswith(resources):
            continue
        digest = MatGui.appearanceDigest(uuid)
        # The uuid kept is whichever card sorts first, so that the same
        # library always renders the same one and a regeneration that
        # changes nothing writes nothing.
        entry = looks.setdefault(digest, {"uuid": uuid, "names": []})
        entry["names"].append(material.Name)
        if uuid < entry["uuid"]:
            entry["uuid"] = uuid
    for entry in looks.values():
        entry["names"].sort()
    return looks


def shared_name(digest):
    """The file name a shared look is bundled under.

    Must agree with MatGui::MaterialIcons::sharedResourceName, which is
    what looks it up again.
    """
    return "Look_" + digest


def rewrite_qrc(files):
    """State the generated icons in Material.qrc, between the markers.

    Rewritten rather than appended so that a preset that goes away takes
    its icon out of the binary with it.
    """
    with open(QRC, encoding="utf-8", newline="") as handle:
        text = handle.read()
    # Material.qrc is `text` in .gitattributes: stored with LF, checked out
    # with the platform ending, so CRLF on Windows. Match the markers either
    # way -- a bare \n finds nothing there and the else branch below then
    # APPENDS a duplicate block instead of replacing the first.
    eol = "\r\n" if "\r\n" in text else "\n"
    lines = []
    for name in sorted(files):
        shared = files[name] if isinstance(files, dict) else None
        if shared:
            # Named so that a reader of the qrc can tell what a digest is
            # the look of without rendering anything.
            lines.append("        <!-- %s -->%s" % (shared, eol))
        lines.append("        <file>%s%s</file>%s" % (QRC_PREFIX, name, eol))
    begin = BEGIN.replace("\n", eol)
    end = END.replace("\n", eol)
    block = begin + "".join(lines) + end
    start = text.find(begin)
    if start >= 0:
        stop = text.find(end, start) + len(end)
        text = text[:start] + block + text[stop:]
    else:
        # First run: put the block just before the qresource closes.
        marker = "    </qresource>"
        text = text.replace(marker, block + marker, 1)
    with open(QRC, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def generate():
    target = os.environ.get("FC_ICON_DIR", HERE)
    if not os.path.isdir(target):
        os.makedirs(target)

    written = {}
    failed = []

    looks = bundled_looks()
    for digest, entry in sorted(looks.items()):
        path = os.path.join(target, shared_name(digest) + ".png")
        if MatGui.renderMaterialIcon(entry["uuid"], path):
            names = entry["names"]
            shared = names[0] if len(names) == 1 else "%s, and %d more: %s" % (
                names[0], len(names) - 1, ", ".join(names[1:8])
                + (", ..." if len(names) > 9 else ""))
            written[os.path.basename(path)] = shared
        else:
            failed.append(entry["names"][0])

    for pattern in FINISHES:
        path = os.path.join(target, "Finish_" + pattern + ".png")
        if MatGui.renderFinishIcon(pattern, path):
            written[os.path.basename(path)] = "surface finish: " + pattern
        else:
            failed.append("finish " + pattern)

    if failed:
        # Nothing rendered at all means no GPU, which is worth saying
        # plainly rather than leaving as an empty directory.
        App.Console.PrintError(
            "Material icons: %d of %d did not render (%s)\n"
            % (len(failed), len(failed) + len(written), ", ".join(failed[:5]))
        )
    if written:
        # Anything of ours the run did not write is left over from a
        # naming that no longer holds, and would otherwise sit in the
        # binary for good under a name nothing looks up.
        keep = set(written)
        for stale in os.listdir(target):
            if stale in keep or not stale.endswith(".png"):
                continue
            if (stale.startswith("Appearance_") or stale.startswith("Finish_")
                    or stale.startswith("Look_")):
                os.remove(os.path.join(target, stale))
                App.Console.PrintMessage("Material icons: dropped %s\n" % stale)
        rewrite_qrc(written)
        cards = sum(len(e["names"]) for e in looks.values())
        App.Console.PrintMessage(
            "Material icons: wrote %d into %s (%d looks covering %d cards, "
            "plus %d finishes)\n"
            % (len(written), target, len(looks), cards, len(FINISHES))
        )

    if not os.environ.get("FC_ICON_KEEP"):
        Gui.getMainWindow().close()


# The scene these are rendered from is a widget with a GL context, so
# there has to be an event loop first: schedule and let startup finish.
QtCore.QTimer.singleShot(0, generate)
