# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com>
#
# This file is part of FreeCAD.
#
# FreeCAD is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 2.1 of the License, or (at your
# option) any later version.
#
# FreeCAD is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FreeCAD. If not, see <https://www.gnu.org/licenses/>.

"""Draw the bundled hatch pattern swatches.

The Patterns library is the one part of the material bundle a rendered
sphere cannot speak for. A card there states a hatch -- either an AutoCAD
PAT line definition or an SVG tile -- which is a 2D fill for a TechDraw
section, not a surface. There is nothing in it for a shader to read, and
wrapped on a ball it says nothing at all; every one of the 32 hashes to
the same default appearance, so they would all show the SAME grey sphere.

So they get flat swatches instead, drawn the way the pattern is actually
used: dark ink on pale paper. Paper rather than transparency because a
hatch is black and would disappear against a dark theme.

Unlike scripts/material-icons.py this needs no GPU, no renderer and no
FreeCAD -- it reads the cards off disk and draws with QPainter, so it
runs anywhere PySide is installed:

    python3 scripts/pattern-icons.py

It writes into src/Mod/Material/Gui/Resources/icons/materials and
rewrites its own block of Material.qrc there, so the whole set is
regenerated by running it and committing what changes.
"""

import math
import os
import re
import sys

try:
    from PySide6 import QtCore, QtGui, QtSvg
except ImportError:  # pragma: no cover - a FreeCAD env supplies one or the other
    from PySide2 import QtCore, QtGui, QtSvg

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CARDS = os.path.join(ROOT, "src", "Mod", "Material", "Resources", "Materials", "Patterns")
RESOURCES = os.path.join(ROOT, "src", "Mod", "Material", "Gui", "Resources")
HERE = os.path.join(RESOURCES, "icons", "materials")
QRC = os.path.join(RESOURCES, "Material.qrc")
QRC_PREFIX = "icons/materials/"
BEGIN = "        <!-- drawn by scripts/pattern-icons.py -->\n"
END = "        <!-- end pattern swatches -->\n"

# Rendered at the size the material icons ship at, so the two sit at the
# same resolution in the tree and scale down together.
SIZE = 256

# The paper the hatch is drawn on. Light, because a hatch is ink: a black
# line on transparency is invisible under a dark theme, and a swatch that
# shows nothing is worse than no swatch. Faintly bordered so the tile
# reads as an object rather than as a hole in the row.
PAPER = QtGui.QColor(247, 246, 243)
EDGE = QtGui.QColor(160, 158, 152)

# How many line spacings to show across the tile. Few enough that each is
# separate at 32px -- the size the tree actually paints -- and enough that
# a pattern reads as a pattern and not as one stray line. The same lesson
# the finish icons taught: a swatch has to lie about scale to stay legible.
SPACINGS = 5


def cards():
    """Every pattern card in the bundle, as (name, kind, values)."""
    found = []
    for base, _dirs, files in os.walk(CARDS):
        for name in sorted(files):
            if not name.endswith(".FCMat"):
                continue
            path = os.path.join(base, name)
            with open(path, encoding="utf-8-sig", errors="replace") as handle:
                text = handle.read()
            card = re.search(r'^\s*Name:\s*"?(.*?)"?\s*$', text, re.M)
            title = card.group(1) if card else name[:-6]
            block = _scalar(text, "Hatch Pattern")
            if block is not None:
                found.append((title, "pat", block, _colour(text, "Hatch Color")))
                continue
            block = _scalar(text, "Pattern File")
            if block is not None:
                found.append((title, "svg", block, _colour(text, "Pattern Color")))
    return sorted(found)


def _scalar(text, key):
    """The body of a YAML block scalar, dedented.

    The cards write these as "Key: |2" followed by an indented body, and
    the indent is what ends the block -- so the body runs to the first
    line that is neither blank nor indented past the key.
    """
    match = re.search(r"^(\s*)%s:\s*\|.*$" % re.escape(key), text, re.M)
    if not match:
        return None
    indent = len(match.group(1))
    lines = []
    for line in text[match.end():].splitlines()[1:]:
        if line.strip() and len(line) - len(line.lstrip()) <= indent:
            break
        lines.append(line[indent + 2:] if len(line) > indent + 2 else "")
    return "\n".join(lines).strip("\n")


def _colour(text, key):
    match = re.search(r'^\s*%s:\s*"\(([^)]*)\)"' % re.escape(key), text, re.M)
    if not match:
        return QtGui.QColor(0, 0, 0)
    parts = [float(p) for p in match.group(1).split(",")]
    while len(parts) < 3:
        parts.append(0.0)
    return QtGui.QColor.fromRgbF(*parts[:3])


def parse_pat(body):
    """The line families of an AutoCAD PAT definition.

    Each is "angle, x-origin, y-origin, delta-x, delta-y" and then any
    number of dash lengths -- positive drawn, negative skipped. The
    header line names the pattern and is not one of them.
    """
    families = []
    for line in body.splitlines():
        line = line.split(";")[0].strip()
        if not line or line.startswith("*"):
            continue
        try:
            values = [float(v) for v in line.split(",")]
        except ValueError:
            continue
        if len(values) < 5:
            continue
        families.append(
            {
                "angle": values[0],
                "origin": (values[1], values[2]),
                "delta": (values[3], values[4]),
                "dashes": values[5:],
            }
        )
    return families


def draw_pat(painter, body, colour):
    families = parse_pat(body)
    if not families:
        return False

    # The tile shows a fixed number of line spacings, whatever units the
    # pattern states its own in -- a 0.125 separation and a 5.0 one have
    # to come out the same size on screen.
    spacings = [math.hypot(*f["delta"]) for f in families if math.hypot(*f["delta"]) > 1e-9]
    world = (max(spacings) if spacings else 1.0) * SPACINGS
    scale = SIZE / world
    # Far enough out that a family offset along its own direction still
    # crosses the tile; the diagonal is the worst case either way.
    reach = int(SPACINGS * 1.5) + 2

    painter.save()
    painter.translate(SIZE / 2.0, SIZE / 2.0)
    painter.scale(scale, -scale)  # PAT counts y upward, Qt counts it down
    half = world / 2.0
    span = world * 1.5

    pen = QtGui.QPen(colour)
    pen.setWidthF(max(world / SIZE, 1.0 / scale) * 1.6)
    pen.setCapStyle(QtCore.Qt.FlatCap)
    for family in families:
        radians = math.radians(family["angle"])
        along = (math.cos(radians), math.sin(radians))
        across = (-math.sin(radians), math.cos(radians))
        step = family["delta"]
        dashes = [abs(d) for d in family["dashes"]]
        if dashes and any(d > 1e-9 for d in dashes):
            # Qt states a dash pattern in pen widths, and the lengths are
            # in pattern units, so they divide through by the width.
            pen.setDashPattern([max(d / pen.widthF(), 0.01) for d in dashes])
        else:
            pen.setStyle(QtCore.Qt.SolidLine)
        painter.setPen(pen)
        for index in range(-reach, reach + 1):
            # Offset is stated in the line's own frame: delta-x along it,
            # delta-y across it.
            ox = family["origin"][0] + index * (step[0] * along[0] + step[1] * across[0])
            oy = family["origin"][1] + index * (step[0] * along[1] + step[1] * across[1])
            painter.drawLine(
                QtCore.QPointF(ox - along[0] * span, oy - along[1] * span),
                QtCore.QPointF(ox + along[0] * span, oy + along[1] * span),
            )
        pen.setStyle(QtCore.Qt.SolidLine)
    painter.restore()
    return True


def draw_svg(painter, body):
    """An SVG tile, drawn to fill the swatch as the material editor does."""
    renderer = QtSvg.QSvgRenderer(QtCore.QByteArray(body.encode("utf-8")))
    if not renderer.isValid():
        return False
    renderer.render(painter, QtCore.QRectF(0, 0, SIZE, SIZE))
    return True


def swatch(kind, body, colour):
    image = QtGui.QImage(SIZE, SIZE, QtGui.QImage.Format_ARGB32)
    image.fill(QtCore.Qt.transparent)
    painter = QtGui.QPainter(image)
    painter.setRenderHint(QtGui.QPainter.Antialiasing, True)

    inset = QtCore.QRectF(0.5, 0.5, SIZE - 1.0, SIZE - 1.0)
    painter.setBrush(PAPER)
    painter.setPen(QtCore.Qt.NoPen)
    painter.drawRect(inset)
    painter.setClipRect(inset)

    drawn = draw_pat(painter, body, colour) if kind == "pat" else draw_svg(painter, body)

    painter.setClipping(False)
    painter.setBrush(QtCore.Qt.NoBrush)
    painter.setPen(QtGui.QPen(EDGE, 1.0))
    painter.drawRect(inset)
    painter.end()
    return image if drawn else None


def resource_name(name):
    """The file name a swatch is bundled under.

    Must agree with MatGui::MaterialIcons::patternResourceName, which is
    what looks it up again.
    """
    return "Pattern_" + re.sub(r"[^A-Za-z0-9._-]+", "_", name)


def rewrite_qrc(names):
    with open(QRC, encoding="utf-8", newline="") as handle:
        text = handle.read()
    # Material.qrc is `text` in .gitattributes, so it is stored with LF
    # and checked out with the platform ending -- CRLF on Windows. The
    # markers have to be found either way: matching a bare \n found
    # nothing there, and the else branch below then APPENDED a second
    # block on every run instead of replacing the first, leaving the
    # stale names in place beside the new ones.
    eol = "\r\n" if "\r\n" in text else "\n"
    begin = BEGIN.replace("\n", eol)
    end = END.replace("\n", eol)
    block = begin + "".join(
        "        <file>%s%s</file>%s" % (QRC_PREFIX, name, eol) for name in sorted(names)
    ) + end
    start = text.find(begin)
    if start >= 0:
        stop = text.find(end, start) + len(end)
        text = text[:start] + block + text[stop:]
    else:
        marker = "    </qresource>"
        text = text.replace(marker, block + marker, 1)
    with open(QRC, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def main():
    # Nothing here reaches a screen, and the box that generates the icons
    # need not have one.
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    app = QtGui.QGuiApplication.instance() or QtGui.QGuiApplication(sys.argv[:1])
    _ = app

    target = os.environ.get("FC_ICON_DIR", HERE)
    if not os.path.isdir(target):
        os.makedirs(target)

    written = []
    failed = []
    for name, kind, body, colour in cards():
        image = swatch(kind, body, colour)
        leaf = resource_name(name) + ".png"
        if image is not None and image.save(os.path.join(target, leaf), "PNG"):
            written.append(leaf)
        else:
            failed.append(name)

    if failed:
        sys.stderr.write("Pattern swatches: %d did not draw (%s)\n"
                         % (len(failed), ", ".join(failed[:5])))
    if not written:
        return 1

    keep = set(written)
    for stale in os.listdir(target):
        if stale in keep or not stale.endswith(".png"):
            continue
        if stale.startswith("Pattern_"):
            os.remove(os.path.join(target, stale))
            print("Pattern swatches: dropped %s" % stale)
    rewrite_qrc(written)
    print("Pattern swatches: wrote %d into %s" % (len(written), target))
    return 0


if __name__ == "__main__":
    sys.exit(main())
