/****************************************************************************
 *   Copyright (c) 2026 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef FEM_APP_PARAMS_H
#define FEM_APP_PARAMS_H

#include <Mod/Fem/FemGlobal.h>

/*[[[cog
import FemParams
FemParams.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:82)
#include <Base/Parameter.h>


// Auto generated code (Tools/params_utils.py:90)
namespace Fem {
/** Convenient class to obtain the settings of the Fem workbench that C++ reads

 * The parameters are under group "User parameter:BaseApp/Preferences/Mod/Fem"
 *
 * This class is auto generated by Mod/Fem/App/FemParams.py. Modify that file
 * instead of this one, if you want to add any parameter. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r Mod/Fem/App/FemParams.h Mod/Fem/App/FemParams.cpp
 * @endcode
 *
 * You can add a new parameter by adding lines in Mod/Fem/App/FemParams.py. Available
 * parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
 * a new Int type parameter,
 * @code
 *     ParamInt(parameter_name, default_value, documentation, on_change=False)
 * @endcode
 *
 * If there is special handling on parameter change, pass in on_change=True.
 * And you need to provide a function implementation in Mod/Fem/App/FemParams.cpp with
 * the following signature.
 * @code
 *     void FemParams:on<parameter_name>Changed()
 * @endcode
 */
class FemExport FemParams {
public:
    static ParameterGrp::handle getHandle();

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter PostAutoRecompute
    ///
    /// Recomputes a post-processing object as soon as one of its settings
    /// is changed in a task panel. Takes effect at once.
    static const bool & getPostAutoRecompute();
    static const bool & defaultPostAutoRecompute();
    static void removePostAutoRecompute();
    static void setPostAutoRecompute(const bool &v);
    static const char *docPostAutoRecompute();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter DefaultSolver
    ///
    /// Solver added to a new analysis container: 0 none, 1 CalculiX, 2
    /// Elmer, 3 Mystran, 4 Z88. Takes effect when the next analysis is
    /// created.
    static const long & getDefaultSolver();
    static const long & defaultDefaultSolver();
    static void removeDefaultSolver();
    static void setDefaultSolver(const long &v);
    static const char *docDefaultSolver();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter MeshExportLevel
    ///
    /// Which mesh elements are written to a VTK file: All, or Highest for
    /// only those of the highest dimension. Takes effect at the next
    /// export.
    static const std::string & getMeshExportLevel();
    static const std::string & defaultMeshExportLevel();
    static void removeMeshExportLevel();
    static void setMeshExportLevel(const std::string &v);
    static const char *docMeshExportLevel();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AbaqusElementChoice
    ///
    /// Which mesh elements are written to an Abaqus INP file: 0 all, 1
    /// only the highest, 2 only the FEM elements. Takes effect at the
    /// next export.
    static const long & getAbaqusElementChoice();
    static const long & defaultAbaqusElementChoice();
    static void removeAbaqusElementChoice();
    static void setAbaqusElementChoice(const long &v);
    static const char *docAbaqusElementChoice();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter AbaqusWriteGroups
    ///
    /// Writes the mesh groups as well when a mesh is exported to an
    /// Abaqus INP file. Takes effect at the next export.
    static const bool & getAbaqusWriteGroups();
    static const bool & defaultAbaqusWriteGroups();
    static void removeAbaqusWriteGroups();
    static void setAbaqusWriteGroups(const bool &v);
    static const char *docAbaqusWriteGroups();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter GmshLogVerbosity
    ///
    /// How much Gmsh reports in the task panel while it meshes, as its
    /// verbosity level: from 0, silent, to 99, debug. Takes effect at the
    /// next meshing run.
    static const std::string & getGmshLogVerbosity();
    static const std::string & defaultGmshLogVerbosity();
    static void removeGmshLogVerbosity();
    static void setGmshLogVerbosity(const std::string &v);
    static const char *docGmshLogVerbosity();
    //@}

    // Auto generated code (Tools/params_utils.py:139)
    //@{
    /// Accessor for parameter Z88Solver
    ///
    /// Solver method given to a new Z88 solver object. Applies to solver
    /// objects created afterwards.
    static const std::string & getZ88Solver();
    static const std::string & defaultZ88Solver();
    static void removeZ88Solver();
    static void setZ88Solver(const std::string &v);
    static const char *docZ88Solver();
    //@}

// Auto generated code (Tools/params_utils.py:179)
}; // class FemParams
} // namespace Fem
//[[[end]]]

#endif // FEM_APP_PARAMS_H
